### ISSUE TITLE
Syntax highlighting regression

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3436]
On master, syntax highlighting highlights far fewer things, which makes code readability much worse.

Here is 7.2 with the Monokai theme:

<img width="1002" alt="2017-12-01_1212" src="https://user-images.githubusercontent.com/183285/33494440-422f0650-d691-11e7-8a33-26ff68980448.png">

Here is master:

<img width="1006" alt="2017-12-01_1214" src="https://user-images.githubusercontent.com/183285/33494425-35d47cfa-d691-11e7-812f-2f809493e6bf.png">

> VS bug #568029

**Comment by mhutch** [comment]
For comparison, here's VS Code. I general I prefer MD 7.2, but rather quite like the highlighted operators in VS Code.

<img width="868" alt="2017-12-01_1218" src="https://user-images.githubusercontent.com/183285/33494610-c6a4d87e-d691-11e7-81df-1c6be79b3ebe.png">

**Comment by mhutch** [comment]
@Therzok we can add them upstream

**Comment by mhutch** [comment]
The missing classification functionality has now been added to Roslyn: https://github.com/dotnet/roslyn/pull/24931

**Comment by Therzok** [comment]
Should be fixable once https://github.com/mono/monodevelop/pull/4101/files is in.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.122 (master)

Author: Kirill Osenkov
Commit: 0b642af9e5131e86c5c689c9cc747f0ebfac6b9f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.853 (d15-7)

Pull Request #4159 merged by: Lluis Sanchez
Author: mono
Commit: da30061ffe6dc2ffe7ebd6dd17164b79618cb2cc (mono/monodevelop)
