### ISSUE TITLE
Tooltips are unreadable with Monokai editor theme

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3437]
Editor tooltips are unreadable when using the Monokai dark editor theme with the light UI theme

<img width="1005" alt="00000138" src="https://user-images.githubusercontent.com/183285/33496862-d1912d70-d699-11e7-8f65-e69c6972abc2.png">

> VS bug #568030

**Comment by slluis** [comment]
We used to have a logic to automatically adapt colors to backgrounds. I wonder what happened to that.

**Comment by sevoku** [comment]
Proposed fix: https://github.com/mono/monodevelop/pull/3888

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.437 (master)

Author: Vsevolod Kukol
Commit: d50b371e84a45e131376846f6c76744fdfa68e72 (mono/monodevelop)

**Comment by slluis** [comment]
@sevoku can you prepare a PR for 15.6?

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.4.1.25 (d15-6)

Pull Request #4098 merged by: Lluis Sanchez
Author: mono
Commit: f1f64ce35353f6a4a6d85f6406bd6b620b3c02a1 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '7.4' that is not in the list of supported values

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #3888 merged by: Lluis Sanchez
Author: mono
Commit: 4f95fb9676851ad665d9fe558d23cddfb992b3ec (xamarin/monodevelop)
