### ISSUE TITLE
Extensions cannot override built-in highlighting

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3438]
The syntax highlighting service loads the built-in syntax highlighting definitions directly from the assembly resources, instead of registering them into the extension point. As a result, extension `insertbefore` and `insertafter` attributes cannot be used to override the built-in definitions.

This is a problem because the XML definition binds to an over-broad set of files extensions. For many of these it it possible to define a better, format-specific highlighting scheme, but it's not possible to register it as the built-in generic one takes precedence.

> VS bug #568048

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.979 (master)

Author: Mike Krüger
Commit: b8df6240fcb19d0eed140f3c2721559746d3a576 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4930 merged by: Mike Kr??ger
Author: mono
Commit: 562bae845e11ae716299bfc1b833463bd5c5e41f (xamarin/monodevelop)
