### ISSUE TITLE
Multiple identical entries for Tuple in completion list

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3441]
When import items are enabled, the completion list shows multiple identical entries for importing Tuple:

<img width="1114" alt="00000134" src="https://user-images.githubusercontent.com/183285/33507261-cb8a871e-d6c1-11e7-903a-677af2abd1bc.png">

The duplicates go away after the `using System` is added

> VS bug #568065

**Comment by slluis** [comment]
I can still reproduce in VSMac 7.4.

**Comment by slluis** [comment]
Fixed by https://github.com/mono/monodevelop/pull/3863

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #3863 merged by: Mike Kr??ger  
 Author: mono  
 Commit: c734a899ea1c73e77a7329631b4ec6a183f5fbb2 (xamarin/monodevelop)
