### ISSUE TITLE
It looks like very nerving me! MonoDevelop won't build under Ubuntu 16.04 :(

### ISSUE THREAD

**Issue by sourceskyboxer** [mono/monodevelop#3444]
Hello everyone, 

why does it not work? I really miss MonoGame on newest version of MonoDevelop. Stop advantage my development!

```
Synchronizing submodule url for 'main/external/RefactoringEssentials'
Synchronizing submodule url for 'main/external/cecil'
Synchronizing submodule url for 'main/external/debugger-libs'
Synchronizing submodule url for 'main/external/guiunit'
Synchronizing submodule url for 'main/external/ikvm'
Synchronizing submodule url for 'main/external/libgit-binary'
Synchronizing submodule url for 'main/external/libgit2'
Synchronizing submodule url for 'main/external/libgit2sharp'
Synchronizing submodule url for 'main/external/macdoc'
Synchronizing submodule url for 'main/external/mdtestharness'
Synchronizing submodule url for 'main/external/mono-addins'
Synchronizing submodule url for 'main/external/mono-tools'
Synchronizing submodule url for 'main/external/monomac'
Synchronizing submodule url for 'main/external/nrefactory'
Synchronizing submodule url for 'main/external/nuget-binary'
Synchronizing submodule url for 'main/external/sharpsvn-binary'
Synchronizing submodule url for 'main/external/xwt'
make[1]: Entering directory '/home/jens/7.0.1.24/main'
Making all in external
make[2]: Entering directory '/home/jens/7.0.1.24/main/external'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jens/7.0.1.24/main/external'
Making all in .
make[2]: Entering directory '/home/jens/7.0.1.24/main'
touch vcrevision
MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
All packages listed in packages.config are already installed.
Restoring packages for /home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj...
Committing restore...
Lock file has not changed. Skipping lock file write. Path: /home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/obj/project.assets.json
Restore completed in 416.23 ms for /home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj.

NuGet Config files used:
    /home/jens/7.0.1.24/NuGet.config
    /home/jens/.config/NuGet/NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/
    https://dotnet.myget.org/F/roslyn/api/v3/index.json
    https://ci.appveyor.com/nuget/nugetizer3000
    https://dotnet.myget.org/F/vstest/
    https://dotnet.myget.org/F/templating/
    https://api.nuget.org/v3/index.json
msbuild /t:Restore /p:RestoreDisableParallel=true external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj
Microsoft (R) Build Engine version 15.4.0.0 ( Mon Nov 27 18:23:43 UTC 2017) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/3/2017 6:45:59 PM.
Project "/home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj" on node 1 (Restore target(s)).
/home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj : error MSB4057: The target "Restore" does not exist in the project.
Done Building Project "/home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

"/home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj" (Restore target) (1) ->
  /home/jens/7.0.1.24/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj : error MSB4057: The target "Restore" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.69
Makefile:1145: recipe for target 'restore-packages' failed
make[2]: *** [restore-packages] Error 1
make[2]: Leaving directory '/home/jens/7.0.1.24/main'
Makefile:676: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/jens/7.0.1.24/main'
Makefile:31: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Please don't force me! I want build it. And I already tried latest version won't work....

**Comment by mrward** [comment]
Which Mono version are you using? This looks like an MSBuild problem.

**Comment by sourceskyboxer** [comment]
Really? MSBuild has problem? impossible? I have installed completed with sudo apt install mono-complete -fy than it is okay. 

Mono Version from Github I have built and installed to /usr 
Before 5.4.16 but it has problem of msbuild I tried to compile and install from github of Mono and 5.9.0 and It works fine and I already tried WaveEngine, UrhoEngine and any frameworks have not problems.

MonoDevelop can not build because it looks like PresentationCore.dll doesn't exist to Ubuntu because MonoDevelop need reference assemblies.  That is why I am surprised why Ubuntu need Microsoft Net Frameworks 4.x. But for Mono Runtime has not any more reference assemblies from C:\Windows\Microsoft.Net\Frameworks\ or C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5 here required assemblies.

But it doesn't support for Linux OS because Linux OS has another dllimport of so files....

Thanks!

**Comment by mrward** [comment]
You might be running into this [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=60770). Which I believe is causing the required MSBuild targets for .NET Standard projects to not be imported and causing the build of the RefactoringEssentials project to fail.

**Comment by sourceskyboxer** [comment]
Are you sure? I have readden xamarin bug tracker - It sees like it is same old. Why does MonoDevelop source from Github not update? Since I download on Dec 3 2017. It is impossible to late to fix msbuild from Mono Runtime. Thanks for explanation. I should wait for next release?

**Comment by mrward** [comment]
@grendello Had the same restore error and I believe updating to a newer Mono fixed the build error.

**Comment by sourceskyboxer** [comment]
@mrward Hello please re read correctly! I have to download mono from Github and build mono again and it has same errors. Because mono doesn't have sometimes unsupported reference assemblies like PresentationCore.dll, UIAccess.dll etc...

That is why MonoDevelop has requirements like for Windows 10.x - Why does it not work for Ubuntu? Because Ubuntu has not any reference assemblies like Windows's reference assemblies. It is a reason and compilation throws error like PresentationCore.dll could not found....

**Comment by grendello** [comment]
http://www.mono-project.com/download/beta/

    $ sudo apt-get -f -u install mono-complete msbuild msbuild-libhostfxr msbuild-sdkresolver
    $dpkg -l|grep msbuild
      ii  msbuild                                                     1:15.4+xamarinxplat.2017.11.27.11.23-0xamarin1+ubuntu1404b1 all          build platform for .NET and Visual Studio
      ii  msbuild-libhostfxr                                          2.0.0.2017.07.06.00.01-0xamarin14+ubuntu1604b1              amd64        Helper library for MSbuild .NET Core support
      ii  msbuild-sdkresolver                                         1:15.4+xamarinxplat.2017.11.27.11.23-0xamarin1+ubuntu1404b1 all          build platform for .NET and Visual Studio
