### ISSUE TITLE
Completion should always prefer exact case-sensitive match

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3457]
I typed `Path`, and the completion list matched `path`. As a result, it interfered with what I was typing.

<img width="843" alt="00000143" src="https://user-images.githubusercontent.com/183285/33618435-90b5576c-d9b0-11e7-8955-090dc166f7fc.png">

> VS bug #577084

**Comment by decriptor** [comment]
Agreed. I've been running into this lately and it is kind of annoying in that it feels like it slows down typing. Also, I find that I hit the wrong thing sometimes and it causes something to be imported which reformats the file and jumps around.

**Comment by nosami** [comment]
![intellisense-case](https://user-images.githubusercontent.com/667194/33622610-3a07015a-d9e6-11e7-89f2-670220c030e3.gif)

F# behaviour (just checking)

**Comment by mhutch** [comment]
I think that's happening here is that the "match most recently used" is taking precedence.

If i type `var x =Path.Combine("a", "b"); Path` it's not an issue (on the latter one at least)
