### ISSUE TITLE
Rerunning a test appears to cause the projects to build again

### ISSUE THREAD

**Issue by decriptor** [mono/monodevelop#3459]
I'm not sure why it'd trigger this, but when I go to run the same test without code changes it appears to build parts of the solution again. This makes running tests time consuming.

Also, It seems like there are times when I tell it to run a test and it triggers a build, but forgets to actually run the test in the end. This means it has to run the build yet again.

> VS bug #567935

**Comment by mrward** [comment]
I usually have 'Build projects before executing unit tests' disabled because of this (Preferences - Projects - Build).

I think @DavidKarlas made some changes to detect projects that need building again in master recently.

**Comment by decriptor** [comment]
I believe I already have @DavidKarlas' changes. I shouldn't have to disable it?

**Comment by mrward** [comment]
Just reviewing the commits. If you are on master then it looks like there is a new option that may help here - `Skip building unmodified projects` (Preferences - Projects - Build). It seems to be off by default.

**Comment by mhutch** [comment]
Unit testing, like execution, should use the fast up to date check to determine whether to build the project

**Comment by decriptor** [comment]
@mrward that seems like a really silly check to have off by default? Is there a case where you'd want to rebuild a project that doesn't need to be built?
