### ISSUE TITLE
Completion after using keyword should be in suggestion mode

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3461]
If I type `using `, completion comes up with a list of namespaces. However, it's in completion mode. If I try to type an alias (e.g. `using BF = System.Reflection.BindingFlags`) it interferes with me typing the alias. It should be in suggestion mode.

> VS bug #567937

**Comment by mhutch** [comment]
Appears to have been fixed by https://github.com/mono/monodevelop/commit/b65943bc33c075af252f3312265d0407a6984ed1

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #3921 merged by: Mike Kr??ger  
 Author: mono  
 Commit: f9a21f193342bf0679d8a72abbf62008fe527bdf (xamarin/monodevelop)
