### ISSUE TITLE
Allow editing function breakpoint

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3465]
It's not possible to edit a function breakpoint after creating it.

*Steps to reproduce:*

1. Create function breakpoint
2. Realize you made a typo
3. Open breakpoint properties to change it
4. try to edit the function name, fail
5. try to copy the function name you you can paste into a new function breakpoint and edit there, fail

> VS bug #568053

**Comment by slluis** [comment]
Work in progress fix in https://github.com/mono/monodevelop/pull/3698

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-40] Comment by **xamarinc**



Fixed in version 8.6.0.823 (master)



Pull Request #3698 merged by: Matt Ward  
 Author: mono  
 Commit: 52a5a0e6919b5e8c30a4644cbfd0ad159b9364d5 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-41] Comment by **xamarinc**



Fixed in version 8.5.0.1714 (release-8.5)



Pull Request #3698 merged by: Matt Ward  
 Author: mono  
 Commit: 52a5a0e6919b5e8c30a4644cbfd0ad159b9364d5 (xamarin/monodevelop)
