### ISSUE TITLE
Running tests with margin marker ignores "build before running" setting

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3467]
Running tests with the margin marker ignores the "build before running" setting.

To repro:
1. enable test margin markers
2 disable prefs -> project -> build -> build project before running test
3. open a test project
4. change the code
5. run a test using the margin markers
6. the test project builds, ignoring the setting from (2)

**Comment by slluis** [comment]
Fixed by https://github.com/mono/monodevelop/pull/3518
