### ISSUE TITLE
Version attribute metadata converted to element after updating package

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3468]
When updating a NuGet PackageReference, the Version metadata is converted from an attribute to an element.

To repro:

1. edit the csproj and add an outdated PackageReference that uses an attribute for metadata, for example 

```
<PackageReference Include="System.Net.Http" Version="4.3.3" />
```

2. update NuGet packages in the IDE

The reference is converted to the old style:

```
<PackageReference Include="System.Net.Http">
  <Version>4.3.3</Version>
</PackageReference>
```

> VS bug #567929

**Comment by mrward** [comment]
This was fixed when #3881 was fixed.
