### ISSUE TITLE
Align quote matching with Visual Studio behavior

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3475]
The text editor is far too over-eager in inserting matching quotes. No matter where I type a quote or paren, I seem to get two. And when I delete the extra one, it often deletes both! It feels like I'm fighting the editor.

VS Code has the same feature, but the heuristics for when to insert the matching quote are much better. It usually (though not always) only inserts the matching quote when there's whitespace on both sides. It also appears to be determined by whether the caret is in a string or comment, and is [configured per-language](https://github.com/Microsoft/vscode/blob/master/extensions/csharp/language-configuration.json#L11).

> VS bug #568059

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.286 (master)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1140 (release-7.7)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (xamarin/monodevelop)
