### ISSUE TITLE
Adding or renaming file blocks all commands for several seconds

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3476]
Adding or renaming file blocks all commands for several seconds.

To reproduce:

1. add a new file to a project, or rename an existing file
2. the status bar shows "saving..." for 2-5 seconds
3. During this time, all commands are blocked

This makes it very, very painful to rename several files in a row

**Comment by slluis** [comment]
I optimized the save operation, so it should be significantly faster now. For big projects with many files it may still take a second, but that's the best I can do for now. The commands need to be blocked while the project is saving, the IDE may crash if the project is modified while being saved.
