### ISSUE TITLE
No command to global search commands

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3479]
Although the global search includes commands, there is no filter for commands, nor is there a command to open the search with this filter (like "Go to type" and "Go to file" for types and files).

It would also be good to bind this to *cmd-shift-p* for compat with VS Code.

> VS bug #540610

**Comment by Therzok** [comment]
You can type `cmd:`, `command:`, `c:`, but yes, there is no UI.

**Comment by mhutch** [comment]
Huh, okay. The dropdown filter menu doesn't include commands then.

**Comment by Therzok** [comment]
Yeah, every category defines its own tags. We should probably show all the possible filters.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #3658 merged by: Lluis Sanchez
Author: mono
Commit: 6bb421103a69c8b28fd723322cead5f2eb1469c6 (xamarin/monodevelop)
