### ISSUE TITLE
TestSessionTimeout is not configurable

### ISSUE THREAD

**Issue by k-green** [mono/monodevelop#3513]
VS Test supports a run settings file in which you can pass a TestSessionTimeout.

This is [ hardcoded to a value of 60 seconds](https://github.com/mono/monodevelop/blob/9288325908994ab782b76171b8e2ca8c8af892bc/main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestAdapter.cs#L70) meaning that it is not possible to properly run test classes that take longer than a minute to complete.

> VS bug #554671

**Comment by mediumTaj** [comment]
This is preventing me from running integration tests in VS.

**Comment by gfhcs** [comment]
Is there any workaround for this? Does 'longRunningTestSeconds' help?

**Comment by usr-sse2** [comment]
It also prevents debugging unit tests, because test is aborted after 60 seconds + some waiting time (in practice, it is another 60 seconds). No time to stand on a breakpoint and think.

**Comment by DalSoft** [comment]
And UI tests now using the command line instead

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.814 (master)

Pull Request #4800 merged by: Lluis Sanchez
Author: mono
Commit: d61cf28fdb1abbaabf3e8c543ffe346d0c75b40a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4800 merged by: Lluis Sanchez
Author: mono
Commit: d61cf28fdb1abbaabf3e8c543ffe346d0c75b40a (xamarin/monodevelop)
