### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by wboswall** [mono/monodevelop#3531]
I installed both the Nemiver and GDB debuggers and attached the process of gdb and tried to run it but it still displayed this above my project in debugger mode: 
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
Not quite sure why it is not working.  Is it possible that it would be a potential bug?
Many thanks.

**Comment by wboswall** [comment]
I am just following up to see if there is a work around.

**Comment by DavidKarlas** [comment]
Are you trying to debug native app(C/C++) or C#?

**Comment by wboswall** [comment]
Thank you for your reply.  Yes, I am trying to debug native app in both C/C++.  I am assuming that it works fine with C#, F# and VB.NET.  I am just using Codeblock's IDE for c/c++ and use your software for C#,F# and VB.NET.  But I would love to use your software for all of the above and not just partial.  I would just love to know why just donesn't want to debug C/C++ projects.  Also it doesn't like to debug single files of C/C++ either.

**Comment by wboswall** [comment]
I was wondering if the flat pak would be better than the regular latest version on working with both c and c++.

**Comment by wboswall** [comment]
I noticed that the flat pak doesn't support c/c++.  How come?

**Comment by Therzok** [comment]
C/C++ support was removed from the main MonoDevelop repo. The repo that should now be used is https://github.com/mhutch/cbinding

**Comment by wboswall** [comment]
@Therzok Is there a way to install that library?

**Comment by Therzok** [comment]
It seems like the addin does not build. /cc @mhutch 

Once that's fixed, the next step would probably be installing it via the addin maker install target (which would probably be just an `msbuild /t:InstallAddin` invocation)

**Comment by wboswall** [comment]
@Therzok I don't think msbuild invocation would work for Monodevelop on Ubuntu.

**Comment by Therzok** [comment]
I don't know how flatpak works (and I don't have a linux VM handy to test yet), but the targets inside the cbinding repo should be able to detect which MD to install to.

Otherwise, `msbuild /t:PackageAddin` and you can install the addin via the Addin Manager by selecting the mpack file (see `Install from file...`)
<img width="807" alt="screen shot 2017-12-29 at 23 02 22" src="https://user-images.githubusercontent.com/109974/34447424-5bcb1df8-ecec-11e7-8f59-1a41626ddb08.png">
.

**Comment by wboswall** [comment]
@Therzok Thank you for the tip.

**Comment by jstedfast** [comment]
gdb support is dead
