### ISSUE TITLE
F Sharp is not installing properly in Monodevlop in Ubuntu 16.04 LTS X64 bit

### ISSUE THREAD

**Issue by wboswall** [mono/monodevelop#3535]
Hello, I was wondering if you might consider putting F Sharp directly into Mono Develop to limit the time for configuration.  I tried to install the extension under Mono Develop but it just fails and gives no reason.   Thank you.

**Comment by nosami** [comment]
It should already be installed directly. There is no reason to install the
extension separately any more.

**Comment by wboswall** [comment]
When I restarted it up again, and clicked on new project, I still couldn't find F# but could C# and VB.  So I don't know what is going on.  Any suggestions are appreciated.  Thank you.

**Comment by Therzok** [comment]
@nosami is it enabled in the Debug/ReleaseGnome configs?

**Comment by wboswall** [comment]
Hello @nosami and @Therzok!  I tried to look for the setting but couldn't it so I went under tools>add-in manager>gallery>language bindings and then installed F# and then the below incident happened.  Is there any way to workaround this problem? When I first downloaded the IDE, F Sharp wasn't included like C# and VB.NET.  
![monodevelopf](https://user-images.githubusercontent.com/34065293/34395935-457c34c2-eb3b-11e7-920c-6f7cd899c159.png)

**Comment by nosami** [comment]
@wboswall : Which version of monodevelop are you using? I suspect that you are using a version that is quite old now.

You might be better off using the flatpak version which I suspect will be much newer and also I expect this to be better supported in the future. F# is known to work via flatpak. See https://flatpak.org/getting.html and  http://www.monodevelop.com/download/linux/

**Comment by wboswall** [comment]
Hi @nosami actually nope the version that I downloaded was the most recent one.  It's the regular download not the flatpak. The version I have is  6.1.  I'll just uninstall it and install the flatpak.  
Does the flatpak also debug the c/c++ source code also.  I am also having a problem with that too.  I recently posted a question about that too.  
Thank you again @nosami for your helpful advice.

**Comment by nosami** [comment]
@wboswall : not sure about c/c++ source code - I don't use it for that. Let me know how you get on. Thanks!

**Comment by wboswall** [comment]
@nosami I installed the flatpak and then installed the monodevelop software.  However, while testing the F#, I selected the F# tutorial and saved it as a project.  I then compiled it and attempted to run it in both debug and release modes but both failed and gave an (debug) error: Error: Debugger operation Failed cannot start process because a file name has not been provided when attempted to run with out debugger.  In release mode Error: Cannot execute. I then tried to rebuild and clean and tried it again but in both debug and release modes and still gave me the same errors.  
 I also tried creating projects in both C# and VB and still gave me the errors in both debug and release modes.  
The regular install, C# and VB works fine and C/C++ runs fine in run mode but not in debug.  So I don't know why C# and VB doesn't run without a hitch.  F# should also run perfectly also.  
I noticed a few problems also:
- No support for C/C++ in the flat pak

- having to run the flat pak version every time in the terminal is annoying.  If there is a better way, that would welcomed.  

- Can't create library projects for VB, F#, C/C++ just only for C#

- Portable library doesn't include VB and C/C++

- Shared Library doesn't include VB, C/C++

- Multi-platform is only C# supported.  What about including VB, F#, C/C++

- ASP.NET has no VB support 

- Empty Project doesn't support F# and C/C++
These are just mere observations while using Mono.

**Comment by wboswall** [comment]
How do I do a complete uninstall of the flatpak to do a clean install? I ran the flatpak command: flatpak run com.xamarin.MonoDevelop and monodevelop flat pak version still loads up even though it should have been unistalled. I'm confused.

**Comment by nosami** [comment]
@wboswall did you try `sudo flatpak uninstall com.xamarin.MonoDevelop` or `flatpak uninstall --user com.xamarin.MonoDevelop` ?

**Comment by wboswall** [comment]
@nosami I tried the first one and it worked fine.  Thank you for those commands because now I can freshly install it and hopefully it will work properly.  Have you ever heard of it not working properly on Linux distributions like I have experienced?
I never really had this much problems when I first tried it out on Windows a few years ago.  It's kind of strange.

**Comment by nosami** [comment]
As far as I know, most of the issues with flatpak have between resolved. It
should work identically on any Linux distribution, that's the point of
flatpak.

**Comment by wboswall** [comment]
@nosami I agree but for some reason it's not playing nice with Ubuntu which is weird.  I'll do a clean reinstall and see how it goes.

**Comment by nosami** [comment]
<img width="1146" alt="screen shot 2018-01-02 at 17 42 17" src="https://user-images.githubusercontent.com/667194/34493568-7190daba-efe4-11e7-9145-cef422a1c598.png">
I installed Ubuntu 16.04 and the monodevelop flatpak to see how it went. Seems to work ok, but lots of missing templates for some reason.
<img width="630" alt="screen shot 2018-01-02 at 17 48 53" src="https://user-images.githubusercontent.com/667194/34493770-45be86de-efe5-11e7-978a-1049d574f4ac.png">

**Comment by wboswall** [comment]
@nosami Will there be a future update to fix that?

**Comment by nosami** [comment]
@wboswall I will add the F# version of the Multiplatform library. The others all seem to be there (except some from Visual Studio for Mac, Android, iOS etc)

**Comment by nosami** [comment]
F# version of Multiplatorm library is missing from VS for Mac too.

**Comment by wboswall** [comment]
@nosami  Okay thank you for the reply!

**Comment by nosami** [comment]
<img width="550" alt="screen shot 2018-01-02 at 18 42 15" src="https://user-images.githubusercontent.com/667194/34495341-b114ccca-efec-11e7-95d5-a4344198e75d.png">

> I then compiled it and attempted to run it in both debug and release modes but both failed and gave an (debug) error: Error: Debugger operation Failed cannot start process because a file name has not been provided

OK.. can replicate this

**Comment by wboswall** [comment]
That's the same error as I got for all three F# C# and VB.net.

**Comment by wboswall** [comment]
so I'll just use the sudo apt -update flexpak or something to that effect? ...after the update gets released.

**Comment by nosami** [comment]
> so I'll just use the sudo apt -update flexpak or something to that effect? ...after the update gets released.

Something like that :), not so familiar with flatpak

**Comment by wboswall** [comment]
Okay thank you.  What would cause that error when compiling the FS CS and VB.NET. Could the linker not be finding the source code?

**Comment by nosami** [comment]
> Okay thank you. What would cause that error when compiling the FS CS and VB.NET. Could the linker not be finding the source code?

If I were to guess, I would guess that the `mono` isn't being passed into the debugger args. No idea how to debug the flatpak install... I'm hoping that @directhex can chime in.

**Comment by directhex** [comment]
Can you try updating (`flatpak --user update`)? I've pushed an enormous series of changes from the alpha branch, including the first phase of sandbox bypass patches.

![screenshot from 2018-01-02 14-08-33](https://user-images.githubusercontent.com/308992/34496193-97fc7736-efc6-11e7-9b25-d6ebb09d1f53.png)

**Comment by nosami** [comment]
![debug-fs](https://user-images.githubusercontent.com/667194/34496357-2b57bcb4-eff1-11e7-8ab5-605d3b0f05b2.gif)

@directhex : definitely an improvement, but the breakpoint didn't actually hit

**Comment by nosami** [comment]
@directhex for some reason, the .mdb file isn't being copied into the output folder

```
jason@jason-VirtualBox:~/Projects/fsconsole$ tree
.
├── fsconsole
│   ├── AssemblyInfo.fs
│   ├── bin
│   │   └── Debug
│   │       ├── fsconsole.exe
│   │       ├── FSharp.Core.dll
│   │       ├── FSharp.Core.xml
│   │       └── System.ValueTuple.dll
│   ├── fsconsole.fsproj
│   ├── obj
│   │   └── x86
│   │       └── Debug
│   │           ├── fsconsole.exe
│   │           ├── fsconsole.exe.mdb
│   │           ├── fsconsole.fsproj.CopyComplete
│   │           ├── fsconsole.fsproj.CoreCompileInputs.cache
│   │           ├── fsconsole.fsproj.FileListAbsolute.txt
│   │           ├── fsconsole.fsprojResolveAssemblyReference.cache
│   │           └── FSharp.Core.dll
│   ├── packages.config
│   └── Program.fs
├── fsconsole.sln
```

**Comment by directhex** [comment]
OK, well, that's a bug. I don't think it's the cause of the breakpoint not breaking though.

**Comment by nosami** [comment]
Not having the .mdb file in the output folder would cause the debugger to not hit the breakpoint if it wasn't inside a flatpak install. Why that's happening, no idea yet.

**Comment by directhex** [comment]
I think it's an issue with msbuild. Running `msbuild` on the command line skips the .mdb in the bin/ dir, `xbuild` does not.

**Comment by nosami** [comment]
I think there is a missing patch here.... newer versions of mono default to `.pdb`.... I'm just looking now.

**Comment by nosami** [comment]
@directhex https://github.com/xamarin/bockbuild/blob/xamarin/packages/patches/fsharp-fix-mdb-support.patch is missing it seems... newer versions drop this patch

**Comment by directhex** [comment]
OK, dispatching a MD build w/ that patch

**Comment by nosami** [comment]
@directhex - awesome - thanks!

**Comment by directhex** [comment]
https://jenkins.mono-project.com/view/Releases/job/release-flatpak-monodevelop/225/ - it'll take a few hours

**Comment by nosami** [comment]
> https://jenkins.mono-project.com/view/Releases/job/release-flatpak-monodevelop/225/ - it'll take a few hours

Great, will give it a try in the morning

**Comment by nosami** [comment]
@directhex Nice work with flatpak btw, surprisingly easy to get a recent version of MD running on a quite old version of Ubuntu 👍

**Comment by wboswall** [comment]
Cool glad to hear the good news.  I'll reinstall it tonight and will update it regularly.  I'll definitely keep watching this feed for sure.  You guys are awesome.

**Comment by nosami** [comment]
```
22:00:15 Applying patch patches/fsharp/fsharp-fix-mdb-support.patch
22:00:15 can't find file to patch at input line 19
```

try Microsoft.FSharp.`T`argets - 👎  OSX case insensitivity

**Comment by wboswall** [comment]
@nosami Cool! Thank you for the update.

**Comment by directhex** [comment]
Fix works. Promoting through to stable, since it's one of only 2 changes since the last version

**Comment by nosami** [comment]
LGTM 
<img width="846" alt="screen shot 2018-01-03 at 19 22 20" src="https://user-images.githubusercontent.com/667194/34535936-87aedd74-f0bb-11e7-89da-e5696ba27f0c.png">
