### ISSUE TITLE
Fuck flatpak

### ISSUE THREAD

**Issue by mobi12** [mono/monodevelop#3540]
Fuck Flatpak!!!!!why don't take everyone a deb package?

**Comment by nosami** [comment]
Because not everyone use deb packages?

**Comment by breiteswiesel** [comment]
What about using also snap packages?

**Comment by pkillnine** [comment]
@mobi12 rood

**Comment by nosami** [comment]
> What about using also snap packages?

The answer to that can be found here https://apebox.org/wordpress/linux/1184
