### ISSUE TITLE
Mono.TextEditor control and code-completion: how does it work?

### ISSUE THREAD

**Issue by mennodeij** [mono/monodevelop#3554]
I have isolated the `Mono.TextEditor` control from MonoDevelop codebase in an effort to integrate a control that supports syntax highlighting, indentation, folding and code completion into another standalone app (mainly for editing XML where the code completion is based on an XML schema set). 

So far, it works well and syntax highlighting and indentation work out-of-the box (two lines of code).

What I'm having more trouble with, is the code completion. I can bring up a `ListWindow<string>` containing the suggestions, but there is no built-in keyboard navigation. In the monodevelop source, I also found the TextLinkEditMode that uses code completion, but I have a hard time understanding how that edit mode works and what it is supposed to do.

Can anyone help me along towards an XML editor with code-completion based on Mono.TextEditor?

By the way: I have taken Mono.TextEditor from the last 6.x release. What happened to it in 7.x?

**Comment by mrward** [comment]
The TextLinkEditMode I believe is used for inline renaming (renaming multiple variables available in the currently open file in one go) so you probably do not need to look at that for now.

For key handling and code completion I would take a look at the [CompletionTextEditorExtension class](https://github.com/mono/monodevelop/blob/9b425b18fe8605fb6c5e998c33075e099283231f/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs#L129).

Maybe the [Xml Editor text extension](https://github.com/mono/monodevelop/blob/master/main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs) would help.

In 7.x the TextEditor classes should be available in the MonoDevelop.Ide assembly but will probably be using a different namespace.

**Comment by mennodeij** [comment]
After some failed attempts I got it to work, thanks for pointing me towards the XML text editor extension.

**Comment by sor** [comment]
I'm sorry to necromance this thread exactly 2 years after closing...
I also need a nice cross platform C# code editor widget as well and I don't care about much else. I 

@mennodeij :
Did using MonoDevelop's TextEditor turn out to be a good decision?
Is the extraction you performed available somewhere public that I don't need to extract it myself?

@mrward :
Do you think MonoDevelop.Ide.Editor.TextEditor (thats the right one, yes?) is still extractable from the current version or is it tied too much into the rest of MD to be feasible?
I would not mind the editor being just GtkSharp on every platform, would you still recommend using MonoDevelop.Ide.Editor.TextEditor in that case?

**Comment by mrward** [comment]
Might be a better question for @mkrueger about how easy it would be to extract the text editor and use it outside MonoDevelop.

**Comment by mennodeij** [comment]
In the end the decision to use the TextEditor was not kept, and I switched to using Gtk# binding to GtkSourceView, which is more aligned with the cross-platform toolkit we use (Eto).

The extraction is not publicly available and I also don't have it anymore I'm afraid.

**Comment by sor** [comment]
Thanks for your responses.
If I get it done, I need to remember to make it available publicly so anyone else who's in a similar need does have a solution right away ;)
Yesterday I searched through the sln's of MD and thought I might have found a rather extracted version of the texteditor, but sadly it was not... so any bits of input would be greatly appreciated @mkrueger
