### ISSUE TITLE
Roslyn code issues are not configurable anymore

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#3576]
`AnalyzersFromAssembly` still exists, mirroring functionality of `MonoDevelopWorkspaceDiagnosticAnalyzerProviderService`.

The `AnalysisOptionsPanel` only gets analyzers from `AnalyzersFromAssembly`, which doesn't have `Microsoft.CodeAnalysis.CSharp`. So we don't bridge UI for that in MD.

The other problem is that we don't pass in specific diagnostic options on compilation requests:
http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,198

**Comment by Therzok** [comment]
To fix, instead of doing `ToDiagnosticAsync` [here](https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs#L175)

Wrap into own code which switches severity based on the options:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/DiagnosticData.cs,254

**Comment by slluis** [comment]
Fix merged.

**Comment by Therzok** [comment]
I tried bridging the code so we pass in `SpecificDiagnosticOptions` in the compilation options, but we don't support modifying the compilation options on the fly. That would require a lot more work to do right.
