### ISSUE TITLE
[Diagnostics] Implement RuleSet file support

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#3578]
VS normally looks for ruleset files included via MSBuild:

https://github.com/dotnet/roslyn/blob/0c62bae6aade582227232183540fd891254a76cb/src/Compilers/Core/Portable/CodeAnalysis.csproj#L14

Support for that is implemented below for VS:

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/RuleSets/VisualStudioRuleSetManager.RuleSetFile.cs,106

> VS bug #577079

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.726 (master)



Pull Request #9502 merged by: Matt Ward  
 Author: mono  
 Commit: 7cd10e45004a2422b3a4eab51fae6a62d6442efb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.5.0.1610 (release-8.5)



Pull Request #9502 merged by: Matt Ward  
 Author: mono  
 Commit: 7cd10e45004a2422b3a4eab51fae6a62d6442efb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #9502 merged by: Matt Ward  
 Author: mono  
 Commit: 7cd10e45004a2422b3a4eab51fae6a62d6442efb (xamarin/monodevelop)
