### ISSUE TITLE
Message bubble do not show warning code

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3601]
Message bubble do not show the warning code. This means if you want to search for it or suppress it with a pragma, you have to go find it in the error pad.

![image](https://user-images.githubusercontent.com/183285/34734375-8bbe157e-f539-11e7-8425-4f1ac1496f09.png)

One fix for this might be to have an "Errors and warnings" context menu on locations affected by error bubbles. This could have commands in it like "Suppress with #pragma" and "Copy message".

> VS bug #568082

**Comment by slluis** [comment]
We can start by showing the error code in the bubble.

**Comment by slluis** [comment]
Fixed in version 7.5.0.443 (master)

Author: Mike Krüger
Commit: df0b78e94dad7de4982042d49de827d61b6db518 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Mike Kr??ger  
 Commit: df0b78e94dad7de4982042d49de827d61b6db518 (xamarin/monodevelop)
