### ISSUE TITLE
Making MonoDevelop from sources fails on Linux

### ISSUE THREAD

**Issue by dsdante** [mono/monodevelop#3602]
So I have:
Arch Linux
Mono 5.4.1.7
MSBuild 15.4_xamarinxplat.2017.11.27.11.23

When making MonoDevelop from the latest sources, I get at least 50 errors [in the output](https://pastebin.com/raw/qhZsZ7ss). I think this can be the cause:
```
MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
```
For some reason, instead of /usr/bin/msbuild it uses /usr/lib/mono/xbuild/14.0/bin/xbuild.exe.

This issue probably has something in common with [another one](https://github.com/mono/monodevelop/issues/3444), but that one [was fixed](https://bugzilla.xamarin.com/show_bug.cgi?id=60770#c6) in the version 15.4+xamarinxplat.2017.09.14.16.14.

Any help is appreciated.

**Comment by gamesguru** [comment]
try just removing the binary in the /lib folder for a moment.  do a 'whereis mono' to make sure you only have one of those in the path, as well.

i'm assuming you did a submodule update?

**Comment by dsdante** [comment]
The second line (the warning) was from an older log, my bad. I removed it from the OP.

Removing xbuild.exe didn't help, same "using msbuild version '14.0'", but [with a much earlier fail](https://pastebin.com/raw/BUNXtGtf).
```
$ whereis mono
mono: /usr/bin/mono /usr/lib/mono /etc/mono /usr/share/man/man1/mono.1.gz
```
Submodules were updated without problems.

**Comment by gamesguru** [comment]
put the binary back then.  mine says using v14.0 and i get a bunch of warnings, no errors

try running a make clean; make, or a make clean then ./configure ; make
if you have problems with a make install, try running it after a 'sudu su'
is this machine a fresh install of linux, or is there any package history we should be aware of?  ie. installing mono-complete before updating mono to v5.4?  that was what caused it for me.
are you installing the database or extras?

only other suggestion is try a whereis on some other package components, let us know if there are any duplicates with a version mismatch (ie. one is older than the other).  maybe if you removed the older xbuild, it would indicate the /bin one is outdated? unlikely but worth a check

attaching the .binlog file from the /main folder might help

**Comment by dsdante** [comment]
I tinkered at some packages here and there, but I can't think of anything relevant.

I can try installing Mono from sources if you think it worth a try. Or try reverting from Testing repository to the regular one (Mono 5.0.0.100) and building a compatible version of Monodevelop.

Interesting thing, MSBuild executable is actually a DLL:
```
$ cat /usr/bin/msbuild
#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /usr/bin/mono $MONO_OPTIONS /usr/lib/mono/msbuild/15.0/bin/MSBuild.dll "$@"
```

Here is the binlog: [MonoDevelop.binlog.zip](https://github.com/mono/monodevelop/files/1626066/MonoDevelop.binlog.zip)

**Comment by gamesguru** [comment]
mine is a dll too

what versions of gtk-sharp, gtk, gdk, and atk are you running?  downgrade from 3.0 to 2.0 on all counts

**Comment by Tacolizard** [comment]
i managed to solve this issue on arch by uninstalling `msbuild-bin` and installing `msbuild-stable`

**Comment by Tacolizard** [comment]
however then i get the following group of errors:

"/home/taco/monodevelop/main/Main.sln" (default target) (1) ->
"/home/taco/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj" (default target) (2) ->
"/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj" (default target) (4:2) ->
(CoreCompile target) -> 
  Mono.Addins.Setup/AddinPackage.cs(39,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]
  Mono.Addins.Setup/AddinStore.cs(41,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]
  Mono.Addins.Setup/SetupService.cs(37,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]


"/home/taco/monodevelop/main/Main.sln" (default target) (1) ->
"/home/taco/monodevelop/main/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj" (default target) (13) ->
"/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj" (default target) (14:2) ->
  Mono.Addins.CecilReflector/Reflector.cs(37,30): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(36,12): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(281,52): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(281,15): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(293,57): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(293,3): error CS0246: The type or namespace name 'MethodReference' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(319,10): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(354,39): error CS0246: The type or namespace name 'AssemblyNameReference' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(360,37): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(404,49): error CS0246: The type or namespace name 'AssemblyNameReference' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(404,3): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(481,45): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(481,3): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(492,66): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(503,68): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(503,92): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,38): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,69): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,3): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(46,22): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(47,3): error CS0246: The type or namespace name 'DefaultAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(272,104): error CS0246: The type or namespace name 'IMemberDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/taco/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]


"/home/taco/monodevelop/main/Main.sln" (default target) (1) ->
"/home/taco/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj" (default target) (25) ->
(BeforeBuild target) -> 
  /home/taco/monodevelop/main/external/libgit2/src/openssl_stream.c(36,3): error G08E93E1A: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’ [/home/taco/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj]
  /home/taco/monodevelop/main/external/libgit2/src/openssl_stream.c(94,1): error GC2E79D46: variable ‘git_stream_bio_method’ has initializer but incomplete type [/home/taco/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj]
  /home/taco/monodevelop/main/external/libgit2/src/openssl_stream.c(94,19): error GC0CDC97E: storage size of ‘git_stream_bio_method’ isn’t known [/home/taco/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj]
  /home/taco/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj(243,5): error MSB3073: The command "bash build_libgit2.sh" exited with code -1.

**Comment by directhex** [comment]
`make dist` tarballs from download.mono-project.com/sources/monodevelop should build now - the key commits in master are e1de20f0eec6d66e78cf0640f00b03c1afcf7f23 and 94d5c2950c41bbd74cadee61d9191b3fd56dfacd which are cherry-picked into tarballs.

**Comment by directhex** [comment]
And FWIW, GitHub releases will never work, as they exclude submodules (a general problem with `git archive`)

**Comment by livingsilver94** [comment]
I'm having the very same problem @Tacolizard was having in his latest message on Solus, with [this tarball](http://origin-download.mono-project.com/sources/monodevelop/monodevelop-7.5.0.1254.tar.bz2).

**Comment by directhex** [comment]
Bottom one looks like https://github.com/mono/monodevelop/issues/4651

Top one, dunno, Lack of `make restore-packages`, or SharpZipLib not installed.

**Comment by livingsilver94** [comment]
Actually I don't have the libgit2 issue.
Here are my errors. `make restore-packages` did nothing, every needed package has been already downloaded, and SharpZipLib **is** inside packages/
```"/home/fabio/Desktop/monodevelop-7.5/Main.sln" (default target) (1) ->
"/home/fabio/Desktop/monodevelop-7.5/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj" (default target) (2) ->
"/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj" (default target) (4:2) ->
(CoreCompile target) -> 
  Mono.Addins.Setup/AddinPackage.cs(39,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]
  Mono.Addins.Setup/AddinStore.cs(41,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]
  Mono.Addins.Setup/SetupService.cs(37,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj]


"/home/fabio/Desktop/monodevelop-7.5/Main.sln" (default target) (1) ->
"/home/fabio/Desktop/monodevelop-7.5/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj" (default target) (13) ->
"/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj" (default target) (14:2) ->
  Mono.Addins.CecilReflector/Reflector.cs(37,30): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(36,12): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(281,52): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(281,15): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(293,57): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(293,3): error CS0246: The type or namespace name 'MethodReference' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(319,10): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(354,39): error CS0246: The type or namespace name 'AssemblyNameReference' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(360,37): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(404,49): error CS0246: The type or namespace name 'AssemblyNameReference' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(404,3): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(481,45): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(481,3): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(492,66): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(503,68): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(503,92): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,38): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,69): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(528,3): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(46,22): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(47,3): error CS0246: The type or namespace name 'DefaultAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
  Mono.Addins.CecilReflector/Reflector.cs(272,104): error CS0246: The type or namespace name 'IMemberDefinition' could not be found (are you missing a using directive or an assembly reference?) [/home/fabio/Desktop/monodevelop-7.5/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]

    181 Warning(s)
    25 Error(s)
```

**Comment by gamesguru** [comment]
building from source not recommended since latest 7.5 builds are available in synaptic with ubuntu 18.04.  Regarding the Cecil and ICSharpCode namespaces missing, what versions of gtk-sharp, gtk, gdk, and atk are you running?  Must be running v2, as version 3 is not supported

**Comment by livingsilver94** [comment]
What do you mean with 

> building from source not recommended since latest 7.5 builds are available in synaptic with ubuntu 18.04. 

I'm trying to package Monodevelop for Solus, I'm not running Ubuntu.
Anyways, here are the deps I'm currently installing to build it:
```
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(libssh2)
    - pkgconfig(mono)
    - fsharp
    - mono-msbuild
```
gtk-sharp is 2.12.45, mono is 5.4.1.6 and fsharp in 4.0.1.20.1. Speaking of msbuild instead, I built it from [here](https://github.com/mono/linux-packaging-msbuild/releases/tag/debian%2F1%2515.6%2Bxamarinxplat.2018.01.17.14.14-0xamarin2).

**Comment by directhex** [comment]
Do you get results from `gacutil -l | grep ICSharpCode`?

Additionally, there's fairly tight coupling on version numbers for all the pieces at play. The conjunction we expect is:

* MonoDevelop 7.5.x
* Mono 5.10.x
* FSharp 4.1.33
* Mono MSbuild fork from somewhere on mono-2017-12 branch
* OpenSSL 1.0 (not 1.1)

**Comment by livingsilver94** [comment]
Yup, the output is
`ICSharpCode.SharpZipLib, Version=4.84.0.0, Culture=neutral, PublicKeyToken=1b03e6acf1164f73`

So it all could be a matter of outdated dependencies... mono is old, and so is FSharp. OpenSSL is 1.0.2o so it should be OK. MSBuild is from 2018 but that's the less concerning issue since it's not officially in Solus repository yet, I have the faculty of downgrading it before inclusion.

**Comment by directhex** [comment]
Can you upload a COMPLETE build log to Gist?

**Comment by livingsilver94** [comment]
You guessed it right @gamesguru !! Disabling version control did the trick :D

**Comment by gamesguru** [comment]
it's something to do with your machine.  i had 3 out of 4 with this issue, but one i could compile any commit and version control just worked.

never managed to figure out what was 'right' with that one machine, but have a hunch it was related to git 2.15 being manually installed by the .NET core or xamarin oss pakages.  the version control module has some dated dependencies that tend to break other things, but refactoring it is an immense task so you can't blame the guys

**Comment by directhex** [comment]
Version control is a distinct issue (libgit2/libcurl linkage problems), and off-topic for this issue.
