### ISSUE TITLE
RunInMainThread and toolkit invoke issues

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#3613]
We have many abstractions on top of the UI thread invoke methods. Most of them use boxing and/or lambda captures and delegate allocations. We should optimize them in the long run:

GuiSyncObject - allocates lambdas which capture the cb and state

* Possible solution: short-cirtuit Runtime.RunInMainThread and use DispatchService sync context directly.

GtkSynchronizationContext - allocates lambdas on invoking to Gtk

* Possible solution: Write own gtk_timeout handlers which are optimized for this use-case.

RunInMainThread - this currently only boxes a valuetask as of - https://github.com/mono/monodevelop/pull/3614

* Possible solution: Offer an abstraction at MD.Core level of `SyncronizationContext` with `T` passed instead of `state`, and most of the API should now return a `SynchronizationContextWithT`. Then the `T` can be used without boxing in the callback

Xwt: all the invokes wrap lambdas with captures

* Review all the invoke code and fix it up

Thoughts?

> VS bug #576794

**Comment by slluis** [comment]
Can you explain what is the problem and what/how it needs to be fixed?

**Comment by Therzok** [comment]
Take a look at this example:
https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs#L50

The invoke allocates a lambda closure with capture of `d` and `state`. This could be optimized if, for example, we did not go through the `Invoke (Action)` method of Gtk#, but instead wrote our custom timeout.

Another example:
https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/GuiSyncContext.cs#L41

GuiSyncContext, in the common case of not being on the UI thread, allocates lambdas with captures for the `StatefulMessageHandler` and `object`. Moving this to doing `Runtime.MainSynchronizationContext.Post/Send` and wrapping the initial delegate in a new one will allow again to use a static cached delegate for this site, and no lambda closure being allocated.

An example of an already done fix is https://github.com/mono/monodevelop/pull/3614, which passes in the lambda capture arguments via the state parameter, thus avoiding the lambda capture (and the lambda is now a static cached delegate created by the compiler).

These methods are pretty heavily called (in await state machine building), so making them capture-less is going to improve performance in the long run.

**Comment by Therzok** [comment]
I tried making the `GtkSynchronizationContext` captureless some time ago using Gtk# APIs, but it is less efficient. The actual win would happen when we have our own implementation of g_timeout_add for this case.

**Comment by KirillOsenkov** [comment]
I think this is now fixed with https://github.com/mono/monodevelop/pull/3624?

**Comment by Therzok** [comment]
Not all of it. There's also the boxing of valuetuples I want to get rid of.

**Comment by Therzok** [comment]
Closing. The benefits of change 4. are pretty small.
