### ISSUE TITLE
"Open Containing Folder" command doesn't work in Flatpak version

### ISSUE THREAD

**Issue by roman-yagodin** [mono/monodevelop#3620]
"Open Containing Folder" command from the Solution pad context menu just do nothing in Flatpak version. On the contrary, "Open Log Directory" command from "Help" menu opens log directory using desktop-default filemanager without fail.

> Monodevelop: 7.3.2.12 (from official release Flatpak)
Mono: 5.4.1.6 (from Xamarin Debian repos)
OS: Linux Mint Debian Edition Betsy 2 x64 (Debian 8 Jessie)
Desktop: Cinnamon 3.4.6
Filemanager: Nemo 3.4.7

**Comment by directhex** [comment]
This should be fixed, as of 6b22ba9c35b64b794eb654ec8ce10d54b6dbc997
