### ISSUE TITLE
Name Conventions setting is missing in latest build.

### ISSUE THREAD

**Issue by PotterDai** [mono/monodevelop#3625]
It seems Naming Conventions setting is missing in latest build.
Is this done by intention?
Thank you!

**Comment by slluis** [comment]
Where is it missing from? What's the build number?

**Comment by PotterDai** [comment]
Fresh compiled from current master branch
![screenshot 2018-01-18 11 19 31](https://user-images.githubusercontent.com/3758951/35108493-b7bef22e-fc41-11e7-825a-b5b5c001307a.png)

**Comment by slluis** [comment]
I don't think we ever had a Naming Conventions panel there. Maybe it is from an add-in you had installed?

**Comment by PotterDai** [comment]
@slluis 
Not sure if that's the case.
Check this image: https://answers.unity.com/storage/temp/69415-screen-shot-2016-05-04-at-142918.png
There is "Name Conventions" right below standard header.

**Comment by PotterDai** [comment]
@slluis 
This is a screen shot from Xamarin 6.3, you can see what's inside of "Name Convention" panel.
![screenshot 2018-01-18 19 10 22](https://user-images.githubusercontent.com/3758951/35128199-51794306-fc83-11e7-8dd7-0549df2221b3.png)

**Comment by slluis** [comment]
You're right, I forgot about this panel. It was removed in VS for Mac 7.0. This is not likely to come back any time soon since the type system is now based on Roslyn, and Roslyn doesn't support custom naming conventions.

**Comment by mhutch** [comment]
Roslyn does support naming conventions, but they don't map 1:1 so can't easily be migrated

They can be specified in editorconfig files: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions

This will be supported when we merge editorconfig support
