### ISSUE TITLE
Port brace completion to EditorFeatures

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3638]
MonoDevelop currently has [an old copy](https://github.com/mono/monodevelop/tree/master/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket) of the Roslyn EditorFeatures automatic bracket insertion code: 

However, by wiring up the VS editor [IBraceCompletionSessionProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.bracecompletion.ibracecompletionsessionprovider?view=visualstudiosdk-2017) we should be able to consume the [the Roslyn implementation](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/AutomaticCompletion/BraceCompletionSessionProvider.cs) directly.

> VS bug #568078

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.286 (master)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1140 (release-7.7)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5293 merged by: Lluis Sanchez
Author: mono
Commit: 4edf53d2399bf2e6e79b1d49160a066cd7f1de55 (xamarin/monodevelop)
