### ISSUE TITLE
Toggle Suggestion Mode no longer has keybinding or menu entry

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3640]
The 'Toggle Suggestion Mode' command is missing from the Edit Menu and no longer has a keybinding. it's now only possible to find it in the keybindings panel. A number of folks have complained that VS for Mac doesn't have this command.

This is an important feature - it's even called out in the [VS introductory docs](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense#list-members).

We should add it back to the menu and restore the *Ctrl + Alt + Space* keyboard shortcut.

> VS bug #552034

**Comment by sevoku** [comment]
Yeah, it was a design descision to remove it from the main menu, and the keyboard shortcut has been removed much earlier with 3aea18098ae30eec5ea456e688f063366d34482d back in 2013 (@mkrueger do you remember the reason?). We can revert both changes easily. cc @hbons

**Comment by GLjackyvaswani** [comment]
I can confirm that the above issue is not reproduiceble in below builds.

Build Info:

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 945)

Xamarin.Mac
Version: 4.2.0.8 (Visual Studio Enterprise)
Xamarin.iOS
Version: 11.8.0.8 (Visual Studio Enterprise)
Xamarin.Android
Version: 8.2.0.6 (Visual Studio Enterprise)

Gist Link: https://gist.github.com/parasAmbhore/eef24234c94652607602e7c443063f28
Screen Cast: https://www.screencast.com/t/T84eOyNAG

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #3757 merged by: Vsevolod Kukol
Author: mono
Commit: 4daa08a2f8305b11dc944b512658aea0a59b5a34 (xamarin/monodevelop)
