### ISSUE TITLE
Insert Snippet and Surround Selection are separate commands

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3641]
The Insert Snippet and Surround Selection used to be a single command that switched between the between names depending on whether something was selected or not.

This makes sense, as they're basically the name command, except one takes the selection and sticks it in the middle of the template. This meant that they took up a single menu entry *and they had the same shortcut*.

Now they're separate commands, for some reason

> VS bug #576782

**Comment by mkrueger** [comment]
They have even different UIs. However I don't know if surround selection is really that useful. 

The whole snippet system could need a rework - or we just dnd the vs.net one in.

**Comment by mkrueger** [comment]
closing -> we're following the vs.net commands here.
