### ISSUE TITLE
Implicit folders are incorrectly ordered in F# projects

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3747]
I noticed that the folders in FSharp.Compiler.Private.fsproj of http://github.com/Microsoft/visualfsharp are out of order, e.g.  folders `Reflection` and `ErrorText` implied by the fragment of FSharp.Compiler.Private.fsproj below

![image](https://user-images.githubusercontent.com/7204669/35475267-3be0534c-0393-11e8-9d1c-751216eb9ad7.png)

Looking at the [sorting code](https://github.com/mono/monodevelop/blob/8bdbe25b9a00c8767f13c0c844565d5c3ae8d443/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs#L146
) I believe this is because these folders are implied by the Link entries in the project file.  But the sorting code is sorting by file path using the index of the first file in the folder:

            let childfile =
                folder.Project.Files
                |> Seq.tryFind (fun p -> p.FilePath.IsChildPathOf folder.Path)

Note the use of FilePath and folder.Path.

Here's the fragment of the project file:

```
    <Compile Include="..\..\utils\reshapedreflection.fs">
      <Link>Reflection\reshapedreflection.fs</Link>
    </Compile>
    <Compile Include="..\..\utils\reshapedmsbuild.fs">
      <Link>Reflection\reshapedmsbuild.fs</Link>
    </Compile>
    <Compile Include="..\..\utils\sformat.fsi">
      <Link>ErrorText\sformat.fsi</Link>
    </Compile>
    <Compile Include="..\..\utils\sformat.fs">
      <Link>ErrorText\sformat.fs</Link>
    </Compile>
```

> VS bug #566631

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4136 merged by: Jason Imison  
 Author: mono  
 Commit: 5e417fd92ca6bb0721720cd2658418259b60143d (xamarin/monodevelop)
