### ISSUE TITLE
MonoDevelop stops debug randomly inspecting the code under a breakpoint

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#3752]
It happened to me in large projects (like monodevelop, iot or profiler).

To hit the issue:

1) Start a normal debug session on the project
2) Hit a breakpoint
3) Go to next step and repeat this action also inspecting variables 

Expected: All is fine!
Result: Sometimes debugger stops to work and breaks the debugger session. 

I know there are no much information, sorry about that I forgot store the logs. I opened the issue to record this case.
I will attach more info and logs when it happens again.

> VS bug #567924

**Comment by decriptor** [comment]
I've seen this many times. Unfortunately, I don't know that I have better repro steps. It does always seem to happen when inspecting variables. I can't say with certainty, but I think collections (arrays, lists, etc) are probably the worst?

**Comment by DavidKarlas** [comment]
I'm suspecting this might be fixed with fix for https://bugzilla.xamarin.com/show_bug.cgi?id=58508 aka. https://github.com/mono/mono/issues/6299

**Comment by decriptor** [comment]
I'm not sure about the original post, but I know I've seen this dozens of times on mac
