### ISSUE TITLE
Styles.CodeCompletion.SelectionHighlightColor is never used

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#3769]
https://github.com/mono/monodevelop/blob/fb28c6d/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs#L485

> VS bug #571242

**Comment by mkrueger** [comment]
Was requested by design - however I didn't remove the old color there because I think the design will change back.
