### ISSUE TITLE
Completions sometimes show in the middle of strings for F# editing

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3799]
Completions sometimes show in the middle of strings. I don't have a step-by-step repro yet

![image](https://user-images.githubusercontent.com/7204669/35922363-4cfb7104-0c15-11e8-8893-0b3c3f603ce8.png)

> VS bug #563771

**Comment by cartermp** [comment]
I believe this is actually a subset of #3798. String literals are just one of the places where completion should not be shown.

**Comment by nosami** [comment]
I spotted what was going wrong here while debugging https://github.com/mono/monodevelop/issues/3892. Cached lexer tokens are sometimes used to determine whether or not the caret is currently inside a string or comment etc. I just need to remove the cached lexer token lookup - the lexer is quick.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4960 merged by: Jason Imison  
 Author: mono  
 Commit: b5b9c681030f753d0025d8b3621cfbabd6636dd5 (xamarin/monodevelop)
