### ISSUE TITLE
No autocomplete in Xaml files in F# projects

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3802]
Repro: 

1. create a new F# Xamarin Forms application. 
2. Go to the Xaml and press space inside a element's attributes.

Expected: auto-completion of attributes shows
Actual: no auto-complete shows

Auto-complete shows in the corresponding C# project

Ocne we get this working we should put it under automated test.

> VS bug #566617

**Comment by dsyme** [comment]
I’d imagine the completion context is getting information from the project context, possibly via Roslyn.  The F# project context is probably just returning null for something at some point.  It’s not the end of the world if we don’t provide completion through to F# names etc., but we need the basic Xaml attribute completion in order to even learn or use Xaml.

Any pointers to code would be appreciated for when we come to fix this (I haven't looked yet)

**Comment by dsyme** [comment]
@xamarin-release-manager  @nosami Do you know why "Area F# would have been removed as a label?  It's very useful to have the area label to track F#-related issues

**Comment by nosami** [comment]
> Do you know why "Area F# would have been removed as a label? It's very useful to have the area label to track F#-related issues

@slluis ^^ bug in the vs-sync bot?

**Comment by slluis** [comment]
Not really a bug. Labels are mapped to area paths, and there was no area path with the name F#. This is now fixed.

**Comment by nosami** [comment]
Started working on a [Roslyn API for F#](https://github.com/nosami/Roslyn.FSharp) to help with this work and other features.

**Comment by nosami** [comment]
![xamlfsharp](https://user-images.githubusercontent.com/667194/41857393-53d49b36-788f-11e8-959e-3a54d8362094.gif)

I think we should close this for now. XAML intellisense is working for compiled code now and is probably fine for 99% of users.
