### ISSUE TITLE
Incorrect display of type abbreviation in F# tooltip

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3803]
This tooltip is incorrect.   The F# type abbreviation is not being displayed correctly:

Actual: ``type X = List``
Expected: ``type X = int list``

![image](https://user-images.githubusercontent.com/7204669/35925492-bed55f6c-0c1d-11e8-911c-20260fd49393.png)

> VS bug #563781

**Comment by nosami** [comment]
Fixed by #3933

**Comment by slluis** [comment]
Testing sync.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #3933 merged by: Jason Imison  
 Author: mono  
 Commit: 72c8d0024a4fd92ee41a7186050651486bb6ad85 (xamarin/monodevelop)
