### ISSUE TITLE
Generate Method Quick fix doesn't focus on new code nor does offer to support argument names

### ISSUE THREAD

**Issue by kumpera** [mono/monodevelop#3805]
When using the Generate Method quick fix, it won't change the editor to the newly create method.
One can assume that looking at the new method is what most users would want.

Beyond that, this quick fix doesn't offer a way to supply argument names and the user has to edit the v_0, v_1... auto generated then the original call site has expressions for arguments.

> VS bug #566615

**Comment by mkrueger** [comment]
See discussion in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/566615
