### ISSUE TITLE
Insert of two ' characters when pressing ' is incorrect for F# code

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3806]
By default the editor inserts two ``'`` marks when you press ``'`` once.

This is wrong for F# code because ``'T`` is a type variable.

We should just disable this behaviour for this key for F# code

> VS bug #564268

**Comment by mhutch** [comment]
See also https://github.com/mono/monodevelop/issues/3475

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #3828 merged by: Mike Kr??ger  
 Author: mono  
 Commit: 253eca238de88767d32b75e81db22d19ae546fdc (xamarin/monodevelop)
