### ISSUE TITLE
Special case MemberAttributes in flags analyzer

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3815]
The 'Bitwise operation on enum not marked with Flags attribute' analyzer triggers on `System.CodeDom.MemberAttributes`. Unfortunately this is a framework type and there's no way to fix or work around it. In CodeDom code MemberAttributes is used very heavily and so this analyzer becomes pure noise and obscures all the other issues. Can we special case this enum in the analyzer?

> VS bug #565046

**Comment by Therzok** [comment]
This is a RefactoringEssentials bug

**Comment by mhutch** [comment]
What's the resolution for this?

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/pull/3830

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #3830 merged by: Mike Kr??ger  
 Author: mono  
 Commit: b473fef2769b9550252258382cb4f597140228da (xamarin/monodevelop)
