### ISSUE TITLE
Encapsulate field quick fix broken pos-apply navigation change

### ISSUE THREAD

**Issue by kumpera** [mono/monodevelop#3825]
I'm using 7.4 build 884.

After using the "Encapsulate Field" quick fix, it sends me to the end of the source file which makes no sense. Either keep me where I am like other quick fixes/refactorings or navigate me to the new definition.

> VS bug #566614

**Comment by mkrueger** [comment]
Can't reproduce that

**Comment by kumpera** [comment]
I'm on 7.4 build 1033 and can't no longer reproduce as well.
I'll reopen if I find a reliable way to reproduce this issue.
