### ISSUE TITLE
Quick fix context dialog incorrectly handles enter key

### ISSUE THREAD

**Issue by kumpera** [mono/monodevelop#3826]
I'm using the 7.4 preview.

In the quick fix preview, say I have "Generate variable name" and there are multiple options to it. If i press enter it dismiss the dialog and nothing happens.

This is pretty confusing, specially since it doesn't navigate me to the new code if I picked one of the sub-options.

> VS bug #566612

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.527 (master)

Pull Request #3955 merged by: Mike Krüger
Author: mono
Commit: abf24c68b78f6b779366f6e91126a4842ec16276 (mono/monodevelop)
