### ISSUE TITLE
"[TestCaseSource ("xzy")]" isn't seen as a test in the text editor. No dot next to it.

### ISSUE THREAD

**Issue by decriptor** [mono/monodevelop#3869]
Methods with the `[Test]` or `[TestCase ()]` attribute on it have a dot in the margin that allows you to execute a test. However, a method with the `[TestCaseSource()]` attribute doesn't have a dot in the margin.
<img width="294" alt="screenshot 2018-02-15 13 44 17" src="https://user-images.githubusercontent.com/49821/36280053-59f9e13c-1256-11e8-8866-f4e4c65d2c12.png">

> VS bug #569964

**Comment by decriptor** [comment]
TestCaseSource docs -> https://github.com/nunit/docs/wiki/TestCaseSource-Attribute

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.628 (master)

Pull Request #5412 merged by: Lluis Sanchez
Author: mono
Commit: 43a85f8419405146f239dd96b345d0eb9012369b (mono/monodevelop)
