### ISSUE TITLE
Updating PackageReference removes metadata

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3881]
Right clicking on a package reference in the solution tree and choosing "update" caused the following changes to my project:

![image](https://user-images.githubusercontent.com/183285/36331660-c842bcd6-133c-11e8-943c-15140b8abd63.png)

It seems to have removed and re-added them, changing the location and removing important metadata.

> VS bug #568994

**Comment by slluis** [comment]
Fixed in version 7.6.0.1769 (release-7.6)

Author: Matt Ward
Commit: bccffdeeeb200769602a03eaa9d4073952b6e206 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: 3fb4abda8f2e8e15df68521b361c3489edc2bacb (xamarin/monodevelop)
