### ISSUE TITLE
[F#] Update to FSharp.Core nuget 4.3.4

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3894]
We should update FSharp.Core used in monodevelop to the latest FSharp.Core nuget package (4.3.4)

A simple `paket update` in main/external/fsharpbinding should do the trick

4.3.4 includes an incremental update containing Async.StartImmediateAsTask, which should I believe generally be used instead of Async.StartAsTask

> VS bug #569218

**Comment by nosami** [comment]
This ticket was closed in favour of https://github.com/mono/monodevelop/issues/5029
