### ISSUE TITLE
[ F# ] Remove/review use of locking and Async.RunSynchronously

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#3896]
The implementation of the F# binding has uses of Async.RunSynchronously that look suspicious 

For example this code https://github.com/mono/monodevelop/blob/d4627becd4fef461a2e667ddbac41280d0d80209/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTextEditorCompletion.fs#L442 which contains both a very suspicious use of a lock and a nested call to RunSynchronously.

I believe this should be something like this:
```
                let! typedParseResults =
                    asyncMaybe {
                        let! document = documentContext.TryGetFSharpParsedDocument() |> async.Return
                        let! location = document.ParsedLocation |> async.Return
                        let trimmedLine = lineToCaret.TrimEnd()
                        let reparse = trimmedLine.EndsWith("->") || trimmedLine.Contains(").") || trimmedLine.EndsWith("].")
                        if location.Line = context.line && not reparse then
                            LoggingService.logDebug "Completion: got parse results from cache"
                            return! document.TryGetAst() |> async.Return
                        else
                            LoggingService.logDebug "Completion: syncing parse results"
                            // force sync
                            let projectFile = documentContext.Project |> function null -> document.FileName| proj -> proj.FileName.ToString()
                            let! ast = languageService.ParseAndCheckFileInProject(projectFile, document.FileName, 0, editor.Text, true) |> Async.map Some
                            document.Ast <- ast
                            return ast
                    }
```

> VS bug #569293

**Comment by dsyme** [comment]
@nosami Do you happen to know if MD is "good" at sending cancellation requests for activity (e.g. for computing completions) when the results will no longer be needed (e.g. the completions have been dismissed)?  I assume so.  Visual Studio/Roslyn is good at sending these and it's critical to prevent ever-growing request queues.

If so the above feels right. It has the advantage that if the completion request gets cancelled then the ParseAndCheckFileInProject request will also be cancelled.

**Comment by Therzok** [comment]
@dsyme completion requests are cancelled on every keypress. Doesn't seem to happen when manually triggering completion, which is a bug.

**Comment by Therzok** [comment]
Fixed that: https://github.com/mono/monodevelop/pull/3906

**Comment by nosami** [comment]
Fixed by https://github.com/mono/monodevelop/pull/3897
