### ISSUE TITLE
[Multi-targeting] Support building multi-targeted projects

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3958]
When building a project with multiple `TargetFrameworks`, build all of them

> VS bug #572330

**Comment by JelleDamen** [comment]
Is there a roadmap to see when this feature will be available ?

**Comment by ChaseFlorell** [comment]
With all of the blog posts from prominent MS MVP's et al pushing folks to use Multi-Targeting, I would hope the team here is going to give this higher priority. We've now run into this issue hard whereby we have conflicting configurations with no way out.

if we use `netstandard2.0;netstandard1.4` we run into https://github.com/dotnet/project-system/issues/1519

if we use `netstandard1.4;netstandard2.0` we can't build our project in VS for Mac.

**Comment by mattleibow** [comment]
I just noticed in the latest previews I can open those multi-target projects and it builds. Just the first platform, but it still builds!

**Comment by mhutch** [comment]
@mattleibow yes, that has been the behavior since before this bug was filed. This bug is about building the rest of the frameworks :)

Note that in addition to multitargeted projects not building completely, projects in the same solution that reference these multitargeted projects will often fail to build as the assemblies they're referencing will not be built.

**Comment by mattleibow** [comment]
Yeah, I noticed that 😄 Now, this I am not trying to be snarky, but I genuinely don't know: can't the IDE just run MSBuild on the entire project? Why doe it pick a particular platform? When I hit that build button, is it not actually using the MSBuild bits but trying something "fancy"?

**Comment by mhutch** [comment]
It's not that simple. MD doesn't invoke MSBuild to build the solution, it hosts MSBuild in a builder process and uses the MSBuild hosting APIs to load the projects.

There are quite a few reasons for this:

* It can query information from MSBuild for each project e.g. getting the resolved assemblies from MSBuild so it can initialize the Roslyn workspace for IntelliSense.
* It gets direct access to MSBuild log events for reporting progress and build output.
* Build perf is improved a little - when you build, the projects have already been loaded and evaluated, and just need to be executed.
* It can completely avoid building _individual projects_ in the solution if it knows that their files haven't been touched since they were last built.
* It can build projects in parallel, which Mono's MSBuild does not yet support.
* MSBuild doesn't have a hosting API for loading projects, just solutions.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.3.0.88 (master)



Pull Request #7658 merged by: Marius Ungureanu  
 Author: mono  
 Commit: c551d6fdc09129bfa3b1bb33205eb35677643c88 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.2.0.542 (release-8.2)



Pull Request #7658 merged by: Marius Ungureanu  
 Author: mono  
 Commit: c551d6fdc09129bfa3b1bb33205eb35677643c88 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-42] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7658 merged by: Marius Ungureanu  
 Author: mono  
 Commit: c551d6fdc09129bfa3b1bb33205eb35677643c88 (xamarin/monodevelop)
