### ISSUE TITLE
Make adding PackageReferences to multi-framework projects robust

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3964]
In projects with multiple `TargetFrameworks`, it should be possible to add a PackageReference to a NuGet package that is only supported in some of the frameworks. In this case, the PackageReference should be added with a TargetFramework condition so that it's only included in the frameworks that support it (possibly with UI confirmation)?

> VS bug #572317

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.2.0.161 (master)



Author: Matt Ward  
 Commit: b3e30152db46e70acbfce985847cfc4dde8bf62e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-30] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: b3e30152db46e70acbfce985847cfc4dde8bf62e (xamarin/monodevelop)
