### ISSUE TITLE
[Multi-targeting] Multi-framework support in Roslyn workspace

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3967]
The Roslyn workspace should contain multiple instances of multi-framework projects, once instance for each framework, with all project references wired up to the correct framework-specific project instance.

This will fix intellisense in "normal" projects referencing multi-framework projects.

> VS bug #572311

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.4.0.775 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-32] Comment by **xamarinc**



Fixed in version 8.3.0.1260 (release-8.3)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-39] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (xamarin/monodevelop)
