### ISSUE TITLE
[Multi-targeting] Execution target support for multi-framework projects

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3968]
The execution target picker for multi-framework projects should support picking any of the execution targets for any of the target frameworks.

> VS bug #572309

**Comment by UKDeveloper99** [comment]
8.3 that's ages away :( 

Can we not fast-track this one a bit?

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-36] Comment by **xamarinc**



Fixed in version 8.4.0.775 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-37] Comment by **xamarinc**



Fixed in version 8.3.0.1260 (release-8.3)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-44] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (xamarin/monodevelop)
