### ISSUE TITLE
[Multi-targeting] Ensure navigation/refactoring operations on multi-frameworks projects are coalesced

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3970]
When working with projects with multiple target frameworks, navigation and refactoring operations like “Find References” and "Rename" should deduplicate when results are found in multiple of the per-framework Roslyn project instances. In theory Roslyn handles this but we should verify it.

> VS bug #572307

**Comment by mhutch** [comment]
(hopefully shproj already handled this)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-27] Comment by **xamarinc**



Fixed in version 8.4.0.775 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.3.0.1260 (release-8.3)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (xamarin/monodevelop)
