### ISSUE TITLE
[multi-targeting] Support picking target framework for intellisense

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3974]
When editing files in a multi-framework project, the editor should support picking the target framework to use for intellisense/#defs/etc via a combobox in the editor breadcrumbs.

> VS bug #572342

**Comment by nosami** [comment]
Doesn't VS (Windows) show completions for all frameworks (where they differ) in the completions list here?

**Comment by mhutch** [comment]
Maybe, but we still need this to pick which project is used for analyzers, defines, etc

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.4.0.775 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.3.0.1260 (release-8.3)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-42] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7848 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ae85672d1f783b3b84fe1a018fc46aed49ec5fef (xamarin/monodevelop)
