### ISSUE TITLE
VSforMac crashes opening a Xamarin.Forms solution

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#3978]
I am in alpha channel, I tried to create a normal Xamarin.Forms solution and VSforMac is crashing

1) Open Blank Forms App
2) It crashes!

Attached log

https://gist.github.com/netonjm/45e9a396e128e59e42ac8e9897b0514e

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 1026)
Installation UUID: ac2f5f5a-65c6-4e02-aae1-61d2ac9aabc1
Runtime:
	Mono 5.8.0.127 (2017-10/1eac626536b) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000127

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
	1.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview2-003156
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Users/jmedrano/Projects/profiler/src/XamarinProfiler.Mac/bin/Debug/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.2.0.15 (Visual Studio Enterprise)
Android SDK: /Users/jmedrano/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.2.0.20 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.8.0.20 (Visual Studio Enterprise)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704001026
Git revision: 56e88d4d0e790e77e1414b8fed22832260fb244f
Build date: 2018-02-16 13:51:48-05
Xamarin addins: 593b39138609e1e4fa0da4c1a1cdfecc97a285a5
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Gist Ide Information 1.1.0
AddinMaker 1.4.2
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.2
Redth's Addins 1.0.9
Show in Github 1.0.4
Internet of Things (IoT) development (Preview) 9.2

> VS bug #572820

**Comment by slluis** [comment]
The problem seems to be that `DocumentContext.OnDocumentParsed()` is not always called from the UI thread.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.629 (master)

Author: Mike Krüger
Commit: 9450d0176dca33f472ba750c896c2ab679843add (mono/monodevelop)

**Comment by slluis** [comment]
Reopening until the fix is merged to 15.6.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '7.4' that is not in the list of supported values
