### ISSUE TITLE
F# templates are missing some references in the iOS projects

### ISSUE THREAD

**Issue by dsyme** [mono/monodevelop#4008]
The F# iOS template is missing some references which cause problems in some corner cases. We need to have all of these.  

    <Reference Include="mscorlib" />
    <Reference Include="System.Numerics" />
    <PackageReference Include="FSharp.Core" Version="4.3.3" />

* `mscorlib`: without it the latest alpha of VS for Mac (7.4 Preview build 1026) shows a red squiggly in AppDelegate.fs of the iOS project when adding a reference to a .NET Standard 2.0 F# library. 

* `FSharp.Core`: The explicit reference to FSHarp.Core is needed to avoid using the old-and-out-of-date FSharp.Core that is part of the iOS framework.  We no longer want to reference that FSharp.Core and instead always use the package reference.

* The explicit reference to `System.Numerics` is necessary to support the reference to the FSharp.Core package

> VS bug #574374

**Comment by nosami** [comment]
fixed by https://github.com/xamarin/md-addins/pull/2937/commits/929aa5ebbfac0b3ed867e89893f9ecfd97e64ee3
