### ISSUE TITLE
mono-addins caching broken on filesystems without mdate

### ISSUE THREAD

**Issue by directhex** [mono/monodevelop#4029]
In Flatpak, all files in an app's install tree have a creation time of epoch 0 (allowing deduplication of files whose only difference is creation time).

Mono-addins uses date on files to determine whether the cache is stale or not - and never decides a cache is stale, on Flatpak. As a result, Flatpak MonoDevelop includes a workaround to regenerate the entire addin cache at every startup (which is slow and sucks).

Mono-addins should (optionally?) include another mechanism to determine staleness, e.g. file size.

> VS bug #575664

**Comment by directhex** [comment]
@slluis which minimum version of mdtool provides this?

**Comment by slluis** [comment]
There is no official release of mono-addins that supports this feature. I'll try to make one.

**Comment by directhex** [comment]
Don't worry about shipping releases, if MD is the only consumer. Just wondered about branches, but the 15.8 milestone was already added above. I'll wait for that to hit alpha, and can integrate the changes on linux.
