### ISSUE TITLE
GitHub zips do not build when downloaded

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4034]
We lack the generated `buildinfo` that's added into tarballs. We should figure out a way to have the `buildinfo` without depending on a git repo in that case. Maybe, if not under git and no buildinfo, generate a mock one?

**Comment by akoeplinger** [comment]
The GitHub zips are pretty useless in general since they don't contain submodules...

**Comment by Therzok** [comment]
@akoeplinger you're right!
