### ISSUE TITLE
IDE needs to provide a mapping between a file type and it's roslyn language name

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4036]
See https://github.com/mono/monodevelop/blob/a5e61d670bb0ca4755ee959db9e6c5a643a1d041/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.Legacy.cs#L75

We need a smarter way to map a file to a roslyn language name so we can just probe whether the language service for the language exists.

> VS bug #576712

**Comment by mhutch** [comment]
This metadata exists in the mimetype system, see DesktopService.GetMimeTypeForRoslynLanguage

We just need a method that does the opposite lookup on the same data.

**Comment by Therzok** [comment]
`GetRoslynLanguageForMimeType` was added. To fix the usage in CommentTasksProvider.

**Comment by mhutch** [comment]
In b720ddf0c7b70d0e5a25f1dd1b0475ec205c9d5e, specifically :)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.2.0.125 (master-vnext)



Pull Request #716 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: d268eb11024f3fc9a17630cbc6b5e252a19a1fdb (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #716 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: d268eb11024f3fc9a17630cbc6b5e252a19a1fdb (xamarin/monodevelop)
