### ISSUE TITLE
Report version of Xamarin.Mac that's used at runtime

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4057]
Request from @alanmcgovern to have the Xamarin.Mac version that we use in the logs and the about dialog.

> VS bug #577285

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 7cfd9c80e6a4503c964abbec6390c542da65968c (xamarin/monodevelop)
