### ISSUE TITLE
Missing files in Xamarin Forms SDK style shared project (Master)

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4061]
![image](https://user-images.githubusercontent.com/667194/37043703-40aec582-2159-11e8-889e-65597afb9a03.png)

> VS bug #577354

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.58 (master)

Pull Request #2956 merged by: Jason Imison
Author: xamarin
Commit: a53d2ac386d1c26dbe9197c66b4d9bd0309d90aa (xamarin/md-addins)
Included in Commit: ec60978fd3203022a2f7a51baf16c91f8f1102e2 (mono/monodevelop)
