### ISSUE TITLE
[editorconfig] Cannot remove vertical ruler

### ISSUE THREAD

**Issue by garuma** [mono/monodevelop#4086]
With the editorconfig branch merged in if you have a max column setting declared, the vertical ruler bar shows up in the editor all the time despite the setting “Show column ruler” being disabled.

VSWin doesn’t do that, is that expected or an issue?

(i.e. you might have a max column setting for formatting without actually wanting the visual cue with it)

> VS bug #578758

**Comment by mkrueger** [comment]
if you've it in editorconfig it's expected we only have that for showing a column. There is nothing else. 

setting max_line_length=off turns that off. Editorconfig always overrides IDE settings.
