### ISSUE TITLE
Remove ManagedEsent dependency

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4089]
Roslyn 2.6+ does not use ManagedEsent any longer. No need to ship it anymore.

> VS bug [#581513](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581513)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 48a70cd618b7478cf15622a8d1938f0e4bc6e320 (xamarin/monodevelop)
