### ISSUE TITLE
F# should get its list of keywords from FCS instead of using hardcoded list

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4095]
As discussed in [this issue](https://github.com/Microsoft/visualfsharp/pull/4427) that adds a new keyword to F#.

https://github.com/Microsoft/visualfsharp/blob/1e7037cba0119b0d53fc60c8cc0d7e3d7813ff17/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L45-L47

> VS bug #578995

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4111 merged by: Jason Imison  
 Author: mono  
 Commit: c707183f3b723254ce96da22ad31b676ac17a7bb (xamarin/monodevelop)
