### ISSUE TITLE
Xamarin Studio. Cound not launch web server.

### ISSUE THREAD

**Issue by akoeplinger** [mono/monodevelop#4097]
_From @edsokolova on March 18, 2016 8:41_

I'm trying to remote debugging. But I can't...

Steps (using Windows):
1. I set an environment variable named MONODEVELOP_SDB_TEST to 1.
2. Open project.
3. Run -> Run With -> Custom Command Mono Soft Debugger.
4. Write IP, Port. 
5. Click 'Listen' (or 'Connect', have the same problem).

After that I have a message:
"Could not launch web server. Unable to cast object of type 'MonoDevelop.AspNet.Execution.AspNetExecutionCommand' to type  'MonoDevelop.Core.Execution.DotNetExecutionCommand' ".

_Copied from original issue: mono/md-website#50_

**Comment by akoeplinger** [comment]
_From @nikhil850144 on August 3, 2017 6:50_

i experience same issue with mono develop 5.10.0 on Linux any update on this issue ?

**Comment by DavidKarlas** [comment]
is that monodevelop 5.10? can you update to something newer?

**Comment by DavidKarlas** [comment]
Here are instructions on how to install latest versions on Linux: https://www.monodevelop.com/download/#fndtn-download-lin
