### ISSUE TITLE
Xamarin Live Player not launching in Android when running VS4Mac 7.4 with XamarinForms app

### ISSUE THREAD

**Issue by knocte** [mono/monodevelop#4104]
Trying to deploy/run [this app](https://github.com/knocte/gwallet/tree/frontend) through Xamarin Live Player in Android returns in the following output:

```
Running /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.Droid/bin/Debug/GWallet.Frontend.XamForms.Droid.dll…
Start GWallet.Frontend.XamForms.Droid, Sony G3116 Player, .
Attempting connection to debug address: 10.178.101.157:37847.
Connected to: 10.178.101.157:37847.
Deploying /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.Droid/GWallet.Frontend.XamForms.Droid.fsproj…
Got device info: Sony G3116 Player (Android) @ 10.178.101.157:37847
Synchronizing files…
Building and running…
Built with 0 messages.
Deploy to Sony G3116 Player succeeded.
```

So, no errors; however, the application is never launched in the phone.

Using Xamarin Live Player extension v1.3.131 along with VS4Mac 7.4 build 1033

> VS bug [#587464](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/587464)

**Comment by jamesmontemagno** [comment]
F# development with the Xamarin Live Player is only supported on iOS at the moment. I will be sure to add this to the limitations documentation.

**Comment by olegoid** [comment]
Closing this issue for now.

**Comment by knocte** [comment]
@jamesmontemagno why not give the user an error message saying that it's not supported? Just placing this limitation in the documentation will cause a lot of confused users.
