### ISSUE TITLE
C# 7.2 LangLevel option is broken

### ISSUE THREAD

**Issue by yamachu** [mono/monodevelop#4105]
Now we can set compile lang level C# 7.2 via ProjectOption panel.
But if we set this, csproj shows 702, not 7.2

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.103 (master)

Author: Yusuke Yamada
Commit: a0f239a8fecbb9bdbc1650215ab6e8f371c524eb (mono/monodevelop)
