### ISSUE TITLE
Inconvenient behavior of Ctrl+Right and Ctrl+Left

### ISSUE THREAD

**Issue by jkpubsrc** [mono/monodevelop#4110]
Pressing Ctrl plus Cursor-Right or Cursor-Left will let you skip too much code in the edit component. MonoDevelop exhibits a quite strange behavior here compared to other IDEs and general text editors.

Here is a more detailed analysis of the situation describing stops that occur if pressing Ctrl+Right:

```
foo ( ) [ ] { }  bar
```

* MonoDevelop:
    * after "foo"
    * after "bar"
* Pluma:
    * after "foo"
    * after "bar"
* Notepad (Mono):
    * before "("
    * before "["
    * before "{"
    * before "bar"
* VisualStudioCode:
    * after "foo"
    * after "("
    * after ")"
    * after "["
    * after "]"
    * after "{"
    * after "}"
    * after "bar"
* Github text edit control in FireFox:
    * after "foo"
    * before ")"
    * before "["
    * before "]"
    * before "{"
    * before "}"
    * after "bar"
* vi
    * before "("
    * before ")"
    * before "["
    * before "]"
    * before "{"
    * before "}"
    * before "bar"
* NetBeans:
    * after "foo"
    * before "("
    * before ")"
    * before "["
    * before "]"
    * before "{"
    * before "}"
    * before "bar"
    * after "bar"
* LibreOffice Writer:
    * before "("
    * before ")"
    * before "["
    * before "]"
    * before "{"
    * before "}"
    * before "bar"
    * after "bar"

As you can see MonoDevelop behaves more than a regular text editor than as an IDE. We software developers have special needs in regard to backets and other delimiters. Even LibreOffice is more convenient in that regard.

This is extremely annoying if you want to mark something by pressing Shift as well. If you have comment lines starting with "//" - even multiple comment lines - it can happen that a single press of Ctrl+Right will pass through many many source code lines. You can NOT mark a single line comment conveniently.

I'd personally expect a Ctrl+Right to somehow ...

* stop before "//" which mark the beginning of a line comment (as I'd like to mark them sometimes which can't be done no as easily as in other IDEs)
* stop before "("
* stop before "{"
* stop before "."
* stop before any word.

For example Visual Studio Code seems to stop whenever some character is followed by a whitespace. If no whitespaces occur stops are performed before "[", before "(", after "}" and before ".". This might be debatable but it's much more convenient than the behavior in MonoDevelop where there is almost no stop.

I've no idea what would be the best behavior as almost every text edit component behaves differently. But the least I can say is that NOT stopping on brackets and delimiters at all is not a very good option. Not for an IDE. I recommend to rethink that behavior in general terms and improve that.

> VS bug [#580788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/580788)

**Comment by slluis** [comment]
This behavior can be configured in the global preferences: Text Editor / Behavior / Word break mode. The "Windows" work break mode behaves like VS Code. To be honest, I don't remember why the two options are named "Linux" and "Windows". Maybe it is because the widget that was used originally to implement the editor (GtkSourceView) used that "Linux" word breaking mode, and then later we introduced the "Windows" mode to emulate VS for Windows. In any case, it makes sense to default to the "Windows" mode. /cc @mkrueger

**Comment by jkpubsrc** [comment]
You mean: These options are not merely not just groups of existing settings but switching between complete source code layout engines???? That's extremely strange, if you ask me. I'll check on that soon. If that's so I'm neither understanding why it would be labeled "Windows" and "Linux" as you said, nor am I understanding why it is not described in more detail, nor I am understanding, why it is the default at all. What sense would it make to have such a behavior THE DEFAULT if a much better option is available??? Well, I'll check your recommendation soon.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.718 (master)

Pull Request #5420 merged by: Mike Krüger
Author: mono
Commit: 6cfc80563481bfe37e9ee3e4952613485696abc3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.38 (master)

Pull Request #5517 merged by: Mike Krüger
Author: mono
Commit: aff230c466be728852be48392f745b9b2647125e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.126 (release-7.7)

Pull Request #5517 merged by: Mike Krüger
Author: mono
Commit: aff230c466be728852be48392f745b9b2647125e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.931 (release-7.7)

Pull Request #5517 merged by: Mike Krüger
Author: mono
Commit: aff230c466be728852be48392f745b9b2647125e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5517 merged by: Mike Kr??ger
Author: mono
Commit: aff230c466be728852be48392f745b9b2647125e (xamarin/monodevelop)
