### ISSUE TITLE
Unable to install monodevelop on fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by fderoo** [mono/monodevelop#4127]
## Steps to Reproduce

1. Install Ubuntu 16.04
2. Attempt to install Monodevelop following the instructions at  [https://www.monodevelop.com/download/](url)

## Current Behavior

After adding the third party repo, updating apt-get, and running `sudo apt-get install monodevelop`, a lot of packages have unmet dependencies. 

               Depends: mono-runtime-sgen but it is not going to be installed
               Depends: mono-xbuild but it is not going to be installed
               Depends: mono-runtime (>= 3.0~) but it is not going to be installed
               Depends: libgconf2.0-cil (>= 2.24.0) but it is not going to be installed
               Depends: libglade2.0-cil (>= 2.12.10-1ubuntu1) but it is not going to be installed
               Depends: libglib2.0-cil (>= 2.12.10-1ubuntu1) but it is not going to be installed
               Depends: libgnome-vfs2.0-cil (>= 2.24.0) but it is not going to be installed
               Depends: libgnome2.24-cil (>= 2.24.0) but it is not going to be installed
               Depends: libgtk2.0-cil (>= 2.12.10-1ubuntu1) but it is not going to be installed
               Depends: libmono-cairo4.0-cil (>= 4.0.4.1) but it is not going to be installed
               Depends: libmono-corlib4.5-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-microsoft-build-engine4.0-cil (>= 3.2.1) but it is not going to be installed
               Depends: libmono-microsoft-build-framework4.0-cil (>= 3.6.0) but it is not going to be installed
               Depends: libmono-microsoft-build-utilities-v4.0-4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-microsoft-csharp4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-posix4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-sharpzip4.84-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-componentmodel-dataannotations4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-configuration4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-core4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-data-services-client4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-data4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-design4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-drawing4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libmono-system-numerics4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-runtime-serialization4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
               Depends: libmono-system-security4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
               Depends: libmono-system-web-mvc3.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-web-razor2.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-web-services4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-web-webpages-razor2.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-web4.0-cil (>= 2.10.3) but it is not going to be installed
               Depends: libmono-system-windows-forms4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-xaml4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-xml-linq4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system-xml4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-system4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: libmono-windowsbase4.0-cil (>= 4.2.0) but it is not going to be installed
               Depends: monodoc-base (>= 3.2.1) but it is not going to be installed
               Recommends: libglade2.0-cil-dev but it is not going to be installed
               Recommends: libgtk2.0-cil-dev but it is not going to be installed
               Recommends: mono-devel but it is not going to be installed

After manually installing the dependencies, i managed to reduce that list to two items

               The following packages have unmet dependencies:
               monodevelop : 
                       Depends: libfsharp-core4.3-cil (>= 4.1.33) but 4.1.25-0xamarin4+ubuntu1604b1 is to be installed
                       Depends: msbuild but it is not going to be installed

The error tells me it needs the libfsharp-core4.3-cil package at version 4.1.33 but 4.1.25 is installed. 
Running `apt-cache policy libfsharp-core4.3-cil` shows me that i already have the last version

               libfsharp-core4.3-cil:
               Installed: 4.1.25-0xamarin4+ubuntu1604b1
               Candidate: 4.1.25-0xamarin4+ubuntu1604b1
               Version table:
               *** 4.1.25-0xamarin4+ubuntu1604b1 500
               500 http://download.mono-project.com/repo/ubuntu vs-xenial/main amd64 Packages
               500 http://download.mono-project.com/repo/ubuntu vs-xenial/main i386 Packages
               100 /var/lib/dpkg/status

The second dependency ask me to install mono-xbuild ( >= 1.0.0) but when i manually install it it tells me it is already installed at version ( `mono-xbuild is already the newest version (5.8.0.129-0xamarin1+ubuntu1604b1).
` )

## Expected Behavior

One single installation with all its dependencies met and correctly installed.

### On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:

7.4 (7.4.0.1033) (according to the MonoDevelop website)

**Comment by directhex** [comment]
Yeah, seems about right. I need to do another build, against older F# in vs- repo.

**Comment by directhex** [comment]
Doing new builds now, but it might take a few days for a successful set to get published.

**Comment by directhex** [comment]
Looks like the msbuild version in vs-* was wrong too (the build compatible with Mono 5.8 wasn't copied over, the version in there already works on 5.4 but not newer). Republishing in progress.

**Comment by directhex** [comment]
Fixed another repo issue - F# was missing entirely on Debian 8.

**Comment by fderoo** [comment]
When you say "Fixed" do you mean the whole problem is fixed ?

Thanks a lot for your celerity

**Comment by directhex** [comment]
In the process of trying to resolve the issue (monodevelop in vs-* requires fsharp from preview-*) a bunch of other issues have come to light, so it's taking time to resolve.

**Comment by monyarm** [comment]
i'm getting the following on 17.10 monodevelop : Depends: libfsharp-core4.3-cil (>= 4.1.33) but 4.1.25-0xamarin4+ubuntu1604b1 is to be installed

**Comment by monyarm** [comment]
As a temporary workaround is there any way for me to install a slightly older version ? I don't neceserilly need 7.4, the latest i need is 7.3.3, though 6.9 would also work, can i somehow force apt-get to install an older version ?

**Comment by directhex** [comment]
reprepro (the repo management software) doesn't retain old versions.

The workaround is to switch to a `stable-*` or `preview-*` repo instead of `vs-*` as those repositories include a newer F# (also newer Mono)

**Comment by directhex** [comment]
http://www.monodevelop.com/download/beta/

**Comment by monyarm** [comment]
Thanks, i managed to install it

**Comment by Polatouche** [comment]
Release and beta version are both 7.4.0.1033.
I can't install monodevelop on my ubuntu 14.04 box due to
«Les paquets suivants contiennent des dépendances non satisfaites :
 monodevelop : Dépend: libfsharp-core4.3-cil (>= 4.1.33) mais 4.1.25-0xamarin4+ubuntu1404b1 devra être installé»

$ mono --version
Mono JIT compiler version 5.8.0.129 (tarball Mon Mar  5 21:06:12 UTC 2018)

**Comment by directhex** [comment]
Resolved.

**Comment by Polatouche** [comment]
Thank you!
