### ISSUE TITLE
Debugger session not properly exited

### ISSUE THREAD

**Issue by jbevain** [mono/monodevelop#4128]
Reproduces 100% with a Unity project on 7.4.

* Open Unity
* Open VSfM from Unity
* Use `Run -> Attach to Process` instead of starting the debugger with the play button.
* Press `CMD+Q`
* DebuggerSession.OnExit is not called:
* The connection is not properly terminated
* This leaves the debugger server in Unity in a broken state.

> VS bug [#581032](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581032)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4302 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a3df292198ddafe7d104ac72301572122d6351f2 (xamarin/monodevelop)
