### ISSUE TITLE
Completion list details window shows up empty [d15-7-razor]

### ISSUE THREAD

**Issue by minestarks** [mono/monodevelop#4145]
(On Windows, haven't tried on Mac)
1. Build monodevelop d15-7-razor 
2. Build WebToolingAddin d15-7-razor
3. Open a TypeScript file and type to bring up completion list

Completion list details windows show up empty:

![image](https://user-images.githubusercontent.com/16928427/37360310-14d1d856-26ad-11e8-9b2f-9d584a84b789.png)

@KirillOsenkov @DavidKarlas

> VS bug [#581509](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581509)

**Comment by DavidKarlas** [comment]
Fixed with https://github.com/mono/monodevelop/commit/180996a5cafee06cf2bbe3a38475e46af4291c22
