### ISSUE TITLE
[Discussion] Lower the persistent storage threshold

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4149]
Right now, the persistent storage threshold is 50MB. Over the past weeks, we've dropped slightly under 50MB for Main.sln.

That means we don't dogfood the feature while developing. Despite roslyn being battle tested to know 50mb is the right configuration, we need to consider dropping it a bit lower.

We should choose a number that works for both monodevelop and md-addins, so we see it in use.

> VS bug [#581688](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581688)

**Comment by Therzok** [comment]
Brought this into discussion with roslyn folks: https://github.com/dotnet/roslyn/issues/25453

**Comment by Therzok** [comment]
Set the storage size to 0mb. Let's see how this pans out.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Author: Marius Ungureanu
Commit: 35b95e6e04de14bccf7cb7e22f0be55028b4dc29 (xamarin/monodevelop)
