### ISSUE TITLE
How to extend SyntaxModes on 7.x?

### ISSUE THREAD

**Issue by roman-yagodin** [mono/monodevelop#4154]
Trying to install add-in on MonoDevelop 7.4 produces following message: 

> The add-in [...] is trying to extend '/MonoDevelop/SourceEditor2/SyntaxModes', but there isn't any add-in defining this extension point. 

From `addin.xml`:

```XML
<Extension path="/MonoDevelop/SourceEditor2/SyntaxModes">
     <Templates file="SyntaxModes/DnnSqlDataProviderSyntaxMode.xml" />
</Extension>
```

Previously this worked fine with MonoDevelop 6.3.

**Comment by mrward** [comment]
The `/MonoDevelop/SourceEditor2/SyntaxModes` extension point no longer exists.

It should be possible to use the `/MonoDevelop/SourceEditor2/Bundles`.

https://github.com/mono/monodevelop/commit/ca594ded382b69f1aa258a48eccdf72ee7f16694

However the old syntax xml file format is no longer supported. The file formats supported are listed:

https://github.com/mono/monodevelop/blob/ca594ded382b69f1aa258a48eccdf72ee7f16694/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs#L214-L318

**Comment by roman-yagodin** [comment]
OK, thanks!

Never understood the old XML file format completely, so I think it's gone for good.
