### ISSUE TITLE
mdtool should not show interactive UI when mono is too old

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#4177]
mdtool is used for CI/command-line builds/actions and so should not block execution and display interactive UI when mono is too old.

Can we adjust the stub launcher so that monodevelop shows interactive UI when mono is too old, but mdtool logs to stdout/stderr and also immediately exits with a non-zero exit code to indicate failure?

> VS bug [#583932](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/583932)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: be80e67e9c6464fec0d6c6043bf8f9e28b5e7338 (xamarin/monodevelop)
