### ISSUE TITLE
F# - Support 'Find Reference Usages'

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4194]
<img width="369" alt="screen shot 2018-03-16 at 11 16 47 am" src="https://user-images.githubusercontent.com/667194/37518401-e29f71ec-290c-11e8-9694-ae98400a1017.png">

C# has this handy feature to determine how a reference is used. Should be fairly easy to implement this for F# too.

> VS bug [#584824](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584824)

**Comment by nosami** [comment]
Fixed in version 7.7.0.286 (master)

Pull Request #5094 merged by: Jason Imison
Author: mono
Commit: 20dc760519b89722c05c6e9b67b30d074635091b (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-52] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5094 merged by: Jason Imison  
 Author: mono  
 Commit: 20dc760519b89722c05c6e9b67b30d074635091b (xamarin/monodevelop)
