### ISSUE TITLE
LogView UnsafeBeginTask UnsafeEndTask log spew

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4205]
We log an execution failure in Android device deployment
https://gist.github.com/Therzok/c3d36ddb59c7b42af9706ff90810dc89

Then, the log is filled with this:
https://gist.github.com/Therzok/7e95c8cd09556d4da3a5acea6a91ca26

It's probably due to multiple monitors on the same logview.

> VS bug [#584931](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584931)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4300 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a5ea4e4b862526062a611c0ece0f0f63a02c34ae (xamarin/monodevelop)
