### ISSUE TITLE
Add File/[Options] UI is not shown

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#4217]
I tried adding some resource files, and when I selected the files, and tried to change the default build action, I chose [Options], the UI is not show properly.

See just above the Cancel/Open buttons:

![image](https://user-images.githubusercontent.com/36863/37550436-d2aeffda-2963-11e8-9bd8-a87277c35819.png)

<details>
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 985)
Installation UUID: 8956d53d-443d-454e-8cf3-e11cbc219f06
Runtime:
	Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000123

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.0.1
	1.0.0
	1.0.0-rc2-3002702
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.0-preview3-004056
	1.0.0-preview2-003121
	1.0.0-preview1-002702
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.19 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.0.19 (Visual Studio Community)
Hash: 5b1f7168
Branch: d15-6
Build date: 2018-02-01 18:50:51-0500

=== Xamarin.Android ===

Version: 8.2.0.12 (Visual Studio Community)
Android SDK: /Users/miguel/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 21.1.2

Java SDK: /usr
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704000985
Git revision: 0bed5a3380dbe82009f80c895623208d6c0df152
Build date: 2018-02-02 20:00:14-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

</details>

> VS bug [#585364](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585364)

**Comment by Therzok** [comment]
High sierra bug, got a fix.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4221 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8aeecab8c96787f98a91903af75d17b00dfba777 (xamarin/monodevelop)
