### ISSUE TITLE
F# - Add support for "Find Implementing Symbols"

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4226]
<img width="450" alt="screen shot 2018-03-19 at 8 39 31 am" src="https://user-images.githubusercontent.com/667194/37585462-1b94fe72-2b51-11e8-9357-ad3b55a9871a.png">

> VS bug [#585696](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585696)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-50] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5122 merged by: Jason Imison  
 Author: mono  
 Commit: 38fc2c96232fc255d1b00548def9e5b979e004c9 (xamarin/monodevelop)
