### ISSUE TITLE
AbstractResultsStore never prunes data

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4234]
The unit test results store never removes cached data, thus potentially having unbounded growth. We should prune based on some heuristics:

* A date/time one, delete records older than X days
* A TestRecord count cap
* A file size cap based on the number of total tests (i.e. allow X bytes in the file for every Test, so we know how many data points we end up saving)

> VS bug [#586003](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/586003)

**Comment by Therzok** [comment]
@slluis question on this. It seems like we support showing the test history, via the test chart.

I was expecting having pruning would be an option, but it seems like that would break the history functionality.

I tried to think of a different way to improve this, and that was to prune some strings that I thought weren't used (stacktrace, output, error text). It seems like those are written too.

Should we pursue this? I initially came across this as an IO bound operation when opening the test chart.

Maybe what we should do is reorganize the test cache using sqlite or something different?

I can't seem to optimize this without breaking something else.

**Comment by Therzok** [comment]
One thing we could do is probably use a different storage system, like an sqlite db.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 7.8.0.1304 (master)



Pull Request #6643 merged by: Lluis Sanchez  
 Author: mono  
 Commit: dda7f5967c956cbb69d58cbae943a6eef4a3729d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.0.0.800 (release-8.0)



Pull Request #6643 merged by: Lluis Sanchez  
 Author: mono  
 Commit: dda7f5967c956cbb69d58cbae943a6eef4a3729d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 7.8.0.1339 (release-7.8)



Pull Request #6643 merged by: Lluis Sanchez  
 Author: mono  
 Commit: dda7f5967c956cbb69d58cbae943a6eef4a3729d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 5a4e5005cf6dfe3a768684264e90dabef9af8d22 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6643 merged by: Lluis Sanchez  
 Author: mono  
 Commit: dda7f5967c956cbb69d58cbae943a6eef4a3729d (xamarin/monodevelop)
