### ISSUE TITLE
F# function keyword is highlighted incorrectly after pipe symbol

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4242]
<img width="186" alt="screen shot 2018-03-20 at 11 57 49 am" src="https://user-images.githubusercontent.com/667194/37653222-026be5f6-2c36-11e8-8c69-56da79f844e2.png">

> VS bug [#586435](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/586435)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4421 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 9ee8bd62bd89374cf8ce73253ffd08a802663b34 (xamarin/monodevelop)
