### ISSUE TITLE
Multi-line comment classification not working properly

### ISSUE THREAD

**Issue by garuma** [mono/monodevelop#4267]
![screen shot 2018-03-21 at 5 30 20 pm](https://user-images.githubusercontent.com/104105/37738513-a207b23c-2d2d-11e8-8d9f-029d7f84751e.png)

Using master e5f1de424b

> VS bug [#587466](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/587466)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.199 (master)

Pull Request #4268 merged by: Mike Krüger
Author: mono
Commit: fca8c712d99720995ddec1e48359e983e90a1a06 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.957 (d15-7)

Pull Request #4269 merged by: Mike Krüger
Author: mono
Commit: 561ad6c7962f05da271440732b22c7f4b2a1316c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4268 merged by: Mike Kr??ger
Author: mono
Commit: fca8c712d99720995ddec1e48359e983e90a1a06 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4268 merged by: Mike Kr??ger  
 Author: mono  
 Commit: fca8c712d99720995ddec1e48359e983e90a1a06 (xamarin/monodevelop)
