### ISSUE TITLE
version control crashes

### ISSUE THREAD

**Issue by gamesguru** [mono/monodevelop#4312]
Must disable version control globally to load or create solutions on my laptop.  Not sure if maybe I have a library on my desktop that I am missing on my laptop, or vice versa?

It crashes with version control enabled.  I can make more stacktrace available as it goes on for quite a while...

Ubuntu 17.10
Unix 4.13.0.37
Mono 5.10.1.12
MonoDevelop 7.5.0.933 or 7.5.0.646

```
> WARNING [2018-03-25 18:57:36Z]: Gdk-Warning: gdk_window_set_icon_list: icons too large
> Stack trace: 
>   at Gtk.Widget.gtk_widget_realize (System.IntPtr ) [0x00000] in <e8d21baece374fadb4e2b3899720848c>:0 
>   at Gtk.Widget.Realize () [0x00000] in <e8d21baece374fadb4e2b3899720848c>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.CreateComponents () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.InitializeLayout () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.Workbench.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeApp.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Main (System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Startup.MonoDevelopMain.Main (System.String[] args) [0x00000] in <2b25ae23bd014a5984748045e91e92aa>:0 
> WARNING [2018-03-25 18:57:36Z]: GLib-GObject-Warning: ../../../../gobject/gsignal.c:2423: signal 'request-actions' is invalid for instance '0x18ad980' of type 'GailContainer'
> Stack trace: 
>   at GLib.Signal+SignalClosure.g_signal_connect_closure (System.IntPtr , System.IntPtr , System.IntPtr , System.Boolean ) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at GLib.Signal+SignalClosure.Connect (System.Boolean is_after) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at GLib.Signal.AddDelegate (System.Delegate d) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate+<>c.<set_Owner>b__3_0 (GLib.Signal signal, System.EventHandler`1[TEventArgs] handler) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate.HandleSignalAttachment (Atk.Object owner, System.Action`2[T1,T2] action) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate.set_Owner (Atk.Object value) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate..ctor (Gtk.Widget widget) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor (Gtk.IconSize size, System.String[] icon_names) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor (Gtk.IconSize size, System.String icon_name) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.SearchEntry.BuildWidget () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.SearchEntry..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.MainToolbar.MainToolbar..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Desktop.PlatformService.CreateMainToolbar (Gtk.Window window) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.DesktopService.CreateMainToolbar (Gtk.Window window) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.CreateComponents () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.InitializeLayout () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.Workbench.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeApp.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Main (System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Startup.MonoDevelopMain.Main (System.String[] args) [0x00000] in <2b25ae23bd014a5984748045e91e92aa>:0 
> WARNING [2018-03-25 18:57:36Z]: GLib-GObject-Warning: ../../../../gobject/gsignal.c:2423: signal 'perform-cancel' is invalid for instance '0x18ad980' of type 'GailContainer'
> Stack trace: 
>   at GLib.Signal+SignalClosure.g_signal_connect_closure (System.IntPtr , System.IntPtr , System.IntPtr , System.Boolean ) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at GLib.Signal+SignalClosure.Connect (System.Boolean is_after) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at GLib.Signal.AddDelegate (System.Delegate d) [0x00000] in <940f51fcd0434c359bfa4fdc8e64ad03>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate+<>c.<set_Owner>b__3_0 (GLib.Signal signal, System.EventHandler`1[TEventArgs] handler) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate.HandleSignalAttachment (Atk.Object owner, System.Action`2[T1,T2] action) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate.set_Owner (Atk.Object value) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.AtkCocoaHelper.ActionDelegate..ctor (Gtk.Widget widget) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor (Gtk.IconSize size, System.String[] icon_names) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.HoverImageButton..ctor (Gtk.IconSize size, System.String icon_name) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.SearchEntry.BuildWidget () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.SearchEntry..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Components.MainToolbar.MainToolbar..ctor () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Desktop.PlatformService.CreateMainToolbar (Gtk.Window window) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.DesktopService.CreateMainToolbar (Gtk.Window window) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.CreateComponents () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.DefaultWorkbench.InitializeLayout () [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.Gui.Workbench.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeApp.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Ide.IdeStartup.Main (System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) [0x00000] in <f717a0febdd8484baff93f24e25f3daa>:0 
>   at MonoDevelop.Startup.MonoDevelopMain.Main (System.String[] args) [0x00000] in <2b25ae23bd014a5984748045e91e92aa>:0 
```

**Comment by Therzok** [comment]
The log above does not seem to contain anything Version Control related.

I suppose the problem is the Git backend. Do you have libgit2 installed?

**Comment by gamesguru** [comment]
Pretty sure i have libgit2 on both machines, as I am building from source without issue.  Not sure what I changed.  Seems I did everything the same on both machines.
Updated git to 2.16.2, mono and monodevelop.  But the laptop is crashing with version control enabled.

Interestingly, if I re-enable version control after loading the solution everything is okay, I can even review solution and commit.  But again when I reload a fresh solution, it must be disabled.

I could upload the full log.  It contains more messages like that

**Comment by Therzok** [comment]
Please upload the full log, that would help us diagnose the actual issue.

**Comment by gamesguru** [comment]
The error persists even after a fresh clone, submodule update and make install.  It persists even after deleting the /usr/local/lib/monodevelop folder and downgrading to the 7.4 version in Synaptic.

Maybe I should try removing the mono preview from my ppa keys?

[Ide.2018-03-25__20-18-53.log](https://github.com/mono/monodevelop/files/1852472/Ide.2018-03-25__20-18-53.log)

**Comment by gamesguru** [comment]
I've had to disable version control on a second machine now.  seems different versions of git might be the cause

i actually have git version 2.15.1 on the machine that is working.  the other two have 2.16.1, from

> sudo add-apt-repository ppa:git-core/ppa
> sudo apt-get update

**Comment by Therzok** [comment]
It's not libgit2, the problem is sqlite.

See https://github.com/mono/monodevelop/issues/4224, as this is a dupe.

**Comment by gamesguru** [comment]
let's see about it.  I'm currently editing line 112 of MonoDevelopWorkspace.cs.  I loaded it in visual studio and went to mdocs, but I'm still troubled by the units of the last argument.

It just says object or template.  You say set it to 1gb, so i just put 1000000000?

**Comment by Therzok** [comment]
@gamesguru can you try deleting the `.vs` folder from the solution folder? It might help here:
```
ERROR [2018-03-29 16:03:15Z]: Roslyn error: StorageDatabase_Exceptions Kind=Microsoft.CodeAnalysis.SQLite.Interop.SqlException|Reason=Microsoft.CodeAnalysis.SQLite.Interop.SqlException: database table is locked: StringInfo1
database table is locked
```

**Comment by gamesguru** [comment]
is this from the first log, or the second/third?  only have access to my laptop (first log).

the issue from the first log was resolved by downgrading from 2.16.2 git to 2.14.1.  The older version agrees better with monodevelop.  You can probably reproduce this by upgrading git

**Comment by Therzok** [comment]
It's from both logs you uploaded here:
https://github.com/mono/monodevelop/issues/4312#issuecomment-377405838

We don't use anything from actual git in MonoDevelop. Not sure how git impacted that.

On the other hand, there are a lot of accessibility errors logged. cc @iainx

**Comment by Therzok** [comment]
The first log does not have any information about what caused the crash, sadly.

**Comment by gamesguru** [comment]
Both of those logs are from a computer I won't have access to til Tuesday.  I'd rather not spend too much attention there, it's possible I have bigger issues in the .vs folder, i.e) .fuse_hidden files

I thought i had it working but no.  Similarly deleting the .vs folder seemed to help at first, but (maybe when i started switching between projects) it's still very unstable.  The working computer actually somehow has git 2.15.2, i don't want to change anything on it though.

And deleting both .vs folders still left issues after a computer reboot.  No point in sharing more logs.  I'm getting the same errors, it's all gdk icon too large, GLib blah blah, gail container

Disabling version control reliably fixes the issue.

**Comment by gamesguru** [comment]
okay the exceptions i thought were the problem are occurring in healthy logs too, so nevermind those.

but if you scroll past them.  there's a fatal exception.  sqlite, codeanalysis, SIGSEGV.  i've attached three logs.

the first, a healthy one.  no crashes.  everything loads fine (a small console app).  version control disabled globally.
the second, a normal crash, the .vs folder intact. version control enabled.
the third, a crash with the .vs folder freshly deleted.  version control enabled.

in my opinion second and third log are pretty much identical.  i'm trying to figure out how i got git 2.15 on the good computer, to see if maybe that is the reason
[Ide.2018-03-31__08-15-17.log](https://github.com/mono/monodevelop/files/1865462/Ide.2018-03-31__08-15-17.log)
[Ide.2018-03-31__08-19-48.log](https://github.com/mono/monodevelop/files/1865463/Ide.2018-03-31__08-19-48.log)
[Ide.2018-03-31__08-23-44.log](https://github.com/mono/monodevelop/files/1865464/Ide.2018-03-31__08-23-44.log)

**Comment by gamesguru** [comment]
Not having these issues with the build 1255 in the synaptic store for ubuntu 18.04

**Comment by livingsilver94** [comment]
This issue also seems to be fixed with preview version 7.6 on Solus.

**Comment by gamesguru** [comment]
@livingsilver94 Are you building from source, or installing from a package manager? If it's the latter, it should always be tested and working.

**Comment by livingsilver94** [comment]
from source of course, as I'm packaging monodevelop for Solus :) it hadn't monodevelop in repository yet.
