### ISSUE TITLE
Enum Color Syntax Incorrect

### ISSUE THREAD

**Issue by brminnick** [mono/monodevelop#4329]
Below is a screenshot from the current VSMac Beta Channel, VSMac 7.5 build 933, using the Monokai color theme.

The enum (`Star` in this example) is given the same syntax coloring as classes/structs (Blue in Monokai). 

Enums are typically given the same syntax coloring as local variables (White in Monokai)

<img width="562" alt="screen shot 2018-03-22 at 2 32 01 pm" src="https://user-images.githubusercontent.com/13558917/37920293-5420e230-30db-11e8-83bf-59a6cf7497dd.png">

### Environment

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 933)
Installation UUID: 97f93b74-bd84-4161-86fb-e8c474d1a273
Runtime:
	Mono 5.10.0.179 (2017-12/dac60775616) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
	Package version: 510000179

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.4.0.31 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.10.0.32 (Visual Studio Enterprise)
Hash: 4d8c4e32
Branch: d15-7
Build date: 2018-03-07 18:39:46-0500

=== Xamarin.Android ===

Version: 8.3.0.5 (Visual Studio Enterprise)
Android SDK: /Users/bramin/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705000933
Git revision: ace1e107c88477db1abe5e807809650f064112c4
Build date: 2018-03-19 17:42:41-04
Xamarin addins: a01263bdbba2589b1f6e42ef085bd31f6e3bfcf4
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MFractor 3.04.14
AddinMaker 1.4.2
NuGet Package Management Extensions 0.12.6
Template Creator 0.2
WakaTime 3.0.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

> VS bug [#591652](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591652)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.372 (master)

Pull Request #4413 merged by: Mike Krüger
Author: mono
Commit: 755e51873fe7d1450deb0e46b18521a811cf7957 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4413 merged by: Mike Kr??ger
Author: mono
Commit: 755e51873fe7d1450deb0e46b18521a811cf7957 (xamarin/monodevelop)
