### ISSUE TITLE
Project model evaluation contention

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4330]
Loading Main.sln on Windows shows that out of 60s split across all threads in evaluation, 19s are spent on lock contention.

* ~5s in MSBuildEvaluationContext.GetPropertyValue (cache and lock was added due to Environment.GetEnvironmentVariable allocating a lot - maybe switch to immutable dictionary)~
* 15s in DefaultMSBuildEngine.ImportFile on the loaded projects dictionary

> VS bug [#591651](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591651)

**Comment by mhutch** [comment]
What about just using `GetEnvironmentVariables` to initialized the dictionary and make it readonly?

**Comment by Therzok** [comment]
Fixed that via https://github.com/mono/monodevelop/pull/4335/commits/2054c2399d0a534416d8e328bdbc2fd621da7771

Thanks!

**Comment by Therzok** [comment]
I was looking around the code for imports, so, what happens is:

Imported project load and contention:
* Each import file is loaded once - OK
* We are using fully sync IO - OK, maybe async can bring gains by not blocking the thread with the task
* We are locking on the loaded projects dictionary while loading the file from disk. Maybe we can avoid waiting there and do it in parallel, and wait when we actually do the evaluation.

We _could_ get away with a .Result and spin up a task on which consumers wait when actually using the imported project for evaluation. That moves the contention, to a .Result call, but gives us 2 following benefits:

* We know that we need to fix the API to be async in the future.
* We can do other operations in the meantime and not fully block pre-emptively for IO to be done.

Post load:
* Each import file is evaluated for every importer - Can be improved (for contexts which are equivalent, by not evaluating twice - this can be useful for other scenarios too)
* Evaluation code is fully sync, we're not using anything from async code - OK

One solution I had in mind was switching to async semaphoreslim, but we can't, because the code is modeled around sync API, and there's public sync API that's called.

**Comment by Therzok** [comment]
Now that I think of it, we can reduce contention a bit:
https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs#L133

We have a few options here:
* Change the lock to not be on the dictionary, but be a lock-per-file. That means that the first time we have a lock per fileName, rather than a lock per msbuild engine, and only lock on the dictionary when modifying it (2 dictionaries, one with pending, one with loaded, lock and retrieve based on what's happening)
* We can also preload some files - i.e. Microsoft.CSharp.Targets asynchronously in the background when, for example, the C# binding is loaded.

**Comment by Therzok** [comment]
WIP at https://github.com/mono/monodevelop/pull/4335

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 5fb15f227aa93a5f615047d9ccf7faa333ff662f (xamarin/monodevelop)
