### ISSUE TITLE
Avoid double loading files from disk

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4331]
Currently, we load files from disk:
1. Once from MonoDevelopTextLoader, so we pass the files to roslyn.
2. Once via BufferFactoryService.CreateTextBuffer

This results in double IO and memory pressure on solution load

> VS bug [#591650](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591650)

**Comment by Therzok** [comment]
cc @KirillOsenkov

**Comment by mkrueger** [comment]
Not really an option here - one is for loading from disk for creating the project system and one is for the editor. There is no connection here.

@KirillOsenkov how does vs.net handle that ?

**Comment by mkrueger** [comment]
Note: we did the same on nrefactory and I do not see much of an issue here except for really, really big files.

**Comment by Therzok** [comment]
Roslyn supports directly using the text editor ITextBuffer: http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.TextBufferContainer.cs,18

**Comment by mkrueger** [comment]
Doesn't matter much - they can load it several times as well. There is a timing problem here. 

Open text editor != files on disk 

When the file on disk is loaded for the type system the editor is usually closed and I do not think that we should cache all files on disk in memory just for the option that it's opened in the editor later on.

**Comment by Therzok** [comment]
Yeah, seems like VSWindows is not doing anything special over here - need to validate whether preserving identity of the documents on opening and closing docs.
