### ISSUE TITLE
Log addin load stacktraces to have a baseline of where an addin is loaded

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4345]
We should have a way to determine what causes an addin to load (i.e. a stacktrace for where the load comes from).

That way, we can determine if we regress on addin load - i.e. an addin is loaded because of an extension point that's not designed to make use of metadata).

> VS bug [#591639](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591639)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-49] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5269 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a2ea92d1318e6d2ccf7d79056bf43cc7c0745519 (xamarin/monodevelop)
