### ISSUE TITLE
Text editor - curly brace problems

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4346]
Affects d15-7: Visual Studio Mac 7.5 build 990.

Creating a C# console project then add a new method:

    void Foo()
    {
    }

Then with the cursor at the opening brace press return to put a new line between the curly braces. The text editor then shows two closing curly braces. Also if you delete entered text here the end curly brace disappears. Looks like the text editor is not refreshing and still showing the old line.

Video showing the curly brace behaviour:

![editorcurlybrace-d157](https://user-images.githubusercontent.com/372361/38021798-c299a06c-3275-11e8-872e-516c37eda5c0.gif)

> VS bug [#591002](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591002)

**Comment by mrward** [comment]
My text editor preferences are:

<img width="670" alt="screen shot 2018-03-28 at 10 52 35" src="https://user-images.githubusercontent.com/372361/38021992-3a69b0c8-3276-11e8-9933-be2b0368552a.png">

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.367 (master)

Pull Request #4378 merged by: Greg Munn
Author: mono
Commit: 0cbc54fa692964a37d933751aa7029a00623d57d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.367 (master)

Pull Request #4378 merged by: Greg Munn
Author: mono
Commit: 0cbc54fa692964a37d933751aa7029a00623d57d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1029 (d15-7)

Pull Request #4379 merged by: Greg Munn
Author: mono
Commit: 71ee79060d36fe77058397eec87d38e81de2992a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.379 (master)

Pull Request #4419 merged by: Mike Krüger
Author: mono
Commit: 696cd8e7f960177dd18bacbc854f00a5274da245 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.379 (master)

Pull Request #4419 merged by: Mike Krüger
Author: mono
Commit: 696cd8e7f960177dd18bacbc854f00a5274da245 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1041 (d15-7)

Author: Mike Krüger
Commit: cb0a59e3b19c668fbc19968c7765bd70ef6a3733 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1041 (d15-7)

Author: Mike Krüger
Commit: cb0a59e3b19c668fbc19968c7765bd70ef6a3733 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.4.3.4 (d15-6)

Pull Request #4412 merged by: Lluis Sanchez
Author: mono
Commit: c992ebd433e39720659ad3fedfab5910a060759c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.4.3.4 (d15-6)

Pull Request #4412 merged by: Lluis Sanchez
Author: mono
Commit: c992ebd433e39720659ad3fedfab5910a060759c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '7.4' that is not in the list of supported values

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4419 merged by: Mike Kr??ger
Author: mono
Commit: 696cd8e7f960177dd18bacbc854f00a5274da245 (xamarin/monodevelop)
