### ISSUE TITLE
Fix the Cannot find ruleset file during build

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4386]
I need to make sure our toolset variables match those in the actual MSBuild

> VS bug [#592072](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/592072)

**Comment by KirillOsenkov** [comment]
On Windows, this is fixed by https://github.com/mono/monodevelop/pull/5707.

Now need to fix this on Mac, to remove the Can't find the MinimumManagedRuleset.ruleset warning.

**Comment by KirillOsenkov** [comment]
Reopening because I think I saw that on a Mac as well. Need to check the CodeAnalysis targets on a Mac.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5707 merged by: Kirill Osenkov
Author: mono
Commit: 26b36d1256911cf8a6e6d78fb05c88317f8eb90c (xamarin/monodevelop)
