### ISSUE TITLE
Cmd-click navigation sometimes gets stuck

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4389]
Sometimes when I use Cmd-click to navigate, the editor gets "stuck" in navigation mode after I let go of Cmd: the underlines keep lighting up, and clicking on a symbol navigates. This is extremely annoying as I can no longer select text. If I switch to another editor tab and back it starts working again.

> VS bug [#593842](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593842)

**Comment by mkrueger** [comment]
I've problems reproducing that - is there any pattern to trigger that behavior ?

**Comment by mhutch** [comment]
I haven't found a repro but i still see this from time to time.

**Comment by decriptor** [comment]
I don't a repro, but I do notice issues with it from time to time when working on the `xamarin/designer` Xamarin.AndroidDesigner solution.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.716 (master)

Pull Request #5436 merged by: Mike Krüger
Author: mono
Commit: 0f8f19f9ac14d8513448ddae2ca13aacb2443807 (mono/monodevelop)

**Comment by nosami** [comment]
I just saw this bug in the release notes for 7.7. I mentioned this bug to Mike before. I used to be able to repro this every time by holding cmd down in the editor so that the underline would show, then without letting go, hold Cmd+Tab to tab away to any other app and then back again.

I can confirm that it's now fixed.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5436 merged by: Mike Kr??ger
Author: mono
Commit: 0f8f19f9ac14d8513448ddae2ca13aacb2443807 (xamarin/monodevelop)
