### ISSUE TITLE
Cmd does not light up navigation for symbol under mouse

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4390]
If I have the symbol on a mouse and hold down cmd, the navigation link link does not light up for the symbol under the mouse. If I move the mouse, it lights up.

> VS bug [#593843](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593843)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.716 (master)

Pull Request #5436 merged by: Mike Krüger
Author: mono
Commit: 0f8f19f9ac14d8513448ddae2ca13aacb2443807 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5436 merged by: Mike Kr??ger
Author: mono
Commit: 0f8f19f9ac14d8513448ddae2ca13aacb2443807 (xamarin/monodevelop)
