### ISSUE TITLE
7.4.1 release uses 7.4 extension repository

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4395]
The 7.4.1 release uses the 7.4 extension repository. As a result, it's unable to download extensions that are published for 7.4.1 unless the URL is added manually

> VS bug [#593846](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593846)

**Comment by mrward** [comment]
Seems OK for me. When I updated to 7.4.1 a few days ago there was an error about the 7.4.1 urls not being available and had to ask Tim to create the links.

<img width="595" alt="vsmac-extensions-3" src="https://user-images.githubusercontent.com/372361/38130166-d5dcf342-33f9-11e8-956b-6d2082eb88a4.png">

<img width="775" alt="vsmac-extensions-1" src="https://user-images.githubusercontent.com/372361/38130150-c5f4e714-33f9-11e8-87b5-34454f899efe.png">

**Comment by slluis** [comment]
I also get the right urls. @mhutch can you attach the IDE log?
