### ISSUE TITLE
Drag and Drop into welcome page does not work anymore

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4403]
The welcome page used to support drag and drop of files into the welcome page, and that would load the files in the IDE.

My test case was a `.dll` file.

> VS bug [#593849](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593849)

**Comment by Therzok** [comment]
cc @vancura @sevoku

**Comment by vancura** [comment]
I am not sure how HTML/JS/CSS part could do it, but maybe the WebView we have there might have such an event notification? @sevoku

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.916 (master)

Pull Request #4777 merged by: Vsevolod Kukol
Author: mono
Commit: e7129e5b9e30a975513f4ca7155a4ff65f9f7506 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4777 merged by: Vsevolod Kukol
Author: mono
Commit: e7129e5b9e30a975513f4ca7155a4ff65f9f7506 (xamarin/monodevelop)
