### ISSUE TITLE
Constant Local Variable Syntax Highlighting Incorrect

### ISSUE THREAD

**Issue by brminnick** [mono/monodevelop#4405]
Below is a screenshot from the current VSMac Beta Channel, VSMac 7.5 build 933, using the Monokai color theme.

The `const` local variables are colored green, which is the coloring used for Fields & Properties.

Local variables should be colored white in Monokai.

<img width="1072" alt="screen shot 2018-03-31 at 1 18 21 pm" src="https://user-images.githubusercontent.com/13558917/38167184-04971b76-34e6-11e8-8495-6eba344fdcb5.png">

### Environment

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 933)
Installation UUID: 97f93b74-bd84-4161-86fb-e8c474d1a273
Runtime:

- 	Mono 5.10.0.179 (2017-12/dac60775616) (64-bit)
- 	GTK+ 2.24.23 (Raleigh theme)
- 	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
- 	Package version: 510000179

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.6
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.101/Sdks
SDK Versions:
	2.1.101
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.0.31 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.10.0.32 (Visual Studio Enterprise)
Hash: 4d8c4e32
Branch: d15-7
Build date: 2018-03-07 18:39:46-0500

=== Xamarin.Android ===

Version: 8.3.0.5 (Visual Studio Enterprise)
Android SDK: /Users/bramin/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705000933
Git revision: ace1e107c88477db1abe5e807809650f064112c4
Build date: 2018-03-19 17:42:41-04
Xamarin addins: a01263bdbba2589b1f6e42ef085bd31f6e3bfcf4
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MFractor 3.04.15
AddinMaker 1.4.2
NuGet Package Management Extensions 0.12.6
Template Creator 0.2
WakaTime 3.0.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

> VS bug [#593851](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593851)

**Comment by mkrueger** [comment]
No it's not incorrect constants now have their own syntax highlighting color. This affects all constants.
