### ISSUE TITLE
Version Control does not return good errors on failure. 

### ISSUE THREAD

**Issue by se5a** [mono/monodevelop#4406]
this initially worked a couple of times after I updated to MD 7.4 then stopped. 
same credentials work fine if I git push on the commandline. 

after giving up and closing the credentials dialog box MD throws this error: 
Failed to resolve address for https: Name or service not known

> VS bug [#596562](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596562)

**Comment by se5a** [comment]
ok I feel a little silly now, it seems that I'd messed up a little with github, I forget exactly, but I'd renamed the branch in MD's version control then tried to push. somehow I ended up with a new branch on origin but locally the branch name and the tracking branch names didn't match. thought I'd fixed the problem but for some reason was still `git push branchname` on the commandline so it was working all good there. 

I guess the bug is really a lack of good error messages now.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.2.0.123 (master-vnext)



Pull Request #687 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: f03216a863f4bbc2a940293d6f19d856fe840f94 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #687 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: f03216a863f4bbc2a940293d6f19d856fe840f94 (xamarin/monodevelop)
