### ISSUE TITLE
[VSTS] Modify version-checks to allow shallow cloning

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4408]
Currently, we clone whole md-addins and submodules as part of the build.

We should be doing shallow clones for those repositories with --depth=1.

> VS bug [#593853](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593853)

**Comment by alanmcgovern** [comment]
doesn't this break the ability to calculate the correct version number?

**Comment by Therzok** [comment]
But, I'm not sure it'll work. We allow non tip commits. It takes a long time to find the commit (for MD, it timed out when I tried)

**Comment by alanmcgovern** [comment]
The last digit is auto-generated using git based commands. I believe they'll fail if we use shallow clones :)

**Comment by alanmcgovern** [comment]
Oh, never mind, i thought you were shallow cloning monodevelop too, but you're not! :P
