### ISSUE TITLE
Quick Fix preview for fix all should be done using a dialog

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4432]
Currently, quick fix shows a tooltip for previewing changes.

In the case of fix all, that can force bind the whole document. That can be costly. That behaviour has been reverted here - https://github.com/mono/monodevelop/pull/4431/commits/9e77af68412dcf2978279500f4fd4dfa0d5dedf0

The tooltip can also not be big enough, as it can need scrollable text.

We need a dialog which has a progress bar hooked to the roslyn progress tracker and shows diffs for the changes.

> VS bug [#597611](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597611)

**Comment by vancura** [comment]
This is really bad. You're right, we need a better way to display all the changes – but for now, can you disable preview on _Fix all_ item? Just the preview.

**Comment by Therzok** [comment]
The preview is disabled as of https://github.com/mono/monodevelop/commit/9e77af68412dcf2978279500f4fd4dfa0d5dedf0

**Comment by Therzok** [comment]
The reason I'm asking for a replacement is that we need to show the user what changes are going to happen so they can decide what to do.

**Comment by vancura** [comment]
The problem with the approach we have here is that it's difficult to add any interactive (navigation) elements to the preview. The preview here is virtually just a tooltip, which is not meant to be used for any interactivity. We need something better.

**Comment by vancura** [comment]
Nice, we can have something similar, in fact absolutely same thing except button alignment (Apply default and right, cancel on the left edge of the window). Do you need me to draw it or is this _description_ fine? :)

**Comment by Therzok** [comment]
Dupe of #5359

**Comment by Therzok** [comment]
Dupe of #5359
