### ISSUE TITLE
How to get a dark theme on Monodevelop 7.4?

### ISSUE THREAD

**Issue by JustinSarwer** [mono/monodevelop#4457]
I recently started using Monodevelop 7.4, and found that under "Edit -> Preferences -> Visual Style -> User Interface Theme", all I see are Adwaita, Greybird, HighContrast, Numix, and Raleigh. I was previously using Monodevelop 7.0 installed via flatpak, and there is an option for "Xamarin-Dark" in the same place. 

I read somewhere that Monodevelop will use the system theme, something about the gtk theme being shared. However, I tried modifying my gtk-theme-config on my machine, and all it did was update the context menus. I am using Xubuntu 16.04 if that helps.

Hopefully there is a solution, because having a dark text editor doesn't work well with a bright solution explorer etc.

> VS bug [#596601](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596601)

**Comment by directhex** [comment]
`sudo apt install xamarin-gtk-theme`
