### ISSUE TITLE
F# tests shouldn't inherit the Nuget.config from MonoDevelop

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4459]
The MonoDevelop NuGet.config has some unreliable package sources (such as myget).

Ideally we should isolate the tests from unnecessary sources. We should investigate how to override or remove the package sources that come from MonoDevelop's root NuGet.config and just leave the relevant ones.

> VS bug [#595393](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595393)

**Comment by KirillOsenkov** [comment]
Potentially relevant test code: https://github.com/mono/monodevelop/blob/master/main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs#L153-L157

**Comment by nosami** [comment]
Fixed by https://github.com/mono/monodevelop/pull/4460

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4460 merged by: Jason Imison  
 Author: mono  
 Commit: 51600c0f7a72f9cc66706a6bbe9d51130da42115 (xamarin/monodevelop)
