### ISSUE TITLE
Mono.Security.Protocol.Tls.TlsException

### ISSUE THREAD

**Issue by vdidxho** [mono/monodevelop#4464]
I installed mono via `sudo apt-get install mono-runtime` on raspbian. How do I install cert-sync in order to install certificates? Commands appreciated. Thanks.

**Comment by directhex** [comment]
It should already have been pulled in - unless for some reason your distribution uses non-default `apt` settings & doesn't include recommends.

The package you need is `ca-certificates-mono`
