### ISSUE TITLE
Make tooltip timeout configurable

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4469]
650ms seems too slow to me. Could we make this configurable?

https://github.com/mono/monodevelop/blob/8162e3f09b31267a21153aa99e72da708c2bf517/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs#L3082

> VS bug [#596600](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596600)

**Comment by mkrueger** [comment]
We can change the value - but configurable - no.

We should choose a time that makes sense and be in line with outher mac apps.
I'll look at tooltip timeouts on the mac - the 650 was arbitrary and hadn't any deep reason. And y I agree with it beeing too long.

**Comment by nosami** [comment]
Would it also be possible to remove the timeout completely when it is invoked via the keyboard command?

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.443 (master)

Pull Request #4480 merged by: Mike Krüger
Author: mono
Commit: 43c177799334a58407a1db4634d8a6fff18bc52e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4480 merged by: Mike Kr??ger
Author: mono
Commit: 43c177799334a58407a1db4634d8a6fff18bc52e (xamarin/monodevelop)
