### ISSUE TITLE
3rd party addins can't create TextSegmentMarkers

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4470]
I created this [addin](https://github.com/nosami/QuickJump) a while back that used to draw it's own TextSegmentMarkers, but since then `TextSegmentMarker` has been made private. 

How can a 3rd party addin create it's own markers?

![QuickJump demo](https://raw.githubusercontent.com/nosami/nosami.github.io/master/quickjump.gif)

> VS bug [#596599](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596599)

**Comment by mkrueger** [comment]
They can't they can only chose from existing text markers and there are many of it - use the text marker factory in the texteditor.

**Comment by nosami** [comment]
This is a shame as it used to work and VS for Mac is the only editor that doesn't have an 'easymotion' plugin. E.g VS - https://github.com/jaredpar/EasyMotion

None of the existing marker types are suitable for this. Can we add this type of marker to the text marker factory?

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.455 (master)

Pull Request #4475 merged by: Mike Krüger
Author: mono
Commit: e2889ce1f7b66fd52833dc49b30f3fc04f11ebcc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4475 merged by: Mike Kr??ger
Author: mono
Commit: e2889ce1f7b66fd52833dc49b30f3fc04f11ebcc (xamarin/monodevelop)
