### ISSUE TITLE
[Git] usability: switching to Authors tab should jump to the context line, not to "cached" line state

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#4472]
When you are switching source editor tabs i.e. to and from git blame ("Authors") and primary text editor tab many times, you'd notice that the git blame tab does not respect the current line number on the editor but jumps to the "previous" "cached" position. That does not help investigating code history.

"Changes" tab, on the other hand, perfectly works.

Repro:

- Open some project that are under (committed) git history.
- Open some text.
- Switch to Authors tab.
- Go back to the primary text editor tab.
- Scroll down to some line.
- Switch to Authors tab.

Expected: the Authors tab moves to the current line on the primary editor.

Actual: the Authors tab preserves the line at the first position.

Versions: monodevelop master (8162e3f), Ubuntu 17.10

> VS bug [#596859](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596859)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-6] Comment by **xamarinc**



Fixed in version 8.0.0.1385 (master)



Pull Request #7067 merged by: Jose Medrano  
 Author: mono  
 Commit: a0b1b1040caa6ca38a9a6e66a91bad45187a107a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.0.0.2176 (release-8.0)



Author: Jose Medrano  
 Commit: 3521d06ecca6d5525dcc3f0a5347e03af95cddab (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.2176 (release-8.0)



Pull Request #7067 merged by: Jose Medrano  
 Author: mono  
 Commit: a0b1b1040caa6ca38a9a6e66a91bad45187a107a (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7067 merged by: Jose Medrano  
 Author: mono  
 Commit: a0b1b1040caa6ca38a9a6e66a91bad45187a107a (xamarin/monodevelop)
