### ISSUE TITLE
Virtual indentation handling broken

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#4489]
the first return after { inserts real indentation where it should only insert virtual indent.

Subsequent returns work as expected seems only the '{' context that's not working properly. Note: Display of virtual space doesn't work -> probably due to layout caching.

> VS bug [#597633](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597633)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.469 (master)

Pull Request #4492 merged by: Mike Krüger
Author: mono
Commit: 156453cd11310c7bc276fa0a9ec8f74031d69da7 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4492 merged by: Mike Kr??ger
Author: mono
Commit: 156453cd11310c7bc276fa0a9ec8f74031d69da7 (xamarin/monodevelop)
