### ISSUE TITLE
[MSBuild] Possible cause of slow MSBuild GetSourceFilesAsync evaluation

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4502]
Investigating msbuild evaluation performance, I've come across a few details that might be slowing down actual MSBuild evaluation:

1. https://github.com/mono/monodevelop/issues/4501 - We're not using Design Time targets which make use of caches
2. All C# projects get invalidated 'in memory' by property changes on load - https://github.com/mono/monodevelop/blob/master/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpProjectExtension.cs#L63

We should track which properties are modified on solution load and not modify in memory.

What happens here:
1. We set the `modifiedInMemory` flag to true, even for properties which are not serialized to the csproj - i.e. StockIcon - https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs#L405
2. If we have that flag, we'll end up querying UnsavedContent - http://source.monodevelop.com/#MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.cs,86
3. That means we load the project from memory, instead of from disk, possibly messing up with the timestamps that msbuild uses internally for caches
4. we do `Directory.CreateDirectory` unconditionally here - https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs#L178
5. We do ProjectRootElement.Create without passing in a project collection, thus not reusing caches.

> VS bug [#597807](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597807)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-49] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: f5580cdf4300574a4ca344359fa850c2b9b4acc2 (xamarin/monodevelop)
