### ISSUE TITLE
Investigate structs with readonly fields

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4505]
https://codeblog.jonskeet.uk/2014/07/16/micro-optimization-the-surprising-inefficiency-of-readonly-fields/

> VS bug [#598423](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/598423)

**Comment by Therzok** [comment]
Maybe make use of c#7 features

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 7.8.0.483 (master)



Author: therzok  
 Commit: 58b1968a8068c37a54697575ee270addc4a55ca3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-48] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 58b1968a8068c37a54697575ee270addc4a55ca3 (xamarin/monodevelop)
