### ISSUE TITLE
open statements for F#  must be manually added when pasting/writing code

### ISSUE THREAD

**Issue by willsam100** [mono/monodevelop#4507]
When writing C#, and pasting code into the editor, intellisense is able to add the required `using` statement. 

When pasting in in the same code (syntactically correct) intellisense does not allow me add the required `open` statement.

> VS bug [#598391](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/598391)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1037 (master)

Pull Request #6821 merged by: Lluis Sanchez
Author: mono
Commit: e2d1cf6929de180e5e54d55ed4bd2b928eefd7ae (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1499 (release-7.8)

Pull Request #6838 merged by: Jason Imison
Author: mono
Commit: 27d8e84db93131ef1826e8023677d6149f76e809 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.0.0.1037 (master)



Pull Request #6821 merged by: Lluis Sanchez  
 Author: mono  
 Commit: e2d1cf6929de180e5e54d55ed4bd2b928eefd7ae (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.0.0.1049 (release-8.0)



Pull Request #6821 merged by: Lluis Sanchez  
 Author: mono  
 Commit: e2d1cf6929de180e5e54d55ed4bd2b928eefd7ae (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6821 merged by: Lluis Sanchez
Author: mono
Commit: e2d1cf6929de180e5e54d55ed4bd2b928eefd7ae (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-47] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6821 merged by: Lluis Sanchez  
 Author: mono  
 Commit: e2d1cf6929de180e5e54d55ed4bd2b928eefd7ae (xamarin/monodevelop)
