### ISSUE TITLE
MonoDevelop 7.4 fails to load C#-Projects on Ubuntu 17.10

### ISSUE THREAD

**Issue by obihoernchenxD** [mono/monodevelop#4523]
Whenever I try to open a .sln file or a .csproj file, I get the following error message:
![grafik](https://user-images.githubusercontent.com/30404793/38633679-b09c1dbc-3dc0-11e8-8915-9b93bf934a7b.png)

Logs:
[Ide.2018-04-11__19-57-53.log](https://github.com/mono/monodevelop/files/1899947/Ide.2018-04-11__19-57-53.log)
[Ide.log](https://github.com/mono/monodevelop/files/1899949/Ide.log)

Edit: Added Log files

**Comment by mrward** [comment]
Can you attach the IDE log after reproducing that error? (Help - Open Log Directory). Thanks.

**Comment by obihoernchenxD** [comment]
Sorry, I forgot to add the logs.
[Ide.2018-04-11__19-57-53.log](https://github.com/mono/monodevelop/files/1899926/Ide.2018-04-11__19-57-53.log)
[Ide.log](https://github.com/mono/monodevelop/files/1899928/Ide.log)

**Comment by Therzok** [comment]
How was mono installed? It seems you don't have user permissions to read /etc/mono/registry

**Comment by obihoernchenxD** [comment]
Mono was installed via apt as one of the dependencies of MonoDevelop while installing the "monodevelop"-package.
