### ISSUE TITLE
File->New Blank Forms App in F# sets the Android SDK to 8.0

### ISSUE THREAD

**Issue by jimbobbennett** [mono/monodevelop#4559]
If you create a new blank Xamarin.Forms F# app, and the Droid app has its SDK level fixed to 8.0.

Ideally this should be set to use latest. Having it set to a fixed version is a problem when upgrading support libraries that support a later SDK. At it's most simplest, you can't to File->New then update NuGet packages at a solution level as Support libraries 27 require 8.1

> VS bug [#601028](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601028)

**Comment by nosami** [comment]
Fixed by https://github.com/xamarin/md-addins/pull/3175
