### ISSUE TITLE
Can't expand the hover over evaluate panels in an F# app

### ISSUE THREAD

**Issue by jimbobbennett** [mono/monodevelop#4561]
When debugging an F# app, I hover over a variable and the evaluation panel pops up (sorry, don't know the technical term for it). It's a bit below the cursor, so when try to move the cursor over it to expand the panel to see the details, the popup disappears. See the animated gif below.

This happens in 7.4 and 7.5.

![2018-04-13_16-45-01](https://user-images.githubusercontent.com/1710385/38744673-513d13d2-3f3a-11e8-9316-f933234f75a8.gif)

> VS bug [#601179](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601179)

**Comment by jimbobbennett** [comment]
Seems a bit variable as to when it happens. In my current project it only happens when hovering over the last function parameter of a function, not the one before or inside the method body.

So in the Gif in the first comment, it only happens on the model in the function signature, not msg or model in the lines below

**Comment by nosami** [comment]
I can repro this issue in 7.5, but not in 7.6. 

- 7.5
![tictactoedebug 7.5](https://user-images.githubusercontent.com/667194/40413719-70c47fda-5e6e-11e8-95ef-bf2681005844.gif)

- 7.6
![tictactoedebug 7.6](https://user-images.githubusercontent.com/667194/40413407-a9c8eb00-5e6d-11e8-8e46-cb4983c46c24.gif)

Gonna close this issue as _something_ fixed this :)
