### ISSUE TITLE
Enabling code folding by default

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4566]
Developers often ask for code folding to be supported. We have this feature, but since it's off by default (unlike any other editor or IDE with this feature I can think of), they assume we don't have it and don't even look for the feature.

We should enable this by default (including for existing users).

Additionally, we should reduce the visual noise by following what VS Code does:

* the current version of the fold margin is only displayed when hovering over it
* when not hovering, the fold margin only shows [+] expand markers.

> VS bug [#600192](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/600192)

**Comment by mkrueger** [comment]
I remember that I once implemented an on hover solution ... but no one wanted it at that time :/.

**Comment by slluis** [comment]
@migueldeicaza ok to change the default behavior?

**Comment by Therzok** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Structure/VisualStudio15StructureTaggerProvider.cs,99d968331621305b

They seem to provide a tagger for IBlockTag. We should consider switching to it.

**Comment by Therzok** [comment]
Here is the code used for outlining: https://github.com/dotnet/roslyn/tree/1ead9e9c4dab6dc5092c1690b560dd2f113a236c/src/EditorFeatures/Core.Wpf/Structure

**Comment by nosami** [comment]
Would it also be possible to stop the folds from expanding when you move the caret across a fold? This makes folds almost pointless IMO (unless you only ever move the caret using the mouse)

**Comment by mkrueger** [comment]
The folding translation has nothing to do with the default behavior - do not mix up things up. 

For C# the parsed document should be unused in any case btw.

**Comment by Therzok** [comment]
@mkrueger yeah, it's currently used, at least for the path selector.

**Comment by mhutch** [comment]
@nosami  you should file a separate issue for that

**Comment by mkrueger** [comment]
@Therzok : I didn't mean it is unused now - I work on the parsed document usage from time to time to remove it. It's not a super urgent thing to do but the goal is not longer using the parsed document infrastructure for c#. Roslyn is a complete replacement for all the parsed document features.

However we'll need it for xml or other languages for a while because roslyn is not really extensible enough to provide everything yet. So it's a poor mans solution for the other use cases we have.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.683 (master)

Pull Request #4587 merged by: Mikayla Hutchinson
Author: mono
Commit: 0ddb16e01a46476fac371c2655ea34ade927461f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4587 merged by: Mikayla Hutchinson
Author: mono
Commit: 0ddb16e01a46476fac371c2655ea34ade927461f (xamarin/monodevelop)
