### ISSUE TITLE
New F# Blank Forms App has incorrect page name

### ISSUE THREAD

**Issue by jimbobbennett** [mono/monodevelop#4570]
Using VS for Mac 7.5

File->New->Blank Xamarin Forms app (F#).
Give the project a name.

In 7.4 the page created would be <ProjectName>Page, inside <ProjectName>Page.xaml and <ProjectName>Page.xaml.fs.
In 7.5 it is created with the correct class name, but incorrect file names - it always uses AppPage.xaml and AppPage.xaml.fs. See the attached screenshot.

![2018-04-14_13-25-51](https://user-images.githubusercontent.com/1710385/38768205-b640080e-3fe7-11e8-9a4c-e6fe85b34554.png)

> VS bug [#601029](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601029)

**Comment by nosami** [comment]
This happened as a consequence of trying to shoehorn SDK style project in using the old templating engine.

I could either try and hack this some more to get the correct file names, or wait until all the F# templates are moved to the new templating engine.

**Comment by mrward** [comment]
In the new Blank Xamarin.Forms project template the .xaml files are MainPage.xaml and MainPage.xaml.cs and they are not named after the project. So a short term fix would be to use MainPage instead of a .xaml file named after the project.

**Comment by nosami** [comment]
@mrward - Is there any difference between using `MainPage`and `AppPage`? Or are you suggesting that I just change the type name to match?

**Comment by mrward** [comment]
@nosami Just suggesting we use MainPage instead of AppPage since the new C# Xamarin.Forms templates (using the new templating engine and in d15-7) use MainPage. That would be simpler than trying to fix the page being named after the project.

Later we can look at moving the F# project templates to the new templating engine and GitHub repo.
