### ISSUE TITLE
Need to move to HttpClient from HttpWebRequest and use nativehandlers on MacOS

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#4571]
We need to audit all uses of our http code to both move from HttpWebRequest to HttpClient and to ensure that on MacOS we use an HttpClient that uses the NSUrlSession-based native handler.

This is required to pick up properly all the system settings for proxies, the policies and other assorted bits that the HttpWebRequest is not able to provide.

> VS bug [#601187](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601187)

**Comment by mrward** [comment]
Existing [Use HttpClient instead of HttpRequest Trello card](https://trello.com/c/Po8zl3oV/351-use-httpclient-instead-of-httprequest) which has a link to a spec that was done at the time.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-75] Comment by **xamarinc**



Fixed in version 8.0.0.1449 (master)



Pull Request #6630 merged by: Matt Ward  
 Author: mono  
 Commit: 049e3c1b1ef5f9e816738e3735689b475c9bd7e7 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-76] Comment by **xamarinc**



Fixed in version 8.0.0.1450 (master)



Pull Request #3865 merged by: Matt Ward  
 Author: xamarin  
 Commit: e7a9ebcc3918c6ae6dc6c74ddac0f0535b9b4c47 (xamarin/md-addins)  
 Included in Commit: 7c2abc2ff2a71292c6d5b760371d7c50153de3ba (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-78] Comment by **xamarinc**



Fixed in version 8.0.0.2176 (release-8.0)



Pull Request #3865 merged by: Matt Ward  
 Author: xamarin  
 Commit: e7a9ebcc3918c6ae6dc6c74ddac0f0535b9b4c47 (xamarin/md-addins)  
 Included in Commit: 8f44d3440a48d6a54e8ca7dcf866e80adb1b41f7 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-81] Comment by **xamarinc**



Fixed in version 8.0.0.2176 (release-8.0)



Pull Request #6630 merged by: Matt Ward  
 Author: mono  
 Commit: 049e3c1b1ef5f9e816738e3735689b475c9bd7e7 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-88] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6630 merged by: Matt Ward  
 Author: mono  
 Commit: 049e3c1b1ef5f9e816738e3735689b475c9bd7e7 (xamarin/monodevelop)
