### ISSUE TITLE
Investigate passing solution file to msbuild builders

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4596]
We currently pass each project in the solution to actual msbuild builders for evaluation.

Maybe a nifty first time load trick would be to pass in the actual solution file?

We'd gain:
* Automatic metaproj generation for the solution file
* Less relying on the IDE to select the right configuration/platform properties

Investigate whether we get:
* Possibly faster design time builds?
* Better caching on msbuild side
* Faster results alltogether
* Problems with current caching logic

> VS bug [#602071](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/602071)

**Comment by slluis** [comment]
How do you load an entire solution into msbuild? is there any api for that?

**Comment by Therzok** [comment]
The APIs msbuild has for solution files is internal.

But we can generate the metaproj with all the projects and configurations, and rely on msbuild to evaluate the right metadata based on what properties we send.

We can basically copy paste the solution metaproj generator from MSBuild and use that in the project collection.

**Comment by Therzok** [comment]
Should be somewhere around here: https://github.com/Microsoft/msbuild/blob/b2db71bebaae4f54f7236ca303e2b0a14aca1a0d/src/Build/Construction/Solution/SolutionProjectGenerator.cs

**Comment by Therzok** [comment]
API isn't public, not sure we can go forward with this. Using actual design time targets should be done.
