### ISSUE TITLE
New blank forms app F# has a choice of PCL or shared, but PCL creates .NET standard

### ISSUE THREAD

**Issue by jimbobbennett** [mono/monodevelop#4601]
Create a new blank forms app (F#). In the wizard there are 2 options - PCL or Shared project. If you select PCL is creates a .NET standard project.

Although .NET standard is the 'correct' project type that should be created, the PCL option is incorrectly named.

**Comment by mrward** [comment]
I fixed this at the same time as fixing #4570 in md-addins PR 3089
