### ISSUE TITLE
[Linux] KDE terminal runner broken

### ISSUE THREAD

**Issue by directhex** [mono/monodevelop#4627]
It seems some time in the last couple of years, Konsole lost its `--caption` argument, breaking our KDE terminal runner.

> VS bug [#603761](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603761)

**Comment by mkrueger** [comment]
ATM linux support in general is very broken. We should consider not shipping on linux anymore in the current state it's pointless.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.503 (master)

Pull Request #5289 merged by: Lluis Sanchez
Author: CallumDev
Commit: 37842a6ccb28d4a802fcc36e1dec0c3650bb1b5b (mono/monodevelop)
