### ISSUE TITLE
ResultsEditorExtension: DocumentContext.AnalysisDocument may be null

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4633]
During project load you can get a NullReferenceException at this line:
https://github.com/mono/monodevelop/blob/8d85385a0a103deb68c5154b8b7c8d8b4448cecb/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs#L154

because DocumentContext.AnalysisDocument can be null.

> VS bug [#603760](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603760)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1216 (d15-7)

Pull Request #4637 merged by: Lluis Sanchez
Author: mono
Commit: 6988d41d7526da1f3dcd49a61a2f213ea31490b5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1216 (d15-7)

Pull Request #4637 merged by: Lluis Sanchez
Author: mono
Commit: 6988d41d7526da1f3dcd49a61a2f213ea31490b5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.593 (master)

Pull Request #4636 merged by: Mike Krüger
Author: mono
Commit: 1512ed5d3fed3eb67fa9548ae38df649a21df791 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.593 (master)

Pull Request #4636 merged by: Mike Krüger
Author: mono
Commit: 1512ed5d3fed3eb67fa9548ae38df649a21df791 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4636 merged by: Mike Kr??ger
Author: mono
Commit: 1512ed5d3fed3eb67fa9548ae38df649a21df791 (xamarin/monodevelop)
