### ISSUE TITLE
Text editor corrupts when you navigate to a file from the search window

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#4655]
1) Search for a field/property using the widget in the top right of the IDE
2) Click around the file

Result:
It corrupts every time the cursor moves to a new location. If you hit command-a to select everything, or scroll, it seems to fix it.

> VS bug [#604925](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/604925)

**Comment by mkrueger** [comment]
Only affects master branch.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.622 (master)

Pull Request #4656 merged by: Mike Krüger
Author: mono
Commit: bc280f20deaec0913d07ea5299530844c1b4e94e (mono/monodevelop)

**Comment by alanmcgovern** [comment]
❤️ 

Will try this one now!

**Comment by alanmcgovern** [comment]
The fix doesn't seem to have affected the case I experience. The same repro steps trigger the problem for me!

**Comment by mkrueger** [comment]
Which project/file you're working on.

Can you give me a screencast for line 1 ? Folding updates should be visible there.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.705 (master)

Author: Mike Krüger
Commit: a1ea6bf7bb22d049beb968d497dafe9324488626 (mono/monodevelop)
