### ISSUE TITLE
[TextEditor] SmartTag marker position wrong

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#4667]
Smart tag markers are painted on top of the line where it should be placed below. 

Seems to be a side effect of the vs.net line data structures are no longer comparable.

> VS bug [#606069](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/606069)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.647 (master)

Pull Request #4668 merged by: Mike Krüger
Author: mono
Commit: 942e82e654c68d6dce9c74bbb3a7fa3ccf773f79 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.0.1233 (d15-7)

Pull Request #4669 merged by: Lluis Sanchez
Author: mono
Commit: 0b2196fa38551a5bc5b486bf95d5b750f51ff6dc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4668 merged by: Mike Kr??ger
Author: mono
Commit: 942e82e654c68d6dce9c74bbb3a7fa3ccf773f79 (xamarin/monodevelop)
