### ISSUE TITLE
[Linux] Monodevelop fsharpbinding doesn't compile

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#4670]
Seems to be a problem with paket:

/home/mkrueger/work/monodevelop/main/external/fsharpbinding/.paket/e7n3db4m.9f4/Tools/Paket.exe does not exist (Nuget)

That fixes it for me:

https://github.com/mono/monodevelop/pull/4671

> VS bug [#606091](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/606091)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.650 (master)

Author: Mike Krüger
Commit: b1935b084aa46430d1590a20060f5ab353b8e158 (mono/monodevelop)
