### ISSUE TITLE
C# folding parser not in line with block structure foldings.

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#4693]
Causes folding text updates after the roslyn update. Slight updates would be ok but not on every fold.

> VS bug [#607624](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/607624)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.705 (master)

Author: Mike Krüger
Commit: 018df50e9a48f15f0fe4d66a719e795737d43c07 (mono/monodevelop)
