### ISSUE TITLE
Basic SDK nuget support fails with message that gives zero information

### ISSUE THREAD

**Issue by chamons** [mono/monodevelop#4705]
I tried out master VSfM with a simple SDK project and I get this 

```Error: Build failed. See the build log for details. (sample)```

You can see the sample here, it literally just hooks into build and prints hi.

https://github.com/chamons/filed-bug-test-cases/tree/master/sdk_nuget

> VS bug [#610302](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/610302)

**Comment by mrward** [comment]
The github repository seems to be missing the `Tasks/bin/Debug/Sdk.Project.Prototype.Tasks.dll` file so the Makefile does not work.

**Comment by chamons** [comment]
Apologies, I neglected to update the Sdk.Project.Prototype.nuspec file to remove those task assemblies (not needed for example). Update pushed.

**Comment by chamons** [comment]
Also, the makefile assumes you have a nuget feed setup in  ~/nuget/ so you can copy the nuget there and call `	dotnet nuget locals all --clear` to force it to be used.

If your machine is setup differently, you'll have to change it. I know of no general way to insist that a project use a certain nuget file.

**Comment by chamons** [comment]
Apologies for the missing directions.

**Comment by chamons** [comment]
At least locally it's doing "the right thing" when you build on the command line:

```
msbuild sample.csproj
Microsoft (R) Build Engine version 15.6.0.0 (xplat-master/ca830585 Tue Mar 20 17:58:54 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/3/2018 9:38:02 AM.
Project "/Users/donblas/Programming/filed-bug-test-cases/sdk_nuget/sample.csproj" on node 1 (default targets).
SayHi:
  Hello Bob
Done Building Project "/Users/donblas/Programming/filed-bug-test-cases/sdk_nuget/sample.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.37
```
