### ISSUE TITLE
Tooltip sticks on Ubuntu Mate

### ISSUE THREAD

**Issue by nddipiazza** [mono/monodevelop#4720]
MonoDevelop Version 7.4 build 1035
MATE Desktop Environment 1.18.0
Ubuntu 17.10

Tooltips stick on UbuntuMate sometimes.

![image](https://user-images.githubusercontent.com/2238777/39632244-28897ce6-4f7a-11e8-9400-fde04cb8f056.png)

Not sure what triggers it, but restarting the ide is the only thing that helps.

> VS bug [#611796](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611796)

**Comment by Therzok** [comment]
@DavidKarlas @mkrueger did you fix something in that area recently?

**Comment by mkrueger** [comment]
Y I did - can't repro it in master anymore. 

At least not on my current linux so master should work.

**Comment by nddipiazza** [comment]
This definitely still happens on `7.1 Preview (7.1 build 1291)`

**Comment by nddipiazza** [comment]
i'm using flakpak i think the "updates" feature must not work on that so i'm probably stuck on some older version

**Comment by DavidKarlas** [comment]
This seems pretty old, @directhex what is latest version on Flatpack?

**Comment by directhex** [comment]
7.3.3.5, in the alpha branch?

I don't have the bandwidth to maintain Flatpak as well as distro packages, and distro packages won out because I also don't have enough bandwidth to implement the required fixes for a first-class experience inside a sandbox (https://github.com/mono/monodevelop/projects/2)

**Comment by nddipiazza** [comment]
Just saw this issue again on 7.5 build 1255 not flatpak this time. We shoudl re-open this.
