### ISSUE TITLE
"Non-ValueType enumerator may result in an heap allocation" 

### ISSUE THREAD

**Issue by nddipiazza** [mono/monodevelop#4726]
Non-ValueType enumerator may result in an heap allocation

correction `in a heap allocation`

secondly, what does this even mean? 

![image](https://user-images.githubusercontent.com/2238777/39640270-0c809cbc-4f90-11e8-8159-0697dcbb694a.png)

**Comment by Therzok** [comment]
This is no longer enabled by default.

The analyzer came in from: https://github.com/Microsoft/RoslynClrHeapAllocationAnalyzer

Please open a bug report against that repository.

**Comment by Therzok** [comment]
By enabled by default, I mean you need to explicitly build MonoDevelop with this toggled on for it to show.
