### ISSUE TITLE
quit re-defaulting to "case sensitive" search 

### ISSUE THREAD

**Issue by nddipiazza** [mono/monodevelop#4727]
hit "ctrl + f" for search
note: case sensitive. So uncheck the case sensitive and make your search.

hit "ctrl + f" for search again
note: case sensitive again. 

should not redefault to that

> VS bug [#611793](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611793)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.5.0.490 (master)



Pull Request #8785 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: d2deae9cd363ee35946cc45dc2fad46d0af6a8fc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.4.0.1815 (release-8.4)



Pull Request #8785 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: d2deae9cd363ee35946cc45dc2fad46d0af6a8fc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-25] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8785 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: d2deae9cd363ee35946cc45dc2fad46d0af6a8fc (xamarin/monodevelop)
