### ISSUE TITLE
[Progress Monitoring] No way to use the synchronization context to write to the log

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4734]
`ProgressMonitor.Log` should be abstracted with the containing SynchronizationContext.

Currently, users of ProgressMonitor can either:
a) write the log on the wrong synchronization context by doing `monitor.Log.WriteLine`
b) write the log on the wrong synchronization context because every progress monitor can set their own.

Consider abstracting the log into a ProgressMonitorLog that yields the calls to the right synchronization context - i.e. GUI for dialogs

> VS bug [#612113](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612113)

**Comment by slluis** [comment]
Progress monitors should write log through the sync context they have assigned, like they do for other methods. Not sure what you mean by ProgressMonitorLog.

**Comment by Therzok** [comment]
Ah, so you mean `ProgressLogWriter` should be also keeping a hold of the SynchronizationContext and use that when doing actual writing?

**Comment by Therzok** [comment]
Because, `monitor.Log` is accessed directly in many places and `LogTextWriter` does not use the synchronization context

**Comment by slluis** [comment]
The progress monitor subscribes events from `monitor.Log`, so it can handle those write events in the correct context. LogTextWriter doesn't need to be aware of it.

**Comment by Therzok** [comment]
Fixed via https://github.com/mono/monodevelop/pull/4735

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 0ba4c961ddb304de605857b76417c9fa6aa5bdd9 (xamarin/monodevelop)
