### ISSUE TITLE
Squiggles do not scale with editor

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4743]
As you can see in this example, the suggestion squiggle under the word _var_ is almost invisible.

<img width="427" alt="screen shot 2018-05-07 at 2 28 26 pm" src="https://user-images.githubusercontent.com/183285/39726158-0240f7b8-5203-11e8-8983-19073a5be801.png">

> VS bug [#612541](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612541)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.772 (master)

Pull Request #4753 merged by: Lluis Sanchez
Author: mono
Commit: d5c9ded3bc2b40d2dfef719e637249e45321b479 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4753 merged by: Lluis Sanchez
Author: mono
Commit: d5c9ded3bc2b40d2dfef719e637249e45321b479 (xamarin/monodevelop)
