### ISSUE TITLE
Single-line members should not be collapsible

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4747]
Single-line members should not be collapsible, there's no point to collapsing them and the margin gets very noisy.

<img width="629" alt="screen shot 2018-05-07 at 3 19 13 pm" src="https://user-images.githubusercontent.com/183285/39728066-119e5c12-520a-11e8-8bf9-40d6beecba22.png">

> VS bug [#612371](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612371)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.715 (master)

Author: Mike Krüger
Commit: bbc80493465ff7c7e32b51c3d4b25ed751859610 (mono/monodevelop)
