### ISSUE TITLE
Build error on every startup. Convert solution to 2017

### ISSUE THREAD

**Issue by mikkeljohnsen** [mono/monodevelop#4754]
Every time I open my Solution I have to Convert the solution  to "MSBuld (Visual Studio 2017)" else I get this error:

`/Users/mkj/Projects/XMedicusApp/packages/Xamarin.Forms.3.0.0.446417/build/netstandard2.0/Xamarin.Forms.targets(3,3): Error XF002: Xamarin.Forms tasks do not match targets. Please ensure that all projects reference the same version of Xamarin.Forms, and if the error persists, please restart the IDE. (XF002) (XMedicusApp.iOS)
`
After conversion it compiles fine.

Visual Studio: 7.5 (build 1254).
High Sierra

The project is a shared Xamarin.Forms app.

**Comment by DavidKarlas** [comment]
Once you convert solution, if you close solution and open again. Does it show same dialog again?
Can you also attach screenshot of dialog? Is this happening only with specific solution or also with new solutions?

**Comment by mikkeljohnsen** [comment]
Not using monodevelop anymore. To many problems and to slow.
