### ISSUE TITLE
[F#] Error in Android resource type provider when using XF 3.0 

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4766]
![image](https://user-images.githubusercontent.com/667194/39869829-ea55d97e-5456-11e8-9847-43d526fac578.png)

> VS bug [#614238](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/614238)

**Comment by nosami** [comment]
Compiling the solution makes the error/warning squiggles disappear.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4767 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 64379a2d776ba3c7b76bf9ad6efdeb8a410627c2 (xamarin/monodevelop)
