### ISSUE TITLE
SourceEditor is not loading types, no intellisense with a log growing with a lot of errors

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#4771]
Alpha channel seems to be broken, I tried open different solutions but the source editor is working like  a notepad :-)

INFO [2018-05-10 20:16:17Z]: Unable to parse version from directory. '/usr/local/share/dotnet/sdk/NuGetFallbackFolder'
ERROR [2018-05-10 20:16:18Z]:ERROR [2018-05-10 20:16:18Z]:ERROR [2018-05-10 20:16:18Z]:ERROR [2018-05-10 20:16:18Z]:ERROR [2018-05-10 20:16:18Z]: MSBuild property evaluation failed: [Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath))
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception. ---> System.EntryPointNotFoundException: GetSystemInfo
  at (wrapper managed-to-native) Microsoft.Build.Shared.NativeMethodsShared.GetSystemInfo(Microsoft.Build.Shared.NativeMethodsShared/SYSTEM_INFO&)
  at Microsoft.Build.Shared.NativeMethodsShared+SystemInformationData..ctor () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/msbuild-15/src/Shared/NativeMethodsShared.cs:387 
  at Microsoft.Build.Shared.NativeMethodsShared.get_SystemInformation () [0x0001e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/msbuild-15/src/Shared/NativeMethodsShared.cs:658 
  at Microsoft.Build.Shared.NativeMethodsShared.get_ProcessorArchitecture () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/msbuild-15/src/Shared/NativeMethodsShared.cs:674 
  at Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer..cctor () [0x00010] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/msbuild-15/src/Shared/MSBuildNameIgnoreCaseComparer.cs:40 
   --- End of inner exception stack trace ---
https://gist.github.com/netonjm/f1d5f4eeb83153b9bd3acb21290a02ac

Full log: 

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 711)
Installation UUID: ac2f5f5a-65c6-4e02-aae1-61d2ac9aabc1
Runtime:
	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000226

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
	1.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview2-003156
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Users/jmedrano/Projects/profiler/src/XamarinProfiler.Mac/bin/Debug/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.5.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:01-0400

Xamarin.iOS
Version: 11.11.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:00-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/jmedrano/Library/Android/sdk
	Supported Android versions:
		2.3 (API level 10)
		4.4 (API level 19)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 706000711
Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
Build date: 2018-05-04 16:11:06-04
Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
Build lane: monodevelop-lion-master

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Gist Ide Information 1.1.0
LiveXAMLAddin 1.0
AddinMaker 1.4.2
MSBuild Editor 2.0.3
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.6
Redth's Addins 1.0.9
Show in Github 1.0.4
Template 10 Template Pack 1.19
VSMarketPlaceManager 1.0
Internet of Things (IoT) development (Preview) 7.5
Xamarin.Android Templates Pack 3.0.0

**Comment by Therzok** [comment]
cc @radical

**Comment by DavidKarlas** [comment]
@netonjm is any of this solutions open source so I can try to reproduce?

**Comment by mrward** [comment]
I see this `EntryPointNotFoundException: GetSystemInfo` error in the IDE log when using VS Mac 7.5 (stable) or 7.6 (master) and Mono 5.10.1 when opening or creating a Blank C# Forms project that uses .NET Standard.
