### ISSUE TITLE
Git issue fatal: multiple stage entries for merged file 'FILE'

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#4773]
It seems that if Git operations on the command line are performed while the IDE is open, I get that error, it has happened a number of times.

Once that happens, no git operations can happen.

The work around is less than ideal, and at least once I could not quite recover the changes, and had to manually reapply changes.

The fix is to delete the .git/index file and attempt to restore things from there:

https://stackoverflow.com/questions/27330446/getting-a-fatal-error-in-git-for-multiple-stage-entries?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

> VS bug [#617848](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617848)

**Comment by tzachshabtay** [comment]
I got this error twice this week with VS for Mac on version 7.6.8 (build 38).
The actions that I performed from CLI (or in my case, using Github Desktop) was discarding changes on a few of my changed files.
The workaround as described in the question worked fine for me (thank god) on both times but it's very scary.

On some other occasions, btw, discarding files from Github Desktop caused compilation to fail with various errors on failing to resolve references, and only restarting VS for Mac seemed to solve it (this issue has been going on for a while though, the git error is new).
