### ISSUE TITLE
Cannot rename solution items

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4774]
Files in the solution items cannot be renamed

![image](https://user-images.githubusercontent.com/183285/39910940-56bd7dd6-54ae-11e8-8cff-b325274bdb21.png)

> VS bug [#616403](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/616403)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.827 (master)

Pull Request #4794 merged by: Lluis Sanchez
Author: mono
Commit: b8a651d403ea2b3c5349da855193eb38c91d8224 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4794 merged by: Lluis Sanchez
Author: mono
Commit: b8a651d403ea2b3c5349da855193eb38c91d8224 (xamarin/monodevelop)
