### ISSUE TITLE
Cannot add new file to solution items

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4775]
It's not possible to add a new file to the solution items. This make sit unnecessarily complicated to add a .editorconfig, for example

![image](https://user-images.githubusercontent.com/183285/39910974-74cc755c-54ae-11e8-8f5f-f330e0200d6e.png)

> VS bug [#616402](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/616402)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.827 (master)

Pull Request #4794 merged by: Lluis Sanchez
Author: mono
Commit: b8a651d403ea2b3c5349da855193eb38c91d8224 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4794 merged by: Lluis Sanchez
Author: mono
Commit: b8a651d403ea2b3c5349da855193eb38c91d8224 (xamarin/monodevelop)
