### ISSUE TITLE
F# interactive outputs initial output message without any user input

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4781]
` val it : unit = ()` is output when interactive launches. See screenshot.

![image](https://user-images.githubusercontent.com/667194/39936785-86f1900e-5545-11e8-9623-46c3b613f057.png)

> VS bug [#615186](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/615186)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4782 merged by: Jason Imison  
 Author: mono  
 Commit: cbb3923309c6d53dde7f079c57e9fcc1c9c6efac (xamarin/monodevelop)
