### ISSUE TITLE
Toolbar build icon is confusing

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4804]
The build icon in the main toolbar is confusing, it's not obvious what it means. Maybe we should use the "arrow into a box of things" metaphor from Visual Studio? Hammers are also a common metaphor for this.

> VS bug [#617841](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617841)

**Comment by migueldeicaza** [comment]
The hammer would be my preference, given that Apple uses this idiom already, it would be simpler for Mac users.

**Comment by vancura** [comment]
Hammer is here: https://github.com/mono/monodevelop/pull/5059 and https://github.com/xamarin/md-addins/pull/3244.

**Comment by mhutch** [comment]
Wonderful, thank you!
