### ISSUE TITLE
Unable to hide errors shown in text editor by using Source Analysis preferences

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4809]
VS Mac 7.6.0.818 (master)

Seeing error markers and tooltips in the text editor which cannot be hidden.

# To repro

Create a new console project.
Add a new class similar to:

```
	abstract class EmptyClass
	{
		public EmptyClass()
		{
			int a = 0;
			a++;
		}
	}
```

In the text editor there should be two markers. An error marker at the start of the constructor, and a dotted underline marker highlighting the entire EmptyClass constructor name.

<img width="360" alt="markers" src="https://user-images.githubusercontent.com/372361/40111471-d6f87a78-58fa-11e8-91d2-2883f51f48bf.png">

The info marker can be removed in Source Analysis by unchecking it or setting it to Hide.

<img width="939" alt="sourceanalysis" src="https://user-images.githubusercontent.com/372361/40111552-1049dae2-58fb-11e8-9c29-ad26042e57dd.png">

Note that you need to close the .cs file and re-open it before the info marker disappears - which seems like another problem.

However once that is done it is not possible to hide or change the error marker to be info/warning in preferences.

<img width="371" alt="markers2" src="https://user-images.githubusercontent.com/372361/40111624-528cf222-58fb-11e8-87c4-e8606fbee5bc.png">

You can get rid of this with a pragma or with a suppression file, which is one of the right click quick fixes, but preferences has no affect.

```
#pragma warning disable RECS0120 // Constructor in abstract class should not be public
		public EmptyClass()
#pragma warning restore RECS0120 // Constructor in abstract class should not be public
```

> VS bug [#617274](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617274)

**Comment by DavidKarlas** [comment]
It comes from WebTools... Will be fixed once bumped...

**Comment by DavidKarlas** [comment]
Webtools were bumped and this is fixed.
