### ISSUE TITLE
Configure Rule Quick Fix should filter rules

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4810]
VS Mac 7.6.0.818 (master)

If you right click a warning/error/info which has an associated quick fix rule, and select Configure Rule, the rules should be filtered based on what was selected. Otherwise you have to remember what you selected and find it from the list.

<img width="813" alt="quickfixconfigurerule" src="https://user-images.githubusercontent.com/372361/40111999-825ba8a8-58fc-11e8-81e6-9239219f7da7.png">

After selecting the Configure Rule the Source Analysis preferences dialog is shown but you have to then go and find that particular rule.

<img width="957" alt="configurerule" src="https://user-images.githubusercontent.com/372361/40112082-c9ee62a0-58fc-11e8-803a-ddfd5e0cfd14.png">

It seems that the rule description could be used or the rule code here to filter the rules maybe by just putting the text in the text box at the top and searching.

> VS bug [#617278](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617278)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.829 (master)

Pull Request #4817 merged by: Mike Krüger
Author: mono
Commit: 31e8b0aa4ef7befb0e66f08126d9107cdaccddc7 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4817 merged by: Mike Kr??ger
Author: mono
Commit: 31e8b0aa4ef7befb0e66f08126d9107cdaccddc7 (xamarin/monodevelop)
