### ISSUE TITLE
Tooltip does not disappear on typing or moving to another item

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4816]
VS Mac 7.6.0.818 (master)

The new tooltips, which are different to the original tooltips, do not disappear on typing or moving to another item on the same line. The original tooltips work OK - they disappear on typing or moving to something else on the same line. This makes typing difficult at times since you cannot see what you are typing - you have to move the caret to dismiss the tooltip and then go back to writing some code.

Screen recording:

![tooltipnotdisappear2](https://user-images.githubusercontent.com/372361/40117488-0a3c6f34-590f-11e8-8825-268e5cc620da.gif)

> VS bug [#617304](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617304)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.831 (master)

Pull Request #4826 merged by: Kirill Osenkov
Author: mono/dev/kirillo
Commit: a8e3893b363adc3020909191951d5b2e90a36459 (mono/monodevelop)

**Comment by KirillOsenkov** [comment]
Yes, we haven't bumped WebToolingAddin yet. I'll keep the bug open to check after we do so.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4826 merged by: Kirill Osenkov
Author: mono/dev/kirillo
Commit: a8e3893b363adc3020909191951d5b2e90a36459 (xamarin/monodevelop)
