### ISSUE TITLE
Toggle line comment menu no longer exists

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4822]
VS Mac 7.6.0.818 (master)

Right clicking a selection of code in the text editor and the Toggle line comment menu item is not available. So it is not currently possible to comment out a section of code without typing in the comments yourself.

> VS bug [#617345](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617345)

**Comment by mkrueger** [comment]
It's caused by the syntax highlighting.

**Comment by mrward** [comment]
If you select all the text in the text document the Toggle Line Comment menu does not appear which was been found already by Ashley.

Also if you select text upwards that does not seem to show the Toggle Line Comment but selecting the text downwards for the same selection works fine.

![togglelinecomment](https://user-images.githubusercontent.com/372361/41422906-dc64ace4-6ff1-11e8-82fc-0dfdcf75a110.gif)

The text editor path bar seems just show 'No selection' in each case when Toggle Line Comment is not available. Although this is not always the case - you can select the text upwards but not the entire line and the menu is not available.

This is with VS Mac 7.6.0.1600 (master wrench build).

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1794 (release-7.6)

Pull Request #5127 merged by: Lluis Sanchez
Author: mono
Commit: 0069905b10c35562b13c459326c3da04b69fc281 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5102 merged by: David Karla??
Author: mono
Commit: 895d2ae1a375fceca28ec9803c85df1a43d3acb6 (xamarin/monodevelop)
