### ISSUE TITLE
Intelisense is extremely slow and almost unusable

### ISSUE THREAD

**Issue by bdonnahue** [mono/monodevelop#4844]
To get to System.Configuration namespace takes literally 3.5 seconds.

I'm working on an i5 with 16 gb memory.

I have tracked this issue from monodevelop 7.4 - 7.6

> VS bug [#618945](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/618945)

**Comment by bdonnahue** [comment]
I do not know if this is related. But the whole UI seems to slow down when there are multiple projects open at the same time. For example, scrolling, code folding, right click menu etc.

Thanks to everyone for their work thus far!!

**Comment by Therzok** [comment]
Closing this PR as the slowness is not exhibited locally. Please open a new github issue or reopen this one with repro steps in case this happens anymore.

**Comment by bdonnahue** [comment]
@Therzok , im confused. Are you saying those linked issues may have fixed my issue and that I should install a new version?

**Comment by Therzok** [comment]
Yup!

**Comment by bdonnahue** [comment]
@Therzok I just installed the latest version, it is much better!!!

I will say that it is still a bit slow though. While trying to use System.Threading.ManualResetEventSlim for example, it takes about 3 seconds for the intelisense to resolve the names at each hop (eg, at System, at System.Threading etc). The menu also greys out and requires a down arrow to activate and refresh the list of items found for each namespace.

Should we reopen?

**Comment by Therzok** [comment]
Can you provide a screen recording of what exactly you're referring to? Code completion should not take 3 seconds to pop up.

Is this linux? In this case, there might be some services which are not enabled (i.e. typesystem persistence).

Does this happen constantly? Is there any project you can share to repro on?

**Comment by bdonnahue** [comment]
Just an update, it seems the performance degrades over time. If I restart monodevelop and reopen the solution the intelisense populates from 0 - 3 seconds. After about an hour I noticed the performance was around 10 seconds or in some cases longer (I press escape to cancel the query).

**Comment by Therzok** [comment]
Just attach a gif or whatever you prefer to this issue 👍 

This is an interesting scenario. It might be related to the lack of the persistence service and having to recompute information for the AST (https://github.com/mono/monodevelop/issues/4224)

Maybe we're missing a dll.config mapping. I'll have to investigate further. I don't see this on either Windows or Mac, so it's definitely something fishy.

**Comment by bdonnahue** [comment]
@Therzok  I noticed monodevelop is using a lot of resources with the GUI thread. This is the output of the top program with the IDE sitting idle.

<pre>
<code>
top - 14:27:27 up  3:59,  6 users,  load average: 1.38, 1.59, 1.55
Tasks: 135 total,   1 running, 134 sleeping,   0 stopped,   0 zombie
%Cpu(s): 41.2 us, 12.4 sy,  0.0 ni, 45.9 id,  0.0 wa,  0.0 hi,  0.4 si,  0.0 st
KiB Mem :  6977960 total,  4857360 free,   649660 used,  1470940 buff/cache
KiB Swap:  1678332 total,  1678332 free,        0 used.  6036636 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                  
16047 root      20   0 2549640 411916  65940 S 197.3  5.9   1:03.88 GUI Thread  
<code>

GUI has been up for like 10 min and cpu is around 100% now for GUI thread.

Seems fishey... I am using the ide using X11 but i dont think that is the issue

**Comment by Therzok** [comment]
Gui Thread is the name of the app on Linux, so it's the whole app combined.

I'm not sure how to get profiling info for mono on linux, would be worth a try to see the managed stacktraces.
