### ISSUE TITLE
Mono Develop does not hit breakpoint in F# solution, C# works fine

### ISSUE THREAD

**Issue by boeremak** [mono/monodevelop#4850]
Hi,

I was hesitant to report this because it seems like such a core feature that I can't imagine it being broken but here goes:

If I create a C# console application from withing Mono Develop and put a breakpoint on "Hello World" the breakpoint gets hit. If I create a F# application and put a breakpoint on: `    printfn "%A" argv` in the F# solution it does not hit the breakpoint and the program just ends. These are new solutions.

The only thing I've changed is the "Run external terminal" thing, otherwise it won't even run the debug session.

Versions:

Mono Develop 7.5

Mono:

`Mono JIT compiler version 5.10.1.47 (tarball Tue Apr 17 15:12:35 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
`

I've installed Mono Complete from your PPA on my KUbuntu 17.10 system.
Any ideas?

**Comment by nosami** [comment]
Please can you post the log of `msbuild /t:Rebuild /v:diag` ?

**Comment by boeremak** [comment]
All of it? For both solutions? It is quite some amount of text.

**Comment by nosami** [comment]
One solution should be fine. You can post the text as a [gist](https://gist.github.com/)

**Comment by boeremak** [comment]
Here it is: https://gist.github.com/boeremak/b449e897cb6a583922ceb2bb0737b5a5

**Comment by nosami** [comment]
Does `/home/user/Projects/testf/testf/bin/Debug/testf.pdb` exist?

**Comment by boeremak** [comment]
No, it does not.

**Comment by boeremak** [comment]
It does in the C# solution.

**Comment by nosami** [comment]
OK. So it looks like [this patch](https://github.com/mono/mono/blob/master/packaging/MacSDK/patches/fsharp-portable-pdb.patch) is missing from your version of Mono. @directhex: did you add this patch to a later version of Mono?

For now, if you don't want to upgrade Mono, you should edit `/usr/lib/mono/fsharp/Microsoft.FSharp.Targets` so that it looks like [this](https://gist.github.com/nosami/28987d4c36758eed6811443ca133064b)

**Comment by nosami** [comment]
Re-opened so that we don't forget about the fsharp patch.

**Comment by directhex** [comment]
Should be published in the `preview` repos

**Comment by nosami** [comment]
@directhex: thanks!

**Comment by directhex** [comment]
Tested as working, and I clicked the buttons to promote to other release branches, so marking closed.
