### ISSUE TITLE
F# Xamarin.Forms project template description mentions PCL

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4852]
Visual Studio for Mac 7.5.1.22

The description for the F# Xamarin.Forms project template needs updating since it still refers to PCL whilst the wizard page shows .NET Standard.

<img width="897" alt="formsfsharp" src="https://user-images.githubusercontent.com/372361/40277722-15ae15c4-5c1c-11e8-9f0a-57d92a6f0a80.png">

> VS bug [#619363](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/619363)

**Comment by nosami** [comment]
Fixed by https://github.com/xamarin/md-addins/pull/3174
