### ISSUE TITLE
Text editor misrenders when jumping to a line of source

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#4868]
Use quicksearch to jump to a line of source and then the screen corrupts. Using command-a to select all text forces a re-render and fixes the problem: http://recordit.co/zQJUx4ZX0a

This happens across a lot of files.

> VS bug [#620304](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/620304)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.866 (master)

Author: Mike Krüger
Commit: 627e657551a63d22b723d687afaaea3e35a56d93 (mono/monodevelop)
