### ISSUE TITLE
Typing can be slow in large files when accessibility is enabled

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4871]
VS Mac 7.6.0.818 and 7.6.0.857 (master wrench builds).

Opening Main.sln and waiting a while for code completion to work, then typing into Project.cs, pressing return and deleting can be slow. Profiling for 5 seconds it seemed to be about 2 seconds spent updating accessibility for folding. Disabling accessibility and it seems OK.

<img width="1260" alt="screen shot 2018-05-22 at 12 38 20" src="https://user-images.githubusercontent.com/372361/40367527-937b0884-5dd1-11e8-9da8-baeb64338159.png">

> VS bug [#620363](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/620363)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 7.8.0.740 (master)



Pull Request #6138 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc9a44f0bf46b45762b3c7e6caa6c2352373a97d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.197 (release-8.0)



Pull Request #6138 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc9a44f0bf46b45762b3c7e6caa6c2352373a97d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 7.7.0.1555 (release-7.7)



Pull Request #6230 merged by: Lluis Sanchez  
 Author: mono  
 Commit: d2192a721262d3546a1aece53751fdde7c0e9eb5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6138 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc9a44f0bf46b45762b3c7e6caa6c2352373a97d (xamarin/monodevelop)
