### ISSUE TITLE
Add code folding for F#

### ISSUE THREAD

**Issue by jwosty** [mono/monodevelop#4884]
Title says it all. This feature would be really nice.

**Comment by nosami** [comment]
It's there already - you just need to switch it on.

![image](https://user-images.githubusercontent.com/667194/40474710-a4ca9c64-5f37-11e8-94da-72a05990b7d3.png)

It seems many people aren't aware of this, so it will be switched on by default in the next release :)

![image](https://user-images.githubusercontent.com/667194/40474820-e9c791fa-5f37-11e8-9691-3c174ef31f06.png)

**Comment by jwosty** [comment]
Oh, strange... I recently turned on that setting, but F# files weren't getting folded (everything else was), even after I restarted VS for Mac. It only worked after I rebooted my machine.

Thanks!
