### ISSUE TITLE
[F#] Remove 'System.ValueTuple.4.3.0' from templates

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#4888]
It isn't required with latest builds of FSharp.Core and it is missing from NuGet servers.

> VS bug [#621590](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/621590)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4966 merged by: Jason Imison  
 Author: mono  
 Commit: f39391ed8f28461ace112906a74ba4bc269a51bc (xamarin/monodevelop)
