### ISSUE TITLE
Implement background compiler for MDWorkspace

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4900]
Currently, our monodevelop workspace does not have a background parser/compiler.

The advantage of having them is:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Workspace/BackgroundCompiler.cs,19

Background compiler keeps caches for compilations.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspace.cs,472017cdc20f0808,references
It enables partial semantics, which means we can incrementally get more information about the current typesystem state (i.e. completion can return data before a project is fully loaded)

It also keeps compilations around, so we shouldn't be seeing compilation recomputation that often.

> VS bug [#622595](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/622595)

**Comment by Therzok** [comment]
Split background parser into another issue: #4910

**Comment by slluis** [comment]
This looks like an important internal change. I think it is too late to include this in 7.6.

**Comment by Therzok** [comment]
Well, without this, we'll keep having the beachball while typing problem that people have been seeing (cc @alanmcgovern )

**Comment by alanmcgovern** [comment]
Is there a build with the changes that we can begin dogfooding? A performance difference of that magnitude would be worth heavily dogfooding and shipping once we're confident in it!

**Comment by Therzok** [comment]
Can be taken from here: https://github.com/mono/monodevelop/pull/4912

**Comment by Therzok** [comment]
Still, will profile and give actual statistics on the changes.

**Comment by slluis** [comment]
Ok, I'll keep it in 7.6.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-45] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 1092826de76370d3c6a1822f63bd0bf031b09da3 (xamarin/monodevelop)
