### ISSUE TITLE
Gutter on the left corrupts when you hover over the '...' associated with a compile error

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#4906]
Repro:

1) introduce a compile time error in your code and compile it.
2) When the line highlights with red hover over the '...' on the very right hand side of the error to get more info.

Result:

The gutter on the left misrenders.

> VS bug [#622559](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/622559)

**Comment by alanmcgovern** [comment]
Screencast attached to the internal issue :)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.5.3.7 (d15-7)

Pull Request #4922 merged by: Greg Munn
Author: mono
Commit: 13cecd02aceddf29a1ed57b86f81c02994df1483 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #4921 merged by: Lluis Sanchez
Author: mono
Commit: 2443ae0065a8207cb5da19d91f7e1a24d83d7fef (xamarin/monodevelop)
