### ISSUE TITLE
Debugger fetches locals for stack frames even if display is turned off

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4945]
The debugger fetches locals for stack frames _even if display of these values is turned off_

This is likely adding a lot of overhead to stepping, particularly as it's fetched for every frame, _even the frames that aren't visible in the treeview_.

> VS bug [#623925](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/623925)

**Comment by DavidKarlas** [comment]
There are 2 problems here:
1) It fetches locals for each frame to get `Type` and `Name` but not `Value` of parameter, this could be optimized by a) caching this data per method and b) by getting this data from local assembly on IDE side(Cecil)
2) TreeView in GTK doesn't support Virtualization(which allows fetching data as needed based on scroll position) afaik.

**Comment by mhutch** [comment]
1. Ideally both 🙂
2. It's a bit of work but it is possible to virtualize. In this case I don't think that's even necessary, you can just use a custom cell renderer.

**Comment by Therzok** [comment]
@DavidKarlas extensible tree view supports only building child nodes when they're shown.

Miguel had a managed implementation of lists that uses virtualization: https://github.com/migueldeicaza/mlist

**Comment by mhutch** [comment]
Implementing your own list is a lot of work, you also need to handle accessibility, keyboard, etc.

I was thinking more of implementing a custom tree model http://www.mono-project.com/docs/gui/gtksharp/implementing-ginterfaces/

**Comment by mhutch** [comment]
Also, even without a custom model, you can take advantage of the fact that the tree view uses cell renderers to render visible cells. Just put proxy objects in the store instead of actual data, and implement a custom renderer.

**Comment by mhutch** [comment]
That kinda seems like overkill 🙂

**Comment by slluis** [comment]
We need to fetch the locals for the currently active frame, and only when the locals pad is visible. I think that's enough.

**Comment by mhutch** [comment]
@slluis this is for the stack pad though. The debugger appears to be fetching locals for every frame simply to display parameter types (not values) on the stack frame. This is useful and important information to disambiguate overloads, but it could be more efficient e.g. just get the signature from the method mirror

**Comment by slluis** [comment]
Ok, it was not clear that the problem was in the stack pad. Let's fix this for 7.6.
