### ISSUE TITLE
XML intellisense is very annoying

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4969]
*Repro*

1. Create new xslt file
2. Try to type `<xsl:stylesheet`

*Actual result*

the `:` commits the first completion result (`<xsl:if`) then is entered as a char and you end up with `<xsl:if:stylesheet`

*Expected result*

You get what you typed

This is a regression. i'm not sure from what version, but I'm certain that years ago I made sure that characters would not commit intellisense if they matched an entry in the list.

Maybe we should fix this like we did for XAML: not insert the colons into the list, and instead add intellisense for the portion after the colon.

> VS bug [#624635](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624635)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.823 (master)

Pull Request #5630 merged by: Lluis Sanchez
Author: mono
Commit: 721ae7bfedfc65f7ab78700cf2af1dc45cae60cc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.277 (release-8.0)

Pull Request #5630 merged by: Lluis Sanchez
Author: mono
Commit: 721ae7bfedfc65f7ab78700cf2af1dc45cae60cc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1780 (release-7.7)

Pull Request #6286 merged by: Lluis Sanchez
Author: mono
Commit: ea86370a912870bb612a679029280b5d7d32a9f8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5630 merged by: Lluis Sanchez
Author: mono
Commit: 721ae7bfedfc65f7ab78700cf2af1dc45cae60cc (xamarin/monodevelop)
