### ISSUE TITLE
Editor tooltips never go away

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4972]
On master, on both Windows and Mac, editor tooltips never go away.

> VS bug [#624651](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624651)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1498 (master)

Pull Request #834 merged by: Lluis Sanchez
Author: mono
Commit: 0b65fe756159f48df543bd32842e29e92d94fdb3 (mono/xwt)
Included in Commit: 02d5c520963b77b04aab330f56822fed950bd5d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1498 (master)

Pull Request #834 merged by: Lluis Sanchez
Author: mono
Commit: 0b65fe756159f48df543bd32842e29e92d94fdb3 (mono/xwt)
Included in Commit: 02d5c520963b77b04aab330f56822fed950bd5d5 (mono/monodevelop)
