### ISSUE TITLE
Error Tooltips don't close

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4976]
![tooltipsdontclose](https://user-images.githubusercontent.com/679326/40821136-e061ee84-6519-11e8-848c-90818c90a93b.gif)

This is on latest master. @mkrueger Any idea what could it be? Language tooltips and keyword tooltips seem to be closing normally.

In general we're seeing quite a lot of strangeness with tooltips nowadays.

> VS bug [#624915](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624915)

**Comment by KirillOsenkov** [comment]
Reproduces on Mac as well.

**Comment by Therzok** [comment]
cc @DavidKarlas

**Comment by nosami** [comment]
Looks like a dupe of #4972

**Comment by slluis** [comment]
Closing since it is a duplicate.
