### ISSUE TITLE
Build output tab build time does not update

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4981]
When you open the Build output after building it shows a time in the tab title. On building again this time does not update in the tab title. 

<img width="895" alt="buildoutputtab" src="https://user-images.githubusercontent.com/372361/40838168-e8ce1428-6594-11e8-8aa6-0e806e042350.png">

I was expecting it to change since the time being displayed in the tab. If you close and re-open the build output the time is updated. I guess another option here would be to not show the time.

Also minor problem with the time formatting in that screenshot. It shows 12.4 pm in that screenshot when it should be 12.04.

> VS bug [#625410](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/625410)

**Comment by rodrmoya** [comment]
hmm, I fixed this already, is this with latest master?

**Comment by mrward** [comment]
Seems OK with a more recent 7.6 build.
