### ISSUE TITLE
Be able to toggle on/off the "(suggested name)" feature

### ISSUE THREAD

**Issue by define-private-public** [mono/monodevelop#4997]
While some code completion is nice, I'd like it if there was a way to turn off this feature.  I use MonoDevelop w/ [XSVim](https://github.com/nosami/XSVim). When I try to press `ESC` to close the dialog, it isn't going away.  the only thing I can do is move my cursor away from the line.

This is really frustrating to work around.

**Comment by nosami** [comment]
Does this setting work for you?

![image](https://user-images.githubusercontent.com/667194/40994465-28c3a69e-68f4-11e8-9661-5663d1c01a48.png)

**Comment by nosami** [comment]
I noticed that this setting is ignored completely for web based languages (html, razor) etc. I created another ticket to track this. Closing this in favour of the web specific ticket (https://github.com/mono/monodevelop/issues/5016)

When using the vim addin with C# or F# etc, the checkboxes above are sufficient
