### ISSUE TITLE
Structured log viewer does not show any loading progress

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4998]
Open IDE then open a binlog.

An empty build output log is shown, then something magically pops up later. There is no notification that something is happening - maybe use the status bar?

> VS bug [#629161](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/629161)

**Comment by Therzok** [comment]
cc @rodrmoya

**Comment by slluis** [comment]
Some kind of progress bar or spinner should be shown in the viewer while loading.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5056 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 9be96c9134ec6612f1e684eff20d7d688f07f8ec (xamarin/monodevelop)
