### ISSUE TITLE
Typed counter metadata is more complex that it needs to be

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5001]
Typed counter metadata can make use of [CallerMemberName](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx) to automatically figure out the property name it needs to write to.

To use that, we need to change:
`protected void SetProperty (string name, object value)` to `protected void SetProperty (object value, [CallerMemberName]string name = null)`

Since we haven't shipped this API yet, we can do this now.

If we don't want that, we can still use strings as direct names, but we should rely on `nameof()` rather than manually typing strings.

There is a problem that can appear when using `new string MyProp { get; set; }`, by masking base values. So in those cases, users can override via passing over a specific name.

> VS bug [#626931](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/626931)

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/pull/5002

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 6d8abd6d5bde382748b1a601575c2bec8222e057 (xamarin/monodevelop)
