### ISSUE TITLE
Structured Log - Missing IDE mapping in Finder

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5003]
See: https://github.com/mono/monodevelop/blob/master/main/build/MacOSX/Info.plist.in#L8

We should have a `Editor` role.

> VS bug [#626970](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/626970)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 6cee79bc9269e381d317324e7d3dbb33091a2bd1 (xamarin/monodevelop)
