### ISSUE TITLE
Search window is overdrawn

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#5014]
Search window flickers on linux while typing/scrolling.

> VS bug [#628322](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/628322)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1544 (master)

Pull Request #5015 merged by: Mike Krüger
Author: mono
Commit: de2396aa00c46d030709a4640059444f3b618096 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1755 (release-7.6)

Pull Request #5015 merged by: Mike Krüger
Author: mono
Commit: de2396aa00c46d030709a4640059444f3b618096 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5015 merged by: Mike Kr??ger
Author: mono
Commit: de2396aa00c46d030709a4640059444f3b618096 (xamarin/monodevelop)
