### ISSUE TITLE
Investigate memleak fix in roslyn

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5017]
We currently source copy editor config support from roslyn wpf editorfeatures.

They recently fixed a leak with it:
https://github.com/dotnet/roslyn/pull/27561/files

Investigate whether it impacts us

> VS bug [#631799](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/631799)

**Comment by Therzok** [comment]
Yes, it applies to us, but we have an even worse problem. For us, it's a static cache, not in a dictionary, and we only remove items if a text editor's been renamed.

The whole thing needs to be per-workspace with proper cache retention tests.

**Comment by Therzok** [comment]
@mkrueger can we tie the editor config service to a given MD.Project (i.e. make it one service per project instance)?

That way, we gain:
a) consistent retention semantics
b) testability
c) small number of dupes in projects included twice, but worth it

**Comment by mkrueger** [comment]
We clear the cache of the file after the text editor closes - so I don't see a problem with that.

**Comment by Therzok** [comment]
Closing. I missed the clear on disposal.
