### ISSUE TITLE
Wrong(?) keyword highlight on Oblivion theme

### ISSUE THREAD

**Issue by Uriel6575** [mono/monodevelop#5019]
So far I've been using MonoDevelop built from the 46137e141f revision, but now I've tried to update to the trunk.
The first thing I've noticed is the strange keyword colors. You can see the old and the new styles.
![old](https://user-images.githubusercontent.com/1276902/41162814-6758e5b4-6b50-11e8-996d-cbe14fe1df1a.png)
![new](https://user-images.githubusercontent.com/1276902/41162812-672e9b92-6b50-11e8-9230-a59f27c7e616.png)
I thought that this change was intentional and went to the style file to patch it back only to know that it wasn't changed at all. So was it intentional after all or not?
Thank you.

**Comment by DavidKarlas** [comment]
I'm pretty sure what is happening here is, we switched to Roslyn to provide highlighting, but Roslyn doesn't give detailed coloring for different types of keywords, so now everything falls under `Keyword(Other)` which in case of Oblivion is White, while most others are Purple. Can you try modifying https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json#L189 to `"plum1"` and see what happens?

**Comment by Uriel6575** [comment]
Yes, I believe that for most cases it looks the same now.
Thanks for the advice.
