### ISSUE TITLE
[F#] Highlight usages extension does too much work on foreground thread

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#5020]
GetReferencesAsync runs synchronously and then finally [runs Task.FromResult](https://github.com/mono/monodevelop/blob/8dda703f3f6017a2b2a9a41d76b774e4470e82c5/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpHighlightUsagesExtension.fs#L71)

> VS bug [#631120](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/631120)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5026 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 7411572a3d786dea7272ddd1815991e83dcf494a (xamarin/monodevelop)
