### ISSUE TITLE
Idea: Build via shell script

### ISSUE THREAD

**Issue by Dartomic** [mono/monodevelop#5023]
Would it be possible for someone to make a bash script for Linux, which:

1. Checks that needed dependencies are installed
2. For each dependency not installed, to install it.
3. Perform any task dealing with a current build of monodevelop that may be needed in order for the script to compile monodevelop.
4. Have the script issue the commands to compile monodevelop.

Sorry for the long question. I was just informed that MonoDevelop is still being developed, is available here on GitHub, and works great. I love C#, and am in the process of making a GUI application on VisualStudio Community. But I really miss using Linux. I know the steps are listed here, in order to build the IDE, but I am not familiar with how to perform some of these tasks yet. I'm afraid of spending 6 hours trying to figure it out, like the guy that informed me of this still being developed did to build this. I get side tracked a lot from working on my software, just like I am now by writing this big paragraph.

**Comment by Dartomic** [comment]
I'm closing this because I just realized that CentOS and Fedora have a good build of it.

**Comment by Therzok** [comment]
Ideally, this should all be driven via a single `msbuild` call
