### ISSUE TITLE
Roslyn bug: private instance fields are reported as "Accessibility modifiers required"

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#5032]
I was trying to edit code like this, and noticed that Roslyn reports invalid message:

```
using System;
using System.Runtime.InteropServices;

namespace SoundIOSharp
{
	public struct SoundIOChannelAreas
	{
		static readonly int native_size = Marshal.SizeOf<SoundIoChannelArea> ();

		internal SoundIOChannelAreas (IntPtr head, int channelCount, int frameCount)
		{
			this.head = head;
			this.channel_count = channelCount;
			this.frame_count = frameCount;
		}

		IntPtr head;
		int channel_count;
		int frame_count;
<snip>
```

result:

![screenshot from 2018-06-12 02-35-00](https://user-images.githubusercontent.com/53929/41247891-56452bec-6dea-11e8-8c36-d092f07882d9.png)

C# language specification disagrees with that. Fields without accessibility modifiers are simply private.

```
MonoDevelop
Version 7.6 Preview (7.6 build 1542)
Installation UUID: 5c0e0cb6-8574-4b67-9624-cfb2e33a0596
Runtime:
	Mono 5.14.0 (2018-04/47fe82d812c 2018年  6月 11日 月曜日 19:46:23 JST) (64-bit)
	GTK+ 2.24.31 (Adwaita-dark theme)

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/share/dotnet/dotnet
Runtime Versions:
	2.1.0-rc1
	2.0.5
SDK: /usr/share/dotnet/sdk/2.1.300-rc1-008673/Sdks
SDK Versions:
	2.1.300-rc1-008673
	2.1.4
MSBuild SDKs: /devel/lib/mono/msbuild/15.0/bin/Sdks

Build Information
Release ID: 706001542
Git revision: dff6c0d26853d96ceb6ba3fb7b62e2193ba5efca
Build date: 2018-06-11 15:49:37+09

Operating System
Linux
Linux 4.13.0-43-generic #48-Ubuntu SMP Wed May 16 12:18:48 UTC 2018 x86_64

Enabled user installed extensions
EditorConfig 1.0
AddinMaker 1.4.2
```

**Comment by mhutch** [comment]
This is a Roslyn feature: https://github.com/dotnet/roslyn/issues/7066

Try adding this to your editorconfig

`dotnet_style_require_accessibility_modifiers = never`

**Comment by atsushieno** [comment]
Okay, editor config worked, but I don't want to do that for every single project I have. I tried to simply disable it by code rules, which didn't work. I created another issue.

I'm closing this and primarily track the new issue. Thanks hutch.

**Comment by mhutch** [comment]
Technically you could just put an editorconfig in the folder your projects are in, it should apply to any of the projects which don't have an editorconfig :)

However, this setting should probably be exposed as a preference.
