### ISSUE TITLE
Fix FSW hangs by deterministically disposing all the registered FSWs on exit

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5037]
Keep track of all filesystemwatchers and deterministically dispose them on test runner/host exit.

Otherwise, we'll just hang.

Mono 2018-04 has an icall as opposed to a pinvoke to fix that, but we can't use it yet.

> VS bug [#632168](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632168)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 1a9d7e9ca84cda346d44be52c0121d647dc25e84 (xamarin/monodevelop)
