### ISSUE TITLE
Editor doesn't work with .NET Standard 2 nugets

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5041]
https://github.com/xamarin/xamarin-macios/issues/4092

> VS bug [#632353](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632353)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5055 merged by: Lluis Sanchez  
 Author: mono  
 Commit: d500e7601f4bdeec486b734658742cb1e1b249c5 (xamarin/monodevelop)
