### ISSUE TITLE
BuildOutputSearch needs reworking

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5042]
1. it does not cancel the previous search, allowing for an older search to overwrite the new one. Use a CancellationTokenSource
2. It does not reuse finished searches. Usually, typing is incremental `a` -> `ab`. In this case, previous search results can be reused

> VS bug [#632363](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632363)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 7.8.0.594 (master)



Pull Request #5752 merged by: Rodrigo Moya  
 Author: mono  
 Commit: a23d028e7f8734bbf583e51f71acd280982d5408 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5752 merged by: Rodrigo Moya  
 Author: mono  
 Commit: a23d028e7f8734bbf583e51f71acd280982d5408 (xamarin/monodevelop)
