### ISSUE TITLE
cannot properly clone master consistently

### ISSUE THREAD

**Issue by MinnieTheMoocher** [mono/monodevelop#5045]
I'm trying to clone the repository
   git@github.com:mono/monodevelop
to my local machine. The commit I try to clone is the latest master commit,
   cdca899b753ba639fffc51c06f302cd00b7dd65c
, including initialization etc. of its git submodules, of course.

That commit cannot be cloned properly because
2 commit IDs inside submodules are referenced by commit ID,
but those commit IDs do not exist in them:

* main/external/libgit2sharp: Commit 319fa363ef12bba42680d880ac00a127d335fb49 not found in repository

* main/external/RefactoringEssentials: Commit 069dcc18aea0285b359112b10c5e124252b003e9 not found in repository.

*Expected:*

The monodevelop source code can consistently be cloned from github.

**Comment by Therzok** [comment]
Can you try the commands below:
`git submodule sync`
`git submodule update --init --recursive`

**Comment by MinnieTheMoocher** [comment]
yes, that solved the problem.
I had used SmartGit to clone that repo from scratch, including recursive initialization of all submodules.
It initialized all of them except for these 2.
I reported that as a bug to SmartGit now.
Thanks for your help.

**Comment by MinnieTheMoocher** [comment]
the reason is that the problematic submodules are submodules within submodules:

- the 2 problematic repos "libgit2" and "libssh2" are contained in the submodule "libgit-binary" which is contained in the root repo

- the 1 problematic repo "maccore" is contained in the submodule "monomac" which is contained in the root depo

SmartGit did not recursively initialize all submodules, just the ones on the top level
referenced by the root git repo. I asked them to complete their feature and extend it
also to submodules contained within submodules.

**Comment by Therzok** [comment]
Cool, glad you could get unblocked!
