### ISSUE TITLE
Unable to re-run tests after stopping tests 

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5058]
VS Mac 7.6.0.1600 (master wrench build).
Mono 5.10.1.57 (2017-12/ea8a24b1bbf Tue Apr 24 14:53:01 EDT 2018)

Ran into this twice whilst running tests with Main.sln. To repro:

1. Create a new NUnit library.
2. Build it.
3. Open the Unit Tests pad.
4. Click Run All button in the Unit Tests pad and then quickly click the Stop button.

Expected result:

Tests are cancelled. Main toolbar button changes back to Run icon. Can re-run the tests.

Actual result:

Tests are cancelled. Main toolbar button still shows Stop icon. You cannot re-run the tests since the Run all tests button is now disabled.

Unable to reproduce with VS Mac 7.5.2 or slightly older 7.6 build 1579 (master wrench). So this looks like a fairly recent regression. The diff between those two versions:

https://github.com/mono/monodevelop/compare/c48b8e2ab4e90f70a66337f7478906f1f1dca45b...ce9e1789ab8a6dde1e5fc27ce27bf74cdbd2ef55

> VS bug [#633539](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633539)

**Comment by Therzok** [comment]
Seems like `HasExited` is set to true when we try to `Cancel`.

**Comment by Therzok** [comment]
On my list. I found a few issues when I removed old mono hacks.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 2a2000f748455579031c948e176da7d0a0f5d525 (xamarin/monodevelop)
