### ISSUE TITLE
Extract Interface dialog layout flickers/glitches

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5061]
When the "Extract Interface" refactoring, the first time the dialog is shown it flickers/glitches very obviously while it does the layout dance.

It's XWT-based. The classic way to avoid these issues with GTK was to `ShowAll()` the contents of the dialog before `Show()`ing the dualog itself, but that doesn't seem to work here. Maybe this is something XWT should be handling.

> VS bug [#636608](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636608)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.326 (master)

Pull Request #5163 merged by: Mike Krüger
Author: mono
Commit: a6f3ba511165a86f9bb8579b30b2a906be169111 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5163 merged by: Mike Kr??ger
Author: mono
Commit: a6f3ba511165a86f9bb8579b30b2a906be169111 (xamarin/monodevelop)
