### ISSUE TITLE
References in CSharpProjects do not include those added via NuGet

### ISSUE THREAD

**Issue by drewgillies** [mono/monodevelop#5066]
In a Xamarin.Forms C# project (as opposed to an F# project which doesn't have this problem), the References property doesn't include references added via NuGet packages.

C# projects use PackageReferences rather than packages.config (used by F#), and this could be the reason we don't see NuGet references in the References property. However, there appears to be no other way to find them for a C# project except by using Roslyn.

[I'm not using Roslyn in my case because F# doesn't have the same Roslyn features lit up and I was hoping to avoid coding once for F# and once for C#--it appears that until this is resolved there is no alternative]

**Comment by mrward** [comment]
PackageReference projects do not have references in the project so the Project's References collection would be empty. Projects that use packages.config files have references explicitly defined in the project file so the References collection is populated.

You should get the full set of references by calling the DotNetProject's GetReferencedAssemblies method. This is what the type system does.

**Comment by drewgillies** [comment]
Thanks a bunch, @mrward--this was tremendously helpful. My scenario works well now.
