### ISSUE TITLE
CSharpProjects do not fire a ProjectItemAdded event on initial NuGet package restore

### ISSUE THREAD

**Issue by drewgillies** [mono/monodevelop#5067]
This event fires in an FSharpProject but not a CSharpProject. It could be as a result of F# using packages.config and C# using PackageReferences. If firing a ProjectItemAdded event during a restore of a PackageReference-referenced NuGet package is inappropriate, perhaps a different event could be added in its place.

**Comment by mrward** [comment]
For a package restore of a project that uses PackageReferences I would not expect a ProjectItemAdded event to be fired. The ProjectItemAdded event is fired when something is added to the project. This is not the case for a restore.

On restoring PackageReferences the NuGet addin will trigger the project's Modified event for "References". This is used to notify the type system so it can refresh its reference information.

**Comment by drewgillies** [comment]
Thanks a bunch, @mrward--this was tremendously helpful. My scenario works well now.
