### ISSUE TITLE
Unit testing addin slow perf on finishing a test suite

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5072]
Given a test suite, when it finishes, we create the status of a test group by iterating all its children.

That means, given a tree with enough unit test suites, we end up iterating each test multiple times.

`GetLastResultDynamicaly` and `UpdateStatusFromChildren`

> VS bug [#635510](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635510)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 16339c299d509c2194062f78d1b9c2d21fec35e5 (xamarin/monodevelop)
