### ISSUE TITLE
FileWatcherService needs a bit of reworking

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5086]
1. There is no way to use `WatchDirectories` reliably, as there is no way to unsubscribe for watching paths.

Consider adding an `object id` parameter which buckets the paths to be watched, so:
```
public static void WatchDirectories (object id, IEnumerable<string> paths)
{
    // remove old id bucket
    // add paths to id bucket
    // update watchers
}
```

2. Split out in a different issue: https://github.com/mono/monodevelop/issues/5207

> VS bug [#634793](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/634793)

**Comment by mrward** [comment]
There is a Normalize method that reduces the set of directories to only the root directories otherwise we would get duplicate file service events. So isn't 2) already implemented or am I missing something? Or is this to do with having a different set for each object id?

**Comment by Therzok** [comment]
Edited out that bit, I misread the initial implementation. It also has tests for that, so it's good!
