### ISSUE TITLE
Pasted text indents with extra whitespace

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5087]
- VS Mac 7.6.0.1736.
- Text editor - Behaviour - Enable on the fly code formatting - disabled.

Pasting text from one part to another indents the first line with extra tabs. It seems that the virtual indentation is always being included.

![indentation2](https://user-images.githubusercontent.com/372361/41499372-1c661a04-7177-11e8-94ef-f0bdb369b343.gif)

VS Mac 7.5.2 does not behave like this - it pastes the text as expected with the original formatting of the text.

> VS bug [#634797](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/634797)

**Comment by mkrueger** [comment]
Fixed with 2a2ecda9f9905a5d8c5c993d4310e1d8a5a0379e

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5116 merged by: Mike Kr??ger  
 Author: mono  
 Commit: 2a2ecda9f9905a5d8c5c993d4310e1d8a5a0379e (xamarin/monodevelop)
