### ISSUE TITLE
Debugger tooltip not always displayed

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5100]
VS Mac 7.6 Preview (build 1771) - VSTS build.

Hitting a breakpoint and hovering over a variable from the right shows a different tooltip (normal text editor tooltip) than if you hover over a variable from the left hand side (debugger tooltip). In both cases the debugger tooltip I was expecting the debugger tooltip to be displayed.

![exceptiontooltip](https://user-images.githubusercontent.com/372361/41592111-80cd8728-73b3-11e8-9b51-e2d8898bb73e.gif)

VS Mac 7.5.2 seems OK.

> VS bug [#635513](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635513)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.389 (master)

Pull Request #5132 merged by: Lluis Sanchez
Author: mono
Commit: 7273f7b933effb3ef87142488bf8ffd4457b2e57 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1860 (release-7.6)

Pull Request #5236 merged by: Lluis Sanchez
Author: mono
Commit: 226e7a935cbb435e8a02f5c33a26045332430821 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5132 merged by: Lluis Sanchez
Author: mono
Commit: 7273f7b933effb3ef87142488bf8ffd4457b2e57 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Mike Kr??ger  
 Commit: 51f8edcd50052bc3af7afb4adca6bbd93d12b07b (xamarin/monodevelop)
