### ISSUE TITLE
Running unit tests aways does full build

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5108]
When running unit tests, MD always rebuilds them. This is quite annoying when debugging. It should use the same fast "needs build" check that execution uses.

> VS bug [#636094](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636094)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.698 (master)

Pull Request #5408 merged by: Lluis Sanchez
Author: mono
Commit: 827c074a2ee451386a8ddad7ad438f1ac096e21a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5408 merged by: Lluis Sanchez
Author: mono
Commit: 827c074a2ee451386a8ddad7ad438f1ac096e21a (xamarin/monodevelop)
