### ISSUE TITLE
Arabic Characters in Visual Studio for Mac

### ISSUE THREAD

**Issue by jrahma** [mono/monodevelop#5121]
Hi,

The Arabic Characters in Visual Studio for Mac is unreadable and makes it difficult to write and read the code.

Hope this will be solved soon..

Thanks,
Jassim

> VS bug [#636348](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636348)

**Comment by bratsche** [comment]
@jrahma Can you give us a little more detail about what exactly is not working as expected? I'm not very familiar with Arabic so would you post an example string along with a screenshot of how it looks in Visual Studio for Mac and a screenshot of how it looks in another app that is rendering the string correctly?

**Comment by jrahma** [comment]
![arabicvsmac](https://user-images.githubusercontent.com/6236241/41716608-103351a8-7568-11e8-8c4a-a6571dbfaa1d.png)

Please see the attached.. VS is writing the arabic from left to right where it should be written from right to left..

The attached says Good Morning :)

You can see the correct way written in the same image..
