### ISSUE TITLE
"Copy comments from base" refactoring suggests huge irrelevant comments from BCL

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5135]
The "copy comments from base" refactoring suggests copying an absurd amount of irrelevant comments from System.Object and System.ValueType.

![image](https://user-images.githubusercontent.com/183285/41727885-6a16812e-7543-11e8-8373-76eb87e69e3f.png)

I suggest it ignore `<remarks>` sections, and also ignore the System.Object and System.ValueType types.

> VS bug [#641297](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641297)

**Comment by mhutch** [comment]
Note also that there's a noticeable lag of a about a second when displaying the preview for this particular fix.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.71 (master)

Pull Request #5631 merged by: Mike Krüger
Author: mono
Commit: 7a498d377f2d487c9618f666f9b8675d799d93f3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.126 (release-7.7)

Pull Request #5631 merged by: Mike Krüger
Author: mono
Commit: 7a498d377f2d487c9618f666f9b8675d799d93f3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.931 (release-7.7)

Pull Request #5631 merged by: Mike Krüger
Author: mono
Commit: 7a498d377f2d487c9618f666f9b8675d799d93f3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5631 merged by: Mike Kr??ger
Author: mono
Commit: 7a498d377f2d487c9618f666f9b8675d799d93f3 (xamarin/monodevelop)
