### ISSUE TITLE
Code fix preview menu hangs several seconds UI on large fixes

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5136]
When when moving the focus up and down the "fix" context menu with the keyboard, there's a noticeable UI delay on items with large previews e.g https://github.com/mono/monodevelop/issues/5135. In this particular case it felt like about half a second. This is annoying when skipping over a fix I don't want to get to a fix I do want.

> VS bug [#638816](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638816)

**Comment by Therzok** [comment]
Agreed, it should asynchronously compute and show it when it's ready

**Comment by mhutch** [comment]
Oof it's about 3 seconds on enums

**Comment by Therzok** [comment]
So, it seems like it's a roslyn issue: https://github.com/dotnet/roslyn/pull/28029#issuecomment-398958754

**Comment by mhutch** [comment]
Is it? That doesn't look like the same issue to me

**Comment by CyrusNajmabadi** [comment]
Agreed, that is not the same issue.  Note: the CodeFix API is designed to be async.  So it should be possible for you guys to kick off the work to compute the preview on a BG thread, and only show once we return.

**Comment by Therzok** [comment]
The reason why it's taking some time to compute might be because it's trying to do it on the whole project.

Us being able to avoid that, sure.

Two different issues, both fixable :p

**Comment by mhutch** [comment]
It's hanging the UI

**Comment by Therzok** [comment]
Pinned it down, it's the drawing code doing diff calculation on the UI thread.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-30] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 1345e0641bd8fcfdd966464f56b4c9884b833147 (xamarin/monodevelop)
