### ISSUE TITLE
Selecting "Build succeeded" from breadcrumb bar breaks breadcrumb bar

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5140]
Selecting the "Build succeeded" item from the breadcrumb bar in the structured build output causes the path bar to become completely empty/broken

> VS bug [#636683](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636683)

**Comment by maryanne-exe** [comment]
The same related to Solution selection once we remove it from breadcrumbs. Here's a solution from a code editor:
<img width="282" alt="screenshot 2018-06-21 15 00 22" src="https://user-images.githubusercontent.com/4580041/41739784-1dba4b00-7564-11e8-8eaa-f0a9835b381d.png">

**Comment by mhutch** [comment]
With structured build output, there's an item to select "Build succeeded":

![image](https://user-images.githubusercontent.com/183285/41741486-3a2800ca-7569-11e8-93bd-3776329ae373.png)

But if I select it, the breadcrumb bar disappears entirely:

![image](https://user-images.githubusercontent.com/183285/41741430-12028ac0-7569-11e8-939a-65cb5cb462da.png)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.324 (master)

Author: Rodrigo Moya
Commit: f817c2b9a66dd2a6925f29e2fa18b871da19bb1d (mono/monodevelop)
