### ISSUE TITLE
Next/previous in structured build output should be insensitive when no results

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5143]
The next/previous buttons in the structured build output should be displayed as insensitive when there are no results. The green icons look like they're sensitive.

<img width="551" alt="screen shot 2018-06-21 at 12 55 22 pm" src="https://user-images.githubusercontent.com/183285/41733655-8486938c-7552-11e8-9807-cd3d38d946d8.png">

> VS bug [#636689](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636689)

**Comment by rodrmoya** [comment]
This is fixed also, are you testing the latest build?

**Comment by mhutch** [comment]
This is current master

**Comment by rodrmoya** [comment]
@vancura we are using gtk-go-up/down as the icons for those 2 buttons, which is the same as the search in the text editor, so should we have a "unselected" version of these?

**Comment by vancura** [comment]
Yes, there are `~disable` tags for these icons: `go-up-16~disabled@2x.png` and `go-down-16~disabled@2x.png`, referenced as usual as `gtk-go-up` and `gtk-go-down`.

One other thing, the eye icon on the screenshot above is from the light theme (it has white cut-out). Please make sure you're using `~dark` tag when in the dark theme.
