### ISSUE TITLE
Breadcrumb bar "no selection" pops up empty list

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5145]
When using the structured build output and no build has yet been performed, the breadcrumb bar shows "no selection", and clicking on this pops up empty list that looks like a glitch

<img width="316" alt="screen shot 2018-06-21 at 1 04 42 pm" src="https://user-images.githubusercontent.com/183285/41734002-b880f69a-7553-11e8-9a86-1309ed28e6ca.png">

> VS bug [#636697](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636697)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.324 (master)

Author: Rodrigo Moya
Commit: d29b1cb98aa7c83733ea9e24389cd83f79c89263 (mono/monodevelop)
