### ISSUE TITLE
Structured build output should expand more nodes by default

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5146]
When I build a project and look at the structured build output, the tree is almost entirely collapsed.

This is a waste of the available space. I think we should expand some more nodes by default, maybe all of them?

<img width="1327" alt="screen shot 2018-06-21 at 1 07 17 pm" src="https://user-images.githubusercontent.com/183285/41734123-0d013dd8-7554-11e8-97a5-2fd082cffa83.png">

> VS bug [#636701](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636701)

**Comment by maryanne-exe** [comment]
If the build succeeded we need to expand Solution and Projects by default;
If the build failed, expand Solution, Projects, Target, and Task that contains an error.

See [spec 3) Default folded view](https://microsoft-my.sharepoint.com/:w:/p/maekzemp/EXCIdy4Nc9lKttO3pJS6NxoBZRh22lO_9UpE7efIBuFCcw?e=1dFzZJ)

**Comment by rodrmoya** [comment]
We already do the correct thing when the build fails, which is to expand errors, but not when build succeeded, so I'll add that

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1985 (release-7.6)

Author: Rodrigo Moya
Commit: 7a46a42f4b956e3abca73e63572607d1eeede593 (mono/monodevelop)
