### ISSUE TITLE
Structured build output has no indicator that build is in progress

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5148]
When a build is in progress, the structured build output tab is completely empty, and shows no visual indication why

> VS bug [#636705](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636705)

**Comment by rodrmoya** [comment]
This is fixed already (see https://github.com/mono/monodevelop/commit/b88abb800f7769c8e852e2e633a015cef7422ac0), so are you not seeing the spinner when it loads?

**Comment by mhutch** [comment]
No.

I see a spinner when switching to/from diagnostic output, but I don't see a spinner while the build is in progress.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1985 (release-7.6)

Author: Rodrigo Moya
Commit: 07353ea6119d62d830446acd089ffe3a45de06f7 (mono/monodevelop)
