### ISSUE TITLE
Structured build output breadcrumb bar has too much padding

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5153]
The structured build output breadcrumb bar has much too much padding.

Here it is compare to the C# editor:

![image](https://user-images.githubusercontent.com/183285/41741546-68e61ed8-7569-11e8-9537-46e76b3eab9e.png)

Her it is compared to the assembly browser, which also has a search entry:

![image](https://user-images.githubusercontent.com/183285/41741559-74c9a6de-7569-11e8-8141-e1aaf5eb9136.png)

> VS bug [#636817](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636817)

**Comment by mhutch** [comment]
cc @vancura

**Comment by vancura** [comment]
Yes, it's huge. Please follow [our toolbar specs](https://mseng.visualstudio.com/_git/DevDivDesign?path=%2Fspec%2Fvsmac-editor-toolbars%2FREADME.md&version=GBmaster&_a=preview) and replicate metrics as much as possible.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1985 (release-7.6)

Author: Rodrigo Moya
Commit: be21ea9e1c502f92cef20122eb40b096dc4a6409 (mono/monodevelop)
