### ISSUE TITLE
Structured build output should not render "0s" times

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5155]
The structured build output should not render "0s" times. These are not useful and distract from the interesting values.

![image](https://user-images.githubusercontent.com/183285/41742426-e5feabfe-756b-11e8-9449-a66cff5830c8.png) ![image](https://user-images.githubusercontent.com/183285/41742477-179fb68a-756c-11e8-833b-219c5584560d.png)

> VS bug [#636828](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636828)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5196 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bb382966ad739c0630faf9257807bcc11ae5ff50 (xamarin/monodevelop)
