### ISSUE TITLE
Structured build output should not display leading zeros on times

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5156]
The structured build output pad should not display leading zeroes on timestamps in diagnostic mode, as this makes it harder to visual distinguish larger values

![image](https://user-images.githubusercontent.com/183285/41742503-2ee65a42-756c-11e8-9ef7-fc63d04e33d6.png)

It's also missing units

> VS bug [#636830](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636830)

**Comment by mhutch** [comment]
Before | After
------------ | -------------
00:00.001 | .001s
00:02.341 | 2.341s
1:50.211 | 1m 50.001s

**Comment by mhutch** [comment]
They weren't implemented correctly though, so it isn't a fair test.

**Comment by mhutch** [comment]
cc @maryanne-exe

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5196 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bb382966ad739c0630faf9257807bcc11ae5ff50 (xamarin/monodevelop)
