### ISSUE TITLE
Graphical glitching in the text editor

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5160]
There is frequent graphical glitching in the text editor, as can be seen in the images below. It seems to turn solid lines into dashed lines.

![image](https://user-images.githubusercontent.com/183285/41750910-839e7176-758c-11e8-83e3-af5f615a12ab.png)
![image](https://user-images.githubusercontent.com/183285/41750917-917883c2-758c-11e8-9f40-3cd740041d88.png)

> VS bug [#641296](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641296)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.408 (master)

Pull Request #5248 merged by: Mike Krüger
Author: mono
Commit: b48fbfd99c2cde4c59748802adf9ce531bfd5ec6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1871 (release-7.6)

Pull Request #5249 merged by: Lluis Sanchez
Author: mono
Commit: 689497995e4fb66f6f820455dfc9f0f713495c4a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5248 merged by: Mike Kr??ger
Author: mono
Commit: b48fbfd99c2cde4c59748802adf9ce531bfd5ec6 (xamarin/monodevelop)
