### ISSUE TITLE
Show stack trace in exception bar does not show display any information

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5170]
Using the repro in #5169 you should be able to generate the exception bar message. Clicking on the Show Stack Trace does not seem to do anything.

If there is nothing to be displayed then the Show Stack Trace should not be visible. Not sure if this is the case here.

VS Mac 7.6.0.1797

> VS bug [#637462](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637462)

**Comment by Therzok** [comment]
There is no easy way to blacklist the button, and our UI usually does not show exceptions.

Solution: Open the log file after writing.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.355 (master)

Author: therzok
Commit: 613afc0528617a7214df807102f2ac0e313ea134 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1818 (release-7.6)

Pull Request #5205 merged by: Lluis Sanchez
Author: mono
Commit: 2ca4a7a6db357dc529a41892cb6b482423ee6c4f (mono/monodevelop)
