### ISSUE TITLE
IF DEF section coloring remains inactive visually even if they are active

### ISSUE THREAD

**Issue by PureWeen** [mono/monodevelop#5171]
I'm using the https://github.com/xamarin/Xamarin.Forms project

Open a file with IF DEFS
https://github.com/xamarin/Xamarin.Forms/blob/a8ec456ac02917d7da8dba7db7331ca85dfd2307/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1975.cs

All sections of code between if def statements are greyed out even if the code itself is active. If you select different projects to be active from the dropdown you can hover the mouse over the block to see that the code itself is active but it's just greyed out

Version info:
Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.6 Preview (7.6 build 1773)

This only broke for me once I moved up to the Preview build

![2018-06-22_10-29-48](https://user-images.githubusercontent.com/5375137/41789338-2ee14520-760c-11e8-85f3-1dcb1cfc5c24.gif)

> VS bug [#637533](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637533)

**Comment by mkrueger** [comment]
Fixed in newer 7.6 builds.

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/pull/5869
