### ISSUE TITLE
Updated FWLink for Automatic Feature Suppression

### ISSUE THREAD

**Issue by jmatthiesen** [mono/monodevelop#5175]
The current FWLink for Automatic Feature Suppression points at document related to Visual Studio 2015, we should update this for VS for Mac. Here's the incorrect FWLink in source:

https://github.com/mono/monodevelop/blob/e88b727ec8509a171017dd543107f34158cecd4c/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs#L175

Please use this new FWLink and we'll work on putting in an appropriate VS for Mac version of this doc:

https://go.microsoft.com/fwlink/?linkid=2003417&clcid=0x409

> VS bug [#637580](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637580)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5298 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bad07c6137e86e8fd6b273ff3e97f7fa04af52fd (xamarin/monodevelop)
