### ISSUE TITLE
EditorConfig settings not applied to new file added to project

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5178]
VS Mac 7.6.0.1797 (release-7.6)

.editorconfig file contents:

```
# All Files
[*.cs]
indent_style = space
indent_size = 4
```

The above file exists in the solution directory and works when typing and generating code in .cs files that exist in the project.

When you add a new file to the project it does not use the information from the editorconfig. It seems to use default settings for VS Mac. So currently this means the file has tabs instead of spaces. My expected result would be that the .editorconfig formatting is applied to new files. Currently you have to select Edit - Format Document for the .editorconfig formatting to be applied to the new file.

> VS bug [#637707](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637707)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.365 (master)

Pull Request #5200 merged by: Lluis Sanchez
Author: mono
Commit: 8a3ccf3f4d43ad1a11ed8d36e28f90f865b577b3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1851 (release-7.6)

Pull Request #5201 merged by: Lluis Sanchez
Author: mono
Commit: 3ef2ad58528835abc96d66df2ff42406c5a1c4f6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5200 merged by: Lluis Sanchez
Author: mono
Commit: 8a3ccf3f4d43ad1a11ed8d36e28f90f865b577b3 (xamarin/monodevelop)
