### ISSUE TITLE
Quick fixes - Add usings and Implement interface not available

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5182]
VS Mac 7.6.0.1800 - Not working.
VS Mac 7.7.0.335 - OK

VS Mac 7.6 does not offer quick fixes to add using statements or implement interfaces.

Repro:

1. Create a C# console project.
2. Add IDisposable to MainClass.
3. No quick fix to implement interface. No warning marker in editor for IDisposable not being implemented.
4. Remove 'using System;' statement.
5. No quick fix to add using statement. No warning marker for Console.WriteLine or IDisposable use.

> VS bug [#638024](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638024)

**Comment by mrward** [comment]
Just reproduced the same problem on VS Mac 7.7.0.335 (master) after using VS Mac 7.6 for a bit and then re-opening VS Mac 7.7.

**Comment by mkrueger** [comment]
if it happens again - attach the log file maybe that is  useful.

**Comment by mrward** [comment]
It happens all the time for me. Is there something I can do to debug this?

**Comment by mrward** [comment]
Mmm, today it is working. I will re-open this if it happens again.
