### ISSUE TITLE
'extensions' and 'default' are displayed in language bundles panel

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5186]
The internal 'extensions' and 'default' language bundles are displayed in the language bundles panel, along with an option to remove them 😱

![image](https://user-images.githubusercontent.com/183285/41866982-c003b73e-787f-11e8-8611-aacb997c6805.png)

(side-note: does this mean user bundles could conflict with the build in ones' ids?)

> VS bug [#638580](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638580)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.391 (master)

Pull Request #5229 merged by: Mike Krüger
Author: mono
Commit: 9406afb4b8d09cdc5dc704027fcacf7839f375da (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1843 (release-7.6)

Pull Request #5230 merged by: Lluis Sanchez
Author: mono
Commit: 5aea27734c38b27019a8ef9bfc5a5fcef7411c52 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5229 merged by: Mike Kr??ger
Author: mono
Commit: 9406afb4b8d09cdc5dc704027fcacf7839f375da (xamarin/monodevelop)
