### ISSUE TITLE
Indentation is broken when you cut/paste lines

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#5197]
Cut and paste some code in text editor. The indentation is broken when you paste it: http://recordit.co/mOlX00LOgb

> VS bug [#638583](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638583)

**Comment by mrward** [comment]
Is this the same as #5087?

**Comment by alanmcgovern** [comment]
That bug is marked as fixed but i'm still seeing this in master builds, so i would assume not?

**Comment by alanmcgovern** [comment]
My build does have commit 634797 in it so the fix there doesn't fix my case.

**Comment by mrward** [comment]
Yeah looks like a different problem. #5087 seems to be fixed with a recent 7.7 master build.

**Comment by mkrueger** [comment]
y it 's possible to break indentation in that case if you paste indentation in. However it's by  design - VS.NET does the same:

https://www.screencast.com/t/zBXnipl6Um

Our old formatter was a bit more strict in these cases. On the fly formatting is the typing behavior - cnp fromatting is independent of that setting. If you don't want to use the formatting on paste you can undo it (when generating additional undo steps).
