### ISSUE TITLE
FileWatcherService resource starvation

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5207]
Use a smarter model to manage how many threads are alive at once.

We create one file watcher per directory root, with the rule that if a path is a child of another path, remove the former from the watch list.

While this optimizes for some cases, there are problems with other scenarios:
a) out of tree file watchers
b) sibling directories

corefx FileSystemWatcher creates [one thread per watcher](https://github.com/dotnet/corefx/issues/30600), so we can end up starving resources if we use FileWatcherService in a bad way.

Work is being done on a separate lib that will handle this scenario regardless of the underlying FileSystemWatcher implementation: https://github.com/Therzok/PathTree

PathTree is a sorted tree, that mirrors the paths we want to watch in a tree. The logic behind the tree is that we can easily request a max of 8 root nodes by doing bfs traversal with a queue, keeping track of how many nodes are added and comparing the current queue length and the popped node's children count with 8.

Work on integrating that code into MonoDevelop

> VS bug [#638612](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638612)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: c5927cdaa7033ade58c8b68e2e6250524bfdaee5 (xamarin/monodevelop)
