### ISSUE TITLE
Roaming profile serialization behaviour has changed in roslyn

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5208]
Roslyn PR: https://github.com/dotnet/roslyn/pull/26165

What changed:
* TryPersist uses the first RoamingProfileStorageLocation it can find
* TryFetch probes all the RoamingProfileStorageLocation's it can find

Solution:
* Harden [OptionExtensions.GetPropertyName](https://github.com/mono/monodevelop/blob/55fef4c2f249f1fa043543521a3adaa8082d5b22/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/OptionsExtensions.cs#L36) to handle these kind of scenarios.

* Write unit tests for the changes

> VS bug [#638653](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638653)

**Comment by Therzok** [comment]
Setting to high priority as it can cause user settings to be reset without them knowing.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: b68f95a9c890ff381a2cb00e20aaff3454973d64 (xamarin/monodevelop)
