### ISSUE TITLE
Show scopes command includes markup.

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#5212]
Show scopes shows pango markup in the popup dialog.

> VS bug [#639187](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/639187)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.382 (master)

Pull Request #5219 merged by: Mike Krüger
Author: mono
Commit: ef815d9072a84a6e53bd21632ec3b8d884b1bbab (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.1836 (release-7.6)

Author: Mike Krüger
Commit: acc897987d33094e19f466ed029bcca59cabc79f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5219 merged by: Mike Kr??ger
Author: mono
Commit: ef815d9072a84a6e53bd21632ec3b8d884b1bbab (xamarin/monodevelop)
