### ISSUE TITLE
Class pad shows compiler generated fields and ctors

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5216]
The class pad shows compiler generated backing fields and constructors.

![image](https://user-images.githubusercontent.com/183285/41999225-f9928258-7a2a-11e8-93c1-7cb75e20b1ff.png)

> VS bug [#641292](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641292)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.410 (master)

Pull Request #5264 merged by: Mike Krüger
Author: mono
Commit: 6f676b7bcbea04c4ee58a760a5dc93f21154fb18 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5264 merged by: Mike Kr??ger
Author: mono
Commit: 6f676b7bcbea04c4ee58a760a5dc93f21154fb18 (xamarin/monodevelop)
