### ISSUE TITLE
MonoDevelop custom MSBuild evaluation parser not handling ItemDefinitionGroup

### ISSUE THREAD

**Issue by garuma** [mono/monodevelop#5221]
If I set up a `ItemDefinitionGroup` with the intention that all the `MyItem` I declare in my main project won't show up in the solution tree like so:

```
<ItemDefinitionGroup>
    <MyItem>
      <InProject>False</InProject>
      <Visible>False</Visible>
    </MyItem>
</ItemDefinitionGroup>
```

VSMac still shows them as red entries. A cursory look over `DefaultMSBuildEngine` seems to indicate that ItemDefinitionGroup are not handled in general.

> VS bug [#641291](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641291)

**Comment by mrward** [comment]
Support for ItemDefinitionGroups has been added. The ItemDefinitionGroup defined above works in VS Mac 8.3 and hides the MyItem in the solution pad.
