### ISSUE TITLE
Feature request: Add support for making mobile apps (iOS, Android) from Linux

### ISSUE THREAD

**Issue by aaronfranke** [mono/monodevelop#5228]
Currently, it appears that the tools for creating mobile apps with Mono and C# are not available for Linux.  Tools such as Xamarin Live Player are available for Visual Studio for Mac but not for MonoDevelop. I would greatly appreciate the ability to create mobile apps from my Linux computer.

**Comment by KirillOsenkov** [comment]
@directhex what's the best way to track this request?

**Comment by directhex** [comment]
Good question. Voting on https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/10662897-visual-studio-for-linux probably helps. Flag a work item on VSTS? I tweeted a big-ass thread on this whole topic last year: https://twitter.com/directhex/status/943990479917670400

The long and short of it is it's a policy decision not to spend engineer effort on shipping a Linux project, so if there's demand, we need to help communicate that demand exists.

**Comment by KirillOsenkov** [comment]
Yes, I think we can close this issue and use the UserVoice item to track this request.

**Comment by aaronfranke** [comment]
I'm not sure if that is exactly the same issue. I don't specifically want or need a product branded as "Visual Studio for Linux", and I doubt Microsoft will be making this soon. At minimum, what we need is the mobile development components able to work on base MonoDevelop, and on Linux. As a starting point - what would it take to get mobile development working on MonoDevelop for Mac (not VS)?

Also, at least for Android, [I was able to find this](https://github.com/xamarin/xamarin-android). Builds are currently failing for Linux, [but they were working 50 days ago, available here.](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/lastSuccessfulBuild/Azure/)

For me personally I don't require an Android emulator, I am fine with just using physical devices.

**Comment by KirillOsenkov** [comment]
Have you considered opening an issue on that repo something along the lines of "Make xamarin-android work on Linux with MonoDevelop"?

**Comment by aaronfranke** [comment]
I probably will ask about MonoDevelop specifically, but only after they get their Linux builds fixed. There seem to be plenty of [issues about specific problems with building](https://github.com/xamarin/xamarin-android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+linux) and also [a generic issue about Linux builds](https://github.com/xamarin/xamarin-android/issues/1272).

Also, I wouldn't mark this issue as "has dependencies" or similar, since we may be able to do stuff in the meantime, such as trying to get mobile dev stuff working on MonoDevelop on Mac (not VS branded)

**Comment by directhex** [comment]
I've been trying to write a reply here which won't get me fired for an hour so far. I don't want to be seen as making company policy, or revealing company secrets.

This is all a discussion of high-level management policy. There's no insurmountable technical barriers to any of the feasible ways to close this issue.

VS for Linux is the 4th most requested item on the VS UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide

I'd say moving up to 2nd is pretty feasible, with some community campaigning. Those UserVoice numbers *do* end up on CVPs' desks. Anyone with a big Microsoft contract who wants it should be passing their feelings on to their sales rep, too.

**Comment by aaronfranke** [comment]
Do you mean to say that it is company policy to only ship the Xamarin mobile development components on products branded as Visual Studio? If so, sad, but it does mean VS for Linux is the solution.

**Comment by Therzok** [comment]
Closing this bug report and this should be handled via uservoice.

**Comment by aaronfranke** [comment]
@Therzok The UserVoice link that @directhex posted now says "This UserVoice instance is no longer available".

**Comment by ice-j** [comment]
@aaronfranke and everyone else trying to see the old UserVoice suggestion, you can use ​[Wayback Machine](https://web.archive.org/web/20190112160747/https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/10662897-visual-studio-for-linux)​. You can just easily navigate to ​[Visual Studio IDE](https://web.archive.org/web/20190113221232/https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) and verify that it was the second most requested feature.

PS. It's been more than 2 years now, are there maybe any news or updates on this that you know of @directhex?

**Comment by KirillOsenkov** [comment]
Folks, I'm just a messenger and it's not my decision, but we have no plans to add any kind of Linux support. Just wanted to set the right expectations. Sorry about that.

The new Developer Community is a good channel to send feedback for the product:
https://developercommunity.visualstudio.com/spaces/41/index.html
