### ISSUE TITLE
Duplicate items in Build Output when running Clean All

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5245]
VS Mac 7.7.0.336 (master)
VS Mac 7.6.0.1838 (release-7.6)

To repro:

 1. Create a new C# library project.
 2. Build it once.
 3. Open the Build Output
 4. Run Clean All
 5. Run Clean All again. Duplicate project node is displayed in Build Output.
 6. Run Clean All a few times - no more duplicates.
 7. Switch to diagnostic view - each Clean All has added a project node.

<img width="704" alt="screen shot 2018-07-01 at 13 48 59" src="https://user-images.githubusercontent.com/372361/42134577-6f240ede-7d36-11e8-9582-2887bcb8b4c5.png">

> VS bug [#641608](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641608)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Rodrigo Moya  
 Commit: b462fa51eac20872a49739da3e42a3ded8d474e1 (xamarin/monodevelop)
