### ISSUE TITLE
Implement Debugger checksum mismatch workaround for line endings

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5260]
Tomas Matousek recommends the following workaround used by the Windows debugger:

if the file was found, but the checksum doesn't match what's mentioned in the .pdb, look at the line endings of the file. Try convert the line endings to opposite (\n -> \r\n, \r\n -> \n) and try calculating that checksum. If that matches, open the file with changed line endings.

This is because the .pdbs can get generated on Windows where Git checks out a file with CRLF, whereas on Mac the file is checked out as-is with LF.

> VS bug [#642329](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/642329)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.282 (master)

Pull Request #7822 merged by: Jeffrey Stedfast
Author: mono
Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.3.0.282 (master)



Pull Request #7822 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.2.0.707 (release-8.2)

Pull Request #7822 merged by: Jeffrey Stedfast
Author: mono
Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.2.0.707 (release-8.2)



Pull Request #7822 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7822 merged by: Jeffrey Stedfast
Author: mono
Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7822 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 56d5c462ffc9b1c0067cbf27195ba243e7063160 (xamarin/monodevelop)
