### ISSUE TITLE
CompositionManager does not provide GetExports API

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5273]
CompositionManager should be surfacing the `GetExports` API endpoints, so users can lazily request parts.

> VS bug [#643097](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643097)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-26] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: b6326c820ef3d3e7c97b957399d6d4ce61e9362f (xamarin/monodevelop)
