### ISSUE TITLE
Text Editor outdents to hard left instead of going back an indent level

### ISSUE THREAD

**Issue by praeclarum** [mono/monodevelop#5279]
When you hit Return in the F# editor it moves the cursor the next line and the same column. Great. However, the virtual space system is broken and if you outdent, it takes you to the beginning of the line.

This is very frustrating when trying to write new functions or else blocks, etc.

This is a regression! The editor used to behave itself.

**Current Behavior**

If you hit backspace, or unindent (Cmd+[) then it takes you to the beginning of the line. 

**Expected Bahavior**

It should outdent the cursor as the C# and text editors do.

I have included a video. 

![fsharpbadoutdent](https://user-images.githubusercontent.com/323548/42232000-262a3178-7ebb-11e8-8045-0aae90751e65.gif)

> VS bug [#642673](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/642673)

**Comment by nosami** [comment]
This behaviour happens in C# files too, but only when unindenting _immediately_ after inserting a newline. As soon as you indent once or more, unindenting works as expected.

![outdentcsharp](https://user-images.githubusercontent.com/667194/42449342-394c4b62-8378-11e8-9ec7-4f38c8bad866.gif)

**Comment by praeclarum** [comment]
Yes it seems to be a bug with the virtual space system.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.592 (master)

Author: Mike Krüger
Commit: 71afefd7f06aa29fde7daa77b50036ba0f66c916 (mono/monodevelop)
