### ISSUE TITLE
Can't click on symbol for Goto Decl when symbol is the first one hovered over

### ISSUE THREAD

**Issue by praeclarum** [mono/monodevelop#5280]
When you hold Cmd in order to jump to a symbol, the first symbol you hover over will not be highlightable again after you move to another symbol.

![fsharpcantselectfirstsymbol](https://user-images.githubusercontent.com/323548/42232749-63a3bf4a-7ebd-11e8-8a5c-5eeae5e1b604.gif)

> VS bug [#642684](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/642684)

**Comment by nosami** [comment]
This bug is reproducible with C# too.

![hoverlinks](https://user-images.githubusercontent.com/667194/42234869-d7fbad50-7eed-11e8-8a83-7e80e54b4d8e.gif)

**Comment by mkrueger** [comment]
Duplicate #4390
