### ISSUE TITLE
Invalid UnityShader.sublime-syntax error logged

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5308]
Seeing the following in the IDE log:

    Invalid .sublime-syntax file : UnityShader.sublime-syntax

Build info:
VS Mac 7.6.0.1910 (release-7.6)
Release ID: 706001910
Git revision: 1984457fb568dd59e9411aa77bd04a89ad7c6daf
Build date: 2018-07-04 02:13:48+00
Build branch: release-7.6
Xamarin extensions: 3f8195c74b50d999fa3dbbe5e8ae1263cb9dc0a5

> VS bug [#643296](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643296)

**Comment by sailro** [comment]
cc @DavidKarlas, I'm going to look at this. Does something changed regarding sublime syntax support ?
Never had issues before
