### ISSUE TITLE
PathTree should be able to remove a node directly

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5316]
Given a `PathTreeNode` returned by `AddNode`, we should be able to call `Remove` on it so it gets removed from the tree itself, without doing an O(n) lookup for the node.

> VS bug [#643326](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643326)

**Comment by Therzok** [comment]
Might not be needed after https://github.com/mono/monodevelop/pull/7019

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.4.0.801 (master)



Pull Request #8273 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc7347980e98b11b07780516493b3f2cc4877d7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.3.0.1260 (release-8.3)



Pull Request #8273 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc7347980e98b11b07780516493b3f2cc4877d7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8273 merged by: Lluis Sanchez  
 Author: mono  
 Commit: bc7347980e98b11b07780516493b3f2cc4877d7f (xamarin/monodevelop)
