### ISSUE TITLE
Fix all in file is slow and unreliable, fails silently

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5359]
Repro:

Open MD @ 50cfb60dfff75eab0c4c0c8b61c0d5928039d504

1. Open
https://github.com/mono/monodevelop/blob/50cfb60dfff75eab0c4c0c8b61c0d5928039d504/main/src/addins/MonoDevelop.PackageManagement/Gui/MonoDevelop.PackageManagement.PackageManagementOptionsWidget.cs

2. Use the fix to remove the redundant `private` keywords. It **takes 3 seconds**, and **only half are removed**:

![image](https://user-images.githubusercontent.com/183285/42533399-b6bdf9f8-8457-11e8-8b47-863a8425c0ac.png)

3. Use fix all again to remove the rest. It gets all the rest successfully.

4. Now use "fix all" on the redundant "global" keyword. It **takes 7 seconds**, and **the caret jumps to the bottom** of the document.

5. Now delete the blank lines between the fields, add "using Gtk;" tio the top of the file, and use fix all on the redundant `Gtk.` in the field declarations. After a couple seconds, move the caret. Nothing happens, the fix **silently fails**.

6. Try that again without moving the caret this time. It takes 7 seconds again, and the caret jumps to the end of the document again, but **only the first instance is fixed**

![image](https://user-images.githubusercontent.com/183285/42533707-a767cfb4-8458-11e8-8f31-1fdf01eaffdd.png)

I'm sure there's more, but this is plenty.

> VS bug [#645577](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/645577)

**Comment by mhutch** [comment]
Fixes take a similar amount of time in VS, but after about a second it shows a blocking dialog.

![image](https://user-images.githubusercontent.com/183285/42534818-b3f1a3ce-845b-11e8-8735-92104dd2ea6c.png)

After this it shows a preview dialog

![image](https://user-images.githubusercontent.com/183285/42534839-c47e345a-845b-11e8-97dd-d7f1e5568b0e.png)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 7.8.0.794 (master)



Pull Request #6006 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 1dd6a8f8d39cbc0834c2ff67447133a8ddef7792 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.0.0.240 (release-8.0)



Pull Request #6006 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 1dd6a8f8d39cbc0834c2ff67447133a8ddef7792 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-43] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6006 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 1dd6a8f8d39cbc0834c2ff67447133a8ddef7792 (xamarin/monodevelop)
