### ISSUE TITLE
Not obvious which "fix all" is which

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5360]
In the following screenshot, there's nothing linking each of the "fix all" fixes to the actual fix description, they just have codes. I *guess* it's same order but it's not clear.

![image](https://user-images.githubusercontent.com/183285/42534268-4bd8bc56-845a-11e8-9669-c2bbe9dd6bb9.png)

> VS bug [#645791](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/645791)

**Comment by mhutch** [comment]
VS handles this by displaying the codes in the fix preview

![image](https://user-images.githubusercontent.com/183285/42534680-59f58322-845b-11e8-87f7-4d8dcf9618b1.png)

**Comment by mkrueger** [comment]
We can't do a preview in the context menu unfortunately :(.
However would be possible in a custom popup dialog like in VS.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1228 (release-7.7)

Pull Request #5776 merged by: Mike Krüger
Author: mono
Commit: cf3cd8a1639c614bb122feebeda0b5cd560b3c3e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5776 merged by: Mike Kr??ger
Author: mono
Commit: cf3cd8a1639c614bb122feebeda0b5cd560b3c3e (xamarin/monodevelop)
