### ISSUE TITLE
MonoTODO analyzer is no longer doing anything

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5385]
Mono now uses reference assemblies for the BCL, so that means that the MonoTODO attribute is being stripped out.

Figure out a way to fix that (probably resolving to the real assembly, rather than the reference assembly).

> VS bug [#646386](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646386)

**Comment by mhutch** [comment]
It would probably be a good idea to look at the options that have been explored for .NET Standard to solve this same problem - indicating that an API might have issues on certain implementations. /cc @terrajobst
