### ISSUE TITLE
Editor shouldn't render whitespace marks for virtual space

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5390]
In situations where the caret is in virtual space and whitespace markers (dots) are enabled, the dots are rendered before the caret, making the impression that the space characters are in the buffer.

The dots should not be rendered if the characters aren't physically in the buffer.

> VS bug [#646142](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646142)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.591 (master)

Author: Mike Krüger
Commit: 0302e4f1ca39cb7a568fb60b039b16bc46433738 (mono/monodevelop)
