### ISSUE TITLE
InstrumentationService counters have no way to handle cancellation

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5392]
See comment thread here: https://github.com/xamarin/md-addins/pull/3292#discussion_r199864137

**Comment by slluis** [comment]
Cancel result can be specified using the [CounterMetadata.Result](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs#L246) property.

For timers it is also possible to specify a cancellation token when calling [BeginTiming](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs#L189), and that will set the result to UserCancel if the operation is cancelled.

**Comment by sgmunn** [comment]
cc @bratsche, so we can tell if the operation was cancelled.
