### ISSUE TITLE
Text does not indent on pressing return for new C# files

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5401]
7.7 Preview (7.7 build 593)

Release ID: 707000593
Git revision: 3e446326d8de8d6cd19c44261fd4003bc96ccf46
Build date: 2018-07-12 08:46:03+00
Build branch: master-mk-refatcoringchanges
Xamarin extensions: 240be06f54a86de12cf9e861cab9c06c358ff97c

Repro:

1. Create a new C# console project.
2. In Program.cs see that pressing return inside the Main method and just inside class before the Main menu indents the text for the new line.
3. A new empty class to the project.
4. Pressing return inside the MyClass constructor and just inside the MyClass definition does not indent the text.
5. Closing and re-opening the file and the indentation is working again.

![texteditorindent](https://user-images.githubusercontent.com/372361/42647055-ac2fe52e-85fa-11e8-96ec-7e80814dc458.gif)

No errors in the IDE log.

> VS bug [#646550](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646550)

**Comment by mrward** [comment]
Looks good in VS Mac 7.7.0.595 (Build branch: master-mk-refatcoringchanges).

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.286 (master)

Author: Mike Krüger
Commit: e3297a11d8ba169cf3ee8198dcb7d93067e284aa (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1140 (release-7.7)

Author: Mike Krüger
Commit: e3297a11d8ba169cf3ee8198dcb7d93067e284aa (mono/monodevelop)
