### ISSUE TITLE
Text editor does not indent on pressing return after if statement

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5414]
VS Mac 7.7.0.595

Release ID: 707000595
Git revision: 13747666f5dca0994b322ba8eba52c2d8473d055
Build date: 2018-07-16 05:25:40+00
Build branch: master-mk-refatcoringchanges
Xamarin extensions: 240be06f54a86de12cf9e861cab9c06c358ff97c

If you have some block statement inside a method such as:

```
if (foo == 1) {
}
```
Then if you press return after the last curly brace the text editor does not indent the next line.

![indentafterifstatement](https://user-images.githubusercontent.com/372361/42766857-6a56a720-8913-11e8-9e6f-dd149d555f62.gif)

A similar thing happens if the statement does not include the curly braces and you press return after the last statement of the if. Also does not need to be an if statement.

> VS bug [#649016](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/649016)

**Comment by mrward** [comment]
VS Mac 7.7.0.596 - looks good to me.
Git revision: 9e89e5d2ba679f9261385012489fa2e3aa5685b6
Build date: 2018-07-17 08:24:03+00
Build branch: master-mk-refatcoringchanges

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.286 (master)

Author: Mike Krüger
Commit: 945816530a05af335cb075ac136e2ac7bb0e5467 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1140 (release-7.7)

Author: Mike Krüger
Commit: 945816530a05af335cb075ac136e2ac7bb0e5467 (mono/monodevelop)
