### ISSUE TITLE
Unclassified spans in editor default to `entity.name.class`

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5427]
https://github.com/mono/monodevelop/pull/5102 introduced the behavior where the unclassified parts of the editor get the type name classification.

For webtools, HTML doesn't classify the text inside elements. It used to be black, but now it is the color of type names.

> VS bug [#649777](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/649777)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.2056 (release-7.6)

Pull Request #5448 merged by: Lluis Sanchez
Author: mono
Commit: 94130ce0baf7990888c1bd792ba490b6285f08cd (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.686 (master)

Pull Request #5446 merged by: Lluis Sanchez
Author: mono
Commit: 5ec86200dd9c07d1c103d6300a6a64d9ded0773d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5446 merged by: Lluis Sanchez
Author: mono
Commit: 5ec86200dd9c07d1c103d6300a6a64d9ded0773d (xamarin/monodevelop)
