### ISSUE TITLE
Skip building unmodified projects by default

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5429]
Change the "Skip building unmodified projects" setting to be on by default, as this is the default in VS2017.

> VS bug [#650154](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650154)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.133 (master)

Author: Mikayla Hutchinson
Commit: e6a6e1a272e8dff853244dadbce94004c2269fbf (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1070 (release-7.7)

Author: Mikayla Hutchinson
Commit: e6a6e1a272e8dff853244dadbce94004c2269fbf (mono/monodevelop)
