### ISSUE TITLE
MEF is queried before idle is hit

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5433]
https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs#L307

> VS bug [#650169](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650169)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5440 merged by: Lluis Sanchez  
 Author: mono  
 Commit: e127b35352c5601cfe6c62ce4fe16b8a77a9d5a4 (xamarin/monodevelop)
