### ISSUE TITLE
New  F# Xamarin.Android Forms project won't compile: The type 'BigInteger' is required here and is unavailable

### ISSUE THREAD

**Issue by PureWeen** [mono/monodevelop#5451]
Version: Version 7.6 Preview (7.6 build 2003)

1. Create a new F# Xamarin Forms Solution for Android
2. try to compile it

Fails with the following error:
/Users/shane/Projects/justandroid/Droid/FSC: Error FS1108: The type 'BigInteger' is required here and is unavailable. You must add a reference to assembly 'System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. (FS1108) (justandroid.Droid)

![image](https://user-images.githubusercontent.com/5375137/42904032-e4433d86-8a90-11e8-9a9f-4d4a4eb6f7d5.png)

> VS bug [#650535](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650535)

**Comment by ChrisCarrAu** [comment]
Check this out
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html

If you reference FSharp.Core, you may need to reference System.Numerics
FSharp.Core doesn’t have a strong binary dependency on System.Numerics (i.e. big-integer support).

However, for some deployments of F# code (e.g. Xamarin mobile apps) you may need to add an explicit reference if it is not present already.

It worked for me

**Comment by mrward** [comment]
Editing the .csproj and changing the System.Numerics reference from:

        <Reference Include="System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" />

To:

        <Reference Include="System.Numerics" />

Seems to fix this build error for me.
