### ISSUE TITLE
F# Add code to Xamarin Android Forms AssemblyInfo so that Resources on Android load properly

### ISSUE THREAD

**Issue by PureWeen** [mono/monodevelop#5452]
If you create a new F# Xamarin.Forms Android project the Navigation ToolBar will take up half the screen

```F#
module Initialization =
    let internal LandingPage(): NavigationPage =
        let welcomePage = ContentPage()
        let navPage = NavigationPage welcomePage
        navPage.Navigation.InsertPageBefore(ContentPage(), welcomePage)
        navPage

type App() =
    inherit Application(MainPage = Initialization.LandingPage())
```

The following line needs to be added into the Android project in order for it to properly load the resources

https://github.com/jimbobbennett/TicTacToe/blob/master/Droid/Properties/AssemblyInfo.fs#L6-L8

It would helpful to users to just have this be part of the default template

> VS bug [#650536](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650536)

**Comment by nosami** [comment]
Hey Andres,

Looks like something is bust with the github sync tool. Anyways,

```
@external Fixed in version 7.8.0.296 (master)

Pull Request #3462 merged by: Lluis Sanchez
Author: xamarin
Commit: 879336bcc0488dd80299d01dff31e06a25100352 (xamarin/md-addins)
Included in Commit: fb14928d903eb44d06923b3ae0e1422314ddbe57 (mono/monodevelop)

xamarinc
xamarinccommented 18 hours ago
@external Fixed in version 7.7.0.1141 (release-7.7)

Pull Request #3462 merged by: Lluis Sanchez
Author: xamarin
Commit: 879336bcc0488dd80299d01dff31e06a25100352 (xamarin/md-addins)
Included in Commit: 6839b4b12a8330a7e36f84c9a8f1e4ba1831c8fc (mono/monodevelop)
```

**Comment by knocte** [comment]
Thanks!

**Comment by nosami** [comment]
@knocte https://github.com/xamarin/Xamarin.Forms/issues/3329#issuecomment-417225761
