### ISSUE TITLE
Building NuGet packaging project does not generate .nupkg

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5456]
VS Mac 7.6.0.2005 - Broken.
VS Mac 7.5.3 - OK.

The Multiplatform - Library - Multiplatform Library project template and the Other - .NET - NuGet package project template do not generate a NuGet package

> VS bug [#650951](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650951)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5459 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a4a6e8b261b478ba7602614c89b6436dc96b9914 (xamarin/monodevelop)
