### ISSUE TITLE
code completion: constructor to assign a member does not show argument candidates

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#5477]
There is a code completion bug that appears to happen when 1) we try to use constructor and 2) the assignee is field or property, not local variable.

Repro code fragment is like this:

```
public class C
{
    Uri uri;

    public void M ()
    {
        uri = new Uri  // <<<=== continue from here
    }
}
```

![image](https://user-images.githubusercontent.com/53929/43043366-4c50b914-8dcd-11e8-8f52-01345252f5b2.png)

Environment:

- monodevelop master 6e3695ee
- Mono 5.17.0 (master/0d191ef1ab9 2018年  7月 13日 金曜日 23:32:57 JST) (64-bit)

> VS bug [#652663](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652663)

**Comment by mkrueger** [comment]
Closed - upstream https://github.com/dotnet/roslyn/issues/28806

**Comment by CyrusNajmabadi** [comment]
@atsushieno 

Sorry, i'm not quite understanding what the actual bug is.  What is the expected behavior that is wanted here, and what are the precise repro steps.  I'm not sure what is meant by "continue from here."

Could you help clarify?  Thanks!

**Comment by Therzok** [comment]
I guess this fixes it https://github.com/dotnet/roslyn/pull/23696/files
