### ISSUE TITLE
New line indents end curly brace to different level

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5478]
VS Mac: 7.7.0.596
Git revision: 9e89e5d2ba679f9261385012489fa2e3aa5685b6
Build date: 2018-07-17 08:24:03+00
Build branch: master-mk-refatcoringchanges
Xamarin extensions: 240be06f54a86de12cf9e861cab9c06c358ff97c

Pressing newline on the line with the end curly brace seems to indent the curly brace to the wrong level.

VS Mac 7.7.0.596:

![newlineindent](https://user-images.githubusercontent.com/372361/43046808-5c91ed90-8dc6-11e8-8d38-8370c01e5dbf.gif)

VS Mac 7.6.0.2005:

![newlineindent76](https://user-images.githubusercontent.com/372361/43046810-5f112f68-8dc6-11e8-8122-10ee442b8190.gif)

> VS bug [#652562](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652562)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.286 (master)

Author: Mike Krüger
Commit: 0cc07db905495b53e0acf38084a37076d28b804d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1140 (release-7.7)

Author: Mike Krüger
Commit: 0cc07db905495b53e0acf38084a37076d28b804d (mono/monodevelop)
