### ISSUE TITLE
The updater doesn't give any indication of what it's updating.

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#5480]
It only displays the number of updates and `Installing application...`

<img width="497" alt="screen shot 2018-07-23 at 11 59 22 am" src="https://user-images.githubusercontent.com/667194/43073892-1a0a630a-8e73-11e8-91c1-e98eaab7b0a8.png">

> VS bug [#652852](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652852)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.460 (master)

Pull Request #5970 merged by: Rodrigo Moya
Author: xamarin/fix
Commit: 8ef71e80d62f64b1dafb956f76496aff280788e9 (xamarin/md-addins)
Included in Commit: 6181f69f7b4bcf98cdb2ff26f4f7f96df16f26b6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.6.0.460 (master)



Pull Request #5970 merged by: Rodrigo Moya  
 Author: xamarin/fix  
 Commit: 8ef71e80d62f64b1dafb956f76496aff280788e9 (xamarin/md-addins)  
 Included in Commit: 6181f69f7b4bcf98cdb2ff26f4f7f96df16f26b6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.5.0.1340 (release-8.5)

Pull Request #5970 merged by: Rodrigo Moya
Author: xamarin/fix
Commit: 8ef71e80d62f64b1dafb956f76496aff280788e9 (xamarin/md-addins)
Included in Commit: a0a9193d06b52207e17420c7204419c4de80e4d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.5.0.1340 (release-8.5)



Pull Request #5970 merged by: Rodrigo Moya  
 Author: xamarin/fix  
 Commit: 8ef71e80d62f64b1dafb956f76496aff280788e9 (xamarin/md-addins)  
 Included in Commit: a0a9193d06b52207e17420c7204419c4de80e4d5 (mono/monodevelop)
