### ISSUE TITLE
Outdated Build dialog is no longer displayed

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5485]
VS Mac 7.7.0.730 (master) - Bad
VS Mac 7.7.0.598 (master) - OK
VS Mac 7.6.0.2093 (release-7.6) - OK

To reproduce:

1. In Preferences uncheck Projects - Build - Build project before running.
2. Create a new C# console project
3. Click the Run icon in the main toolbar to run the project.

Expected result:

Dialog is displayed indicating that a build is required.

<img width="609" alt="outdatedbuild" src="https://user-images.githubusercontent.com/372361/43079304-a50538b6-8e84-11e8-9eae-7cb7b801d1b9.png">

Actual result:

No Outdated Build dialog is displayed. An attempt is made to run the project but no .exe has been built.

> VS bug [#652873](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652873)

**Comment by mrward** [comment]
I am guessing that some behaviour has changed in this pull request that was recently merged to master - https://github.com/mono/monodevelop/pull/5408

**Comment by mrward** [comment]
This happens if Build project before running is checked too. No build happens after creating a new project when you try to run the project.

**Comment by mrward** [comment]
Debugging the ProjectOperations.Execute method there is now a new SolutionItemBuildBatch class which is used but it relies on the solution and projects all implementing the GetExecutionDependencies method. All implementations of the GetExecutionDependencies all end up returning no items.

**Comment by mrward** [comment]
Also it looks like the tests are never built when you run them even if the test code has changed now since GetExecutionDependencies is not implemented.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5515 merged by: Matt Ward  
 Author: mono  
 Commit: d34ab4348b059f66c32de24a26b014fe1b22637e (xamarin/monodevelop)
