### ISSUE TITLE
Multi startup project run configuration - arguments not passed after reload

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5498]
VS Mac 7.6.0.2093
Related to fix in https://github.com/mono/monodevelop/pull/5497

**To repro:**

1. Create new C# .NET Core console project A
2. Add new C# .NET Core console project B.
3. Change Program.cs in both console projects to report what project they are and how many command line arguments are being passed.

		static void Main (string[] args)
		{
			Console.WriteLine ("Project A: " + args.Length);
		}
4. Create a new solution run configuration via solution options that starts both A and B projects.
5. Select this new multi solution run configuration in the main toolbar.
6. Edit the run configs for the two projects via project options and add some start arguments to both projects.
7. Build and run the multi solution run config using the main toolbar's run button.
8. Check correct argument counts passed to both console projects.
9. Edit Project A (.csproj) and Project B (.csproj) in the text editor by using Tools - Edit File.
10. Make a small change to each Project A and Project B .csproj in the text editor (e.g. add a space character somewhere that will not break the project) and save the files.
11. Restore should occur.
12. Change the number of arguments passed to A and B in their project run configs.
13. Run the solution from the main toolbar.

**Expected result:**

The number of arguments passed to A and B console apps are correct.

**Actual result:**

The number of arguments is incorrect - still sending the number of arguments at step 8.
Closing and re-opening the solution fixes the problem.

> VS bug [#653269](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/653269)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.6.0.785 (master)



Author: Matt Ward  
 Commit: d15e5c67513b793ec1a27fdd0a5ed7e7817303e2 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: d15e5c67513b793ec1a27fdd0a5ed7e7817303e2 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.5.0.1694 (release-8.5)



Author: Matt Ward  
 Commit: d15e5c67513b793ec1a27fdd0a5ed7e7817303e2 (xamarin/monodevelop)
