### ISSUE TITLE
Cannot open file explorer

### ISSUE THREAD

**Issue by francescofinotto** [mono/monodevelop#5514]
i've build monodevelop from git repo, when i create a project i can't open directory explorer to choose path. 
when compile a project exit with exceptio HRESULT 0x8007010B and 0x80070002

**Comment by OptimusPyne** [comment]
Sounds similar to https://github.com/mono/monodevelop/issues/5501?

**Comment by francescofinotto** [comment]
yes i guess it's the same problem i try to figured out why but it seems like monodevelop cannot access files outside project

**Comment by mrward** [comment]
If you can attach the IDE log after reproducing the error we can see if it is the same problem.

IDE logs should be found in:

~/AppData/Local/MonoDevelop/{version}/Logs/

**Comment by mrward** [comment]
Thanks. Yeah this looks the same as #5501
