### ISSUE TITLE
Hang while computing the compilation on the main thread

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#5520]
I was debugging VSM inside VSM and the second instance started beachballing. I went to the first instance and hit 'pause' in the debugger and captured this trace on the main thread:

https://gist.github.com/alanmcgovern/d925aa55e4aff6b55f71499c232691ba

It's possible the real culprit had completed it's work and i paused on something innocuous, but I'm filing this anyway :)

At the time I had two windows open side by side - i was editing a c# file on the left and on the right I had a forms xaml file open.

> VS bug [#655353](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/655353)

**Comment by Therzok** [comment]
That code went away with https://github.com/xamarin/monodevelop/commit/e87678921c5b953338b9a2b78e4e1dd556bb49c5#diff-9e1391a2b20056d13a7ccda5b699e750R51
