### ISSUE TITLE
Code completion incorrectly inserts code

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#5521]
I'm just trying to write three characters `();` but code completion is insistent that i put in a few extra dots ;p

http://recordit.co/J2HgT28yO2

> VS bug [#654728](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/654728)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.36 (master)

Pull Request #5525 merged by: Mike Krüger
Author: mono
Commit: 70d6c7ed03272f31d5eb6195792bba6f6d9188ee (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.126 (release-7.7)

Pull Request #5525 merged by: Mike Krüger
Author: mono
Commit: 70d6c7ed03272f31d5eb6195792bba6f6d9188ee (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.931 (release-7.7)

Pull Request #5525 merged by: Mike Krüger
Author: mono
Commit: 70d6c7ed03272f31d5eb6195792bba6f6d9188ee (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5525 merged by: Mike Kr??ger
Author: mono
Commit: 70d6c7ed03272f31d5eb6195792bba6f6d9188ee (xamarin/monodevelop)
