### ISSUE TITLE
[System.Net.WebClient] DownloadProgressChangedEventArgs properties returns wrong values when downloading file on Linux.

### ISSUE THREAD

**Issue by wojciechowskidawid** [mono/monodevelop#5541]
When I download file from url by WebClient and subscribe method to DownloadProgressChanged for download progress watching,  TotalBytesToReceive and ProgressPercentage properties returns wrong values. e. g. while download "https://download.mono-project.com/archive/5.12.0/windows-installer/mono-5.12.0.301-x64-0.msi" TotalBytesToReceive returns -1. It works fine on Windows.

My environment: Ubuntu 18.04, MonoDevelop 7.5(build 1255)

# My download method:
~~~~
public void DownloadFromUrl(string url)
        {
            using (var client = new WebClient())
            {
                client.DownloadProgressChanged += (sender, e) =>
                {
                    Console.WriteLine($"Downloading: {e.ProgressPercentage}% | {e.BytesReceived} B / {e.TotalBytesToReceive} B");
                };

                client.DownloadFileCompleted += delegate (object sender, AsyncCompletedEventArgs e)
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                    Console.WriteLine("Download Completed");
                    Console.ResetColor();
                };

                client.DownloadFileAsync(new Uri(url), "output");
            }
        }
~~~~

**Comment by mrward** [comment]
Would you be able to file this on http://github.com/mono/mono/issues since that seems not be a MonoDevelop problem but a mono problem on Linux? Thanks.

**Comment by wojciechowskidawid** [comment]
sure, my bad
