### ISSUE TITLE
Autosave does not load autosaved file

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5542]
VS Mac 7.6.0.2109 - Bad
VS Mac 7.5 - OK.

**To repro:**

1. Create a new C# library project.
2. Edit MyClass.cs with some unsaved changes.
3. Force Quit the IDE (or kill the process).
4. Re-open the IDE.
5. Re-open the project last created.

**Expected result:**

See a message in MyClass.cs about unsaved changes.

<img width="958" alt="autosave" src="https://user-images.githubusercontent.com/372361/43413195-4bfe05b0-9427-11e8-89af-3ce01c3ab5e7.png">

Clicking the Load from autosave button recovers the unsaved changes.

**Actual result:**

Message appears saying that the MyClass.cs file has been changed outside the IDE. The Load from autosave button is not available. The Reload from disk will load the MyClass.cs file without the unsaved changes. The Keep Changes button results in an empty MyClass.cs file.

I suspect this is file watcher related.

> VS bug [#656105](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/656105)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-25] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: 349ceeb50d7fe0ef371c6c56b363aa2d4a6d2d9f (xamarin/monodevelop)
