### ISSUE TITLE
Assembly browser never opens with any assembly

### ISSUE THREAD

**Issue by peteroupc** [mono/monodevelop#5543]
Double clicking on an assembly reference in the Solution or Classes pads shows a message like the following, rather than assembly information.

> **The file [name of assembly file] could not be opened.**
> The type initializer for 'System.Collections.Generic.List`1' threw an exception.

Even choosing "Assembly Browser" in the Tools menu appears to have no visible effect.

What is causing this issue?  

This issue is from MonoDevelop 7.1 preview (build 838) on Ubuntu.

> VS bug [#656410](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/656410)

**Comment by mkrueger** [comment]
Works for me - 7.1 is a bit outdated. I always build the master version from source which is now 7.7.
