### ISSUE TITLE
(Linux/7.6.0) Editor font settings cannot be saved.

### ISSUE THREAD

**Issue by lss4** [mono/monodevelop#5544]
OS: Manjaro Linux XFCE (Kernel: 4.17.9-1-MANJARO)
Version: [monodevelop-stable](https://aur.archlinux.org/packages/monodevelop-stable/) 7.6.0-1760

I'm having this issue with version. While setting fonts work, after restarting it reverts back to default, and from the setting files I couldn't find anything font-related.

This issue doesn't happen with the Flatpak version of monodevelop (7.3.3). However, the reason I now switched to the AUR version was because I couldn't open projects that aren't in my home folder with the Flatpak version (same reason as #3685).

Unfortunately, Arch/Manjaro isn't an officially supported distro so I'm not sure if the issue is caused by packaging (although the PKGBUILD actually builds it from source), or by this version of monodevelop itself.

> VS bug [#669533](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669533)

**Comment by Tomaszal** [comment]
I am experiencing the same issue with this package on Arch Linux.

**Comment by directhex** [comment]
It's not a packaging issue, I can see the same here.

**Comment by mrward** [comment]
Does not seem to be Linux specific. I can repro with VS Mac 7.6. Also reported on the [Developer Community forum](https://developercommunity.visualstudio.com/content/problem/319619/environment-preferences-not-retained.html)

VS Mac 7.5.4.3 is OK.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5762 merged by: Lluis Sanchez  
 Author: mono  
 Commit: f37b71b866e119e45d77baadaee1d9fd17cc7bd1 (xamarin/monodevelop)
