### ISSUE TITLE
Welcome page should not show when load previous solution on startup is checked

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5553]
Similar to 
https://github.com/mono/monodevelop/issues/5472
https://github.com/mono/monodevelop/pull/5473

This should not show the welcome page when load previous solution is checked

> VS bug [#657031](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657031)

**Comment by Therzok** [comment]
@rodrmoya is this still an issue with GTC?

**Comment by asb3993** [comment]
@Therzok This is fixed with GTC
