### ISSUE TITLE
EditorConfig context is queried even for files which will not use it

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5566]
Given a [TextEditor.FileNameChanged](https://github.com/mono/monodevelop/blob/065a119e273dcc332611537138c4b140efe47b42/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs#L1058-L1065) handler invocation, we might end up querying an editor config context even though the editor options might not use them in the end.

Rework the logic a bit so we only query and cache the context _iff_ they will be used.

> VS bug [#657369](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657369)

**Comment by Therzok** [comment]
Fixed via https://github.com/mono/monodevelop/pull/5567

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-29] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 2b178d53e8ed354f09813b2087d02dd145b0b6af (xamarin/monodevelop)
