### ISSUE TITLE
Alt-shift-left/right no longer extends selection

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5590]
Version 7.7 build 768

Rather than extending the selection by a word, alt-shift-left/right now _moves_ the selection by a word 

![2018-08-03 15_57_22](https://user-images.githubusercontent.com/183285/43663021-f0d4aaec-9735-11e8-9113-3143f8ab0241.gif)

> VS bug [#659183](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/659183)

**Comment by mhutch** [comment]
In comments it's even worse, it moves the selection by a single character within words.

![2018-08-03 16_04_21](https://user-images.githubusercontent.com/183285/43663278-e6126ed6-9736-11e8-8333-bdf623fb6174.gif)

**Comment by mkrueger** [comment]
Interesting - works on linux but not on os x

**Comment by mhutch** [comment]
Can we add some tests for this? It's pretty fundamental.

**Comment by mhutch** [comment]
I gave 5bb533efb6a9e7daeb5ad341d3c2c8b1bd283b56 a spin and it's even worse.

Alt-shift-left/right extends the selection now, but it doesn't *start* a selection if nothing is selected.

And word navigation in comments skips over *entire sentences*.

**Comment by mkrueger** [comment]
hm, we had tests for it but I don't know how the vs.net commands should behave. But what's weird is that it doesn't work on os x but on linux it works - I can't find any difference there.

Maybe I should switch back to our custom implementation.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.82 (master)

Pull Request #5650 merged by: Mikayla Hutchinson
Author: mono
Commit: 23fb81854741266de8af1e87863bfbe7537e3bcc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.126 (release-7.7)

Pull Request #5650 merged by: Mikayla Hutchinson
Author: mono
Commit: 23fb81854741266de8af1e87863bfbe7537e3bcc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.931 (release-7.7)

Pull Request #5650 merged by: Mikayla Hutchinson
Author: mono
Commit: 23fb81854741266de8af1e87863bfbe7537e3bcc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5650 merged by: Mikayla Hutchinson
Author: mono
Commit: 23fb81854741266de8af1e87863bfbe7537e3bcc (xamarin/monodevelop)
