### ISSUE TITLE
Snippets in clipboard ring are excessively ellipsized

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5709]
Snippets in the clipboard ring are ellipsized much too short, especially the tooltips:

![image](https://user-images.githubusercontent.com/183285/44276806-ab329800-a216-11e8-8fbb-ccddc1f56f62.png)

> VS bug [#669788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669788)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.429 (master)

Pull Request #5746 merged by: Mikayla Hutchinson
Author: mono
Commit: 85657687b9d8393ccce05b5806ed52c52815e981 (mono/monodevelop)
