### ISSUE TITLE
Project 'po' fails to build

### ISSUE THREAD

**Issue by d07RiV** [mono/monodevelop#5714]
I'm following the instructions for Windows from https://www.monodevelop.com/developers/building-monodevelop/ 

Everything built, except `po` (localization) project, which gives the following error:

    1>------ Build started: Project: po, Configuration: Debug Any CPU ------
    1>C:\Program Files (x86)\Microsoft Visual 
    Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2812,7): error 
    MSB4057: The target "CreateManifestResourceNames" does not exist in the project.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Also, why is there no pre-built version? Building it (or almost anything else on Windows) is such a pain, to the point where it's easier to get a linux VM and install it there.

**Comment by DavidKarlas** [comment]
`po` is special project that Visual Studio doesn't understand. You can ignore it.
