### ISSUE TITLE
Potential hang in AssemblyBrowser

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5716]
http://source.monodevelop.com/#MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs,60

> VS bug [#669791](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669791)

**Comment by mkrueger** [comment]
Can't happen anymore. (note: was a .Result call on UI thread)
