### ISSUE TITLE
'Next' button in 'New Project' dialog does not work

### ISSUE THREAD

**Issue by yannick-kluth** [mono/monodevelop#5733]
When I start a new project in monodevelop and click on the 'Next' button after choosing a project type, nothing happens i.e. the dialog where it should be possible to choose a name for the project won't show up. Clicking the next button once again, I receive an error message saying illegal project name.

monodevelop version: 7.5 build 1255
OS: Ubuntu 18.04.1 LTS

![bildschirmfoto vom 2018-08-22 00-37-11](https://user-images.githubusercontent.com/34140353/44432735-9867ec80-a5a3-11e8-9918-be92266ec9c3.png)

**Comment by mrward** [comment]
This looks the same as https://github.com/mono/monodevelop/issues/5453
