### ISSUE TITLE
Custom MSBuild task built with netstandard 1.3 dependencies fails on latest preview with missing method exception

### ISSUE THREAD

**Issue by PureWeen** [mono/monodevelop#5773]
```
System.MissingMethodException: Method not found: void System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
```

### Reproduction Steps

1) Compile SomeBuildTask
2) Compile MSbuildError

Works fine on: Version 7.6.1 (build 9)
Fails on: 7.8 Preview (7.8 build 129)

### Notes
- If I copy  *System.IO.FileSystem.Primitives.dll* from nuget 2.0.3 netstandard into the bin directory where *CopyLocalLockFileAssemblies* copies everything then everything works fine and msbuild is able to use the custom task
- In our case we are using Mono.Cecil ( which is netstandard 1.3) and we have CopyLocalLockFileAssemblies set to true on our project, but our project is netstandard 2.0 so it seems like it should be copying the netstandard 2.0 version of this library not the 1.3 version.
```
Copying file from "/Users/shane/.nuget/packages/system.io.filesystem.primitives/4.3.0/lib/netstandard1.3/System.IO.FileSystem.Primitives.dll" to "bin/Debug/netstandard2.0/System.IO.FileSystem.Primitives.dll".
```

- this compiles fine on stable but doesn't compile on alpha

Our Xamarin Forms project having issues
[MsbuildError.zip](https://github.com/mono/monodevelop/files/2320276/MsbuildError.zip)

It's using https://github.com/jbevain/cecil/

> VS bug [#672062](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672062)

**Comment by mrward** [comment]
Unable to repro the build error with VS Mac 7.8.0.249 and Mono 5.12.0.301.

Will try alpha channel versions of VS Mac 7.8 and Mono 5.16.

**Comment by PureWeen** [comment]
@mrward   ugh sorry I uploaded the wrong zip for the simpler one :-/ let me fix that

In the mean time
https://github.com/mono/monodevelop/files/2320276/MsbuildError.zip

should still cause the error  but not sure if you already tested that one

**Comment by mrward** [comment]
I tested both projects from the two zip files. They both build OK with Mono 5.12.0.301.

Installing Mono 5.16.0.113 and the project fails to build with VS Mac 7.8.0.249 and VS Mac 7.6.1.

This problem can be reproduced from the command line just using msbuild so it looks like something has changed in Mono 5.16.

**Comment by Therzok** [comment]
Issue moved to [mono/mono #10352](https://github.com/mono/mono/issues/10352) via [**ZenHub**](https://www.zenhub.com/)
