### ISSUE TITLE
CommentTaskProvider should try safe casts to MonoDevelopWorkspace

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5782]
Can throw exception with Razor workspace

> VS bug [#672552](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672552)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 61e8edf83b051f28fbf8f7e25adde619e8cac2f9 (xamarin/monodevelop)
