### ISSUE TITLE
.Net Core needed for build

### ISSUE THREAD

**Issue by ShalokShalom** [mono/monodevelop#5788]
I build this on pure mono, which seems to be too less: 
![screenshot_20180828_145202](https://user-images.githubusercontent.com/6344099/44724104-18c1ac80-aad2-11e8-9739-af6224f3ae83.png)

**Comment by ShalokShalom** [comment]
Wrong repo, GTKSharp is just a dependency. ;)

**Comment by Therzok** [comment]
We don't depend on gtk# 3.0.
