### ISSUE TITLE
Inline search/replace dialog focuses editor

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5802]
When using the search/replace dialog, typing anything will select the text in the editor, not in the search box, thus typing there.

cc @iainx @mkrueger

> VS bug [#674916](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674916)

**Comment by mkrueger** [comment]
I can't reproduce it with the current master version. However it doesn't seem that there are any relevant commits that could've fixed that.

Can you reproduce it with master of today and give me a screencast ? Maybe I do something different.

**Comment by Therzok** [comment]
Can't seem to reproduce anymore.
