### ISSUE TITLE
Inability to load a ruleset file should backup the old one and create a new default one

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5809]
> VS bug [#674260](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674260)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-6] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: b8eec928f8388b4a286791a3c30d15cd81b0f6da (xamarin/monodevelop)
