### ISSUE TITLE
Completion Suggestion Mode doesn't work as expected in collection initializers

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5816]
1. Open a C# file with `using System.Collections.Generic;`
2. Inside a method body, type `var list = new List<string> {`
3. Make sure the closing `}` is auto-inserted and the caret is between the curlies: `new List<string> { |}`
4. Note that at this time completion list is showing, String is soft-selected
5. Press ENTER

**Expected:**
ENTER to insert a line break between the curlies, because String is not hard-selected

**Actual:** 
String is inserted into the buffer, line break is not inserted.

![image](https://user-images.githubusercontent.com/679326/44884249-81925b80-ac6f-11e8-9120-eaff20992934.png)

> VS bug [#674655](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674655)

**Comment by mkrueger** [comment]
This behavior is controlled by roslyn you can open directly roslyn bugs (check vs.net behavior beforehand).

https://www.screencast.com/t/d2mw0l18ubc

**Comment by KirillOsenkov** [comment]
Looks like the following is a prerequisite for the bug to happen: type out the text as per the repro steps, don't use the mouse and you will see the repro:

![5816](https://user-images.githubusercontent.com/679326/45505706-21f18100-b742-11e8-90ee-a307564d0ba6.gif)

Note that in your screencast from Windows you're not following the repro steps, you're manually triggering completion using the mouse. MonoDevelop triggers completion the moment you press `{`, this does not happen on Windows.

![5816windows](https://user-images.githubusercontent.com/679326/45505828-7a288300-b742-11e8-9488-28d4d77d5204.gif)

**Comment by mkrueger** [comment]
Then the bug description is wrong. Then the bug isn't the suggestion mode it's that it opens in this context.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1421 (release-7.7)

Pull Request #6067 merged by: Lluis Sanchez
Author: mono
Commit: d602a5329c6c157f09bacf5464ee0287b21d99f8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.575 (master)

Pull Request #5980 merged by: Lluis Sanchez
Author: mono
Commit: 919a67513629a9b726ac702a98a0d45ad057c6fc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5980 merged by: Lluis Sanchez
Author: mono
Commit: 919a67513629a9b726ac702a98a0d45ad057c6fc (xamarin/monodevelop)
