### ISSUE TITLE
Inconsistent NugetRestore-related build error "Microsoft.NuGet.targets(5,5): Error: Your project is not referencing the 'MonoAndroid,Version=v8.1' framework"

### ISSUE THREAD

**Issue by knocte** [mono/monodevelop#5850]
Steps to reproduce:
1. git clone https://github.com/diginex/geewallet.git
2. cd geewallet
3. git checkout bugreport/vsmac-nuget-android
4. git submodule update --init --recursive
5. Open solution geewallet.sln in Visual Studio for Mac.
6. Open solution folder “build”, right click on project ZXing.Net.Mobile.Forms.Android -> build

Current results:
Gives compiler error “/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/Microsoft/NuGet/Microsoft.NuGet.targets(5,5): Error: Your project is not referencing the "MonoAndroid,Version=v8.1" framework. Add a reference to "MonoAndroid,Version=v8.1" in the "frameworks" section of your project.json, and then re-run NuGet restore. (ZXing.Net.Mobile.Forms.Android)”

Expected results:
1. To begin with, the error is wrong because it should not mention “project.json”, as the file is a .csproj file.
2. It should compile successfully anyway because the file has:
```
<TargetFrameworkVersion>v8.1</TargetFrameworkVersion>
```

VSforMac version: stable channel:
```
Visual Studio Community 2017 for Mac
Version 7.6.3 (build 1)
Installation UUID: fd06ff65-69de-47ae-8b99-ddf257032b7c
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

Xamarin.iOS
Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/andres/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706030001
Git revision: 18a828b090fb6d2cfb0b3576cd6d7eb764f29753
Build date: 2018-08-30 15:12:59+00
Build branch: release-7.6
Xamarin extensions: f4aee57d7b72fa4be6b6d585ac90d614f20fa426

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Internet of Things (IoT) development (Preview) 7.5
```

> VS bug [#678161](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678161)

**Comment by mrward** [comment]
A workaround should be to set AndroidUseLatestPlatformSdk to false to prevent Visual Studio for Mac trying to restore for MonoAndroid v9.0.

This was filed on the developer community forum before. I will try to find that post.

**Comment by mrward** [comment]
Found the developer community feedback post - https://developercommunity.visualstudio.com/content/problem/323035/your-project-is-not-referencing-the-monoandroidver-1.html

**Comment by mrward** [comment]
Going to close this. The feedback item is marked as fixed.
