### ISSUE TITLE
NullRef in SyntaxHighlighting.cs

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5856]
curMatch was null here:
https://github.com/mono/monodevelop/blob/dba41fd415c07390dc4322e7ecb1a8ef144a3175/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs#L242

Apparently I was under debugger and hit a timeout, so curMatch was null. We should protect against that case.

> VS bug [#677272](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677272)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.439 (master)

Pull Request #5859 merged by: Lluis Sanchez
Author: mono
Commit: 46dd660d17d96f78f3647168147cdeba7f51d709 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5859 merged by: Lluis Sanchez
Author: mono
Commit: 46dd660d17d96f78f3647168147cdeba7f51d709 (xamarin/monodevelop)
