### ISSUE TITLE
Log everything that roslyn reports to the log file

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5884]
Currently, we filter out the messages incoming from roslyn and write them in the Ide log.

Add another logger that fully logs roslyn events into its own file.

> VS bug [#679463](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/679463)

**Comment by Therzok** [comment]
@slluis I have a patch for this, can we add it to 7.6 to better diagnose what's going on with roslyn?

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 7.8.0.1156 (master)



Author: Marius Ungureanu  
 Commit: 846802f07456698eda6d78a80e44f3dc77a85c7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 7.8.0.1193 (release-7.8)



Author: Marius Ungureanu  
 Commit: 846802f07456698eda6d78a80e44f3dc77a85c7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.0.0.658 (release-8.0)



Author: Marius Ungureanu  
 Commit: 846802f07456698eda6d78a80e44f3dc77a85c7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: Marius Ungureanu  
 Commit: 846802f07456698eda6d78a80e44f3dc77a85c7f (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-39] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 846802f07456698eda6d78a80e44f3dc77a85c7f (xamarin/monodevelop)
