### ISSUE TITLE
Method curly brace indentation incorrect

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5924]
VS Mac 7.8.0.436
Git revision: 4d3967b5ad4f7d4619acf0b9af30afc3c684b504
Build date: 2018-09-11 08:37:58+00
Build branch: master
Xamarin extensions: 865b7659f99c9ec1f1f675fb98abb2b366f757f1

Indentation for first brace of method is at the wrong level.

![indentation](https://user-images.githubusercontent.com/372361/45358593-c8fadf00-b5c1-11e8-904a-bb4fae740865.gif)

Preferences - Text Editor - C#

- Automatically format when typing - unchecked
- Automatically format on return - checked or unchecked - same behaviour
- Automatically format on paste - checked

Enabling `Automatically format when typing` fixes the problem but causes another problem with the C# removing the space between the end of the method name and the opening brace '(' - will open a separate bug for this other problem.

> VS bug [#681944](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681944)

**Comment by mkrueger** [comment]
This functionality is part of 'Automatically format when typing'
