### ISSUE TITLE
Format document does not use the formatting settings

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5925]
VS Mac 7.8.0.436
Git revision: 4d3967b
Build date: 2018-09-11 08:37:58+00
Build branch: master
Xamarin extensions: 865b7659f99c9ec1f1f675fb98abb2b366f757f1

I have C# formatting options in preferences so that code by default matches the standard MonoDevelop format. However when I format code it seems to use VS on Windows style. This works OK in VS Mac 7.6. Screencast below shows what happens on selecting Edit - Format - Format Document. The code formatting should not change.

![formatting](https://user-images.githubusercontent.com/372361/45359138-8508d980-b5c3-11e8-8ab5-1c51f370bd47.gif)

> VS bug [#681946](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681946)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.489 (master)

Pull Request #5954 merged by: Lluis Sanchez
Author: mono
Commit: 04cef98f963d27918ef7213bd4110c7d8005e521 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1319 (release-7.7)

Pull Request #5955 merged by: Lluis Sanchez
Author: mono
Commit: 654aec98f2743a5533f586a25b54348f7ee9ff13 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5954 merged by: Lluis Sanchez
Author: mono
Commit: 04cef98f963d27918ef7213bd4110c7d8005e521 (xamarin/monodevelop)
