### ISSUE TITLE
MSBuildBuilder.exe is being run as 32bit

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5926]
Not sure why, we should be using mono64 to run it.

> VS bug [#681973](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681973)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.442 (master)



Author: therzok  
 Commit: 3be92db886ff117dfbb6575c743bfdbf9a18be3c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 7.7.0.1306 (release-7.7)



Pull Request #5933 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 9531e91223f506b4094a9b149bad7cbf7547043c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 3be92db886ff117dfbb6575c743bfdbf9a18be3c (xamarin/monodevelop)
