### ISSUE TITLE
Search result text height differences 

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5949]
VS Mac: 7.8.0.444
Git revision: 42be91afe3ba525f327837045ca91fd2c834cd7b
Build date: 2018-09-12 06:07:51+00
Build branch: master
Xamarin extensions: 14685af820b66440e7a955d9a31c4431e592ba6b

Open monodevelop's Main.sln and find the DebuggerFeatures.cs file, right click and find references for the Tracepoint enum.

**Expected result**

All search result lines are the same height.

**Actual result**

<img width="1012" alt="searchresulttextheight" src="https://user-images.githubusercontent.com/372361/45441102-1e181d00-b6b6-11e8-98cb-00f42a7b5361.png">

> VS bug [#682954](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/682954)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 7.8.0.513 (master)



Pull Request #5937 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 64f3e47807c55fe0efd117541c2b33b0c18ea177 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 7.7.0.1368 (release-7.7)



Pull Request #6016 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 5061e0e8a5c0ab6869c331c225370c607e9eebb0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 7.6.7.42 (release-7.6)



Pull Request #6009 merged by: Lluis Sanchez  
 Author: mono  
 Commit: cd4fda86e73cabac7fd7d7d20020de680b67d3fc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #5937 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 64f3e47807c55fe0efd117541c2b33b0c18ea177 (xamarin/monodevelop)
