### ISSUE TITLE
Subversion support on Mac should depend on either Xcode or CommandLineTools

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5950]
Currently we have a hard dependency on Xcode for Subversion support.

Allow CommandLineTools to be used too.

> VS bug [#683000](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/683000)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 7.6.7.26 (release-7.6)



Author: therzok  
 Commit: 08e51fbe000688583c72bec382b6bb4e30bd94da (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 05c8c2cd11155fb618c4b3224bad09bd0ed9477b (xamarin/monodevelop)
