### ISSUE TITLE
Indentation after end of method

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5951]
VS Mac: 7.8.0.444
Git revision: 42be91afe3ba525f327837045ca91fd2c834cd7b
Build date: 2018-09-12 06:07:51+00
Build branch: master
Xamarin extensions: 14685af820b66440e7a955d9a31c4431e592ba6b

Pressing return after the end of the method moves the caret to left. Pressing return again moves to the expected indentation level.

![methodindent](https://user-images.githubusercontent.com/372361/45444757-3bea7f80-b6c0-11e8-91a8-859eb681edd2.gif)

Automatic format when typing is off.
Automatic format on return is off.

> VS bug [#683053](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/683053)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.510 (master)

Pull Request #5957 merged by: Mike Krüger
Author: mono
Commit: 5e5cddf0b870b4ee6ada41051f6e3a9122cdb507 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1410 (release-7.7)

Pull Request #5958 merged by: Lluis Sanchez
Author: mono
Commit: 93f61987e18d834bd3acc57d4322ff33027dc51d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5957 merged by: Mike Kr??ger
Author: mono
Commit: 5e5cddf0b870b4ee6ada41051f6e3a9122cdb507 (xamarin/monodevelop)
