### ISSUE TITLE
Enable MD specific analyzers in the repository and build

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5956]
Use a nuget generated from https://github.com/therzok/monodevelop.analyzers as a build-time analyzer (also enabling it in the IDE).

> VS bug [#683875](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/683875)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 7.8.0.1153 (master)



Pull Request #6557 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ad23e54116fe7f30cbbded3123aff09c236ba718 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 7.8.0.1193 (release-7.8)



Pull Request #6557 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ad23e54116fe7f30cbbded3123aff09c236ba718 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.0.0.658 (release-8.0)



Pull Request #6557 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ad23e54116fe7f30cbbded3123aff09c236ba718 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 06d7316b9a169b59462f05602415ff0df1f1eb10 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-38] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6557 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ad23e54116fe7f30cbbded3123aff09c236ba718 (xamarin/monodevelop)
