### ISSUE TITLE
Modifying .csproj file that is inside SolutionFolder doesn't reload project

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#6013]
I suspect that this is regression caused by https://github.com/mono/monodevelop/pull/5040 more specifically https://github.com/mono/monodevelop/commit/8324211
Problem is that new code is using `solution.OnItemReloadRequiered` event which is not triggered for projects inside SolutionFolder, code causing this is at https://github.com/mono/monodevelop/blob/429ecb52e84709526e173d72b25d663f98db562f/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs#L909

Maybe problem is that `ItemReloadRequired` event is never used. And should be "Chained" until it's triggered on top SolutionFolder...

**Comment by mrward** [comment]
Possibly related - https://github.com/mono/monodevelop/issues/5705

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.576 (master)

Author: Matt Ward
Commit: 128a2d5e560ae1d87090a032e82c7263bee2f7b8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1430 (release-7.7)

Pull Request #6082 merged by: Lluis Sanchez
Author: mono
Commit: 494763318a3e0b452d0efd50aef67e10daaad8f0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.48 (release-8.0)

Author: Matt Ward
Commit: 128a2d5e560ae1d87090a032e82c7263bee2f7b8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.8.34 (release-7.6)

Pull Request #6115 merged by: Lluis Sanchez
Author: mono
Commit: 0f9b1f53213c66c1c9c8f17d9468550078098d94 (mono/monodevelop)
