### ISSUE TITLE
Find references shows invalid search results

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6015]
Not sure if this is related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674268 which was fixed in VS Mac 7.6.4.

VS Mac: 7.6.5.20 (also 7.7.0.1351)
Git revision: f6a29a810eb4b81ceb9a4ea4ba411da98b6e25cf
Build date: 2018-09-11 21:34:07+00
Build branch: release-7.6
Xamarin extensions: 097e18c3e104c652bde3a02799dcba13eaad6f7b
Mono: 5.14.0.177

Search results for Find References does not show correct text after file is edited. Created a C# library, edited MyClass.cs as shown below, ran find references for 'test', edited MyClass.cs by removing some lines, ran find references again for 'test' and this returns invalid search results - the line numbers and text seem to be wrong.

![searchresultsinvalid](https://user-images.githubusercontent.com/372361/45691661-ecd59c00-bb50-11e8-8830-a392e17cd269.gif)

> VS bug [#686384](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/686384)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.526 (master)

Pull Request #6024 merged by: Lluis Sanchez
Author: mono
Commit: ad689ebfa257c7e300e2642c35f4f030a12e45c0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1363 (release-7.7)

Pull Request #6025 merged by: Lluis Sanchez
Author: mono
Commit: 4b592e4320dfe7df79541ad23c148061db07c654 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.7.37 (release-7.6)

Pull Request #6026 merged by: Lluis Sanchez
Author: mono
Commit: ea663527a1c55d160f1427d845b06d8b793d1b57 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1368 (release-7.7)

Pull Request #6016 merged by: Lluis Sanchez
Author: mono
Commit: 5061e0e8a5c0ab6869c331c225370c607e9eebb0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.7.42 (release-7.6)

Pull Request #6009 merged by: Lluis Sanchez
Author: mono
Commit: cd4fda86e73cabac7fd7d7d20020de680b67d3fc (mono/monodevelop)
