### ISSUE TITLE
Cut and paste is broken in the editor

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#6029]
Cut and paste a line.

Tabs are inserted as literal "\t" strings and newlines are literal "\n" strings. 

Screencast: http://recordit.co/4T10COOXNd

> VS bug [#686923](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/686923)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.535 (master)

Pull Request #6030 merged by: Lluis Sanchez
Author: mono
Commit: a2f0d6e1734d9bdecf1204007db96bc729b234d1 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1375 (release-7.7)

Pull Request #6031 merged by: Lluis Sanchez
Author: mono
Commit: d7f43e2ee12f93fb8b593b63fd9e4d5eaec4e2e3 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6030 merged by: Lluis Sanchez
Author: mono
Commit: a2f0d6e1734d9bdecf1204007db96bc729b234d1 (xamarin/monodevelop)
