### ISSUE TITLE
Fix oblivion color style

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#6035]
The keywords in oblivion should be plum not white.

> VS bug [#687047](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/687047)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.556 (master)

Pull Request #6036 merged by: Lluis Sanchez
Author: mono
Commit: 2c25d89a65e47e03df19d51997b87c2ed191b30c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1402 (release-7.7)

Pull Request #6037 merged by: Lluis Sanchez
Author: mono
Commit: d92f4dc60afadd5b67c5f9346eb41af9a57065c2 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6036 merged by: Lluis Sanchez
Author: mono
Commit: 2c25d89a65e47e03df19d51997b87c2ed191b30c (xamarin/monodevelop)
