### ISSUE TITLE
New Application Output window created on each run

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6042]
VS Mac: 7.7.0.1361
Git revision: 7922720e6d668851f551500c5830ad650feb0dc4
Build date: 2018-09-19 11:08:52+00
Build branch: release-7.7
Xamarin extensions: bef0e3cc76756f000c33cf4c5e55d1da69b58e6c

Every time you run/debug a console project a new Application Output window is created. If you configure the console project to not use an external console no output is displayed in the Application Output window.

This seems to affect other output windows, such as the Package Console window, where a new window will be created, none of which has any output.

The Application Output window problem was mentioned in https://github.com/mono/monodevelop/issues/6014 - that bug also includes another problem and is also about running unit tests.

> VS bug [#687103](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/687103)

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/pull/5772 might be related cc @mhutch

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.559 (master)



Author: therzok  
 Commit: 481e8fe86f65422dad67355e638b33641d7acce5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 7.7.0.1382 (release-7.7)



Author: therzok  
 Commit: 165c7aa43f9b70088e184b71ecb86667b638c751 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 481e8fe86f65422dad67355e638b33641d7acce5 (xamarin/monodevelop)
