### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by sayedihashimi** [mono/monodevelop#6043]
We've received feedback from customers that our .gitignore file is missing many items. We should get this updated. For reference the .gitignore file that VS(Windows) uses comes from https://github.com/github/gitignore/blob/master/VisualStudio.gitignore.

**Comment by sayedihashimi** [comment]
Resolved with PR https://github.com/mono/monodevelop/pull/6041

**Comment by slluis** [comment]
PR was merged.
