### ISSUE TITLE
Add using writes the wrong reference down for a framework assembly

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6061]
When adding a GAC dll reference, since we use reference assemblies for a given .net api, we need to tell Roslyn which assembly to resolve to.

The code fix would add:
`\Library\Frameworks\Mono.framework\Versions\$version\mono\lib\4.7-api\MyDll.dll`

What we need to do is import this service:
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/MetadataReferences/VisualStudioFrameworkAssemblyPathResolverFactory.cs,18

> VS bug [#691667](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/691667)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.889 (master)

Pull Request #6228 merged by: Marius Ungureanu
Author: mono
Commit: 7137ac5d73799076d66aa59f2f853153f3ed9eb8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1663 (release-7.7)

Pull Request #6359 merged by: Lluis Sanchez
Author: mono
Commit: da19e1fbc2b6acbe07cb68426def6b958c4c991f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.471 (release-8.0)

Pull Request #6228 merged by: Marius Ungureanu
Author: mono
Commit: 7137ac5d73799076d66aa59f2f853153f3ed9eb8 (mono/monodevelop)
