### ISSUE TITLE
The solution pad duplicates items when using sdk style projects

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#6072]
![screen shot 2018-09-25 at 13 30 12](https://user-images.githubusercontent.com/264396/46014553-9ecc1580-c0c7-11e8-8858-d045646aa3f5.png)

The addin.xml file is in the csproj once but shows up in the solution pad twice. It is also in the final binary once (as expected).

If i run `msbuild -pp:fullproject.xml Xamarin.Designer.MonoDevelop.csproj` then the file is only listed once in the project too.

**Comment by mrward** [comment]
The Xamarin.Designer.MonoDevelop.addin.xml will be added as a None item by default by the .NET Core sdk. If you right click and look at the build actions you should see one is EmbeddedResource and one is None. The project has an Include for the EmbeddedResource but is missing a None Remove item for the file so it is included in both sets of MSBuild items.

     <None Remove="Properties\Xamarin.Designer.MonoDevelop.addin.xml">

The solution pad does not hide duplicate MSBuild items from you - unlike VS on Windows.

**Comment by alanmcgovern** [comment]
Yup - this was it!

I thought that the `-pp` command fully expanded the globs, but not only does it *not* expand globs it also doesn't even show the globs used to import files!
