### ISSUE TITLE
Visual Studio Straight 8s Specflow requires MonoDevelop.Core and .Ide v7.7

### ISSUE THREAD

**Issue by hodgesr** [mono/monodevelop#6096]
Hi, I'm trying to install Straight 8s Specflow Integration Extension In VS Community for Mac and am getting the error that it can't install as it has a dependency on having MonoDevelop.Core v7.7 and MonoDevelop.Ide v7.7 being installed yet I can't seem to locate these versions anywhere.  If they are available, does anyone know from where and how to install them? Thanks

**Comment by mrward** [comment]
There is a bug filed on the SpecFlow GitHub site about the SpecFlow addin.

https://github.com/straighteight/SpecFlow-VS-Mac-Integration/issues/13

VS for Mac 7.7 is available from the beta channel. You can select that update channel when checking for updates.
