### ISSUE TITLE
Symlinked files do not have correct define constants

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6121]
See https://twitter.com/chaoticbox/status/1045383304956928000?s=21

> VS bug [#700204](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/700204)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 7.8.0.1088 (master)



Pull Request #6331 merged by: Lluis Sanchez  
 Author: mono  
 Commit: b37e7c03ec47c5dd826e7e6f4a19680da29336eb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 7.7.0.1808 (release-7.7)



Pull Request #6532 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 101725c0b426ce5853e42561d52aa4c25aff0c22 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.0.0.560 (release-8.0)



Pull Request #6331 merged by: Lluis Sanchez  
 Author: mono  
 Commit: b37e7c03ec47c5dd826e7e6f4a19680da29336eb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 70b5adf2f19512a80b65737848454d204f1dc364 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-26] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6331 merged by: Lluis Sanchez  
 Author: mono  
 Commit: b37e7c03ec47c5dd826e7e6f4a19680da29336eb (xamarin/monodevelop)
