### ISSUE TITLE
.NET Standard missing from the target framework list

### ISSUE THREAD

**Issue by sbrl** [mono/monodevelop#6146]
Hello,

I've recently been investigating _.NET Standard_, and although it's my understanding that `2.0` is the latest version, When I create a new  _.Net Standard Library_ project I don't see the option for a `2.0` project in the list. Furthermore, when I choose `1.6` from the list instead, in the project options it claims that even .NET Standard 1.6 is not installed - even though `msbuild` is perfectly capable of building the project.

That's ridiculous though - .NET Standard is a standard specification, right? Isn't this like asking me to "Install HTML5"?

## System Details:

 - `uname -a`: `Linux Riikaan 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 - Distribution: Ubuntu Desktop 18.04
 - Mono version: `5.14.0.177`
 - MonoDevelop version: `7.5 (build 1255)`
 - I installed `mono` and `monodevelop` via the official `apt` repository available [here](https://www.mono-project.com/download/stable/).

## Screenshots:
![](https://i.imgur.com/QZZfHto.png)

![](https://i.imgur.com/SSi5U82.png)

> VS bug [#694494](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694494)

**Comment by mrward** [comment]
Can you attach the .NET Core  information from the About dialog - Show details page?

Also if you run `dotnet --info` what does that output?

**Comment by mrward** [comment]
If you install the .NET Core 2.x SDK then .NET Standard 2.0 will be available in the New Project dialog.

Looking at the code the project options currently showing `(not installed)` means there is no .NET Core SDK installed (beyond that which is included with Mono). Unfortunately the `(not installed)` is misleading for .NET Standard 1.x since Mono supports compiling .NET Standard 1.x projects. Older Mono versions did not support .NET Standard 2.0, which is why it is not displayed in the New Project dialog.

**Comment by mrward** [comment]
For recent Mono versions (need to check which versions started supporting .NET Standard 2.0) we can change MonoDevelop so that:

- New Project dialog shows all .NET Standard versions (including 2.0) if only Mono is installed and the Mono version is high enough.
- If Mono supports the .NET Standard version used by the project then `(not installed)` should not be displayed in the Project options for the target framework.
- Also we could look into showing all .NET Standard versions in the project options. Currently they are restricted to those installed. `(not installed)` can be displayed for frameworks that are not installed. 

Also may want to rethink how the .NET Core target frameworks work in project options. Currently on those NET Core runtimes that are installed are displayed.

**Comment by mrward** [comment]
When the code for the New Project dialog and project options was written originally, Mono only supported .NET Standard 1.0 through to 1.6. So the options were restricted in the New Project dialog if the .NET Core SDK 2.0 was not installed. The `(not installed)` information for .NET Standard 1.x is incorrect here in the project options - only really makes sense for .NET Core projects.

The .NET Core SDK includes the dotnet runtime for .NET Core projects and ASP.NET Core projects. It also includes various MSBuild targets for .NET Standard, and .NET Core.

Mono itself ships part of the .NET Core SDK so it can compile .NET Standard projects. Looking at Mono 5.14 it looks like it supports compiling .NET Core 2.0 and 1.x, .NET Standard 2.0 and 1.x versions. However Mono does not include the dotnet runtime so you cannot run .NET Core projects without installing the .NET Core runtime or SDK (which includes the runtime).

For a .NET Standard 1.x project you can open the .csproj in the text editor and change the framework version there to 2.0. However there is some work that can be done on the MonoDevelop side now that Mono also supports compiling .NET Standard 2.0 projects. So with a recent Mono installed MonoDevelop should show 2.0 in the New Project dialog and project options which it does not currently.

**Comment by mrward** [comment]
Looking at your About dialog you do not have the .NET Core SDK installed. As a workaround if you install the [.NET Core 2.x SDK](https://www.microsoft.com/net/download) then .NET Standard 2.0 should be available in the New Project dialog and project options.

**Comment by sbrl** [comment]
Thanks for the info. So the following facts are true?

1. The latest version of _Mono_ can compile all .NET Standard projects without the _.NET Core SDK_.
2. The latest version of _Mono_ can compile all .NET Core projects without the _.NET Core SDK_.
3. The latest version of _Mono_ can run .NET Standard projects without the _.NET Core SDK_.
4. The latest version of _Mono_ can't run .NET Core projects without the _.NET Core runtime_.
5. _MonoDevelop_ does not currently recognise point 1) in this list
6. I can workaround 1) by installing the .NET Core SDK

**Comment by mrward** [comment]
1. The latest version of _Mono_ can compile all .NET Standard projects without the _.NET Core SDK_. 
   - Correct. I have tested Mono 5.14. Not tried older versions.
2. The latest version of _Mono_ can compile all .NET Core projects without the _.NET Core SDK_.
   - Up to .NET Core 2.1. .NET Core 2.2 preview is not supported.
3. The latest version of _Mono_ can run .NET Standard projects without the _.NET Core SDK_.
   - .NET Standard projects are libraries. They cannot be run on their own.
4. The latest version of _Mono_ can't run .NET Core projects without the _.NET Core runtime_.
   - Correct. The .NET Core runtime is needed to run. The .NET Core SDK can build native executables.
5. _MonoDevelop_ does not currently recognise point 1) in this list
   - Correct. .NET Standard 2.0 is not recognised as supported by MonoDevelop.
6. I can temporarily workaround 5) by installing the .NET Core SDK
   - Correct.

**Comment by sbrl** [comment]
Thanks for your reply!

> The .NET Core runtime is needed to run the non-native assembly. You can build native assemblies with mono's by using the /property:RuntimeIdentifier when restoring and building with msbuild, passing the required native os identifier. These native assemblies can be run directly from the command line.

I don't understand this. What's all this about native and non-native binaries? I thought that C&sharp; compiled down into CIL (Common Intermediate Language), which can then be run by the .NET Runtime (on Windows), or Mono (on other OSes).

How come Mono can compile _.NET Core_ projects but not run them? I'm baffled.

**Comment by mrward** [comment]
You can compile .NET Core projects to a native binaries:
 - https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
 - https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

Mono does not ship the .NET Core runtime. There are no plans to ship the .NET Core runtime with Mono.

**Comment by sbrl** [comment]
....that link specifies that `dotnet build` compiles to IL (Intermediate Language). Isn't a native binary one that can be executed directly, without a 'runtime'? Why is this _.NET Core Runtime_ needed at all?

Is the intermediate language used by this weird _.NET Core Runtime_ different from the intermediate language in regular CIL binaries output by _Mono_ and `csc.exe`?

Sorry for all the questions. All the microsoft-marketing-speak and vague naming schemes are very confusing.

**Comment by mrward** [comment]
Correct. `dotnet build` generates IL. However you can pass a runtimeidentifier to `dotnet build` and msbuild to build a native binary which can be run without the .NET Core runtime. The .NET Core runtime is needed if you just compile the .NET Core project to IL.

The IL is not different as far as I am aware. A .NET Core project targets a different target framework. .NET Core projects have a different API and use a different runtime.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 7.8.0.698 (master)



Pull Request #6154 merged by: Rodrigo Moya  
 Author: mono  
 Commit: 07ff691c20ef8326fca09b8cb05632fc77142e08 (mono/monodevelop)

**Comment by sbrl** [comment]
When will 7.8 be released?

**Comment by rodrmoya** [comment]
It has been merged to 7.7 branch, so it should be available in beta channel soon

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-27] Comment by **xamarinc**



Fixed in version 7.7.0.1541 (release-7.7)



Pull Request #6190 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ad98e2559ff3bd91895871161b110a46f7f2c07b (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-29] Comment by **xamarinc**



Fixed in version 8.0.0.197 (release-8.0)



Pull Request #6154 merged by: Rodrigo Moya  
 Author: mono  
 Commit: 07ff691c20ef8326fca09b8cb05632fc77142e08 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-41] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6154 merged by: Rodrigo Moya  
 Author: mono  
 Commit: 07ff691c20ef8326fca09b8cb05632fc77142e08 (xamarin/monodevelop)
