### ISSUE TITLE
Build project before executing unit tests now prompts

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6147]
Release ID: 7.7.0.1494
Git revision: 4839455f3814e7b04eb677856225d218193a5b8b
Build date: 2018-09-28 14:21:02+00
Build branch: release-7.7
Xamarin extensions: 3d073a50bbfb010083c11227f0becbfec132c25f

 - If Build project before executing unit tests is checked then the project should build without a dialog prompt before running the unit tests. Currently a prompt is displayed.

 - If Build project before executing unit tests is unchecked then the IDE should prompt to build before running the unit tests if the project needs to be built. Currently the build occurs without any prompt.

It looks like the logic was flipped in https://github.com/mono/monodevelop/commit/ccb1533a56649c9194e09b5148e02d9e82125427

This line I think needs changing back to the original https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs#L133

Currently `!IdeApp.Preferences.BuildBeforeRunningTests` is being passed to IdeApp.ProjectOperations.CheckAndBuildForExecute which causes the opposite behaviour to the setting.

> VS bug [#694574](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694574)

**Comment by mkrueger** [comment]
Flipping the logic produced the original bug. But I made a mistake the bug was about the prompt dialog but the option is not about prompting it's about building. The prompt there is annoying and should never be shown.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.769 (master)

Pull Request #6274 merged by: Lluis Sanchez
Author: mono
Commit: 3fb6251c14722235b2a1e4b3db8baef75f120247 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1580 (release-7.7)

Pull Request #6275 merged by: Lluis Sanchez
Author: mono
Commit: c67086bbae2d9c9ca501070e3c056a55015bf428 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.240 (release-8.0)

Pull Request #6274 merged by: Lluis Sanchez
Author: mono
Commit: 3fb6251c14722235b2a1e4b3db8baef75f120247 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6274 merged by: Lluis Sanchez
Author: mono
Commit: 3fb6251c14722235b2a1e4b3db8baef75f120247 (xamarin/monodevelop)
