### ISSUE TITLE
Folding updates can be deffered if possible

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6265]
We currently have 3 states for code folding:
* Disabled
* Shown on hover
* Always shown

For the former, we already do not do anything regarding foldings, that's okay.

For the case where they're shown on hover, maybe it would be worth it to compute them on demand, rather than on every keypress? It's rare for most of the values to need computed until shown.

> VS bug [#700309](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/700309)

**Comment by mkrueger** [comment]
The computation is done in background and what's running on the UI thread is creating ~100  ? Objects there are not that many folds.

If you don't have data showing that there is a huge problem with UpdateFoldings I don't think it's worth the time invested. It's running like that for 10 years and I'm sure it can run for the next 5 monts until we replace all that.

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/issues/6235

It runs on the UI thread completely.

**Comment by mkrueger** [comment]
Won't do infrastructure changes in the current editor - the new one will replace all that soon.
