### ISSUE TITLE
Allow disabling the `solution already opened` message

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6270]
Currently, we always show this message when we receive a message to open a solution:
https://github.com/mono/monodevelop/blob/724ab15995b7aa0cdca47fefebbc8fc30a23040c/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs#L515

Unity would like to customize this or have a way to disable this message, as they always send 2 open documents event, one for the solution and one for the file(s) being requested to be edited

> VS bug [#701002](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701002)

**Comment by Therzok** [comment]
cc @vancura @slluis

**Comment by vancura** [comment]
I don't have any special relationship with the message. I think we could remove it. @slluis?

**Comment by sevoku** [comment]
We could move the check to the open file command, to explicitely warn. If opened from command line, we won't show this then.

**Comment by Therzok** [comment]
The unity scenario comes from AppleEvents, so please take that into account

**Comment by mkrueger** [comment]
I think moving that warning to the file commands is the best solution. However we can remove it completely as well. 

For now I just moved it to file open & recent projects commands.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.37 (master)

Pull Request #7912 merged by: Mike Krüger
Author: mono
Commit: a14066da703bc5003e82dbad768ff3bfafc25b6f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.2.0.830 (release-8.2)

Pull Request #7931 merged by: Lluis Sanchez
Author: mono
Commit: 0cef01e5a2b762d3174ee2a87a3303dccf235b7d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.203 (release-8.3)

Pull Request #7912 merged by: Mike Krüger
Author: mono
Commit: a14066da703bc5003e82dbad768ff3bfafc25b6f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.578 (release-8.3)

Pull Request #7912 merged by: Mike Krüger
Author: mono
Commit: a14066da703bc5003e82dbad768ff3bfafc25b6f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7912 merged by: Mike Kr??ger
Author: mono
Commit: a14066da703bc5003e82dbad768ff3bfafc25b6f (xamarin/monodevelop)
