### ISSUE TITLE
New Project dialog language selector truncated

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6277]
If you have C# selected by default on opening the New Project dialog if you change the language to show VBNet then the drop down button is truncated and does not show the full contents.

![](https://user-images.githubusercontent.com/372361/46668771-5e8b8d80-cbc5-11e8-9113-368fca0fa8d5.png)

> VS bug [#701568](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701568)

**Comment by cesarnava** [comment]
Hi. Additionally, this dialog does not allow continuing in MonoDevelop 7.6 on Linux. If you click on Next, send error that the path contains invalid characters, and do not let create any type of project.

**Comment by mrward** [comment]
@cesarnava I think you are running into this other issue - https://github.com/mono/monodevelop/issues/5453

**Comment by mrward** [comment]
This was fixed a while ago - https://github.com/mono/monodevelop/commit/e531862f8b9f6cab9b0d70eb801c33117c24d11d
