### ISSUE TITLE
Add a way to report host CPU load percentages

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6294]
> VS bug [#703507](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/703507)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 7.7.0.1590 (release-7.7)



Pull Request #6251 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 896b54741d2aefeee436a9c07ea79c3eb2d77d1a (mono/monodevelop)
