### ISSUE TITLE
Intellisense Soft-Selection is confusing

### ISSUE THREAD

**Issue by iainx** [mono/monodevelop#6303]
In this screen capture, it looks like `vsIndex` is selected. I press Enter and get ... a new line.

https://www.screencast.com/t/bZth9i9GK

I think this is related to https://github.com/mono/monodevelop/pull/6148 and `vsIndex` is "soft-selected" until I press the down arrow. But because it has the pop up tab explaining what it is, it looks like it will complete.

Why do we need this soft-selection state? It just seems to me to increase confusion about what action will take place. IMO, either the Intellisense window is displayed and will complete, or it isn't displayed.

> VS bug [#704892](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/704892)

**Comment by mkrueger** [comment]
It's not that easy if there is a delegate context possible soft selection is needed otherwise intellisense interferes.

**Comment by iainx** [comment]
@mkrueger It happens in literally every project.

Open Main.sln
Open any file
Type something to trigger an intellisense popup.

Actual result:
The first option will be soft selected, but still display the side popout
Press <return>. A new line will be entered instead of the completion

Expected result
The first option will be fully selected and will be committed on pressing return.

**Comment by mkrueger** [comment]
Have you turned on suggestion mode ? 

Go to Edit-> near the bottom there is a item called "switch to suggestion mode" or "switch to completion mode" 

Did that get toggled somehow ?

**Comment by iainx** [comment]
It said "Switch to completion mode"
Switching it back fixed it. How did that get changed? Did we change the default somewhere?

**Comment by iainx** [comment]
@Therzok says he saw the same bug while on completion mode FWIW

**Comment by Therzok** [comment]
![intellisense](https://user-images.githubusercontent.com/109974/46963164-9efb7780-d0ad-11e8-9622-2b460e264d97.gif)

**Comment by mkrueger** [comment]
fixed the case from @Therzok but this is a very special context and in no means connected to the original one.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1005 (master)

Pull Request #6345 merged by: Lluis Sanchez
Author: mono
Commit: 7e73040c5d400a6208437548ad4bb7f89f44b347 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.471 (release-8.0)

Pull Request #6345 merged by: Lluis Sanchez
Author: mono
Commit: 7e73040c5d400a6208437548ad4bb7f89f44b347 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6345 merged by: Lluis Sanchez
Author: mono
Commit: 7e73040c5d400a6208437548ad4bb7f89f44b347 (xamarin/monodevelop)
