### ISSUE TITLE
Redundant private modifier fix all is not working right

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6323]
See attached gif, causes line damage and doesn't fix every appearance
![kapture 2018-10-15 at 17 05 59](https://user-images.githubusercontent.com/109974/46955876-a5352800-d09c-11e8-9d65-dea0c845c71f.gif)

> VS bug [#705955](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705955)

**Comment by Therzok** [comment]
On the other hand, I wonder if we should drop this diagnostic in favor of editorconfig analyzers from roslyn:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/AddAccessibilityModifiers/CSharpAddAccessibilityModifiersDiagnosticAnalyzer.cs,14

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 7.8.0.849 (master)



Pull Request #6346 merged by: Marius Ungureanu  
 Author: mono  
 Commit: a8d1c10154998ed4c6f6ee5f09f0a6ef85f7c92d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 7.7.0.1725 (release-7.7)



Pull Request #6354 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 222bfe417c2cb04da69e30cd4b6be329da1d3de5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Pull Request #6346 merged by: Marius Ungureanu  
 Author: mono  
 Commit: a8d1c10154998ed4c6f6ee5f09f0a6ef85f7c92d (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6346 merged by: Marius Ungureanu  
 Author: mono  
 Commit: a8d1c10154998ed4c6f6ee5f09f0a6ef85f7c92d (xamarin/monodevelop)
