### ISSUE TITLE
Temporarily disable Mono hybrid suspend

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6325]
See https://github.com/mono/mono/issues/11138.

Do so by `MONO_THREADS_SUSPEND=preemptive` in the stub launcher.

> VS bug [#705976](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705976)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.847 (master)



Pull Request #6327 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ac41ec22320a9b336d4069c9dfbba1eaf9e419ec (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 7.7.0.1647 (release-7.7)



Pull Request #6347 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 0eb57fd72e6a85368fcad4f3663bdbe99a30836d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 7.6.10.20 (release-7.6)



Pull Request #6348 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 6c3565d6d8d31fc607a148c242039b21774e024a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 8cc53adac0aae54ad3f6e4bd431d05250babb9ea (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6327 merged by: Lluis Sanchez  
 Author: mono  
 Commit: ac41ec22320a9b336d4069c9dfbba1eaf9e419ec (xamarin/monodevelop)
