### ISSUE TITLE
Re-enable hybrid suspend 

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6326]
We disabled hybrid suspend via https://github.com/mono/monodevelop/issues/6325

Once https://github.com/mono/mono/issues/11138 is fixed and we depend on a mono with the fix, revert the hybrid suspend fix

> VS bug [#706310](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/706310)

**Comment by lambdageek** [comment]
mono/mono#11138 is fixed now:
- on Mono `master` with mono/mono#11183
- on Mono `2018-10` with mono/mono#11184 (available in 5.20.0.61 or later)
- and on Mono `2018-08` with mono/mono#11180 (available in 5.18.0.175 or later)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.3.0.257 (master)



Author: Marius Ungureanu  
 Commit: 41e6fb746da8b651884c91dedaeb60acebe20fab (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.2.0.707 (release-8.2)



Author: Marius Ungureanu  
 Commit: 41e6fb746da8b651884c91dedaeb60acebe20fab (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-32] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 41e6fb746da8b651884c91dedaeb60acebe20fab (xamarin/monodevelop)
