### ISSUE TITLE
Analyzers not retriggered on editorconfig change

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6333]
See https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core.Wpf/Options/EditorConfigDocumentOptionsProvider.Ide.cs#L59

On editorconfig change, projects should be triggered for reanalysis.

> VS bug [#706520](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/706520)

**Comment by mkrueger** [comment]
I'll implement it for the old editor - don't know if it works for the new one.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.612 (master)

Pull Request #7913 merged by: Mike Krüger
Author: mono
Commit: db86d92b7007300c7dd8388edc0609a919fb5ff9 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.1047 (release-8.3)

Pull Request #7913 merged by: Mike Krüger
Author: mono
Commit: db86d92b7007300c7dd8388edc0609a919fb5ff9 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-43] Comment by **xamarinc**



Fixed in version 8.5.0.688 (master)



Pull Request #8872 merged by: Matt Ward  
 Author: mono  
 Commit: 248b26c41fa13887a591025dcf061b8f86341742 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-44] Comment by **xamarinc**



Fixed in version 8.4.0.1990 (release-8.4)



Pull Request #8984 merged by: Matt Ward  
 Author: mono  
 Commit: 9d6593111a8ceb8945ed69a19eaa332fd8ee195e (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7913 merged by: Mike Kr??ger
Author: mono
Commit: db86d92b7007300c7dd8388edc0609a919fb5ff9 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-50] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8872 merged by: Matt Ward  
 Author: mono  
 Commit: 248b26c41fa13887a591025dcf061b8f86341742 (xamarin/monodevelop)
