### ISSUE TITLE
XwtThemedPopup crashes on linux

### ISSUE THREAD

**Issue by mkrueger** [mono/monodevelop#6339]
Crash in : 

  at MonoDevelop.Components.XwtThemedPopup..ctor (Xwt.PopupWindow+PopupType type) [0x0002a] in /home/mkrueger/work/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs:59 
  at MonoDevelop.Components.XwtThemedPopup..ctor () [0x00000] in /home/mkrueger/work/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs:50

> VS bug [#706653](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/706653)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.851 (master)

Pull Request #6341 merged by: Lluis Sanchez
Author: mono
Commit: 0a46f2adcd1efe65c3b35767618a3b361bef9539 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.10.18 (release-7.6)

Pull Request #6343 merged by: Lluis Sanchez
Author: mono
Commit: a69c48e7601ccb4614aca53981c55a56e4bb39a5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1641 (release-7.7)

Pull Request #6344 merged by: Lluis Sanchez
Author: mono
Commit: 599e7b456834e84bdfeecf6637d9c8a27de98084 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.471 (release-8.0)

Pull Request #6341 merged by: Lluis Sanchez
Author: mono
Commit: 0a46f2adcd1efe65c3b35767618a3b361bef9539 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6341 merged by: Lluis Sanchez
Author: mono
Commit: 0a46f2adcd1efe65c3b35767618a3b361bef9539 (xamarin/monodevelop)
