### ISSUE TITLE
Add more editorconfig options to monodevelop editorconfig

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6369]
`dotnet_style_require_accessibility_modifiers` - `omit_if_default`

This is needed so we gain back RE functionality of fading out redundant modifiers

> VS bug [#707438](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/707438)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.901 (master)



Pull Request #6370 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6993b49dff9c55acd4e712c921fecd18bd5ab176 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: Marius Ungureanu  
 Commit: fa20385240dfef907f18f6b283d066a91e3dc463 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6370 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6993b49dff9c55acd4e712c921fecd18bd5ab176 (xamarin/monodevelop)
