### ISSUE TITLE
Missing binding redirect after yamldotnet bump

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6393]
> VS bug [#708456](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/708456)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6394 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 2a6a382abcb94aa1034b1c50ccabda86f5c47efd (xamarin/monodevelop)
