### ISSUE TITLE
Enabling/Disabling breakpoint opens quick fixes menu

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6414]
VSMac: 7.7.0.1710
Git revision: c9d4e85b1570cf599945a3cc639e0540ceff9c7c
Build date: 2018-10-18 16:50:26+00
Build branch: release-7.7
Xamarin extensions: 180b9ddb8b262d7e4ca8d61577bb6c5f1ee5279a

Clicking in the left hand margin of the text editor to enable/disable a breakpoint on a line that shows the screwdriver icon opens the quick fix menu. The quick fix menu should open when the screwdriver is clicked but not the breakpoint icon is clicked.

![breakpointopenquickfixes](https://user-images.githubusercontent.com/372361/47213897-46212d00-d394-11e8-85ed-eb3fe04da917.gif)

> VS bug [#709888](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/709888)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.974 (master)

Pull Request #6421 merged by: Lluis Sanchez
Author: mono
Commit: f873c7c5c50bb75021480491419c912d60bbf42a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1722 (release-7.7)

Pull Request #6422 merged by: Lluis Sanchez
Author: mono
Commit: da6fa13ee8be3447bd86d356075c750d8755dc96 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.471 (release-8.0)

Pull Request #6421 merged by: Lluis Sanchez
Author: mono
Commit: f873c7c5c50bb75021480491419c912d60bbf42a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6421 merged by: Lluis Sanchez
Author: mono
Commit: f873c7c5c50bb75021480491419c912d60bbf42a (xamarin/monodevelop)
