### ISSUE TITLE
can't use msbuild on Linux

### ISSUE THREAD

**Issue by catb0t** [mono/monodevelop#6426]
getting it from Microsoft ([Microsoft/msbuild/blob/master/documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md)) causes these errors when trying to use `artifacts/.dotnet/2.1.300/dotnet artifacts/Debug/bin/MSBuild/netcoreapp2.1/MSBuild.dll` as the system's `msbuild`:

```
/home/cat/Downloads/old_compress/msbuild/artifacts/Debug/bin/MSBuild/netcoreapp2.1/Microsoft.Common.CurrentVersion.targets(1174,5): 
error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" 
were not found. 
To resolve this, install the SDK or Targeting Pack for this framework version or retarget 
your application to a version of the framework for which you have the SDK or Targeting 
Pack  installed. Note that assemblies will be resolved from the 
Global Assembly Cache (GAC)  and will be used in place of reference assemblies. 
Therefore your assembly may not  be correctly targeted for the framework you intend. 
[/home/cat/Downloads/old_compress/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/MonoDevelop.VersionControl.Subversion.Tests.csproj]
```

aside from that repo, in https://github.com/mono/monodevelop/issues/3602 it's never really explained where to reliably get an `msbuild` binary. 

I guess I could just do what Microsoft wants and [install](https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial) the totally proprietary .deb, but I was hoping to be able to avoid that, and build this free software with other free software.

by the way, saying `$ dotnet` in Ubuntu suggests `snap install --classic dotnet-sdk`, but installing that snap doesn't provide any `dotnet` command. 

which `msbuild` am I supposed to use?

**Comment by mrward** [comment]
.NET Core msbuild supports building .NET Standard and .NET Core projects. It does not support building .NET framework projects since it is missing various msbuild target files. If you want to build these you should use msbuild that ships with [Mono](https://www.mono-project.com/download/stable/#download-lin). I think this should just be a case of installing a mono package on Linux.

**Comment by catb0t** [comment]
You're right, I assumed I already had all possible `mono-*` packages installed and didn't consider that it would be provided by other ones. Sorry!

**Comment by catb0t** [comment]
You're right, I assumed I already had all the `mono-*` packages installed (installed `mono-complete` etc) but that provides `msbuild`. Thanks!
