### ISSUE TITLE
Enable RoslynClrHeapAnalyzer behind an env var

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6487]
https://github.com/mono/monodevelop/blob/5d9d5d19a5a51da35ff9424bd3c5473ece92b49c/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj#L105

Should be enabled behind an env var.

> VS bug [#719111](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/719111)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 7.8.0.1141 (master)



Pull Request #6551 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 6ce4647f4e98ca056b699d3313b4668529c067bc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.604 (release-8.0)



Pull Request #6551 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 6ce4647f4e98ca056b699d3313b4668529c067bc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 7.8.0.1193 (release-7.8)



Pull Request #6551 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 6ce4647f4e98ca056b699d3313b4668529c067bc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: af7c1258723f43c807e811d7398c1d7f9f2f0879 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6551 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 6ce4647f4e98ca056b699d3313b4668529c067bc (xamarin/monodevelop)
