### ISSUE TITLE
Look for locked immutable collections and use ImmutableInterlocked

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6495]
> VS bug [#719402](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/719402)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.1144 (master)



Pull Request #6550 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 45d902f2a1c6c3c32da0f3cacd306943747ea40c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.604 (release-8.0)



Pull Request #6550 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 45d902f2a1c6c3c32da0f3cacd306943747ea40c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 7.8.0.1193 (release-7.8)



Pull Request #6550 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 45d902f2a1c6c3c32da0f3cacd306943747ea40c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: a1892f5f28faa62d9fec543e4601097688c00047 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-32] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6550 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 45d902f2a1c6c3c32da0f3cacd306943747ea40c (xamarin/monodevelop)
