### ISSUE TITLE
OnGetSourceFilesAsync can be optimized

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6497]
This is code that can allocate a lot and takes around 10s to run.

https://github.com/mono/monodevelop/blob/3d82fb3b15f827eef7cee03c1886b61c1aca561a/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs#L543

Use a HashSet to optimize it by 8s.

> VS bug [#719932](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/719932)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 7.8.0.1061 (master)



Pull Request #6498 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 44f4dc4924cd73955ae1747582b53116df474eec (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.0.0.560 (release-8.0)



Pull Request #6498 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 44f4dc4924cd73955ae1747582b53116df474eec (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 221541f80f86f39f73364389d358a5585cce4e01 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6498 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 44f4dc4924cd73955ae1747582b53116df474eec (xamarin/monodevelop)
