### ISSUE TITLE
FileSystemWatcher is not watching the correct directories

### ISSUE THREAD

**Issue by alanmcgovern** [mono/monodevelop#6506]
If I open `designer/Xamarin.Designer.iOS/MTDesigner.sln`, which references `designer/Xamarin.Designer.Translations/Xamarin.Designer.Translations.csproj`, then the FileSystemWatcher does not react to any changes in the files contained within the translations directory. This means that VSM is not tracking when files are regenerated by msbuild targets.

> VS bug [#755011](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/755011)

**Comment by Therzok** [comment]
Cc @mrward

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.0.0.1067 (master)



Pull Request #6822 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 5828d5cbe39d498cb1759cd988df7a76d98edf93 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 72d2dd2a7ae5593b59ec70178156d2a792b82a35 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6822 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 5828d5cbe39d498cb1759cd988df7a76d98edf93 (xamarin/monodevelop)
