### ISSUE TITLE
No syntax highlighting for .vb files

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6531]
VS Mac: 7.7.0.1798
Git revision: 69142af91aa9321579f333677ec1e75ce06a5f69
Build date: 2018-11-01 01:47:56+00
Build branch: release-7.7
Xamarin extensions: 9049c8332d83475139d73ee569157ec901c919e3

VS Mac 7.6.10 is OK.

<img width="476" alt="vbsyntax" src="https://user-images.githubusercontent.com/372361/47907336-f86fee80-de82-11e8-9850-3101e0a9fb05.png">

> VS bug [#722812](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/722812)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 7.7.0.1827 (release-7.7)



Pull Request #6539 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 9971289594c170e33e0370b723df0b2ea4d7124a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 7.7.0.1853 (release-7.7)



Pull Request #6618 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 0b774be9862ef6c930878ea87d343cb2b93b950f (mono/monodevelop)
