### ISSUE TITLE
Method level fixes show up throughout method body

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#6552]
Code fixes that apply to the method definition show up throughout the body. They're not relevant at all there.

7.7 build 1738

![image](https://user-images.githubusercontent.com/183285/48030721-faa2a900-e11f-11e8-8859-f05797095f2b.png)

> VS bug [#724319](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/724319)

**Comment by Therzok** [comment]
Those seem to be refactorings. Agreed that they should be limited to certain scopes.

**Comment by Therzok** [comment]
Fixed was pulled in via https://github.com/mono/monodevelop/commit/3c4ae46984bdfd9635d8f27492ffeecc419aa9b4

**Comment by mhutch** [comment]
This was reintroduced by #6611 /cc @slluis

**Comment by Therzok** [comment]
Taking a look at failing tests.

**Comment by Therzok** [comment]
Fixed again via https://github.com/mono/monodevelop/pull/6628

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 7.7.0.1864 (release-7.7)



Pull Request #6631 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 0ceabdc95a7b2be5e33e6760ca56b3633824bf1e (mono/monodevelop)
