### ISSUE TITLE
Debugger cannot inspect named tuple values

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#6564]
The debugger cannot inspect values of C# 7 named tuples.

![image](https://user-images.githubusercontent.com/183285/48098926-14112700-e1ec-11e8-92d4-337d1e8bc2f6.png)

> VS bug [#724860](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/724860)

**Comment by jstedfast** [comment]
This appears to be fixed
