### ISSUE TITLE
Turn off vbcs compiler server until it is reliable

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6569]
Sometimes, vbcscompiler.exe stays as a stray process taking up 100% CPU. Turn it off explicitly until it is fixed.

> VS bug [#798084](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798084)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.0.0.2933 (release-8.0)



Pull Request #371 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 34481391f4f11f22aa5664e0dbc8af56c5d851fc (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.1.0.1701 (master-vnext)



Pull Request #371 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 34481391f4f11f22aa5664e0dbc8af56c5d851fc (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #371 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 34481391f4f11f22aa5664e0dbc8af56c5d851fc (xamarin/monodevelop)
