### ISSUE TITLE
Call [NSApplication Terminate] at the end of the app execution

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6571]
mdtool and main MonoDevelop.Startup.exe should call NSApplication.Terminate() to ensure that Animation threads and FSW runloop threads are terminated on exit.

As a result, remove hacks to manually close FSW threads.

> VS bug [#725899](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/725899)

**Comment by Therzok** [comment]
Call exit when we have an exit code, call terminate in normal exits.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.4.0.78 (master)



Author: iain  
 Commit: 2299cacfc9b17f29f5a59c5663edd69b074965cd (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.4.0.203 (release-8.3)



Author: iain  
 Commit: 2299cacfc9b17f29f5a59c5663edd69b074965cd (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.3.0.578 (release-8.3)



Author: iain  
 Commit: 2299cacfc9b17f29f5a59c5663edd69b074965cd (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.4.0.199 (master)



Pull Request #8086 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 25f5a432edf85862c36c218877346c07992f9298 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-29] Comment by **xamarinc**



Fixed in version 8.3.0.592 (release-8.3)



Pull Request #8086 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 25f5a432edf85862c36c218877346c07992f9298 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-37] Comment by **xamarinc**



Fixed in version 8.4.0.682 (master)



Pull Request #8237 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: b6e403e5402c9696e27fb23a494c5e4596281696 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-38] Comment by **xamarinc**



Fixed in version 8.3.0.1106 (release-8.3)



Pull Request #8237 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: b6e403e5402c9696e27fb23a494c5e4596281696 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-43] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8237 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: b6e403e5402c9696e27fb23a494c5e4596281696 (xamarin/monodevelop)
