### ISSUE TITLE
Double clicking Dependencies folder in Sdk projects does not open nuget dialog

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6579]
You have to right click the dependencies folder to find nuget in that scenario. Double clicking does nothing.

> VS bug [#798085](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798085)

**Comment by mrward** [comment]
Lluis has mentioned this before. Should it open the Add Packages dialog? The top menu item is Edit References and not Add NuGet Packages.

**Comment by Therzok** [comment]
Technically, in the Sdk world, it's more common to add a PackageReference than reference a system assembly.

**Comment by Therzok** [comment]
Because system references are already shipped as nugets.

**Comment by mrward** [comment]
Edit References allows you to add project references too. But I agree that I think package references are what you add more often to an sdk project.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.4.0.664 (master)



Pull Request #8233 merged by: Matt Ward  
 Author: mono  
 Commit: b695858f9bac9d31e581ff76ecc0fb317e6498d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.3.0.1106 (release-8.3)



Pull Request #8233 merged by: Matt Ward  
 Author: mono  
 Commit: b695858f9bac9d31e581ff76ecc0fb317e6498d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8233 merged by: Matt Ward  
 Author: mono  
 Commit: b695858f9bac9d31e581ff76ecc0fb317e6498d5 (xamarin/monodevelop)
