### ISSUE TITLE
Bump C# language version to 7.3

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6596]
> VS bug [#729042](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729042)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 7.8.0.1169 (master)



Pull Request #6597 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 78ac3635eef6c2383e5fc19b878985f13e10d611 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 7.8.0.1193 (release-7.8)



Pull Request #6597 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 78ac3635eef6c2383e5fc19b878985f13e10d611 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.658 (release-8.0)



Pull Request #6597 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 78ac3635eef6c2383e5fc19b878985f13e10d611 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 4f2abfb936e85cfb865db04cd1c2775cff223fc2 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-37] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6597 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 78ac3635eef6c2383e5fc19b878985f13e10d611 (xamarin/monodevelop)
