### ISSUE TITLE
Simplifying expressions interacting strangely with #if

### ISSUE THREAD

**Issue by Marti2203** [mono/monodevelop#6625]
I am using conditional compilation and Monodevelop tries to simplify this code:
```
#if Example
                if (!flag) return 2;
#endif
                return 3;
```
to this:
```
#if Example
                return !flag
                    ? 2
                    : 3;
#endif
```
I know it is not a big issue and will gladly try to fix it myself, but I want to be sure it is a problem and a little guidance to where it is will kickstart my work :smile:

**Comment by Therzok** [comment]
Hey @Marti2203! Thanks for filing the issue.

From the looks of it, it seems like it is a roslyn bug. I would file an issue against their repository [here](https://github.com/dotnet/roslyn/issues/new).

As a kick start, the code fix you would need to look at is [AbstractUseConditionalCodeFixProvider](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/UseConditionalExpression/AbstractUseConditionalExpressionCodeFixProvider.cs,35a150d0c0db7531,references).

It seems to be missing a test case for code that uses regions in the [test suite](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests/UseConditionalExpression/UseConditionalExpressionForReturnTests.cs,14)

**Comment by Therzok** [comment]
Closing as there was an issue opened on roslyn side
