### ISSUE TITLE
MEF cache should invalidate on framework or dependency changes

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6634]
Starting from the assemblies added to the composition, we should also invalidate on changes to all its references.

> VS bug [#734010](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734010)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.1318 (master)



Author: Marius Ungureanu  
 Commit: 3b3e98313b6d862a15f7f31870dd094787871635 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.2001 (release-8.0)



Author: Marius Ungureanu  
 Commit: 3b3e98313b6d862a15f7f31870dd094787871635 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 3b3e98313b6d862a15f7f31870dd094787871635 (xamarin/monodevelop)
