### ISSUE TITLE
Pasting verbatim strings removes double quotes

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6641]
VSMac: 7.7.0.1861
Git revision: abecfa8dd29aeed633ecec6639880860fa6ffc0e
Build date: 2018-11-19 14:51:55+00
Build branch: release-7.7
Xamarin extensions: 2739f0afed101dc16e114333c7ae258dd82f284f

Copy and pasting verbatim strings removes the double quotes from the string.

![copypasteverbatimstring](https://user-images.githubusercontent.com/372361/48894454-b65f1a80-ee3a-11e8-80e7-706cc508378c.gif)

> VS bug [#733886](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733886)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1341 (master)

Pull Request #6668 merged by: Lluis Sanchez
Author: mono
Commit: f0e14bd4bb4e852aab9cd63ad9d30396be196b8c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.832 (release-8.0)

Pull Request #6668 merged by: Lluis Sanchez
Author: mono
Commit: f0e14bd4bb4e852aab9cd63ad9d30396be196b8c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1359 (release-7.8)

Pull Request #6668 merged by: Lluis Sanchez
Author: mono
Commit: f0e14bd4bb4e852aab9cd63ad9d30396be196b8c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.3.14 (release-7.7)

Pull Request #6698 merged by: Lluis Sanchez
Author: mono
Commit: a57337524b010e0a976ca04c0abaee02fdf4ceea (mono/monodevelop)
