### ISSUE TITLE
Line height has changed in v8.0

### ISSUE THREAD

**Issue by nosami** [mono/monodevelop#6649]
7.7 on the left, 8.0 on the right

<img width="670" alt="image" src="https://user-images.githubusercontent.com/667194/48939362-e4f8f600-ef0b-11e8-9500-c810fadbc768.png">

> VS bug [#734817](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734817)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1334 (master)

Pull Request #6664 merged by: Lluis Sanchez
Author: mono
Commit: c0a574071e9d32d2d2545f20056f2bdf7f74efda (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.832 (release-8.0)

Pull Request #6664 merged by: Lluis Sanchez
Author: mono
Commit: c0a574071e9d32d2d2545f20056f2bdf7f74efda (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.1359 (release-7.8)

Pull Request #6664 merged by: Lluis Sanchez
Author: mono
Commit: c0a574071e9d32d2d2545f20056f2bdf7f74efda (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6664 merged by: Lluis Sanchez
Author: mono
Commit: c0a574071e9d32d2d2545f20056f2bdf7f74efda (xamarin/monodevelop)
