### ISSUE TITLE
Opening an F# solution results in 5 of the projects showing errors, opens in Rider fine

### ISSUE THREAD

**Issue by 7sharp9** [mono/monodevelop#6680]
![screen shot 2018-11-28 at 11 37 02](https://user-images.githubusercontent.com/588746/49149388-d6db1900-f301-11e8-8e92-c9cb88ffda1b.png)

See screenshot, repo is here:  https://github.com/jet/falanx
Solution file is in the root `Falanx.sln`

**Comment by 7sharp9** [comment]
Note this is not an F# issue as such, looks like an msbuild parsing error.

```<PublishRepositoryUrl>true</PublishRepositoryUrl>```
removing that allows the projects to load

**Comment by Therzok** [comment]
Hummm: https://github.com/jet/falanx/blob/master/Falanx.Machinery/Falanx.Machinery.fsproj

Looking at the file in hexdump, it seems like some whitespace characters are not treated right. The PropertyGroup element that contains `PublishRepositoryUrl` has these chars: `0a c2`. They seem to be considered text

**Comment by Therzok** [comment]
Comes through here: https://github.com/mono/monodevelop/blob/305bddc1e9dcd90caf25f8bed1a042efc317528b/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildObject.cs#L183

**Comment by Therzok** [comment]
Huh, upon further reading, _maybe_ XmlReader is properly not seeing `0xc2 0x0a` as a valid unicode character, whilst other tools see it as an invalid unicode and skip it.

**Comment by 7sharp9** [comment]
I can certainly remove those characters, I think they came from copying the xml from the dotnet/sourcelink repo examples.

**Comment by Therzok** [comment]
Which tool did you paste it in? Seems like a RTF paste problem.
