### ISSUE TITLE
Analyzers from PackageReference are used despite ExcludeAssets/PrivateAssets

### ISSUE THREAD

**Issue by garuma** [mono/monodevelop#6706]
With the following PackageReference definition:

```
<PackageReference Include="Microsoft.VisualStudio.Threading" Version="16.0.68-beta" ExcludeAssets="analyzers" PrivateAssets="analyzers" />
```

The analyzers are still being included in projects that reference the one containing that PackageReference by VSM in error list and such.

**Comment by Therzok** [comment]
In the error list, that's msbuild. We don't control that. MSBuild passes those to csc.

**Comment by garuma** [comment]
@Therzok yep you right, it seems like MSBuild on normal projects doesn't understand that metadata quite the way I expected
