### ISSUE TITLE
Enter key no longer commits intellisense suggestions

### ISSUE THREAD

**Issue by Doodpants** [mono/monodevelop#6738]
In the Preferences dialog, under "IntelliSense", there is a checkbox labeled "Complete with Space or Punctuation". I have always kept this unchecked because I want the suggested text to be inserted ONLY when I hit the Return key; if I type a space or punctuation character, I don't want the suggested text inserted. 

As of version 7.7 of VS for Mac, when this option is unchecked, the suggested item is now soft-selected (outlined, not filled). So the Return key no longer inserts the text; it adds a newline. So now my muscle memory is working against me, and I have to retrain myself to use the Tab key instead. Turning on the "Complete with Space or Punctuation" option allows me to use the Return key, but of course it inserts the text when I type a space or punctuation, which I don't want.

I would like a way to enable the previous behavior: I type some text, and then press Return to insert the suggested text, or type any other character to NOT insert the suggested text.

**Comment by Therzok** [comment]
cc @jmatthiesen

**Comment by Therzok** [comment]
This mirrors the behaviour on VS Windows with the same completion options toggled.

**Comment by slluis** [comment]
Yes, we not match the VS Windows behavior.

**Comment by Doodpants** [comment]
Ok, but... this still doesn't make any sense. In version 7.6, turning off "Complete with Space or Punctuation" disabled accepting the suggestion by typing a space or a punctuation character, but you could still accept it using Return. In version 7.7, you can no longer accept using Return, even though the name of the setting doesn't mention "Return".

Also, the name of the setting doesn't imply how the suggestion is selected, soft vs. hard. How does it make sense to impement it this way?

Seems to me that the proper response is not to close this issue just because VS Windows works this way, but rather to fix it in VS Windows as well.
