### ISSUE TITLE
Add counter mapping for composition counters

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6758]
> VS bug [#773841](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/773841)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 8.0.0.1222 (master)



Author: Marius Ungureanu  
 Commit: 31f4c229af041d45c0ceb5607d16eeb1a85beb8d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.1267 (release-8.0)



Author: Marius Ungureanu  
 Commit: 31f4c229af041d45c0ceb5607d16eeb1a85beb8d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: Marius Ungureanu  
 Commit: 31f4c229af041d45c0ceb5607d16eeb1a85beb8d (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-26] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 31f4c229af041d45c0ceb5607d16eeb1a85beb8d (xamarin/monodevelop)
