### ISSUE TITLE
Tooltip that does not go away

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6771]
VS Mac: 8.0 build 888
Git revision: 3661193f5971fad0662ed6f10fa6157cf3fd5487
Build date: 2018-12-05 15:29:59+00

Sometimes see a tooltip which does not disappear. Not sure how to reproduce this. Nor how to trigger the tooltip in the first place. Seen it a few times. Seems to maybe happen just when running the debugger to debug MonoDevelop. Sometimes you can get rid of it by focusing another application and switching back, but sometimes not.

<img width="633" alt="zombietooltip" src="https://user-images.githubusercontent.com/372361/49956604-7fda6400-fefd-11e8-83f7-ebd1a4dfb037.png">
> VS bug [#750544](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750544)

**Comment by Therzok** [comment]
This doesn't look like a tooltip, but code drag and drop.

**Comment by mrward** [comment]
Yeah not sure what it is. It happens in v8.0 when I debug. Happened just now. I just click the Run icon and got the dialog about the code needing building, but clicked Execute, and then that window appears. Does not always go away after stopping debugging and switching to another app.
