### ISSUE TITLE
Using statement indenting

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#6788]
Pressing return around using statement indents the text instead of staying at the same level.

VS Mac 8.0.0.992 - Bad.
VS Mac 8.0.0.888 - OK.

VSMac: 8.0.0.992
Git revision: 8d384b289c95138244c6af162c22f16ab2f113a0
Build date: 2018-12-17 12:13:16+00
Build branch: release-8.0
Xamarin extensions: 2aee8e6434240297ac6b4eeaa90d27210dfc418e

![usingindenting](https://user-images.githubusercontent.com/372361/50151928-30f44c00-02ba-11e9-9981-e6e65f41ef46.gif)

> VS bug [#753551](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753551)

**Comment by mrward** [comment]
Possibly due to the change in this pull request - https://github.com/mono/monodevelop/pull/6729

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.1123 (master)



Pull Request #6809 merged by: Mike Krüger  
 Author: mono  
 Commit: 1727c46c8098e01066ee27106bc439c951892cfa (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 7.8.0.1542 (release-7.8)



Pull Request #6810 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 91a775510d3f7f2f87d27bbb29659e8c4ee5a3e6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.0.0.1135 (release-8.0)



Pull Request #6809 merged by: Mike Krüger  
 Author: mono  
 Commit: 1727c46c8098e01066ee27106bc439c951892cfa (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Pull Request #6809 merged by: Mike Krüger  
 Author: mono  
 Commit: 1727c46c8098e01066ee27106bc439c951892cfa (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-28] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6809 merged by: Mike Kr??ger  
 Author: mono  
 Commit: 1727c46c8098e01066ee27106bc439c951892cfa (xamarin/monodevelop)
