### ISSUE TITLE
.NET Core debugger stops at all exceptions

### ISSUE THREAD

**Issue by usr-sse2** [mono/monodevelop#6793]
On a Mac, .NET Core debugger breaks on each exception, even if it is disabled in settings. For example, I want to break on a NullReferenceException, but the debugger stops on InvalidOperationException, Exception, ArgumentException etc.

> VS bug [#754386](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754386)

**Comment by Therzok** [comment]
Missing something here? https://github.com/mono/monodevelop/blob/66515b51acfa06125740894151ec4468a417c3a4/main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs#L132

**Comment by usr-sse2** [comment]
Still happens in 2019 Preview 3

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.3.0.159 (master)



Pull Request #7595 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 67c3306eae430ee19fc0cf9b3b363edbf154c9a6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-38] Comment by **xamarinc**



Fixed in version 8.2.0.653 (release-8.2)



Pull Request #7595 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 67c3306eae430ee19fc0cf9b3b363edbf154c9a6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-45] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7595 merged by: Jeffrey Stedfast  
 Author: mono  
 Commit: 67c3306eae430ee19fc0cf9b3b363edbf154c9a6 (xamarin/monodevelop)
