### ISSUE TITLE
Focusing out/into VisualStudio changes the default focused element on the UI

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#6797]
# Repro steps

Make sure you have a second app running, like a browser that can be tabbed into
Make sure the text editor is open and focused, type "class Foo"
Press Command-Tab to switch focus from the IDE to the browser
Press Command-Tab to switch back to the IDE
Attempt to type: you will notice that the editor is no longer focused, and the input goes somewhere else.

# Scenario

This happens a lot when I am porting code, and I have to switch from VSMac to other tools (Safari, Emacs, Terminal).

I provided an attachment (large) for internal use on an older version of this bug (as I think I did not file it properly):

> VS bug [#754535](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754535)

**Comment by Therzok** [comment]
Attached miguel's screen recording from the other bug to the automated one, and removed the link from the description (for people who want the old one, here it is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753804)

**Comment by Therzok** [comment]
Doing some investigations:
* When the app focuses back in: MonoDevelop.SourceEditor.QuickTasks.QuickTaskOverviewMode is the focused widget
* just pressing tab after the focus is in, we cycle through the top bar items (run button, statusbar, etc)

Seems related to a11y. cc @mkrueger @iainx

**Comment by Therzok** [comment]
It's not just an editor problem, I can see it exhibit in the solution pad and treeview too.

cc @slluis @bratsche

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.1115 (master)



Pull Request #6845 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8bfc86a35f4700b1c38b2ea6f85aa69ebf70a7b7 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.0.0.1135 (release-8.0)



Pull Request #6845 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8bfc86a35f4700b1c38b2ea6f85aa69ebf70a7b7 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 7.8.0.1544 (release-7.8)



Pull Request #6870 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 5908079eac5c4ec1e128237bc2077f2096f05fdb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: therzok  
 Commit: 4153fdcbe39a56fe6f62842d8d6046708f760d83 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-30] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6845 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8bfc86a35f4700b1c38b2ea6f85aa69ebf70a7b7 (xamarin/monodevelop)
