### ISSUE TITLE
Avoid recursive scanning for addin database

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6800]
Currently, we ship `MonoDevelop.exe.addins` which includes the following definitions:
```
<Addins>
	<Directory include-subdirs="true">../AddIns</Directory>
	<Directory include-subdirs="true">../../../local-config</Directory>
</Addins>
```

Maybe a build step could generate the addins information files via an msbuild target which could avoid having to recurse directories and only scan the required items.

The scanning step is still done at startup, so it might be useful to optimize this.

> VS bug [#754586](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754586)

**Comment by mhutch** [comment]
If we're generating an extension info cache at  build time for in-box extensions, we could go a step further and generate a single file containing precomputed info for all the in-box extensions.

**Comment by Therzok** [comment]
@slluis what do you think about this?

**Comment by slluis** [comment]
The add-in data files that we are including in the bundle has an index to all scanned add-ins, so there is no recursive scan at run time. There isn't really much else we can pre-compute. The add-in database can't be pre-computed because it needs to mix data from bundled and external extensions.
