### ISSUE TITLE
pls don't auto-hide text editor on save

### ISSUE THREAD

**Issue by sign-in-smth** [mono/monodevelop#6830]
i have v8.0 preview on windows.
every time i hit save (or save/run or save/debug) monodevelop auto-hides text editor with my source file.
and i have to click the file again in solution explorer to bring it back.
its very annoying, and i didn't see a way to disable this behavior.
pls fix it

**Comment by Therzok** [comment]
Dupe of https://github.com/mono/monodevelop/issues/6488
