### ISSUE TITLE
CSharpCompilationOptions is missing some information

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6839]
2. We should add PublicSign/DelaySign information.

> VS bug [#798087](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798087)

**Comment by Therzok** [comment]
Split app.config info here: https://github.com/mono/monodevelop/issues/7252

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 8.1.0.76 (master)



Pull Request #7253 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 11fdd1e0c3a15b51e3556ca7c7285c0183b7fb1c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7253 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 11fdd1e0c3a15b51e3556ca7c7285c0183b7fb1c (xamarin/monodevelop)
