### ISSUE TITLE
a few questions about monodevelop on Windows

### ISSUE THREAD

**Issue by sign-in-smth** [mono/monodevelop#6868]
- is it possible to use mono compiler in monodevelop on Windows?
only option that seems to work is
Project -> Active Runtime -> Microsoft .NET
if i choose -> Mono (5.18) i only get build errors, even for hello world.
i was hoping to be able to use monodevelop as gui for mono, instead of its commandline

 - Help -> API documentation gives me 'could not start monodoc' exception.
i compiled from source with winbuild.bat, 0 errors, 334 warnings.
any additional steps required to get monodoc to work?

- is there an easy way to separate unneeded source files from build output?
i wouldn't want to keep the entire ~2.4 gig.
is it ok to just leave the build folder with bin and Addins and delete the rest?

is there a user forum? i dont quite understand how to use:
monodevelop-list@lists.ximian.com (questions and discussion)

thank you in advance!

**Comment by Therzok** [comment]
1. I haven't personally tested Mono runtime integration on Windows. Could take a look.

2. monodoc should installed separately via the `Mono libraries` package. See [this](https://www.monodevelop.com/developers/building-monodevelop/#windows).

3. You can do exactly that! You can copy the `monodevelop/main/build` directory somewhere. After that, you can remove the `MacOSX` and `tests` directories. Then MonoDevelop should just work.

We don't have a forum, but we do have a [gitter](https://gitter.im/mono/monodevelop) channel

**Comment by Therzok** [comment]
`main\external` is not used at runtime. So it might have to go in `main\build\bin`

**Comment by Therzok** [comment]
Closing, as questions have been answered.
