### ISSUE TITLE
Can't build some projects with SDK

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#6885]
What happens is NullReferenceException at https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs#L412
Example of project that fails to build is https://github.com/xamarin/vs-editor-core/blob/master/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj

Some more info can be found in Slack chat at: https://xamarinhq.slack.com/archives/C0NRNVCGP/p1547466257354600

This is kinda blocking dogfooding 8.0 when working on new Editor, so if possible fix asap.

> VS bug [#765999](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/765999)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.1237 (master)



Pull Request #6902 merged by: Jose Miguel Torres  
 Author: mono  
 Commit: 938778ff5e77101b98b168c3d7ace85927fbc758 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.0.0.1267 (release-8.0)



Pull Request #6902 merged by: Jose Miguel Torres  
 Author: mono  
 Commit: 938778ff5e77101b98b168c3d7ace85927fbc758 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: Jose Miguel Torres  
 Commit: 3ae32958a30188148e2115effa3582421b831c88 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #6902 merged by: Jose Miguel Torres  
 Author: mono  
 Commit: 938778ff5e77101b98b168c3d7ace85927fbc758 (xamarin/monodevelop)
