### ISSUE TITLE
MonoDoc bundle does not include binary files

### ISSUE THREAD

**Issue by drasticactions** [mono/monodevelop#6889]
In the current 7.8.x and 8.x builds, MonoDoc does not include any binary files. If you try to run Help > API Documentation, nothing launches. If you open up the VSM bundle, you see

<img width="619" alt="image" src="https://user-images.githubusercontent.com/898335/51138503-3ab49500-180f-11e9-8351-5ef9df180c35.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/898335/51138516-4607c080-180f-11e9-895e-416024073151.png">

I've tested this with 8.0.0.1136 and 7.8.0.1544, both don't include the binary files. The currently shipping builds _do_ include it, so something may have changed during that time to cause this break.

> VS bug [#766219](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/766219)

**Comment by mrward** [comment]
Build of monodevelop/main/external/macdoc/macdoc.sln is failing with:

   MMP: error MM0073: Xamarin.Mac 5.6.0 does not support a deployment target of 10.7 for macOS (the minimum is 10.9). Please select a newer deployment target in your project's Info.plist.

Presumably the min version needs to be updated similar to this other [pull request](https://github.com/xamarin/macdoc/pull/3).

Also the build step should be failing but it currently is not.

**Comment by mrward** [comment]
MacDoc ref bumped in this pull request - https://github.com/mono/monodevelop/pull/6890

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.0.0.1141 (master)



Author: Matt Ward  
 Commit: 93fd47ea14fbfd387b3a42ecdb6a567ed3678901 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.0.0.1166 (release-8.0)



Author: Matt Ward  
 Commit: 93fd47ea14fbfd387b3a42ecdb6a567ed3678901 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.1738 (release-8.0)



Author: Matt Ward  
 Commit: 93fd47ea14fbfd387b3a42ecdb6a567ed3678901 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: 93fd47ea14fbfd387b3a42ecdb6a567ed3678901 (xamarin/monodevelop)
