### ISSUE TITLE
Do not log an error if global.json has no SDK version specified

### ISSUE THREAD

**Issue by sandyarmstrong** [mono/monodevelop#6904]
`DotNetCoreSdkPaths.ReadGlobalJson` should (a) have proper checks for the case where `sdk` and/or `sdk.version` elements do not exist, and (b) not log an error if `sdk.version` is not present.

See https://github.com/mono/monodevelop/blob/66f589806316b31463e2d283d9960bc2a424d43a/main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs#L246

According to [the docs](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json), global.json is not required to contain `sdk.version`.

Some projects have a global.json with only a `msbuild-sdks` section.

> VS bug [#768796](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/768796)

**Comment by jtorres** [comment]
This is already fixed [here](https://github.com/mono/monodevelop/commit/ad156c8dcbb50002bb3c52ee16982e98886cb202#diff-05042cb24940fb537f02aedbf0fd45ca)
