### ISSUE TITLE
Possible leak of large data via AsyncOperation

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6918]
Currently, AsyncOperation's CancellationTokenSource is not disposed, thus not allowing the GC to clear out the cancellation callbacks. This can lead to lots of items not GC'd (after a few builds of mono-addins, it led to ~2mb of `char[]` being uneligible for gc until, at least, the next build)

> VS bug [#773051](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/773051)

**Comment by Therzok** [comment]
<img width="1483" alt="screenshot 2019-01-17 at 23 39 34" src="https://user-images.githubusercontent.com/109974/51350573-2e4f6700-1ab1-11e9-82c4-88c6e3c21cc4.png">

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.1224 (master)



Author: Marius Ungureanu  
 Commit: 7aeb14d75a9d7267c4a3ea7737af139e3f1aaabb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.1267 (release-8.0)



Author: Marius Ungureanu  
 Commit: 7aeb14d75a9d7267c4a3ea7737af139e3f1aaabb (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 7aeb14d75a9d7267c4a3ea7737af139e3f1aaabb (xamarin/monodevelop)
