### ISSUE TITLE
Building for Mac: Will not build .app file, no target in Makefile

### ISSUE THREAD

**Issue by badprogramshere** [mono/monodevelop#6939]
Upon running the commands `cd main/build/MacOSX && make MonoDevelop.app && open MonoDevelop.app`, as suggested by the MonoDevelop website, I get this error:

`make: *** No rule to make target 'MonoDevelop.app'.  Stop.`

**Comment by Therzok** [comment]
The target is `make app`

**Comment by Therzok** [comment]
Issue moved to [mono/md-website #96](https://github.com/mono/md-website/issues/96) via [**ZenHub**](https://www.zenhub.com/)
