### ISSUE TITLE
Version Control background thread processing might benefit from using a ConcurrentExclusiveSchedulerPair

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6943]
GetDirectoryVersionInfo and other methods use a background thread which does processing and queues items.

This could be replaced with a Task system that queues on an Exclusive scheduler from ConcurrentExclusiveSchedulerPair.

This would simplify a lot of the logic, making it easier to follow.

> VS bug [#774358](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774358)

**Comment by sevoku** [comment]
Done! #7078 (67c8ba6132038159ef0807f8f744ba3ca41442c1)

**Comment by sevoku** [comment]
Actually only for git, repopening :(

**Comment by mkrueger** [comment]
It's part of the version control API changes now.
