### ISSUE TITLE
Make HackyCache be a proper typesystem info cache

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6949]
Since invalidation is hard in this scenario, we can only do a quick use-cache-then-update mechanism to ensure data is always valid.

1. Always load cached data and pass to workspace
2. Start a background task which queries MSBuild for current data
3. Refresh data with new values depending on which is more optimized (bulk update vs fully replace)

Should build on top of https://github.com/mono/monodevelop/pull/6919

> VS bug [#774359](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774359)

**Comment by DavidKarlas** [comment]
Also "Gathering class information" icon should be displayed until current data comes back from MSBuild, just as "if something is not working as expected, here is this icon saying so".

**Comment by Therzok** [comment]
It's already been done via WorkspaceFilesCache.
