### ISSUE TITLE
Building MonoDevelop.Refactoring from roslyn-upgrade branch fails

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#6994]
I reproduced this problem with master build. Here is screenshot of failure:
![image](https://user-images.githubusercontent.com/774791/51841418-e4674c00-230e-11e9-9f13-ed3425e79040.png)

> VS bug [#779492](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779492)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.0.0.1315 (master)



Author: Rodrigo Moya  
 Commit: e7eb01b9b77cbdc6e8cbedcac85d779f5e1c818c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.0.0.2001 (release-8.0)



Author: Rodrigo Moya  
 Commit: e7eb01b9b77cbdc6e8cbedcac85d779f5e1c818c (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Rodrigo Moya  
 Commit: e7eb01b9b77cbdc6e8cbedcac85d779f5e1c818c (xamarin/monodevelop)
