### ISSUE TITLE
NoWarn IDE0051 is not honored

### ISSUE THREAD

**Issue by jbevain** [mono/monodevelop#7021]
Visual Studio Enterprise 2019 Preview for Mac
Version 8.0 Preview (8.0 build 1805)

* Create a new C# class library project
* In the csproj, set:

```xml
    <NoWarn>IDE0051</NoWarn>
```

* In a C# class, input:

```cs
private void Foo()
{
}
```

Current result: the `Foo` identifier is greyed out, and the IDE offer to remove the unused private method.
Expected result: the NoWarn IDE0051 directive should suppress this behavior.

> VS bug [#783932](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783932)

**Comment by jbevain** [comment]
This impacts the Unity scenario where private methods with specific names are invoked from the game engine.

**Comment by Therzok** [comment]
Hmmm, we should pass this in specific diagnostic options.

**Comment by mrward** [comment]
NoWarn items are passed to the CSharpCompilationOptions as specific diagnostic options. But unfortunately the code prefixes the warning code with 'CS' if it does not start with 'CS' so the wrong code gets added 'CSIDE0051'. Seems like the code should only add 'CS' if the code is a number.

https://github.com/mono/monodevelop/blob/2fc84720ec31c9d2d3c62b03a25bd5a7ec781493/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs#L192

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.0.0.1343 (master)



Author: Marius Ungureanu  
 Commit: f65435df08c17a3bce9ba5e7e44031c8879fdb7d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.0.0.2001 (release-8.0)



Author: Marius Ungureanu  
 Commit: f65435df08c17a3bce9ba5e7e44031c8879fdb7d (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: f65435df08c17a3bce9ba5e7e44031c8879fdb7d (xamarin/monodevelop)
