### ISSUE TITLE
Error while installing monodevelop on Ubuntu 18.04

### ISSUE THREAD

**Issue by AdeelTariq** [mono/monodevelop#7022]
Hi,

Months ago on Ubuntu 18.04.1, I was able to do a successful install by following the steps here: https://www.monodevelop.com/download
Then the installation broke for some reason and I start getting this when trying to install monodevelop again:
```

The following packages have unmet dependencies:
 monodevelop : Depends: fsharp but it is not going to be installed
               Depends: libglib2.0-0 (>= 2.56.3) but 2.56.2-0ubuntu0.18.04.2 is to be installed
               Recommends: libgtk2.0-cil-dev but it is not going to be installed
               Recommends: mono-devel but it is not going to be installed
               Recommends: xamarin-gtk-theme but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

I thought I could maybe upgrade libglib2.0 on my own to fix that but I instead destroyed my Ubuntu installation.

Now I'm on a fresh Ubuntu install of 18.04.1 and still getting the above error. 
**Here's what I think is how the issue can be reproduced:**

- Fresh install of Ubuntu 18.04 from Ubuntu site
- Install all available updates during or after Ubuntu installation
- Try installing [monodevelop](https://www.monodevelop.com/download/)

**Comment by AdeelTariq** [comment]
I was able to update libglib2.0

**Comment by wsw70** [comment]
@AdeelTariq: how exactly did you upgrade `libglib2.0`?
