### ISSUE TITLE
Create new method window prevents typing

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7032]
Release ID: 8.0.0.1307
Git revision: a749d715809613fd7000c009567646f15977a97c
Build date: 2019-01-30 10:49:29+00
Build branch: master
Xamarin extensions: 4a2f830a775afed23556247fe5fe93f46c8d1e0b

Also happens in VS Mac 7.7.

1. Create a new C# library project.
2. With the code as shown below, try to type 'Stopped' as the event handler name after the `+=` characters.

```
using System;
namespace MyProject
{
	public class TestEventHandler
	{
		public event EventHandler Stopped;
	}

	public class MyClass
	{
		public MyClass ()
		{
		}

		public void AddEventHandler ()
		{
			var handler = new TestEventHandler ();
			handler.Stopped +=
		}
	}
}
```
3. The code completion window is displayed and as you type the 'o' character the create method pop-up appears as well and then you cannot type anything until you press escape to close some of the pop-up windows.

![typingblocked](https://user-images.githubusercontent.com/372361/52175986-638fd080-27a4-11e9-8d3d-200f6caba5d2.gif)

It seems as though the create new method window should not appear unless it is activated in the completion list (i.e. press tab with it selected or trigger completion with that item selected).

There are other cases when the new method pop-up window is displayed without it being triggered/activated in the completion list.

> VS bug [#785200](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785200)

**Comment by mkrueger** [comment]
Should be fixed with

https://github.com/mono/monodevelop/pull/6992
