### ISSUE TITLE
MonoDevelop creates a nearly empty ".mono" folder on Linux

### ISSUE THREAD

**Issue by aaronfranke** [mono/monodevelop#7037]
Mono version 5.18.0.240, MonoDevelop 7.7 build 1869, Ubuntu 18.04.

After running MonoDevelop on Linux, it creates an empty folder at `~/.mono/registry/CurrentUser` and creates a file at `~/.mono/registry/last-btime` with a Unix timestamp number.

I have tried running other Mono programs and they do not do this, only MonoDevelop creates it.

This path is not part of the XDG directory specification. Such configuration files should be placed in `$XDG_CONFIG_HOME` aka `~/.config`, or `$XDG_DATA_HOME` aka `~/.local/share`. MonoDevelop already places most of its files in these folders, but it also creates this nearly empty folder in my home dir.

**Comment by mrward** [comment]
This is not specific to MonoDevelop. Any Mono program that uses the registry will use that path.

https://github.com/mono/mono/blob/bb5feb2579733aac92156f2eb0df2ae872ed3e71/mcs/class/corlib/Microsoft.Win32/UnixRegistryApi.cs#L808-L809
