### ISSUE TITLE
Indentation after a comment indents more than expected

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7047]
VS Mac 8.0.0.1344 and VS Mac 7.8.0.1555 and VS Mac 7.7.4
VS Mac 7.6.11 is OK.

If you press return twice after a comment line in a class the second line is indented an extra level compared with the first line. Not sure if this is expected.

![commentindentation](https://user-images.githubusercontent.com/372361/52241868-c8464a80-28cc-11e9-9d6a-8be2b8449dc9.gif)

> VS bug [#785516](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785516)

**Comment by mkrueger** [comment]
Uptream issue: https://github.com/dotnet/roslyn/issues/33282
