### ISSUE TITLE
SQLitePersistentStorage not disposed on solution close and other issues

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7053]
We should trigger a `StorageLocationChanging` when a solution is closed. Without this, the db.lock is held so re-opening the solution or whatever else will not have access ot the storage.

> VS bug [#786109](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786109)

**Comment by Therzok** [comment]
SolutionId map is not right. That class needs reworking:
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Storage/VisualStudioPersistentStorageLocationService.cs,19

**Comment by Therzok** [comment]
Implementation details got changed here: https://github.com/dotnet/roslyn/commit/093be5af2f15abe411383f4c2f24d2434012d561#diff-6c9c3513e1a053f641813f510d73a5fe

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.1374 (master)



Author: Marius Ungureanu  
 Commit: fb7b7834bfc3456090bc6ebdd4a795a267f0ae32 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.2001 (release-8.0)



Author: Marius Ungureanu  
 Commit: fb7b7834bfc3456090bc6ebdd4a795a267f0ae32 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: fb7b7834bfc3456090bc6ebdd4a795a267f0ae32 (xamarin/monodevelop)
