### ISSUE TITLE
Empty working directory prevents project from running

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7082]
The change in https://github.com/mono/monodevelop/pull/7059 prevents the project from being run if no working directory is set.

If the working directory is null or empty the code should not be using Directory.Exists.

> VS bug [#787952](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/787952)

**Comment by usr-sse2** [comment]
It's rather annoying that when starting .NET Core projects, the default working directory is the directory of the project file, so that e. g. application logs and result files are mixed with source code. Maybe change it to the output path (`bin/Debug/netcoreapp2.2`), like in Mono?

**Comment by mrward** [comment]
@usr-sse2 Never noticed that before. I have opened a bug for this https://github.com/mono/monodevelop/issues/7087

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.0.0.1386 (master)



Author: Matt Ward  
 Commit: f38af755345221f053d331055ed5e468f8466426 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.2176 (release-8.0)



Author: Matt Ward  
 Commit: f38af755345221f053d331055ed5e468f8466426 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: f38af755345221f053d331055ed5e468f8466426 (xamarin/monodevelop)
