### ISSUE TITLE
.NET Core console project uses project as working directory by default

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7087]
The default working directory for a .NET Core console project is the project directory. For a classic C# project the default working directory is the output directory.

Whilst using the project directory as the default working directory for an ASP.NET Core project (need to check what VS on Windows does here) for a .NET Core console project it should use the output directory by default.

> VS bug [#788012](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788012)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.1.0.34 (master)



Pull Request #7258 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 251de12ffbecafad614e6a4b703feab07813b363 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.0.0.2580 (release-8.0)



Pull Request #7260 merged by: Lluis Sanchez  
 Author: mono  
 Commit: be3ffe325bc744ec204802688952471bdf434af3 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.1.0.1701 (master-vnext)



Pull Request #7260 merged by: Lluis Sanchez  
 Author: mono  
 Commit: be3ffe325bc744ec204802688952471bdf434af3 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7260 merged by: Lluis Sanchez  
 Author: mono  
 Commit: be3ffe325bc744ec204802688952471bdf434af3 (xamarin/monodevelop)
