### ISSUE TITLE
[Mac] Avoid using NSApplication.SharedApplication.Windows

### ISSUE THREAD

**Issue by sevoku** [mono/monodevelop#7091]
There is a short time period where a native `NSWindow` is still alive in `NSApplication.SharedApplication.Windows` even after it has been closed and disposed and collected on the managed side (Xamarin.Mac) (see #7046). Iterating over `NSApplication.SharedApplication.Windows` during this short period causes a resurrection of the managed object, so it usually comes back in a not well-known state (especially custom NSWindow derivates and Xwt.Mac) and can potentially leak or even bring down the runtime.

In (more or less) distant future `NSApplication.SharedApplication.Windows` will be [removed from Xamarin.Mac due to it's evil nature](https://github.com/xamarin/xamarin-macios/issues/5350).

Possible solutions:

* Use global notifications: we can track closed windows by listening to the `NSWindowWillCloseNotification`, but there is no opposite notification about new windows. This needs more investigation.
* Define an API for controlled NSWindows and derivate creation in MonoDevelop and disallow creating and/or showing a window without going through that new API for extensions (using an analyzer in AddinMaker)

Once we have a way to track all NSWindows, we should replace `NSApplication.SharedApplication.Windows` usage everywhere with the new API and include an analizer to to disallow its usage in extensions (until https://github.com/xamarin/xamarin-macios/issues/5350 comes) or even remove it via IL in our local Xamarin.Mac that we ship.

> VS bug [#788429](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788429)

**Comment by Therzok** [comment]
I think the best solution that would make us have full control is removing `NSApplication.Windows` from the Xamarin.Mac.dll we ship. That would be done by a IL rewrite step.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.2.0.121 (master-vnext)



Pull Request #565 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 68b3c81c67831e9db542006f8835260d3d6621ac (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.1.0.2323 (release-8.1)



Pull Request #705 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 3dba8c874c2f7657364627a334c6de5808c63657 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #565 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 68b3c81c67831e9db542006f8835260d3d6621ac (xamarin/monodevelop)
