### ISSUE TITLE
Change the MonoDevelopWorkspace model to have a primary and secondary workspaces

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7096]
Currently, we create a MonoDevelopWorkspace per solution we open. We should have at least one re-used MonoDevelopWorkspace.

This would help us mitigate leaks coming in from creating multi Host kind workspaces.

> VS bug [#788777](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788777)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.0.0.1523 (master)



Pull Request #7167 merged by: Marius Ungureanu  
 Author: mono  
 Commit: b06d05a55de284af1059e6bf74c3b35d79344b1d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.0.0.2306 (release-8.0)



Pull Request #7167 merged by: Marius Ungureanu  
 Author: mono  
 Commit: b06d05a55de284af1059e6bf74c3b35d79344b1d (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7167 merged by: Marius Ungureanu  
 Author: mono  
 Commit: b06d05a55de284af1059e6bf74c3b35d79344b1d (xamarin/monodevelop)
