### ISSUE TITLE
[VersionControl] Add validations adding a new remote (Git)

### ISSUE THREAD

**Issue by jsuarezruiz** [mono/monodevelop#7114]
Without any validation, can include anything as remote. With a wrong remote, a lot of operations fails.

> VS bug [#789309](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/789309)

**Comment by jsuarezruiz** [comment]
Sent PR: https://github.com/mono/monodevelop/pull/7137

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1503 (master)

Pull Request #7137 merged by: Vsevolod Kukol
Author: mono
Commit: f3acb8385c04d9571222eb5c549d99810b7bcb79 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.2306 (release-8.0)

Pull Request #7137 merged by: Vsevolod Kukol
Author: mono
Commit: f3acb8385c04d9571222eb5c549d99810b7bcb79 (xamarin/monodevelop)
