### ISSUE TITLE
[VersionControl] Add validations to Checkout process

### ISSUE THREAD

**Issue by jsuarezruiz** [mono/monodevelop#7120]
If the Checkout dialog is opened and the button is pressed (without entering an URL), it starts by trying to delete the content of the Target Directory folder. The button should not be enabled.

> VS bug [#789313](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/789313)

**Comment by jsuarezruiz** [comment]
Sent PR: https://github.com/mono/monodevelop/pull/7129

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1513 (master)

Pull Request #7129 merged by: Vsevolod Kukol
Author: mono
Commit: 387cf1414e8b71ba60899f6c523b2da8c5a8deda (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.2306 (release-8.0)

Pull Request #7129 merged by: Vsevolod Kukol
Author: mono
Commit: 387cf1414e8b71ba60899f6c523b2da8c5a8deda (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7129 merged by: Vsevolod Kukol
Author: mono
Commit: 387cf1414e8b71ba60899f6c523b2da8c5a8deda (xamarin/monodevelop)
