### ISSUE TITLE
[Source Control] Issue trying to checkout a git SSH repository (Failed to start SSH session: Unable to exchange encryption keys)

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#7150]
1) Clone any repository with SSH url-> `git@github.com:XXXXX/XXXXX.git`
2) Create/open a Solution in the cloned path in MD
3) Press menu SourceControl/Checkout
4) In connect 'repository url' set your SSH url

Failed to start SSH session: Unable to exchange encryption keys
This is the full log:

https://gist.github.com/netonjm/b7da93a51301d2e144b452ee6ec77ce6

> VS bug [#792840](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792840)

**Comment by Therzok** [comment]
Should be fixed by libgit2 bump

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1594 (master)

Pull Request #7078 merged by: Vsevolod Kukol
Author: mono
Commit: e9006c97e60bc51b1fe82dec9f80c9eb4f57b7cc (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.2351 (release-8.0)

Pull Request #7078 merged by: Vsevolod Kukol
Author: mono
Commit: e9006c97e60bc51b1fe82dec9f80c9eb4f57b7cc (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7078 merged by: Vsevolod Kukol
Author: mono
Commit: e9006c97e60bc51b1fe82dec9f80c9eb4f57b7cc (xamarin/monodevelop)
