### ISSUE TITLE
Build dependencies in imports are not respected

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#7154]
I have a project that imports some shared target files. The shared target files add a build dependency on another project:

```xml
<ItemGroup>
	<ProjectReference
		Include="$(MSBuildThisFileDirectory)SomeOtherProject.csproj"
		Project="{GUID}"
		Name="SomeOtherProject"
		ReferenceOutputAssembly="false"
		SkipGetTargetFrameworkProperties="true"
		/>
</ItemGroup>
```

The resulting dependency is respected by MSBuild but not by MonoDevelop.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Author: Mikayla Hutchinson
Commit: e3b91a4ca8a9831f78f28482a03f9c26f1e0bb0d (xamarin/monodevelop)
