### ISSUE TITLE
Question: Licensing of dependencies?

### ISSUE THREAD

**Issue by wjk** [mono/monodevelop#7170]
While browsing this repository, I note the extensive use of `Microsoft.VisualStudio.*` NuGet packages. As I understand it, some of these packages are not open-source. While things like the MEF library or the threading library are readily available, none of the editor-related libraries are open-source AFAICT. I did find [an old copy of some of the editor code](https://github.com/Microsoft/vs-editor-api), but that repository hasn't been touched since 2017. This irks me heavily, as the MonoDevelop project is more than just "the open-source bits of Visual Studio for Mac". In particular, users (such as myself) wishing to reuse the MonoDevelop core to build another product are blocked by this. Linux users (or distribution maintainers) who insist on using only FOSS code also have a problem. I have so far seen no word from the VS team about this issue. Could someone please clarify this? Thanks!

**Comment by knocte** [comment]
> I did find [an old copy of some of the editor code](https://github.com/Microsoft/vs-editor-api)

Last person to commit into that repo was @KirillOsenkov, pinging him as maybe he can shed some light?

**Comment by KirillOsenkov** [comment]
Hello @wjk! We meet again! :)

The latest source code for the Microsoft.VisualStudio.* (VS Editor) assemblies is at:
https://github.com/KirillOsenkov/vs-editor-api/tree/monodevelop/master

Unfortunately we're kind of in a transition phase right now where we have to build these from a temp location in my fork. Sorry for the inconvenience.

@abock and @slluis can comment more.

**Comment by abock** [comment]
Hello @wjk, as @kirillosenkov mentions, the [MIT-licensed] source is available for the NuGet packages that bring in the core VS Editor API upon which parts of the editor in MonoDevelop depend.

We are in the midst of upgrading to a newer snapshot of the VS editor core for MonoDevelop. I will ensure in the coming weeks that the NuGet packages we produce are more explicit with their metadata with respect to licensing and how to obtain the correct corresponding source code.

The repository structure will also be changing soon, and I will ensure we have better documentation to explain how all the layering works.

Thanks! Please let us know if you have further questions.

**Comment by wjk** [comment]
@abock @KirillOsenkov You've answered all of my questions. Thank you so much for your help!

**Comment by wjk** [comment]
Just checking in about this issue. I've picked through @KirillOsenkov's vs-editor-api repo, and I still cannot find the source for some of the Microsoft.VisualStudio.* DLLs that ship in VSMac; however, nor can I find definitive proof that the assemblies in question are proprietary. Moreover, I’ve looked at the editor-related code in this repository (specifically, `MonoDevelop.SourceEditor2` and `MonoDevelop.TextEditor`) and I still cannot figure out how all the bits fit together. Also, in @abock's post on February 22, there was a mention of a changing repository structure. I have seen no word of that either. Some clarification would be appreciated. Thanks!

**Comment by knocte** [comment]
It seems a recent commit has added a new submodule: eb56def , which maybe helps with this issue?

**Comment by wjk** [comment]
@knocte Unfortunately not. `vs-editor-api` is _not_ the same thing as `vs-editor-core`. The API repository contains interfaces, MEF components, and the like; the core repository contains the nuts-and-bolts implementations of those interfaces that talk to Cocoa et al. It is the core repository that we are missing. Hope this helps!

**Comment by abock** [comment]
Hi @wjk, @knocte!

VS Mac is not open source, and we have no plans to open source the Cocoa editor implementation at this time. We have split the editor API definitions for the new Cocoa editor and continued to update the existing layers that were previously open source (the non-UI text/buffer/logic layers). These live in @KirillOsenkov's fork of `vs-editor-api`. We have plans to move this work back into the "upstream" Microsoft org as well - just haven't gotten there yet.

This issue was opened to point out the fact that we were depending on NuGet packages that did not make it clear where the source came from (they lacked metadata pointing to the repository). To fix this, we are now sub-moduling `vs-editor-api` which is fully MIT-licensed.

This allows MonoDevelop to build, however we do still have some work on the backlog to allow the old editor to work again at runtime in the pure open-source build (I believe some minor MEF parts are missing that we'll need to add). We made a branch before we merged the big changes for 8.0 that introduced the new Cocoa editor but I cannot find it. @slluis can you reply with that branch name?

You are correct that we have a proprietary `vs-editor-core` layer that provides the implementations of the new Cocoa editor, but again, this layer is not slated for open sourcing, at least at this time.

I'm closing this issue as it pertained to the NuGet dependencies lacking metadata to allow their source to be traced, and we have a submodule now instead, but please feel free to ask any followup questions.

**Comment by abock** [comment]
Just to close the loop on this, everything is now back in place in the mainline Microsoft repository: with a README that hopefully provides a little more clarity: https://github.com/Microsoft/vs-editor-api

**Comment by knocte** [comment]
> https://github.com/Microsoft/vs-editor-api

If I try to compile master branch today with VS4Mac, it complains about vs-editor-api missing some DLLs:

```
/Users/knocte/Documents/Code/monodevelopCLEAN/main/src/core/MonoDevelop.Core/CSC: Error CS0006: Metadata file '/Users/knocte/Documents/Code/monodevelopCLEAN/main/external/vs-editor-api/bin/Editor/Language/Def/StandardClassification/Debug/net472/Microsoft.VisualStudio.Language.StandardClassification.dll' could not be found (CS0006) (MonoDevelop.Core)
/Users/knocte/Documents/Code/monodevelopCLEAN/main/src/core/MonoDevelop.Core/CSC: Error CS0006: Metadata file '/Users/knocte/Documents/Code/monodevelopCLEAN/main/external/vs-editor-api/bin/Editor/Text/Def/Extras/Debug/net472/Microsoft.VisualStudio.Text.Extras.dll' could not be found (CS0006) (MonoDevelop.Core)
/Users/knocte/Documents/Code/monodevelopCLEAN/main/src/core/MonoDevelop.Core/CSC: Error CS0006: Metadata file '/Users/knocte/Documents/Code/monodevelopCLEAN/main/external/vs-editor-api/bin/Editor/Text/Impl/PatternMatching/Debug/net472/Microsoft.VisualStudio.Text.PatternMatching.Implementation.dll' could not be found (CS0006) (MonoDevelop.Core)
```

Any chance to have some sort of CI for only the opensource bits? Otherwise people willing to contribute to the opensource repo can't even build the solution.

**Comment by Therzok** [comment]
@knocte it seems like the projects exist, but not added to the projitems.

https://github.com/microsoft/vs-editor-api/blob/master/ProjectReferences.projitems

**Comment by Therzok** [comment]
No, it seems they're added. Hrm.

**Comment by Therzok** [comment]
@knocte does a commandline build work fine? Also, which configuration are you building master on?

**Comment by sandyarmstrong** [comment]
@knocte hello! Can you share your binlog? I'm guessing there is some failure happening earlier in your build.

**Comment by knocte** [comment]
> @knocte hello!

hi!

> Can you share your binlog?

I guess you mean build log? This is why I got in the build output pad: https://gist.github.com/knocte/7f6b8cbd7be1486839c792b3b708ee62

> @knocte does a commandline build work fine?

Just tried `msbuild Main.sln` from macOS and I get some other errors:

https://gist.github.com/knocte/ab3905f5cfdadf17549f73f81bc61cb8

> Also, which configuration are you building master on?

The default one? Debug? I didn't change anything, just opened the .mdw file and right click on the MonoDevelop.Startup project -> Rebuild.

**Comment by Therzok** [comment]
It should be DebugMac on Mac.

Also, we don't really use the mdw file, usually we use Main.sln.

**Comment by decriptor** [comment]
@knocte binlog is a specific msbuild output format. http://msbuildlog.com/

**Comment by Therzok** [comment]
By default, the `make` target will generate a binlog:
https://github.com/mono/monodevelop/blob/3a8c3d7e40ce146a0264483206b541cb9c8a125d/main/xbuild.include#L41

**Comment by knocte** [comment]
Thanks for the info, I've issued now a build with `msbuild main/Main.sln /p:Configuration=DebugMac /t:Build /bl:MD.binlog > build.log` and it still doesn't compile. I've posted the build.log and the binlog here:
https://gitlab.com/knocte/monodevelop/blob/master/build.log
https://gitlab.com/knocte/monodevelop/blob/master/MD.binlog

**Comment by knocte** [comment]
> and it still doesn't compile

Nevermind, it compiled with `make` (I was lazy to figure out how to install some deps that the configure script was telling me about); however, launching it fails, so I've filed this bug: https://github.com/mono/monodevelop/issues/9160
