### ISSUE TITLE
[VersionControl] Cancel project publication in Git

### ISSUE THREAD

**Issue by jsuarezruiz** [mono/monodevelop#7175]
If try to publish a project in a Git repository and during the process, when the dialog to authenticate appears, the process is canceled (closing the authenticate dialog for example); the project is not published but the local .git folder is created and from that moment MonoDevelop manage the project as if it were published (menu options, contextual options, etc.).

> VS bug [#796047](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796047)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.1631 (master)

Pull Request #7178 merged by: Vsevolod Kukol
Author: mono
Commit: 2b2864f1c8eb972bf39aefd9561861b3fed65f6c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.2410 (release-8.0)

Pull Request #7178 merged by: Vsevolod Kukol
Author: mono
Commit: 2b2864f1c8eb972bf39aefd9561861b3fed65f6c (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7178 merged by: Vsevolod Kukol
Author: mono
Commit: 2b2864f1c8eb972bf39aefd9561861b3fed65f6c (xamarin/monodevelop)
