### ISSUE TITLE
[Updater] When closing the MS Sign-in popup 2 more popups appear

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#7196]
1) Open MD
2) Click Menu VisualStudio/Check for updates
3) Opens a MS Sign-in popup
4) Close it
5) 2 popups appear 

![sign-popup](https://user-images.githubusercontent.com/1587480/53166148-d4bce980-35d4-11e9-9095-22e8a069e31b.gif)

Visual Studio Enterprise 2019 Preview for Mac
Version 8.0 Preview (8.0 build 1323)
Installation UUID: ac2f5f5a-65c6-4e02-aae1-61d2ac9aabc1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.1 (d16-0 / 2e9867a4)

	Package version: 520000203

Mono Framework MDK
Runtime:
	Mono 5.20.0.203 (2018-10/2e7daaa78d5) (64-bit)
	Package version: 520000203

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview-27324-5
	2.2.1
	2.2.0
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
	1.0.3
SDK: /usr/local/share/dotnet/sdk/3.0.100-preview-010184/Sdks
SDK Versions:
	3.0.100-preview-010184
	2.2.103
	2.2.101
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview2-003156
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.20.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Users/jmedrano/Projects/profiler/src/XamarinProfiler.Mac/bin/Debug/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

> VS bug [#797835](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797835)

**Comment by mrward** [comment]
@nosami I thought this was fixed.
