### ISSUE TITLE
Deadlock in MonoDevelopPersistentStorageLocationService

### ISSUE THREAD

**Issue by DavidKarlas** [mono/monodevelop#7201]
https://gist.github.com/DavidKarlas/b1d295c785893db00cdaaca4da12eda7
https://gist.github.com/DavidKarlas/a24d691a4df2600860c2b46917b15515
One thread locks on `MonoDevelopPersistentStorageLocationService._gate` other locks on `AbstractPersistentStorageService._lock` and both want to lock on each others locks...

> VS bug [#798080](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798080)

**Comment by DavidKarlas** [comment]
This happened when I had solution open and selected different solution from Recent list.

**Comment by Therzok** [comment]
If we have this bug, Roslyn might have it too, unless this is explicitly because of multiple services/workspaces

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/issues/34283

**Comment by Therzok** [comment]
From what I'm seeing in the code, we might wait a bit for the solution crawler to finish writing, but definitely not a deadlock.

**Comment by Therzok** [comment]
In any case, should be re-opened against Roslyn, as we're using the same code as they are.

**Comment by Therzok** [comment]
Closing, it's not a deadlock, but a hang that's only going to happen if you close the solution while the incremental analyzers don't get cancelled. Most analyzers use the cancellation token, so it should be okay.
