### ISSUE TITLE
Clicking multiple times to New Project template it opens multiple dialogs

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#7203]
![clickmultipe](https://user-images.githubusercontent.com/1587480/53179289-bca89280-35f3-11e9-996a-fa7c05f2594c.gif)

Visual Studio Enterprise 2019 Preview for Mac
Version 8.0 Preview (8.0 build 1323)
Installation UUID: ac2f5f5a-65c6-4e02-aae1-61d2ac9aabc1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.1 (d16-0 / 2e9867a4)

	Package version: 520000203

Mono Framework MDK
Runtime:
	Mono 5.20.0.203 (2018-10/2e7daaa78d5) (64-bit)
	Package version: 520000203

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview-27324-5
	2.2.1
	2.2.0
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
	1.0.3
SDK: /usr/local/share/dotnet/sdk/3.0.100-preview-010184/Sdks
SDK Versions:
	3.0.100-preview-010184
	2.2.103
	2.2.101
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview2-003156
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.20.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Users/jmedrano/Projects/profiler/src/XamarinProfiler.Mac/bin/Debug/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

> VS bug [#797884](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797884)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.0.0.2494 (release-8.0)



Pull Request #4245 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 7758fb6af2d60b9af701ce86e4b28f891351f688 (xamarin/md-addins)  
 Included in Commit: fa48c14e70da1a0644f8a1589215e53ca8ac6e5e (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.1.0.21 (master)



Pull Request #4241 merged by: Rodrigo Moya  
 Author: xamarin  
 Commit: 947a8f32a350992da1ca8080dab79fade02ea85f (xamarin/md-addins)  
 Included in Commit: 921e0974ea3440b90f798f8340b7ec0253fc83c1 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.1.0.1701 (master-vnext)



Pull Request #4245 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 7758fb6af2d60b9af701ce86e4b28f891351f688 (xamarin/md-addins)  
 Included in Commit: 0331b37ed370c639781c87ac969992f362d34eb0 (xamarin/monodevelop)
