### ISSUE TITLE
Possible duplicate assembly added in MEF assembly list

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7214]
Generated assemblies, for some reason, seem to have been added twice here:
https://gist.github.com/netonjm/5076aa1512a184242005f92a2bfe57b6#file-gistfile1-txt-L130-L138

Avoid adding dynamic assemblies to the list of active assemblies.

> VS bug [#798008](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798008)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-6] Comment by **xamarinc**



Fixed in version 8.0.0.1634 (master)



Author: Marius Ungureanu  
 Commit: 4ce2053084d75d41ac90361b607075946b4ce32c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.0.0.2453 (release-8.0)



Author: Marius Ungureanu  
 Commit: 4ce2053084d75d41ac90361b607075946b4ce32c (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 4ce2053084d75d41ac90361b607075946b4ce32c (xamarin/monodevelop)
