### ISSUE TITLE
Fatal crash silent in VS4Mac trying to open a solution

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#7216]
Trying to open a solution:

An exception in the Xamarin.Ide.Updater.UpdatesDialog+UpdateDisplayWidget.CreateDetailsText

And a fatal error in:
MonoDevelop.VersionControl.VersionControlService.GetRepositoryReference

https://gist.github.com/netonjm/cc7b3d6d46f3a003d068c72d58e6eae2

**Comment by sevoku** [comment]
same as #7194
