### ISSUE TITLE
Implement a simple MLPD analysis tool that dumps basic information about an automated stress test run

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7221]
We should be able to parse a mlpd and upload various data points we care about during an automated test run.

> VS bug [#800906](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/800906)

**Comment by Therzok** [comment]
This can be used to automate tasks, such as https://github.com/mono/monodevelop/issues/6439

**Comment by rodrmoya** [comment]
We have XamarinProfiler.Console.exe as part of the XamarinProfiler, which profiles and generates a report of the most allocated classes, samples, etc. I was precisely last weekend looking at adding a VSTS task that could be called from any build definition, but didn't get too far, but I think it should be doable, what that just needs is to download a known profiler build, get an .app/.exe/.mlpd as input, profile that, and generate a XML report.

This is what the Xamarin.Profiler itself uses for automated performance test, so I think it's just a matter of bundling all deps (Profiler itself only) in a VSTS task/Web service that can easily be called from anywhere just passing an app to be profiled or a MLPD.

Just for the record, the XML report it generates is https://github.com/xamarin/profiler/blob/master/src/XamarinProfiler.Core/Reporting/ProfileRunReport.cs but, of course, can be extended to include whatever you think might be needed.

**Comment by Therzok** [comment]
Closing as done.
