### ISSUE TITLE
New Project dialog is not centered

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7222]
Clean build of monodevelop master on its own, no md-addins. When using make run and then using File - New Solution or clicking the New button on the welcome page the new project dialog appears at the bottom left of the screen.

<img width="859" alt="screen shot 2019-02-22 at 12 59 13" src="https://user-images.githubusercontent.com/372361/53244162-f3d57d00-36a1-11e9-81b2-c2ac08c1ea1f.png">

Also seems to be happening with VS Mac with a recent master build:

Build Information
Release ID: 800001634
Git revision: 4ce2053084d75d41ac90361b607075946b4ce32c
Build date: 2019-02-21 19:13:58+00
Build branch: master
Xamarin extensions: d7b2431a48ef15125b9c81930f6cd0a6ef4fec41

Not sure if this is a duplicate.

> VS bug [#800910](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/800910)

**Comment by rodrmoya** [comment]
Yes, a duplicate, marked internal ticket as such
