### ISSUE TITLE
Don't report UI delays until the app has first shown

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7274]
We currently report UI delays that happen during Addin engine initialization and so, which are expected.

We should not be reporting these.

> VS bug [#856378](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/856378)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.2.0.54 (master-vnext)



Pull Request #4510 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 3fc6721770b5aff8dfa17ea66906f51a04f6ad03 (xamarin/md-addins)  
 Included in Commit: 91ec6c5354764e7f6483114a00ac806833b08d3a (xamarin/monodevelop)
