### ISSUE TITLE
Collection was modified (in Project.OnFileDeleted())

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#7277]
I'm seeing a Collection was modified exception here:
![image](https://user-images.githubusercontent.com/679326/53613499-fd238580-3b8a-11e9-97d4-d05c8fa2c24f.png)

MonoDevelop.Projects.Project+<>c__DisplayClass349_0.<OnFileDeleted>b__0 Line 4480

Should we have a .ToArray() here?

**Comment by mrward** [comment]
Marius opened an issue for this #7276 just before you did :)
