### ISSUE TITLE
TimeToCode counter is not processed due to open timer expiring

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7284]
See https://github.com/mono/monodevelop/pull/7275 which is blocked by this bug.

The 2.5second timeout expires before the solution is passed to load.

> VS bug [#806672](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/806672)

**Comment by iainx** [comment]
We should probably have a flag added to the method that opens files whether the user initiated the load (via the GTC dialog, or the Open menu), or whether it was initiated by the OS, like by double clicking the icon in Finder

**Comment by rodrmoya** [comment]
Don't we have that already in IdeStartup's StartupInfo's HasFiles?

**Comment by Therzok** [comment]
@rodrmoya that's different. OpenDocument event comes after AppDidFinishLaunching. So it's not contained in startupinfo.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.1.0.191 (master)



Pull Request #7320 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 4fbf7502e498110e27fabed167da04447356c1a8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.0.0.2920 (release-8.0)



Pull Request #7348 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8c8779dc282f28602d62f90f88aec308cad47186 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.1.0.1701 (master-vnext)



Pull Request #7348 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 8c8779dc282f28602d62f90f88aec308cad47186 (xamarin/monodevelop)
