### ISSUE TITLE
NuGetFallbackFolder log entries for a solution with many .NET Core projects

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7312]
Opening a solution that has many .NET Standard/.NET Core projects results in many of the following entries in the IDE log:

    Unable to parse version from directory. '/usr/local/share/dotnet/sdk/NuGetFallbackFolder'

 - [ ] Special case NuGetFallbackFolder - no logging for this folder.
    - The original logging was supposed to handle invalid version numbers and was added before NuGetFallbackFolder existed.
 - [ ] Can we cache the information read from /usr/local/share/dotnet/sdk?
    - Just wondering if we can avoid reading the sdk versions for each .NET Core project. Seems like we could at least cache this information for a single solution.

> VS bug [#812515](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/812515)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.1.0.1726 (master-vnext)



Pull Request #486 merged by: Rodrigo Moya  
 Author: xamarin  
 Commit: b470fc5b561e734d0e5b19eb82d97fa6e2ccabb4 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #486 merged by: Rodrigo Moya  
 Author: xamarin  
 Commit: b470fc5b561e734d0e5b19eb82d97fa6e2ccabb4 (xamarin/monodevelop)
