### ISSUE TITLE
.NET Core project extension should ignore framework changes for other projects

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7317]
The DotNetCoreProjectExtension currently runs some code when any project's target framework changes. This should be changed so it only runs if the Project being changed matches the Project used by the extension. The event args should have a Project property which can be checked.

https://github.com/mono/monodevelop/blob/46f5727c26569990e25df89b6a353ae2bf0ad2ea/main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs#L379-L388

> VS bug [#812644](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/812644)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.1.0.1726 (master-vnext)



Pull Request #486 merged by: Rodrigo Moya  
 Author: xamarin  
 Commit: b470fc5b561e734d0e5b19eb82d97fa6e2ccabb4 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #486 merged by: Rodrigo Moya  
 Author: xamarin  
 Commit: b470fc5b561e734d0e5b19eb82d97fa6e2ccabb4 (xamarin/monodevelop)
