### ISSUE TITLE
Restore NuGet packages menu disabled for sdk style project targeting net47

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7319]
VS Mac 8.0.0.2696.

1. Create a C# .NET Core console project.
2. Edit the .csproj in the text editor and change the target framework to be `net47`.
3. Save the file and wait for restore to complete.

Expected result:

4. Right clicking the solution and Restore NuGet Packages is enabled.

Actual result:

Restore NuGet packages is disabled.
Also cannot use Restore from the Dependencies folder.
Changing the target framework back to netcoreapp2.1 and the menu is enabled again.

> VS bug [#814579](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/814579)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.3.0.255 (master)



Pull Request #7712 merged by: Matt Ward  
 Author: mono  
 Commit: 2cf3653e4fcfe2ad29f1be5ce1dc517c2b85a9d2 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.2.0.707 (release-8.2)



Pull Request #7712 merged by: Matt Ward  
 Author: mono  
 Commit: 2cf3653e4fcfe2ad29f1be5ce1dc517c2b85a9d2 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7712 merged by: Matt Ward  
 Author: mono  
 Commit: 2cf3653e4fcfe2ad29f1be5ce1dc517c2b85a9d2 (xamarin/monodevelop)
