### ISSUE TITLE
Add counter information for startup handler commands

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7353]
> VS bug [#825767](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/825767)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.5.0.542 (master)



Pull Request #8634 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 731aef48ac1fd8af61d09764ddafbd5bdc3803f6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.4.0.1865 (release-8.4)



Pull Request #8634 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 731aef48ac1fd8af61d09764ddafbd5bdc3803f6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8634 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 731aef48ac1fd8af61d09764ddafbd5bdc3803f6 (xamarin/monodevelop)
