### ISSUE TITLE
Modal NSPanel in Application Output

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7366]
See attached video file.

If the pad is set to autohide and it does hide, you cannot interact with the IDE at all after that.

[app_output_half.zip](https://github.com/mono/monodevelop/files/3004114/app_output_half.zip)

> VS bug [#827074](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/827074)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 8.1.0.1785 (master-vnext)



Pull Request #459 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 570f3e0719412db19000981bef315a2dfcfd0b77 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.0.2.12 (release-8.0)



Pull Request #467 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: c06f65e30ed846c201ebdf39ced9a1b46e4b70ca (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-29] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #459 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 570f3e0719412db19000981bef315a2dfcfd0b77 (xamarin/monodevelop)
