### ISSUE TITLE
Enable performance tests in CI

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7369]
The infrastructure for running CPU performance tests should already be in place.

Ensure CI runs, gathers and reports data on the runs.

> VS bug [#827654](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/827654)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.3.0.296 (master)



Author: Marius Ungureanu  
 Commit: a9864e4d98919c71e8c0b9e91e6faedf5ff46d24 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.2.0.744 (release-8.2)



Author: Marius Ungureanu  
 Commit: a9864e4d98919c71e8c0b9e91e6faedf5ff46d24 (mono/monodevelop)
