### ISSUE TITLE
6.x Mono MSBuild support is broken

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7372]
MSBuild moved the directory it is shipped in, from `15.0` to `Current`.

All these paths need to probe for `Current` before probing for 15.0.

http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core/Runtime.cs,499
http://source.monodevelop.com/#MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdks.cs,41

Maybe a simpler fix would be to probe `Current` first, then the `toolsVersion` version if it doesn't exist:
http://source.monodevelop.com/#MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs,193

> VS bug [#831219](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/831219)

**Comment by mrward** [comment]
Looks like we also need to have custom handling for any project model evaluation of the MSBuildToolsVersion property - https://github.com/Microsoft/msbuild/pull/4158

This is special cased since it could be Current and then numeric comparisons against a number would not work.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.1.0.2142 (master-vnext)



Author: Matt Ward  
 Commit: 11898adb42da9d17c765d43f33dde01b198a6b5b (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: 11898adb42da9d17c765d43f33dde01b198a6b5b (xamarin/monodevelop)
