### ISSUE TITLE
StressTest leak processing should be done in a background thread

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7373]
LeakProcessor should use Tasks or a Thread to handle processing of data.

> VS bug [#833371](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/833371)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.1.0.2188 (master-vnext)



Pull Request #649 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 7fc718d912d0565fc6d717547248741832baa5ba (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #649 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 7fc718d912d0565fc6d717547248741832baa5ba (xamarin/monodevelop)
