### ISSUE TITLE
Open file regression

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7374]
When opening a `.cs` via GTC, we don't show the code layout after opening the document.

Regressed in https://github.com/xamarin/monodevelop/commit/92353cb2e974bf7414e96a5acce200567ea1a4ab

```
Open the IDE
Open a `.cs` file
Observe nothing is shown.
```

Clicking on the `Code` menu item makes it visible.

> VS bug [#835482](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/835482)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-31] Comment by **xamarinc**



Fixed in version 8.1.0.1845 (master-vnext)



Pull Request #526 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 4b0855b8944ffa55db23a830f6f9f9933302b13a (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-32] Comment by **xamarinc**



Fixed in version 8.0.2.27 (release-8.0)



Pull Request #527 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 06350243e589622e1b6a30edbbcbb4420574745f (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-34] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #526 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 4b0855b8944ffa55db23a830f6f9f9933302b13a (xamarin/monodevelop)
