### ISSUE TITLE
Unused field/parameter/expression is now a roslyn diagnostic

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7379]
So, remove it from RefactoringEssentials

> VS bug [#837165](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/837165)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.1.0.1764 (master-vnext)



Pull Request #490 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: e7f6b7de970383f71ab4eeae5c3d393c1254e987 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.2.0.265 (master)



Pull Request #21 merged by: Mike Krüger  
 Author: mono  
 Commit: b33c80dcf2aa2307ae864c8990476bcc335be24c (mono/RefactoringEssentials)  
 Included in Commit: 13d6e33c680a7217482a24cda40f4aee6cc24314 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #490 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: e7f6b7de970383f71ab4eeae5c3d393c1254e987 (xamarin/monodevelop)
