### ISSUE TITLE
[VCS] NullReferenceException while running tests

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7383]
Not sure how to reproduce it, I just run the CommentTask tests with a breakpoint on all exceptions.

Via filesystem events, here: https://github.com/xamarin/monodevelop/blob/master-vnext/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlFileSystemExtension.cs#L123-L125

I reached a NRE on `infoCache` here: https://github.com/xamarin/monodevelop/blob/master-vnext/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs#L340

> VS bug [#839250](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/839250)

**Comment by mkrueger** [comment]
Fixed in 8.1
