### ISSUE TITLE
Control map should use ConditionalWeakTable

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7387]
https://github.com/mono/monodevelop/blob/0b270e49007ebe4409182bd75468729bd7c64a10/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Control.cs#L39

> VS bug [#840977](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/840977)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 8.1.0.1791 (master-vnext)



Pull Request #511 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 0dafd5dcc0a0deea82a244df2023d77e0c2a5655 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #511 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 0dafd5dcc0a0deea82a244df2023d77e0c2a5655 (xamarin/monodevelop)
