### ISSUE TITLE
Add unit test which validates the composition is properly loaded

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7390]
This should do a full composition load and validate that we have all the input assemblies loaded.

> VS bug [#840983](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/840983)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.1.0.2095 (master-vnext)



Pull Request #514 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 50e4baafa450029b94f2fe2a155b7f12dad6239b (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #514 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 50e4baafa450029b94f2fe2a155b7f12dad6239b (xamarin/monodevelop)
