### ISSUE TITLE
Can't list classes in navigation bar

### ISSUE THREAD

**Issue by usr-sse2** [mono/monodevelop#7391]
In source editor navigation bar method list works, but classes list is empty (or insufficient height to display anything).

Visual Studio for Mac 2019 8.0.3001, new editor preview is enabled.

![Снимок экрана 2019-04-05 в 13 27 17](https://user-images.githubusercontent.com/446776/55627358-a7a84d00-57b6-11e9-8df5-21976f277fe2.png)

> VS bug [#841029](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/841029)

**Comment by usr-sse2** [comment]
It works when the cursor is not in any class or namespace.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.3.0.310 (master)



Pull Request #7859 merged by: David Karlaš  
 Author: mono  
 Commit: d0438077f19d233ef1d2381bbee3860cdba8e6d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-24] Comment by **xamarinc**



Fixed in version 8.2.0.744 (release-8.2)



Pull Request #7859 merged by: David Karlaš  
 Author: mono  
 Commit: d0438077f19d233ef1d2381bbee3860cdba8e6d5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-29] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7859 merged by: David Karla??  
 Author: mono  
 Commit: d0438077f19d233ef1d2381bbee3860cdba8e6d5 (xamarin/monodevelop)
