### ISSUE TITLE
Integrate code coverage report in CI

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7394]
We used to (still have) a code coverage system in place.

I think it was coveralls? Maybe we can integrate it in CI to generate coverage reports on PRs.

**Comment by Therzok** [comment]
cc @iainx

**Comment by iainx** [comment]
we had code coverage set up to generate files on tests, no idea if it still works or if the coverage code in Mono still works. I think it was coveralls that I tested using to generate reports, but our coverage files were so big we had to split them into about 300 different files, and then manually select them all for merging, which IIRC brought the whole Coveralls site to its knees for a few hours while it processed them. I wouldn't like to be doing that for every PR :)
