### ISSUE TITLE
OnDocumentClosed causing file to be re-read from disk

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7398]
OnDocumentClosed is called after an editor's document is removed from the documents list, causing an expensive MonoDevelopTextLoader version to be used - which will load the file from disk again.

The file is then immediately discarded instantly by roslyn.

> VS bug [#843379](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843379)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-8] Comment by **xamarinc**



Fixed in version 8.1.0.2045 (master-vnext)



Pull Request #520 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 97adb3c15e32218daf55a6719d0ee5e65bfbb4f9 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #520 merged by: Vsevolod Kukol  
 Author: xamarin  
 Commit: 97adb3c15e32218daf55a6719d0ee5e65bfbb4f9 (xamarin/monodevelop)
