### ISSUE TITLE
Allow simple unit tests to be tracked for Performance

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7401]
Allow annotating unit tests with the performance category and the perf tests analysis tool to handle number metrics on it.

> VS bug [#843397](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843397)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 8.4.0.414 (master)



Pull Request #8100 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 560a020231b345761fadfa63f99ddd8a64d6c1ad (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.3.0.831 (release-8.3)



Pull Request #8100 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 560a020231b345761fadfa63f99ddd8a64d6c1ad (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-25] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8100 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 560a020231b345761fadfa63f99ddd8a64d6c1ad (xamarin/monodevelop)
