### ISSUE TITLE
Menus shown on incorrect folders in Solution pad

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7402]
Build Information
Release ID: 801001843
Git revision: 11609b486485c286e56698517f7530b68cb66fca
Build date: 2019-04-08 20:04:25+00
Build branch: master
Xamarin extensions: bab3989023c948c522b1a5955704440d320f02ec

Seeing context menus available on items in the Solution pad when they should not be there. Right clicking References, Dependencies, or NuGet folders, shows Publish, Add, Tools, Switch to Branch menu items. These should not be available here.

<img width="307" alt="refs" src="https://user-images.githubusercontent.com/372361/55890921-8034f400-5bab-11e9-89a4-92ecfcabe57a.png">

<img width="330" alt="Dependencies" src="https://user-images.githubusercontent.com/372361/55890929-81feb780-5bab-11e9-99b6-e3193b94c08e.png">

VS Mac 8.0 is OK.

> VS bug [#850081](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/850081)

**Comment by mrward** [comment]
All the above menus have autohide set to true so they should not be displayed.

`<ItemSet id = "Tools" _label = "_Tools" autohide="True">`

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.2.0.96 (master-vnext)



Author: Matt Ward  
 Commit: fe9be604d6b6a646f13e42478a54363c0306c72d (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.1.0.2319 (release-8.1)



Pull Request #720 merged by: Lluis Sanchez  
 Author: xamarin  
 Commit: 03e72cbfd2476b46faee05580bf4c1901cde2edd (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-26] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: fe9be604d6b6a646f13e42478a54363c0306c72d (xamarin/monodevelop)
