### ISSUE TITLE
UI hang due to setting DefaultSortFunc in AddChildren

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7403]
[Visual Studio_UIThreadHang_2019-04-09__17-11-18.txt](https://github.com/mono/monodevelop/files/3064893/Visual.Studio_UIThreadHang_2019-04-09__17-11-18.txt)
[Visual Studio_UIThreadHang_2019-04-09__17-13-13.txt](https://github.com/mono/monodevelop/files/3064894/Visual.Studio_UIThreadHang_2019-04-09__17-13-13.txt)
[Visual Studio_UIThreadHang_2019-04-09__17-18-13.txt](https://github.com/mono/monodevelop/files/3064895/Visual.Studio_UIThreadHang_2019-04-09__17-18-13.txt)
[Visual Studio_UIThreadHang_2019-04-09__17-20-08.txt](https://github.com/mono/monodevelop/files/3064896/Visual.Studio_UIThreadHang_2019-04-09__17-20-08.txt)

Looks like ExtensibleTreeView is setting DefaultSortFunc which causes a re-sort of the tree on every addchildren call, and the test pad seems to the cause, as the files are reloaded and it reloads the test list.

Profile traces can be opened in instruments.

> VS bug [#844589](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/844589)

**Comment by Therzok** [comment]
https://forum.unity.com/threads/visual-studio-for-mac-freeze-lag-on-save.649120/
https://developercommunity.visualstudio.com/content/problem/520574/freezelag-on-save-when-unity-editor-is-open.html
https://developercommunity.visualstudio.com/content/problem/525659/vs-for-mac-w-unity-tools-extreme-ui-hang-when-savi.html

@sevoku

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.305 (master)

Pull Request #7815 merged by: Vsevolod Kukol
Author: mono
Commit: 22dfd76a25160219f64f1b7a4f93bfca96a2700d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.2.0.744 (release-8.2)

Pull Request #7815 merged by: Vsevolod Kukol
Author: mono
Commit: 22dfd76a25160219f64f1b7a4f93bfca96a2700d (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7815 merged by: Vsevolod Kukol
Author: mono
Commit: 22dfd76a25160219f64f1b7a4f93bfca96a2700d (xamarin/monodevelop)
