### ISSUE TITLE
NodeBuilder update due to condition changes do not dispose the old ones

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7406]
NodeBuilder update on condition change initialize the builders multiple times, but do not dispose them.

![image](https://user-images.githubusercontent.com/109974/55982749-3e3aa980-5ca2-11e9-9221-2e3fbcab580b.png)

> VS bug [#845531](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/845531)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.364 (master)

Pull Request #7804 merged by: Mike Krüger
Author: mono
Commit: 406966545fc9a1d2a828f3d2df4d9edb6bd703ff (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.2.0.795 (release-8.2)

Pull Request #7804 merged by: Mike Krüger
Author: mono
Commit: 406966545fc9a1d2a828f3d2df4d9edb6bd703ff (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #7804 merged by: Mike Kr??ger
Author: mono
Commit: 406966545fc9a1d2a828f3d2df4d9edb6bd703ff (xamarin/monodevelop)
