### ISSUE TITLE
Expose pooling APIs for consumers

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7425]
ObjectPooling is a technique where we keep a set of reusable objects such as:
* Plain data (plain structs, strongbox, WeakReference, etc)
* Builders (`StringBuilder`, `ImmutableArray.Builder`)
* Collections (`List`, `HashSet`)

It implies pre-allocating a set of objects and having them at the ready for the consumers to rent the object from the pool, then return it when it no longer needs it - most pools have a built in mechanism to help with leak tracking! So that means we incur fewer GC penalties on allocating data that we don't need, with a minimal cost in CPU.

On the API we can introduce, we have a few options we can use, and based on the ease of use, we can choose what to apply. I'm listing them from least to most favoured options.

1. Expose Roslyn's implementations we get via `InternalsVisibleTo` as a wrapper, similar to how we do with `StringInternPool`. This allows us to re-use roslyn's code and automatically get updates whenever we bump it.

Advantages: Free updates when we bump roslyn, lightweight as they don't have extra configuration that nugets expose
DIsadvantages: In case of roslyn API breaks, we need to break too, it's icky to expose something as public as a wrapper over IVT

As this is not the best option for pooling in general, there are some classes which only Roslyn has and we can make good use of them.

2. Include Microsoft.Extensions.ObjectPool nuget

This is more or less the same code as Roslyn, but with a bit more configurability, and it's officially maintained as public API, so we don't need to be scared. Users of the API would have to reference the nuget - and at some point, someone will!

Advantages: public API, nuget, good implementation
Disadvantages: extra assembly

Orthogonally, we also can introduce the `ArrayPool<T>` class from `System.Buffers` specialized to work with arrays, `MemoryPool<T>` for working with unmanaged data

https://adamsitnik.com/Array-Pool/

> VS bug [#857187](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/857187)

**Comment by Therzok** [comment]
By going through the `Microsoft.Extensions.ObjectPool` API, we don't have to maintain _anything_.

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.1.0.2253 (master-vnext)



Pull Request #661 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 262511bb294e92d2a35a8d529c5691a194c4ab19 (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #661 merged by: Marius Ungureanu  
 Author: xamarin  
 Commit: 262511bb294e92d2a35a8d529c5691a194c4ab19 (xamarin/monodevelop)
