### ISSUE TITLE
Class AspNetCoreExecutionCommand should be public

### ISSUE THREAD

**Issue by lextm** [mono/monodevelop#7509]
Just noticed that ASP.NET Core project uses `AspNetCoreExecutionCommand`, but this class is not public. This prevents a debugger extension like https://github.com/lextudio/monodevelop.netcoredbg from supporting ASP.NET Core project debugging.

Of course I can use reflection as workaround, but hope that this class can be made public.

> VS bug [#890143](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890143)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.4.0.25 (master)



Author: Ian Toal  
 Commit: 1c2bc9d304194c24c4a471e6a0f1b5d59344f938 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-20] Comment by **xamarinc**



Fixed in version 8.2.0.844 (release-8.2)



Pull Request #7939 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a9a8c448e355a846fd013148563e177ac554c019 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-22] Comment by **xamarinc**



Fixed in version 8.4.0.203 (release-8.3)



Author: Ian Toal  
 Commit: 1c2bc9d304194c24c4a471e6a0f1b5d59344f938 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-23] Comment by **xamarinc**



Fixed in version 8.3.0.578 (release-8.3)



Author: Ian Toal  
 Commit: 1c2bc9d304194c24c4a471e6a0f1b5d59344f938 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-26] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Ian Toal  
 Commit: 1c2bc9d304194c24c4a471e6a0f1b5d59344f938 (xamarin/monodevelop)
