### ISSUE TITLE
Adding a non-sdk style project to a solution can trigger a NuGet restore

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7584]
To repro:

1. Open md-addins.sln.
2. Allow the NuGet restore to complete.
3. Add a new C# library project to the solution.

Expected result:

No NuGet restore is run. The project is not an sdk style project so nothing needs to be done here for the new project.

Actual result:

NuGet restore is run for the solution. Seems to do this several times.

> VS bug [#893871](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893871)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.2.0.356 (master)



Pull Request #7590 merged by: Matt Ward  
 Author: mono  
 Commit: bc3bbd014a62f4e7fa7f76f4505c0b9e945cee6b (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-21] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7590 merged by: Matt Ward  
 Author: mono  
 Commit: bc3bbd014a62f4e7fa7f76f4505c0b9e945cee6b (xamarin/monodevelop)
