### ISSUE TITLE
Monodevelop release-8.1-preview2 Build failed on Debian 9

### ISSUE THREAD

**Issue by lytico** [mono/monodevelop#7596]
error:
 /usr/share/dotnet/sdk/2.1.604/Sdks/Microsoft.**Net**.Sdk/Sdk not found
in
`monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj`

But:
dotnet sdk 2.1.604 is installed in:

/usr/share/dotnet/sdk/2.1.604/Sdks/Microsoft.**NET**.Sdk

PLEASE MARK: its intalled in .. NET ..., not in ... net ...

**Linux is case sensitiv!**

monodevelop branch from github (cloned from https://github.com/mono/monodevelop in an empty directory):
`git status: Auf Branch release-8.1-preview2`

mono -V

```
Mono JIT compiler version 6.0.0.241 (tarball Thu May 16 09:49:55 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
dotnet --info
```
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.604
 Commit:    c174d0ea92

Laufzeitumgebung:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.604/

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

.NET Core SDKs installed:
  2.1.604 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
monodevelop is installed, and msbuild is used from here:

`MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.`

if I type:
`msbuild -version`

i get:

```
Microsoft (R)-Build-Engine, Version 16.0.0.0 für Mono
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
```

detailed error info: (sorry, german version:)
```
/home/user/monodevelop-preview/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj : error : /usr/share/dotnet/sdk/2.1.604/Sdks/Microsoft.Net.Sdk/Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
Das Projekt "/home/user/monodevelop-preview/monodevelop/main/Main.sln" (1) erstellt "/home/user/monodevelop-preview/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (2) auf Knoten "1" (Standardziele).
Das Projekt "/home/user/monodevelop-preview/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (2) erstellt "/home/user/monodevelop-preview/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj" (3) auf Knoten "1" (Standardziele).
/home/user/monodevelop-preview/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj : error MSB4236: Das angegebene SDK "Microsoft.Net.Sdk" wurde nicht gefunden.
Die Erstellung des Projekts "/home/user/monodevelop-preview/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj" ist abgeschlossen (Standardziele) -- FEHLER.
Die Erstellung des Projekts "/home/user/monodevelop-preview/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" ist abgeschlossen (Standardziele) -- FEHLER.
Die Erstellung des Projekts "/home/user/monodevelop-preview/monodevelop/main/Main.sln" ist abgeschlossen (Standardziele) -- FEHLER.
```
Additional Info:

I tried to build monodevelop cause of 
https://github.com/dotnet/core/issues/2540 
and try to resolve it with 
https://developercommunity.visualstudio.com/content/problem/481018/resolvepackageassets-task-failed.html

there is said, that Visual Studio for Mac 8.1 Preview 1 (build 8.1.0.2306) should solve the problem.

I feared that it will be take years until we linux users will get this monodevelop version, so I wanted to build it.

**Comment by lytico** [comment]
i removed monodevelop (apt remove), same error with the difference:

`MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.`

**Comment by mrward** [comment]
If you change the case on in [MDBuildTasks.csproj](https://github.com/mono/monodevelop/blob/master/main/msbuild/MDBuildTasks/MDBuildTasks.csproj#L1) so it is `Microsoft.NET.Sdk` does that solve the problem for you?

**Comment by lytico** [comment]
thank you, that helped for this specific error.

but ... now it hangs with error
is Xamarin.Mac.Sdk needed somehow? can i install it on linux?

```
  /home/user/monodevelop-preview/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj(5,3): error : Method not found: System.Collections.Generic.IEnumerable`1<string> NuGet.Configuration.SettingsUtility.GetConfigFilePaths(NuGet.Configuration.ISettings)
  /home/user/monodevelop-preview/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj(5,3): error : /usr/share/dotnet/sdk/2.1.604/Sdks/Xamarin.Mac.Sdk/Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.


"/home/user/monodevelop-preview/monodevelop/main/Main.sln" (Standardziel) (1) ->
"/home/user/monodevelop-preview/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (Standardziel) (2) ->
"/home/user/monodevelop-preview/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj" (Standardziel) (4) ->
"/home/user/monodevelop-preview/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj" (GetTargetFrameworks Ziel) (18) ->
  /home/user/monodevelop-preview/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj(5,65): error MSB4236: Das angegebene SDK "Xamarin.Mac.Sdk" wurde nicht gefunden.

    2 Warnung(en)
    3 Fehler
```

**Comment by mrward** [comment]
The Xamarin.Mac.Sdk NuGet package is available from a new package source. You would need to add to the NuGet.Config file - https://www.myget.org/F/mirepoix/api/v3/index.json

You may want to try a different branch - the release-8.0 branch should be OK. The current master branch, even if you manage to build it, may not run properly. Some text editor changes have not yet made it to master.

**Comment by lytico** [comment]
I think  I need  8.1.0.2306 cause of:
https://developercommunity.visualstudio.com/content/problem/481018/resolvepackageassets-task-failed.html

**Comment by mrward** [comment]
That error is because of a mis-match between Mono's MSBuild and the .NET Core SDK. VS Mac 8.1 needs Mono 5.18.1.24 or later (which has MSBuild 16) to work with more recent .NET Core SDK. Mono builds from the [2018-08](https://github.com/mono/mono/tree/2018-08) branch should be OK. Not sure how MSBuild is distributed on Linux.

**Comment by lytico** [comment]
seems there is currently no chance to have monodevelop > 8.x on linux:

https://github.com/mono/monodevelop/issues/7170
https://github.com/mono/monodevelop/issues/7702
https://github.com/mono/monodevelop/issues/7170
https://github.com/mono/monodevelop/issues/8006

https://github.com/Microsoft/vs-editor-api

I close this issue, as there are many others open on this issue (see above)
