### ISSUE TITLE
[regression] Exception class completion popup is hidden under the window

### ISSUE THREAD

**Issue by usr-sse2** [mono/monodevelop#7628]
When creating an exception catchpoint, the class completion popup appears under the dialog window, so it's invisible.
It happens in both 8.0.6 and 8.1.
Here is a video:
https://www.youtube.com/watch?v=4rUi92bkKVk&feature=youtu.be

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.2.0.392 (master)

Author: Matt Ward
Commit: a9deb485a4461a8fb4a384e167862b8391dc31ec (mono/monodevelop)
