### ISSUE TITLE
Review usage of Task.Factory.StartNew

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7678]
[Task.Factory.StartNew](https://source.dot.net/#System.Private.CoreLib/shared/System/Threading/Tasks/TaskFactory.cs,282) has other defaults than [Task.Run](https://source.dot.net/#System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs,db74624ce219c605). Specifically, Task.Factory.StartNew uses _TaskScheduler.Current_ (the UI thread), instead of a thraedpool scheduler unless HideScheduler is specified or a specific scheduler is passed.

Review usage of the API, and migrate to Task.Run where possible.

Additionally, if users need the `state` parameter to avoid overhead of closure allocation, create an extension method for Task.Run which specifies the right parameters.

> VS bug [#900427](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/900427)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-4] Comment by **xamarinc**



Fixed in version 8.3.0.252 (master)



Author: Marius Ungureanu  
 Commit: ef5ea322347547cb6d971b6097b41965312178e6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-6] Comment by **xamarinc**



Fixed in version 8.2.0.707 (release-8.2)



Author: Marius Ungureanu  
 Commit: ef5ea322347547cb6d971b6097b41965312178e6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-7] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: ef5ea322347547cb6d971b6097b41965312178e6 (xamarin/monodevelop)
