### ISSUE TITLE
Review usages of Interlocked

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7689]
Interlocked is really nifty, but performance suffers when we're using int32 values on x64 platforms, which is usually the case.

Swap over to `long` values for interlocked operations.

See https://michaelscodingspot.com/array-iteration-vs-parallelism-in-c-net/

> VS bug [#977400](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/977400)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.5.0.760 (master)



Author: Marius Ungureanu  
 Commit: 5324cd2b69c84670dddd2ba2f4ad062b89422db0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Marius Ungureanu  
 Commit: 5324cd2b69c84670dddd2ba2f4ad062b89422db0 (xamarin/monodevelop)
