### ISSUE TITLE
MacSystemInformation gestalt error

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7745]
When running mdtool under lldb, we get the following message:

`2019-05-31 03:46:33.733759+0300 vstool[26035:217739] WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.14.5. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.`

**Comment by Therzok** [comment]
Broken invocation comes in from here:
http://source.monodevelop.com/#Xwt.Gtk.Mac/GtkMacDesktopBackend.cs,42

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.5.0.265 (master)

Pull Request #967 merged by: Marius Ungureanu
Author: mono
Commit: d765835a6e7ef37fd19182e96fef588f1f1e7f92 (mono/xwt)
Included in Commit: 59c89f90889fac1c199f7e19f6b3a481bdbfafbf (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.5.0.266 (master)

Pull Request #967 merged by: Marius Ungureanu
Author: mono
Commit: d765835a6e7ef37fd19182e96fef588f1f1e7f92 (mono/xwt)
Included in Commit: b9f0803998e5d016bd4a57d828ef107484dc9669 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.1560 (release-8.4)

Pull Request #967 merged by: Marius Ungureanu
Author: mono
Commit: d765835a6e7ef37fd19182e96fef588f1f1e7f92 (mono/xwt)
Included in Commit: 24fbcdef58339dabf9d54e59c349fad2aa012903 (mono/monodevelop)
