### ISSUE TITLE
MonoDevelop.Core tests fail in a local build and unnecessary propagation of MSBuild values

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7747]
Unlike CI, a local build will have a test temporary directory written inside the repository tree, which means we're including all the repository Directory.Build.props and Directory.Build.targets.

Specifically, LocalCopy tests fail due to mdb not being copied, because of [AllowedReferenceRelatedDebugFileExtensions](https://github.com/mono/monodevelop/blob/master/main/Directory.Build.targets#L12)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.5.0.530 (master)

Author: therzok
Commit: d527c7795376550961c2ee92461ea990cabd2a4c (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.1852 (release-8.4)

Author: therzok
Commit: d527c7795376550961c2ee92461ea990cabd2a4c (mono/monodevelop)
