### ISSUE TITLE
Path bar does not show shared projects on re-opening solution

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7781]
Repro:

1. Create a solution with a shared project and two other C# library projects that reference the shared project. Ensure that a file from the shared project is open in the text editor.
2. Close VS Mac.
3. Open the solution
4. File opened automatically on solution load.
5. See that the path bar shows the two other projects that reference the shared project.
6. Close the solution.
7. Open the solution again.

Expected result:

Path bar shows projects that reference the shared project.

Actual result:

Path bar does not show the other projects that reference the shared project.

Affects VS Mac 8.1 and later.
VS Mac 8.0 is OK.

Also seems OK if you created a Xamarin.Forms solution with a shared project. The shared file after the type system has finished updates the path bar so it shows the other projects. 

Build Information
Release ID: 801002697
Git revision: a128ffb65cb7045b2d4c0bbedc1db1b78a34ace7
Build date: 2019-05-31 22:15:33+00
Build branch: release-8.1
Xamarin extensions: f3e01946e5fdc7e28d90cef2e4f935e07bf6b330

Debugging this in a master based branch and the WorkspaceChanged event does not seem to be fired in the CSharpPathedDocumentExtension.

> VS bug [#904951](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904951)

**Comment by DavidKarlas** [comment]
This was fix by https://github.com/mono/monodevelop/pull/7848
