### ISSUE TITLE
Include version of Roslyn in about dialog

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7807]
Currently, we have no way to figure out the Roslyn version from an app bundle. Make it easy to get it from the about dialog.

> VS bug [#910296](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910296)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-9] Comment by **xamarinc**



Fixed in version 8.5.0.96 (master)



Pull Request #8603 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6ca39527dbc48d70347ec68859a15128e0f482a6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.5.0.162 (release-8.4)



Pull Request #8603 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6ca39527dbc48d70347ec68859a15128e0f482a6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.4.0.1447 (release-8.4)



Pull Request #8603 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6ca39527dbc48d70347ec68859a15128e0f482a6 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-14] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8603 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 6ca39527dbc48d70347ec68859a15128e0f482a6 (xamarin/monodevelop)
