### ISSUE TITLE
Old editor adds BOM to file on saving

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#7846]
If you have edit an .xml file with the old text editor and save it a BOM is added to the file. I think it should keep the original file encoding, which is what VS Mac 8.0 does.

This seems to be the opposite of bug 789068.

VS Mac 8.0.9 - OK
VS Mac 8.1.0.2709 - Bad

> VS bug [#915554](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/915554)

**Comment by mkrueger** [comment]
https://github.com/mono/monodevelop/pull/7808

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.3.0.326 (master)



Pull Request #7808 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 8d903ab797c03488fd3706a4ddd781149595be7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.2.0.778 (release-8.2)



Pull Request #7808 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 8d903ab797c03488fd3706a4ddd781149595be7f (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #7808 merged by: Vsevolod Kukol  
 Author: mono  
 Commit: 8d903ab797c03488fd3706a4ddd781149595be7f (xamarin/monodevelop)
