### ISSUE TITLE
Improve padding of InfoBar items when no button is present

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7863]
Adding an infobar without a button in the InfoBarItem list 
![image](https://user-images.githubusercontent.com/109974/59286212-fc18ee80-8c77-11e9-9b34-b9f82122348c.png)

The padding is off. We probably need to set a minimum version.

Also, not adding any InfoBarItem makes the infobar not show at all. Probably due to missing expand.

> VS bug [#934603](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934603)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-11] Comment by **xamarinc**



Fixed in version 8.4.0.91 (master)



Author: Tim Miller  
 Commit: fbf698b7ec05d906ef158396cd80892e19f7d26b (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-13] Comment by **xamarinc**



Fixed in version 8.2.0.924 (release-8.2)



Pull Request #7985 merged by: Lluis Sanchez  
 Author: mono  
 Commit: a3f16c1723cf4235426a435c202f00be256f04b2 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-15] Comment by **xamarinc**



Fixed in version 8.4.0.203 (release-8.3)



Author: Tim Miller  
 Commit: fbf698b7ec05d906ef158396cd80892e19f7d26b (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-16] Comment by **xamarinc**



Fixed in version 8.3.0.578 (release-8.3)



Author: Tim Miller  
 Commit: fbf698b7ec05d906ef158396cd80892e19f7d26b (mono/monodevelop)
