### ISSUE TITLE
Consider using NSBackgroundActivityScheduler to create deferred tasks

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7875]
Instead of using various timers/tasks/dispatch queue work items, we should use [NSBackgroundActivityScheduler](https://developer.apple.com/documentation/foundation/nsbackgroundactivityscheduler?language=objc) for efficient energy usage.

Candidates for this would be:

* AutoSave
* Checking for updates and downloading them

See the [Activity Options](https://developer.apple.com/documentation/foundation/nsactivityoptions?language=objc) and the [Priority](https://developer.apple.com/documentation/foundation/nsqualityofservice?language=objc) associated with the task.

**Comment by abock** [comment]
It's also worth noting that we will bring QOS/priority support into the Dispatcher to map the Windows priorities to Darwin equivalents. The Windows Dispatcher is heavily used in the editor, and [our port](https://github.com/KirillOsenkov/vs-editor-api/tree/monodevelop/master/src/FPF/WindowsBase/System.Windows.Threading) is implemented directly on top of Grand Central Dispatch (same thing `NSBackgroundActivityScheduler` is wrapping). So while I agree, this is a fine API to use, it should also be acceptable to directly use the Windows Dispatcher API 😄

**Comment by Therzok** [comment]
Yep, you are right:
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html#//apple_ref/doc/uid/TP40013929-CH35-SW1
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html

Both documents point to quality of service, so I guess we should use that.
