### ISSUE TITLE
semaphores on Linux?

### ISSUE THREAD

**Issue by mickeyjf** [mono/monodevelop#7914]
If I am reading the docs correctly named semaphores are global across process boundaries:

http://docs.go-mono.com/?link=T%3aSystem.Threading.Semaphore

The test program below should force a second instance of my program to immediately exit, whether on Windows or on Linux. It does work on Windows, but on Linux "createdNew" always returns True and my test fails, allowing me to run any number of instances.

Mono 5.18.1.3
MonoDevelop 7.8.2

Test program:
/*-------------------------------*/
`using System;
using System.Threading;

namespace semaphoreTest
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Test sem started...");

            bool isNew = CheckIfRunning();
            if (!isNew)
            {
                Environment.Exit(-1);
            }
            Console.WriteLine("any key...");
            Console.ReadLine();
        }
        private static bool CheckIfRunning()
        {
            try
            {
                Semaphore V5NotRunning = new Semaphore(0, 1, "V5Running", out bool createdNew);
                Console.WriteLine("New Sem created = {0}", createdNew);

                if (createdNew == false)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.WriteLine("Another V5 current running.");
                    Console.WriteLine("");
                    Console.WriteLine("    Please close the other V5 or kill the V5.exe process.");
                    Console.WriteLine("");
                }
                return createdNew;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }
    }
}
`

**Comment by mickeyjf** [comment]
OK, digging deeper into the docs :

http://docs.go-mono.com/?link=C%3aSystem.Threading.Semaphore.Semaphore(System.Int32%2cSystem.Int32%2cSystem.String%2cSystem.Boolean%26)

I see that this constructor has not been documented, so perhaps I should not expect this to work...

**Comment by mickeyjf** [comment]
Aaaand.... Semaphore.OpenExisting() also fails to find what should be a globally available semaphore. Although this *has* been documented and would be presumed to have been implemented.

**Comment by mickeyjf** [comment]
Is this what I'm tripping over, vis a vis mutexes, semaphores, shared memory, and everything else that appears to be failing for me in Mono but that works as advertised in .NET on Windows?
[https://github.com/mono/website/commit/ad30bfa1b33dd8d07a063c40ce44dcecb49e8f54](url)

**Comment by Therzok** [comment]
@mickeyjf I think you might want to report this against Mono. MonoDevelop has no role in the framework library implementation.

**Comment by mickeyjf** [comment]
Sorry, that's where I thought I was... Monday Morning...
