### ISSUE TITLE
[F#] Double-click on warnings and errors does not jump to source code

### ISSUE THREAD

**Issue by jwosty** [mono/monodevelop#7919]
This is a mismatch between the C# and F# IDE behavior. If you create a C# project, add code that produces a warning or error, and double click on it in the "errors" tab, it will jump you to the source code location matching the error. This does not work for F# projects.

**Comment by knocte** [comment]
I can't reproduce this with VS4Mac 8.1.5(build9)

**Comment by jwosty** [comment]
Cannot reproduce this anymore either (8.2.2 build 21)
