### ISSUE TITLE
Can't add tab caracter in plain text file

### ISSUE THREAD

**Issue by nkosi23** [mono/monodevelop#7991]
I am using monodevelop on Ubuntu (Latest) and since a few weeks, it is no longer possible to add a tab caracter in a text file. When pressing the key tab, four spaces are instead inserted instead of the tab caracter.

This is a major probl when developing programs parsing the tab caracte (as I do)....

Honestly, this in addition to #7415 makes me really wonder if anyone is actually using this IDE. This is a shame since Monodevelop for Ubuntu would be exactly the IDE our team need. We calculated our migration away from Windows based on its existence, but I am really starting to feel burned. If you could just get the basics of text editing working (Word wrap and inserting tab).

 It is frustrating that such basics things would fail us on an IDE that has been around for so long. I would never have expected that. Now we edit on emacs and just open Monodevelop to build. We may need to fully migrate to emacs using omnisharp but this is a whole new learning curve. This is disappointing.

This happens in text files having any extension.

**Comment by mrward** [comment]
You should be able to insert tabs if 'Convert tab to spaces' is unchecked. In preferences - Source Code - Code formatting there are various file types listed there. If you select Text files, for example, there is a 'Convert tab to spaces' option. I think recently this option was changed to be true by default.
