### ISSUE TITLE
ProjectFile.OnPathChanged computes values that are not used

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#7997]
`ProjectVirtualPath` is an expensive property, and we should not compute it in case we don't need it.

Similarly to https://github.com/mono/monodevelop/pull/7901/commits/d3ec80ee8c3a52045eb858af6272d215cd7ad5e6, we should fix `OnPathChanged` to be inlined and not compute values unless needed.

> VS bug [#936533](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936533)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 8.4.0.322 (master)



Pull Request #8063 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 0a82be81f60207c92140245357170e99b7173376 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.3.0.735 (release-8.3)



Pull Request #8063 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 0a82be81f60207c92140245357170e99b7173376 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-17] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #8063 merged by: Marius Ungureanu  
 Author: mono  
 Commit: 0a82be81f60207c92140245357170e99b7173376 (xamarin/monodevelop)
