### ISSUE TITLE
jQuery will not install via NuGet in Monodevelop

### ISSUE THREAD

**Issue by Mascasc** [mono/monodevelop#8159]
I am trying to install Bootstrap via NuGet in my Monodevelop project.  However, I am getting the following error:
`Could not install package 'jQuery 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
Is there a solution to this difficulty?  For reference, I am using Monodevelop version 7.8.2.

Edit: I have tried changing the framework to both version 4.5 and version 4.0, and I receive the same error (with the appropriate version number in each error message).

**Comment by mrward** [comment]
I believe there are problems with NuGet on file system's that are case sensitive.

https://xamarin.github.io/bugzilla-archives/49/49523/bug.html

**Comment by Mascasc** [comment]
Is there an alternative to NuGet for installing this package into a Monodevelop project?

**Comment by mrward** [comment]
You could try using `nuget install jquery` from the command line and adding the .js files directly.

Or download jquery directly from nuget.org

There is also [libman](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-2.2).

Also NPM is another alternative way of getting jQuery.

Neither libman nor NPM have any support in MonoDevelop though, but you can manage jQuery from the command line.

**Comment by Mascasc** [comment]
Ah!  
Well, `nuget install` from the command line seemed to work.
I didn't realize that was a possibility as I'm quite new to Monodevelop.  
But, the command line saves the day again.
Thank you!
