### ISSUE TITLE
Quote mono binary path when passing arguments to external konsole

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [mono/monodevelop#8202]
My path to mono contains a space and that's a problem, since path to the mono binary isn't quoted in arguments passed to the konsole terminal.

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.4.0.492 (master)

Pull Request #8254 merged by: Marius Ungureanu
Author: mono
Commit: 6eb6e589bddde6f12107afe8faa1d09e651541d0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.3.0.913 (release-8.3)

Pull Request #8254 merged by: Marius Ungureanu
Author: mono
Commit: 6eb6e589bddde6f12107afe8faa1d09e651541d0 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #8254 merged by: Marius Ungureanu
Author: mono
Commit: 6eb6e589bddde6f12107afe8faa1d09e651541d0 (xamarin/monodevelop)
