### ISSUE TITLE
ui: Remove trailing period from exception dialog

### ISSUE THREAD

**Issue by hbons** [mono/monodevelop#8204]
Checkboxes should not have trailing periods:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/103326/61281331-c0fb6500-a7b9-11e9-98c8-e85b142ef23b.png">

**Comment by Therzok** [comment]
cc @sevoku

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.245 (master)

Pull Request #9055 merged by: Vsevolod Kukol
Author: mono
Commit: c7cf4b6e66655ee945a85eba3b6854b567f0cad5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.5.0.1114 (release-8.5)

Pull Request #9055 merged by: Vsevolod Kukol
Author: mono
Commit: c7cf4b6e66655ee945a85eba3b6854b567f0cad5 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #9055 merged by: Vsevolod Kukol
Author: mono
Commit: c7cf4b6e66655ee945a85eba3b6854b567f0cad5 (xamarin/monodevelop)
