### ISSUE TITLE
the type initializer for 'monodevelop.projects.msbuild.msbuild evaluationcontext' threw an exception

### ISSUE THREAD

**Issue by Rombersoft** [mono/monodevelop#8220]
After morning updating I can not load any solution. 
I don't know which updating is guilty

![2019-07-17-094938_1920x1080_scrot](https://user-images.githubusercontent.com/19586466/61364439-8283aa00-a88e-11e9-8202-01f2f8806edc.png)
![2019-07-17-094954_1920x1080_scrot](https://user-images.githubusercontent.com/19586466/61364441-831c4080-a88e-11e9-8c0d-65d7c27cb939.png)

**Comment by Rombersoft** [comment]
[Ide.2019-07-17__14-51-51.log](https://github.com/mono/monodevelop/files/3401706/Ide.2019-07-17__14-51-51.log)

**Comment by aidevnn** [comment]
I also have this problem. When i downgraded from Mono 5.20  to Mono 5.1.13.1, the problem was solved.

May be Monodevelop was not ready for the last version of Mono 5.20

**Comment by aidevnn** [comment]
> [Ide.2019-07-17__14-51-51.log](https://github.com/mono/monodevelop/files/3401706/Ide.2019-07-17__14-51-51.log)

I also have this problem. When i downgraded from Mono 5.20 to Mono 5.18.1.3, the problem was solved.

May be the last version of Mono 5.20 for Linux has been compiled with bad parameters

**Comment by Rombersoft** [comment]
I've reinstalled mono, msbuild, mono develop and this problem was solved but new problem appeared

**Comment by aidevnn** [comment]
@Rombersoft  Microsoft.CSharp.Core.targets i also encountered this problem.
Look at mono version, and downgrade to 5.18.

First purge all mono-*, libmono-* and autoremove. Delete /usr/lib/mono/ folder

in the file /etc/apt/sources.list.d/mono-official-stable.list 
deb https://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/5.18.1.3 main

make sure you dont have no other source for mono-offical-vs or something else
then apt upgrade

then apt install mono

**Comment by Rombersoft** [comment]
Yes, thanks. All works!
