### ISSUE TITLE
Meaningful Addin Errors

### ISSUE THREAD

**Issue by Marti2203** [mono/monodevelop#8318]
I am currently trying to write a small addin for Avalonia so I can create some things faster and the first thing I want to create is a XAML template. I am using the CSharpBinding addin as a reference point, but I do not understand where to put the tempate file and the error "System.ApplicationException: Template EmptyXAMLFile.xft.xml not found" is not very helpful in my opinion. Maybe giving the example path where it is trying to find the file is a better solution?

**Comment by mrward** [comment]
File templates can either be an embedded resource, or be files that are included with the addin itself as separate files. With an embedded resource so there would not be a location on disk in that case to report.

For the C# binding it uses an embedded resource

https://github.com/mono/monodevelop/blob/b982d1bbfb9e3187fa34669847b0c65dbfe7f6e9/main/src/addins/CSharpBinding/CSharpBinding.addin.xml#L86

https://github.com/mono/monodevelop/blob/b982d1bbfb9e3187fa34669847b0c65dbfe7f6e9/main/src/addins/CSharpBinding/CSharpBinding.csproj#L105

Note that in your addin I would make sure the resource name, shown in the Properties window, is an exact match for the name used as the resource in the .addin.xml file. There are extra MSBuild imports that are applied in the MonoDevelop solution. For example:

```
    <EmbeddedResource Include="templates\EmptyCSharpFile.xft.xml">
      <LogicalName>EmptyCSharpFile.xft.xml</LogicalName>
    </EmbeddedResource>
```

**Comment by Marti2203** [comment]
Okay. This is interesting. I have not read everything then. Thank you for the information!
