### ISSUE TITLE
MsBuild-Error with more than 10 projects in one solution

### ISSUE THREAD

**Issue by lytico** [mono/monodevelop#8320]
Having a solution with more than 10 .netstandard2 - projects,
i cannot build it with monodevelop

Steps to reproduce:
get 
https://github.com/lytico/MsBuildErrorOnly10_1908/tree/master/test11

open with monodevelop and you get the following error:

`
Getting restore information for solution /data/Projects/MsBuildErrorOnly10/test11/test11.sln
ApplicationName='/usr/bin/mono64', CommandLine='"/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll" "/tmp/NuGetScratch/anmzxi2p.xaq.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"', CurrentDirectory='/data/Projects/MsBuildErrorOnly10/test11', Native error= Cannot find the specified file
`

=== MonoDevelop ===
Version 7.8.4 (build 2)
Installation UUID: 91f2f9a7-8e51-492f-acbf-a8599f5bacac
	GTK+ 2.24.32 (Mint-Y-Grey theme)
=== Mono Framework MDK ===
Runtime:
	Mono 6.4.0.146 (tarball Thu Aug  1 10:43:40 UTC 2019) (64-bit)
=== NuGet ===
Version: 4.8.2.5835
=== .NET Core ===
Laufzeit: Nicht installiert
SDK: Nicht installiert
MSBuild-SDKs: /usr/lib/mono/msbuild/15.0/bin/Sdks
=== Build Information ===
Release ID: 708040002
Git revision: 622db12503514afdb641c31615408bfe905a7312
Build date: 2019-07-17 17:02:07-04
=== Operating System ===
Linux

Linux 4.15.0-20-generic 21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64

Remark:
with 10 projects, it works, try this:

https://github.com/lytico/MsBuildErrorOnly10_1908/tree/master/test10

**Comment by lytico** [comment]
remark 2:
with rider, it works:

JetBrains Rider 2019.1.2
Build #RD-191.7141.355, built on June 5, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic

`
Build with surface heuristics started at 02:15:40
Use build tool: /usr/lib/mono/msbuild/15.0/bin/MSBuild.dll
0>------- Started building project: lib1
1>------- Started building project: lib2
2>------- Started building project: lib3
3>------- Started building project: lib4
4>------- Started building project: lib5
5>------- Started building project: lib6
6>------- Started building project: lib7
7>------- Started building project: lib8
8>------- Started building project: lib9
9>------- Started building project: lib10
10>------- Started building project: lib11
0>------- Finished building project: lib1. Succeeded: True. Errors: 0. Warnings: 0
10>------- Finished building project: lib11. Succeeded: True. Errors: 0. Warnings: 0
9>------- Finished building project: lib10. Succeeded: True. Errors: 0. Warnings: 0
8>------- Finished building project: lib9. Succeeded: True. Errors: 0. Warnings: 0
7>------- Finished building project: lib8. Succeeded: True. Errors: 0. Warnings: 0
6>------- Finished building project: lib7. Succeeded: True. Errors: 0. Warnings: 0
5>------- Finished building project: lib6. Succeeded: True. Errors: 0. Warnings: 0
4>------- Finished building project: lib5. Succeeded: True. Errors: 0. Warnings: 0
3>------- Finished building project: lib4. Succeeded: True. Errors: 0. Warnings: 0
2>------- Finished building project: lib3. Succeeded: True. Errors: 0. Warnings: 0
1>------- Finished building project: lib2. Succeeded: True. Errors: 0. Warnings: 0
Build completed in 00:00:02.989
Build succeeded at 02:15:43

`

**Comment by mrward** [comment]
When you use more than 10 projects then MonoDevelop will use msbuild directly to run a restore instead of running the restore itself.

Do these files exist on your machine?

- /usr/bin/mono64
 - /usr/lib/mono/msbuild/15.0/bin/MSBuild.dll

**Comment by lytico** [comment]
/usr/bin/mono64 **does not exist;** 
/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll **exists**.

ls /usr/bin/mono* :
```
/usr/bin/mono -> mono-sgen
/usr/bin/mono-api-check
/usr/bin/mono-api-html
/usr/bin/mono-api-info
/usr/bin/mono-cil-strip
/usr/bin/mono-configuration-crypto
/usr/bin/mono-csc -> mcs
/usr/bin/monodevelop
/usr/bin/monodocer
/usr/bin/monodocs2html
/usr/bin/monodocs2slashdoc
/usr/bin/mono-heapviz
/usr/bin/monolinker
/usr/bin/monop
/usr/bin/monop2
/usr/bin/mono-sgen
/usr/bin/mono-shlib-cop
/usr/bin/mono-symbolicate
/usr/bin/mono-test-install
/usr/bin/mono-xmltool
```

**Comment by mrward** [comment]
Does it work if you create a symlink for /usr/bin/mono64 that points to /usr/bin/mono?

**Comment by lytico** [comment]
`ln -s /usr/bin/mono /usr/bin/mono64`

solves the problem.

Thank you!

**Comment by mrward** [comment]
I suspect this code is wrong when not on Mac.

https://github.com/mono/monodevelop/blob/e958ae9dc9bab7ff16d21216486098f90c65b7ae/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProcessService.cs#L90

Presumably we do not ship both mono32 and mono64 on Linux.

MSBuild.dll is a 32-bit dll so I think it needs to be run with mono64 on the Mac since we want to ensure mono-sgen64 is used.

```
 file /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/Current/bin/MSBuild.dll
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/Current/bin/MSBuild.dll: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows
```

**Comment by synek317** [comment]
@lytico why did you decide to close this issue? `sudo ln -s` is a workaround (and thank you for inventing it), but definitely not a solution...

**Comment by lytico** [comment]
in recent version of monodevelop (see: https://github.com/dotdevelop/dotdevelop), this error doesn't occur any more; at least on my (new since then installed) machine, there i haven't the workaround.

**Comment by synek317** [comment]
Thanks! I didn't know dotdevelop earlier. I will definitely check it out.
