### ISSUE TITLE
Updating on LinuxMint is broken

### ISSUE THREAD

**Issue by Algorithman** [mono/monodevelop#8356]
Updating on LinuxMint 19.2 spews a lot of errors. Seems a dependency wasn't udpated.

 mono-devel : Depends: ca-certificates-mono (= 6.0.0.319-0xamarin1+ubuntu1804b1) but 5.18.1.28-0xamarin5+ubuntu1804b1 is installed

Any advice how to fix this again?

[aptoutput.txt](https://github.com/mono/monodevelop/files/3478549/aptoutput.txt)

apt install --fix-broken isn't working

**Comment by KFreeze** [comment]
Same problem on Ubuntu 18.04

**Comment by majid1268** [comment]
Same problem on Ubuntu 18.04

**Comment by Algorithman** [comment]
Fix here: https://github.com/mono/mono/issues/16110#issuecomment-519522346

 move /etc/mono/config.dpkg-new over /etc/mono/config and then just update again.

**Comment by elix545** [comment]
#mv /etc/mono/config.dpkg-new /etc/mono/config
#apt update -y --force-yes
#apt upgrade
#apt --fix-broken install

**Comment by Algorithman** [comment]
With this i think we can close the issue. Thx elix545 for the writeup.

**Comment by RadioCaroline** [comment]
> #mv /etc/mono/config.dpkg-new /etc/mono/config
> #apt update -y --force-yes
> #apt upgrade
> #apt --fix-broken install

Thanks, man! It works!

**Comment by luiszandonadi** [comment]
> #mv /etc/mono/config.dpkg-new /etc/mono/config
> #apt update -y --force-yes
> #apt upgrade
> #apt --fix-broken install

Thanks!!!!
