### ISSUE TITLE
Monodevelop does not install on Windows10 using MSBuild - solved!

### ISSUE THREAD

**Issue by LINLINEMS** [mono/monodevelop#8406]
After git clone https://github.com/mono/monodevelop --recursive -j8, go to the 
\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Gui\
and find the file ViewCommandHandlers.cs 
In line 526:
GetContent<Microsoft.VisualStudio.Text.Editor.ITextView3> () != null;
remove digit 3:
GetContent<Microsoft.VisualStudio.Text.Editor.ITextView> () != null;

**Comment by Therzok** [comment]
https://github.com/mono/monodevelop/pull/8402

**Comment by Therzok** [comment]
Just merged, closing.
