### ISSUE TITLE
[Linux, Ubuntu] Sourcefiles can not be opened in Editor after update to mono 6.4.0.170

### ISSUE THREAD

**Issue by lytico** [mono/monodevelop#8491]
no files can not be opened in editor after update to mono 6.4.0.170

OS:
Ubuntu 18.04 bionic 

Error:
`Sequence contains no elements`

**Solution**

delete monodevelop - cache

`rm -R <user>/.cache/monodevelop`

then it works again

**Comment by kryssb** [comment]
GREAT! Saves my workstation! I really got mad about this.
