### ISSUE TITLE
Windows/Debugging: The request is not supported. (Exception from HRESULT: 0x80070032)

### ISSUE THREAD

**Issue by Himura2la** [mono/monodevelop#8820]
I get the following error when I'm trying to debug anything on Windows.

![image](https://user-images.githubusercontent.com/7802808/65873595-2956ed00-e38c-11e9-88bd-c54b3c1e7dbf.png)

Debugger seems to be non-operational at all. I'm trying to debug an existing .NET Standerd/.NET Framework project.

Here's my Windows version:
![image](https://user-images.githubusercontent.com/7802808/65873804-c4e85d80-e38c-11e9-8189-15d7d6d2de3c.png)

**Comment by jtorres** [comment]
Hi, report that issue at: https://developercommunity.visualstudio.com/content/problem/post.html?space=8 

Thanks!

**Comment by Himura2la** [comment]
This is not the problem of Visual Studio!
I've compled MonoDevelop from sources and attached to if using Visual Studio to get the stack trace.
The MonoDevelop windows looks like this when I try to start the debugger

![image](https://user-images.githubusercontent.com/7802808/65876354-bb152900-e391-11e9-9610-af916aed15d1.png)

**Comment by Therzok** [comment]
I think that the problem is trying to launch a 64bit application from MonoDevelop. CorDebug does not support debugging 64bit processes from 32bit, and MonoDevelop is locked in 32bit due to gtk-sharp and most likely other native libraries.

**Comment by Himura2la** [comment]
I used Any CPU configuration to compile the project, Will try to compile for x86 and reply. Thanks for the clue.

**Comment by Himura2la** [comment]
It works. Although the bug does not reproduce, seems like MonoDevelop uses the native .NET runtime
