### ISSUE TITLE
why monodevelop introduces itself as cross-platform?

### ISSUE THREAD

**Issue by Maniues** [mono/monodevelop#9673]
1. You don't offer installers for Windows
2. You don't offer binaries for MacOS
3. You know that people need MonoDevelop for these platforms, you still leave people with the MD building process which is very difficult and buggy (I tried to compile MD several times and it failed).
Then how can you say MD is cross-platform?

**Comment by lextm** [comment]
You came too late to this MonoDevelop/Xamarin Studio game, https://corefx.lextudio.com/

1. Windows installer existed.
2. macOS installer existed.
3. "People need MonoDevelop for these platforms" is rather weak a statement. How many of them are out there? If there really are a lot many of them, they should fight their own fight like https://github.com/dotdevelop/dotdevelop

**Comment by Maniues** [comment]
@lextm 
I've already seen dotdevelop. For now, only the unchanged filenames and the program name tells me that I can talk about dotdevelop that it is monodevelop. I hope this project will be successful.
I wrote this question a little before I found out about dotdevelop. The project looks promising.
